import "server-only";
import { buildDizyBrainBehaviourProfile, normalizeBehaviourFilters, SUPPORTED_BEHAVIOUR_REVIEW_ENGINES, type BehaviourJoinedTrade, type BehaviourProfileFilters } from "./dizybrain-behaviour";
import { readTradeReview } from "./dizybrain-review-store";
import { tradeReviewInputHashFromMemoryMetadata } from "./dizybrain-trade-review";
import type { JournalEntry } from "./journal-model";
import { readJournal } from "./journal-store";
import { readReplayMemoryMetadata, type ReplayMemoryMetadata } from "./replay-memory-store";

export type BehaviourLoadDiagnostics=Readonly<{referencedReviews:number;loadedReviews:number;validReviews:number;staleReviews:number;invalidReviews:number;unsupportedReviews:number;eligibleReviews:number;filesRead:number;metadataReads:number;duplicateReviewReferences:number;aggregationDurationMs:number;profileSerializedBytes:number}>;
type Dependencies=Readonly<{readJournal:typeof readJournal;readTradeReview:typeof readTradeReview;readReplayMemoryMetadata:(userId:string,id:string)=>Promise<ReplayMemoryMetadata|null>}>;
const defaults:Dependencies={readJournal,readTradeReview,readReplayMemoryMetadata};
const relevantSignature=(entry:JournalEntry)=>JSON.stringify({id:entry.id,archived:entry.archived,quality:entry.quality,planDiscipline:entry.planDiscipline,mood:entry.mood,tags:[...entry.tags].map(x=>x.toLocaleLowerCase()).sort(),notesPresent:Boolean(entry.notes.trim()),trade:entry.trade&&{tradeId:entry.trade.tradeId,symbol:entry.trade.symbol,market:entry.trade.market,timeframe:entry.trade.timeframe,direction:entry.trade.direction,entry:entry.trade.entry,exit:entry.trade.exit,stop:entry.trade.stop,target:entry.trade.target,positionSize:entry.trade.positionSize,riskPct:entry.trade.riskPct,leverage:entry.trade.leverage,marginMode:entry.trade.marginMode,fees:entry.trade.fees,pnl:entry.trade.pnl,pnlPct:entry.trade.pnlPct,rMultiple:entry.trade.rMultiple,openTime:entry.trade.openTime,closeTime:entry.trade.closeTime,closeReason:entry.trade.closeReason,strategyVersion:entry.trade.strategyVersion,signal:entry.trade.signal,replayMemoryId:entry.trade.replay?.memoryId,review:entry.trade.dizyBrainReview}});
const matchesFilters=(entry:JournalEntry,filters:BehaviourProfileFilters)=>{const trade=entry.trade;if(!trade)return false;const close=Date.parse(trade.closeTime),from=filters.from?Date.parse(`${filters.from}T00:00:00.000Z`):-Infinity,to=filters.to?Date.parse(`${filters.to}T23:59:59.999Z`):Infinity;return close>=from&&close<=to&&(!filters.symbol||trade.symbol===filters.symbol)&&(!filters.timeframe||trade.timeframe===filters.timeframe)&&(!filters.tag||entry.tags.some(x=>x.toLocaleLowerCase()===filters.tag))&&(!filters.quality||entry.quality===filters.quality)&&(!filters.plan||entry.planDiscipline===filters.plan)&&(!filters.mood||entry.mood===filters.mood)&&(!filters.reviewEngineVersion||trade.dizyBrainReview.engineVersion===filters.reviewEngineVersion);};

/** Per-user, on-demand join. Only bounded Replay Memory metadata slices are read; candles are never parsed or returned. */
export async function loadDizyBrainBehaviourProfile(userId:string,rawFilters:Partial<BehaviourProfileFilters>,generatedAt:string,deps:Dependencies=defaults){
  const started=performance.now(),filters=normalizeBehaviourFilters(rawFilters),journal=await deps.readJournal(userId),entries=journal.entries.filter((x):x is JournalEntry=>x.type==="trade-review"&&Boolean(x.trade)),totalJournalTradeReviews=entries.length;
  const active=entries.filter(x=>filters.includeArchived||!x.archived),archivedExcluded=entries.length-active.length,generatedReviews=entries.filter(x=>x.trade!.dizyBrainReview.available&&x.trade!.dizyBrainReview.reviewId).length,filteredCandidateReviews=active.filter(x=>matchesFilters(x,filters)).length;
  let missingReviews=0,invalidReviews=0,staleReviews=0,unsupportedReviews=0,filesRead=0,metadataReads=0,loadedReviews=0,validReviews=0,duplicateReviewReferences=0;
  const groups=new Map<string,JournalEntry[]>();for(const entry of active){const reference=entry.trade!.dizyBrainReview,id=reference.reviewId;if(!reference.available||!id){missingReviews++;continue;}groups.set(id,[...(groups.get(id)??[]),entry]);}
  const joined:BehaviourJoinedTrade[]=[];for(const [id,rawGroup] of [...groups].sort(([a],[b])=>a.localeCompare(b))){const group=[...rawGroup].sort((a,b)=>a.id.localeCompare(b.id)||relevantSignature(a).localeCompare(relevantSignature(b)));duplicateReviewReferences+=group.length-1;const signatures=new Set(group.map(relevantSignature));if(signatures.size>1){invalidReviews++;continue;}const entry=group[0];let review;try{filesRead++;review=await deps.readTradeReview(userId,id);}catch{invalidReviews++;continue;}if(!review){missingReviews++;continue;}loadedReviews++;
    if(review.id!==id||review.journalEntryId!==entry.id||review.tradeId!==entry.trade!.tradeId||review.marketKey!==entry.trade!.replay?.marketKey||review.symbol!==entry.trade!.symbol||review.timeframe!==entry.trade!.timeframe){invalidReviews++;continue;}
    validReviews++;if(!SUPPORTED_BEHAVIOUR_REVIEW_ENGINES.includes(review.engineVersion as never)){unsupportedReviews++;continue;}const journalMemoryId=entry.trade!.replay?.source==="retained-memory"?entry.trade!.replay.memoryId:null;if(!journalMemoryId||journalMemoryId!==review.replayMemoryId){invalidReviews++;continue;}let metadata;try{metadataReads++;metadata=await deps.readReplayMemoryMetadata(userId,journalMemoryId);}catch{invalidReviews++;continue;}if(!metadata){staleReviews++;continue;}if(metadata.id!==journalMemoryId||metadata.tradeId!==review.tradeId||metadata.marketKey!==review.marketKey||metadata.symbol!==review.symbol||metadata.timeframe!==review.timeframe||metadata.entryTimeMs!==review.entryTimeMs||metadata.exitTimeMs!==review.exitTimeMs){invalidReviews++;continue;}if(metadata.contentHash!==review.provenance.replayMemoryContentHash||metadata.schemaVersion!==review.provenance.replayMemorySchemaVersion||metadata.validationVersion!==review.provenance.replayMemoryValidationVersion){staleReviews++;continue;}
    const currentHash=tradeReviewInputHashFromMemoryMetadata(entry,{id:metadata.id,contentHash:metadata.contentHash});if(entry.trade!.dizyBrainReview.generatedFromHash!==review.generatedFromHash||review.generatedFromHash!==currentHash){staleReviews++;continue;}joined.push(Object.freeze({review,archived:entry.archived,quality:entry.quality,planDiscipline:entry.planDiscipline,mood:entry.mood,tags:Object.freeze([...entry.tags]),notesPresent:Boolean(entry.notes.trim())}));
  }
  const profile=buildDizyBrainBehaviourProfile({reviewedTrades:joined,filters,generatedAt,coverage:{totalJournalTradeReviews,generatedReviews,currentValidReviews:joined.length,filteredCandidateReviews,staleReviews,missingReviews,invalidReviews,unsupportedReviews,archivedExcluded,duplicateReviewReferences}});const diagnostics=Object.freeze({referencedReviews:groups.size,loadedReviews,validReviews,staleReviews,invalidReviews,unsupportedReviews,eligibleReviews:profile.coverage.eligibleCurrentReviews,filesRead,metadataReads,duplicateReviewReferences,aggregationDurationMs:Math.round((performance.now()-started)*100)/100,profileSerializedBytes:Buffer.byteLength(JSON.stringify(profile))});return Object.freeze({profile,diagnostics});
}
