import { createHash } from "node:crypto";
import { CANDLE_TIMEFRAMES, type CandleTimeframe } from "./market/types";
import type { Candle } from "./strategy";
import { validateHistoricalReplayMemory, type HistoricalReplayMemory } from "./historical-replay-memory";
import type { JournalEntry, TradeSnapshot } from "./journal-model";

export const DIZYBRAIN_TRADE_REVIEW_SCHEMA_VERSION = 1 as const;
export const DIZYBRAIN_TRADE_REVIEW_ENGINE_VERSION = "historical-trade-review/1.0.0" as const;
export const DIZYBRAIN_TRADE_REVIEW_CONFIG_VERSION = 1 as const;
export const MAX_TRADE_REVIEW_BYTES = 128_000;
export const MAX_TRADE_REVIEWS_PER_USER = 2_000;
export const MAX_TRADE_REVIEW_BYTES_PER_USER = 64 * 1024 * 1024;

export type ReviewAssessment="strong"|"acceptable"|"mixed"|"weak"|"unavailable";
export type TradeAlignment="aligned"|"counter"|"transition"|"neutral"|"unavailable";
export type TradeEntryTiming="early"|"confirmed"|"late"|"extended"|"unavailable";
export type TradeExitTiming="planned"|"early"|"late"|"stop"|"liquidation"|"manual"|"signal-reversal"|"unavailable";
export type ReviewConfidenceBand="high"|"moderate"|"limited"|"insufficient";
export type TradeReviewEvidencePoint=Readonly<{label:string;value:string|number|boolean|null;timestampMs:number|null;source:"trade"|"replay-memory"|"signal"|"brain"|"journal"}>;
export type TradeReviewFinding=Readonly<{code:string;category:"setup"|"signal"|"trend"|"entry"|"risk"|"exit"|"process"|"outcome"|"data-quality";severity:"positive"|"neutral"|"caution"|"warning";title:string;summary:string;evidence:readonly TradeReviewEvidencePoint[];confidence:number;deterministic:true}>;
export type TradeReviewLimitation=Readonly<{code:string;message:string;severity:"info"|"caution"}>;
export type TradeReviewProvenance=Readonly<{replayMemorySource:"terminal-closed-candle-buffer";replayMemoryServerValidated:true;replayMemoryContentHash:string;replayMemorySchemaVersion:number;replayMemoryValidationVersion:number;closedCandlesOnly:true;entryCovered:boolean;exitCovered:boolean;signalSnapshotSource:"authoritative-trade-reference"|"unavailable";brainSnapshotSource:"unavailable";chartContextSource:"captured-metadata"|"unavailable";flowContextSource:"captured-snapshot"|"unavailable"|"capture-not-supported"}>;
export type TradeReviewEvidenceAvailability=Readonly<{replayMemory:boolean;candleCount:number;signalContext:boolean;brainContext:boolean;strategyContext:boolean;chartContext:boolean;flowContext:boolean;stopKnown:boolean;targetKnown:boolean;positionSizeKnown:boolean;riskPctKnown:boolean;leverageKnown:boolean;feesKnown:boolean;rMultipleKnown:boolean;journalQualityAssessment:boolean;journalPlanAssessment:boolean;journalMood:boolean;journalNotes:boolean;journalTags:boolean}>;
type Component=Readonly<{assessment:ReviewAssessment;score:number|null;reasonCodes:readonly string[];confidence:number;limitations:readonly string[]}>;
export type TradeExcursionReview=Readonly<{mfe:number;mae:number;mfePct:number;maePct:number;mfeR:number|null;maeR:number|null;barsToMfe:number;barsToMae:number;peakFavourablePrice:number;peakAdversePrice:number}>;
export type DizyBrainTradeReview=Readonly<{
 id:string;schemaVersion:1;engineVersion:string;createdAt:string;source:"historical-replay-memory";journalEntryId:string;tradeId:string;replayMemoryId:string;marketKey:string;symbol:string;timeframe:CandleTimeframe;signalTimeMs:number|null;entryTimeMs:number;exitTimeMs:number;
 provenance:TradeReviewProvenance;evidence:TradeReviewEvidenceAvailability;
 setup:Component&Readonly<{strategyVersion:string|null;direction:"long"|"short";configuredConfluenceThreshold:number|null}>;
 signal:Component&Readonly<{direction:"long"|"short"|null;presentOnExactCandle:boolean;directionConsistent:boolean|null;ageMs:number|null;barsFromSignal:number|null;entryOnSignalCandle:boolean|null;confluenceScore:number|null;thresholdMet:boolean|null}>;
 trend:Component&Readonly<{alignment:TradeAlignment;directionAtSignal:null;directionAtEntry:null;higherTimeframeAvailable:false}>;
 entry:Component&Readonly<{timing:TradeEntryTiming;barsFromSignal:number|null;millisecondsFromSignal:number|null;distanceFromSignalClose:number|null;rangePosition:number;priorDirectionalCandles:number;extended:boolean}>;
 excursion:TradeExcursionReview;
 risk:Component&Readonly<{stop:number|null;target:number|null;positionSize:number|null;riskPct:number|null;leverage:number|null;marginMode:"isolated"|"cross"|null;stopDistance:number|null;targetDistance:number|null;plannedRewardRisk:number|null;liquidation:boolean}>;
 exit:Component&Readonly<{timing:TradeExitTiming;closeReason:string;exitPrice:number;profitRetainedPct:number|null;hindsight:Readonly<{available:boolean;favourableContinuationPct:number|null;adverseMovementPct:number|null}>}>;
 process:Component&Readonly<{quality:string|null;planDiscipline:string|null;mood:string|null;tags:readonly string[];notesPresent:boolean;observations:readonly string[]}>;
 outcome:Readonly<{classification:"profit"|"loss"|"flat";pnl:number;pnlPct:number;rMultiple:number|null;fees:number|null;closeReason:string;mfe:number;mae:number}>;
 scores:Readonly<{setupEvidenceScore:number|null;signalConsistencyScore:number|null;trendAlignmentScore:number|null;entryExecutionScore:number|null;riskEvidenceScore:number|null;exitExecutionScore:number|null;processCompletenessScore:number|null;evidenceBasedExecutionScore:number|null}>;
 findings:readonly TradeReviewFinding[];limitations:readonly TradeReviewLimitation[];reviewConfidence:number;confidenceBand:ReviewConfidenceBand;confidenceReasons:readonly string[];generatedFromHash:string;
}>;

export class TradeReviewValidationError extends Error {constructor(public code:string,message:string){super(message);}}
const fail=(code:string,message:string):never=>{throw new TradeReviewValidationError(code,message);};
const sha=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const finiteTime=(value:string)=>{const result=Date.parse(value);return Number.isSafeInteger(result)?result:fail("INVALID_TRADE_TIME","Trade timestamp is invalid.");};
const freeze=<T>(value:T):Readonly<T>=>Object.freeze(value);
const point=(label:string,value:TradeReviewEvidencePoint["value"],timestampMs:number|null,source:TradeReviewEvidencePoint["source"]):TradeReviewEvidencePoint=>freeze({label,value,timestampMs,source});
const component=(assessment:ReviewAssessment,score:number|null,reasonCodes:string[],confidence:number,limitations:string[]=[]):Component=>freeze({assessment,score,reasonCodes:freeze([...reasonCodes].sort()),confidence,limitations:freeze([...limitations].sort())});

export function tradeReviewId(input:{journalEntryId:string;tradeId:string;replayMemoryId:string;marketKey:string;symbol:string;timeframe:string;generatedFromHash?:string;engineVersion?:string;schemaVersion?:number}){
 return `dbr1_${sha({namespace:"dizybrain-historical-trade-review",journalEntryId:input.journalEntryId,tradeId:input.tradeId,replayMemoryId:input.replayMemoryId,marketKey:input.marketKey,symbol:input.symbol,timeframe:input.timeframe,generatedFromHash:input.generatedFromHash??null,engineVersion:input.engineVersion??DIZYBRAIN_TRADE_REVIEW_ENGINE_VERSION,schemaVersion:input.schemaVersion??DIZYBRAIN_TRADE_REVIEW_SCHEMA_VERSION}).slice(0,40)}`;
}
export function tradeReviewInputHash(entry:JournalEntry,memory:HistoricalReplayMemory){const trade=entry.trade??fail("TRADE_REQUIRED","Only completed Trade Review entries can be reviewed.");return sha({engineVersion:DIZYBRAIN_TRADE_REVIEW_ENGINE_VERSION,configVersion:DIZYBRAIN_TRADE_REVIEW_CONFIG_VERSION,memoryContentHash:memory.integrity.contentHash,trade:{tradeId:trade.tradeId,symbol:trade.symbol,market:trade.market,timeframe:trade.timeframe,direction:trade.direction,entry:trade.entry,exit:trade.exit,stop:trade.stop,target:trade.target,positionSize:trade.positionSize,riskPct:trade.riskPct,leverage:trade.leverage,marginMode:trade.marginMode,fees:trade.fees,pnl:trade.pnl,pnlPct:trade.pnlPct,rMultiple:trade.rMultiple,openTime:trade.openTime,closeTime:trade.closeTime,closeReason:trade.closeReason,strategyVersion:trade.strategyVersion,signal:trade.signal,replayMemoryId:trade.replay?.memoryId},process:{quality:entry.quality,planDiscipline:entry.planDiscipline,mood:entry.mood,tags:[...entry.tags].sort(),notesPresent:Boolean(entry.notes.trim())}});}
function exactBoundaries(memory:HistoricalReplayMemory,signalMs:number|null,entryMs:number,exitMs:number){const candles=memory.candles;const exact=(ms:number,code:string)=>{const index=candles.findIndex(c=>c.time*1000===ms);if(index<0)fail(code,`${code==="SIGNAL_NOT_COVERED"?"Signal":"Required trade"} candle is absent from retained memory.`);return index;};const entryIndex=exact(entryMs,"ENTRY_NOT_COVERED"),exitIndex=exact(exitMs,"EXIT_NOT_COVERED"),signalIndex=signalMs===null?null:exact(signalMs,"SIGNAL_NOT_COVERED");if(signalIndex!==null&&signalIndex>entryIndex)fail("FUTURE_SIGNAL","Signal candle occurs after entry.");if(exitIndex<entryIndex)fail("INVALID_TRADE_RANGE","Exit candle occurs before entry.");return freeze({candlesThroughSignal:freeze(signalIndex===null?[]:candles.slice(0,signalIndex+1)),candlesThroughEntry:freeze(candles.slice(0,entryIndex+1)),candlesThroughExit:freeze(candles.slice(0,exitIndex+1)),candlesDuringTrade:freeze(candles.slice(entryIndex,exitIndex+1)),candlesAfterExit:freeze(candles.slice(exitIndex+1)),entryIndex,exitIndex,signalIndex});}
export function historicalTradeCandleBoundaries(memory:HistoricalReplayMemory){const valid=validateHistoricalReplayMemory(memory);return exactBoundaries(valid,valid.signalTimeMs,valid.entryTimeMs,valid.exitTimeMs);}
function excursion(trade:TradeSnapshot,candles:readonly Candle[]):TradeExcursionReview{let fav=-Infinity,adv=-Infinity,favPrice=trade.entry,advPrice=trade.entry,favBar=0,advBar=0;candles.forEach((c,i)=>{const f=trade.direction==="long"?c.high-trade.entry:trade.entry-c.low,a=trade.direction==="long"?trade.entry-c.low:c.high-trade.entry;if(f>fav){fav=f;favPrice=trade.direction==="long"?c.high:c.low;favBar=i;}if(a>adv){adv=a;advPrice=trade.direction==="long"?c.low:c.high;advBar=i;}});const risk=trade.stop===null?null:Math.abs(trade.entry-trade.stop);return freeze({mfe:Math.max(0,fav),mae:Math.max(0,adv),mfePct:Math.max(0,fav)/trade.entry*100,maePct:Math.max(0,adv)/trade.entry*100,mfeR:risk?Math.max(0,fav)/risk:null,maeR:risk?Math.max(0,adv)/risk:null,barsToMfe:favBar,barsToMae:advBar,peakFavourablePrice:favPrice,peakAdversePrice:advPrice});}
const confidenceBand=(score:number):ReviewConfidenceBand=>score>=80?"high":score>=60?"moderate":score>=35?"limited":"insufficient";
const exitTiming=(reason:string):TradeExitTiming=>{const v=reason.toLowerCase();if(v.includes("liquid"))return "liquidation";if(v.includes("stop"))return "stop";if(v.includes("target")||v.includes("take profit"))return "planned";if(v.includes("signal")||v.includes("reversal"))return "signal-reversal";if(v.includes("manual"))return "manual";return "unavailable";};
function weighted(scores:ReadonlyArray<readonly [number|null,number]>) {const available=scores.filter((x):x is readonly[number,number]=>x[0]!==null);return available.length>=3?Math.round(available.reduce((s,[v,w])=>s+v*w,0)/available.reduce((s,[,w])=>s+w,0)):null;}

export function buildDizyBrainTradeReview(input:{journalEntry:JournalEntry;replayMemory:HistoricalReplayMemory;generatedAt:string}):DizyBrainTradeReview {
 const entry=input.journalEntry,trade=entry.trade??fail("TRADE_REQUIRED","Only completed Trade Review entries can be reviewed.");if(entry.type!=="trade-review")fail("TRADE_REQUIRED","Only completed Trade Review entries can be reviewed.");const memory=validateHistoricalReplayMemory(input.replayMemory),createdAt=new Date(input.generatedAt).toISOString();
 const entryMs=finiteTime(trade.openTime),exitMs=finiteTime(trade.closeTime),signalMs=trade.signal?finiteTime(trade.signal.signalTime):null,replay=trade.replay;
 if(!replay||!replay.available||replay.source!=="retained-memory"||replay.memoryId!==memory.id)fail("REPLAY_REFERENCE_MISMATCH","Journal entry does not reference this retained replay memory.");const retainedReplay=replay!;
 if(memory.tradeId!==trade.tradeId||memory.marketKey!==retainedReplay.marketKey||memory.symbol!==trade.symbol||memory.timeframe!==trade.timeframe||memory.entryTimeMs!==entryMs||memory.exitTimeMs!==exitMs||memory.entryPrice!==trade.entry||memory.exitPrice!==trade.exit)fail("TRADE_IDENTITY_MISMATCH","Journal trade facts and retained replay memory do not match exactly.");if(!CANDLE_TIMEFRAMES.includes(trade.timeframe as CandleTimeframe))fail("INVALID_TIMEFRAME","Trade timeframe is unsupported.");if(memory.signalTimeMs!==signalMs)fail("SIGNAL_IDENTITY_MISMATCH","Journal signal and retained replay memory do not match.");
 const b=exactBoundaries(memory,signalMs,entryMs,exitMs),signalCandle=b.candlesThroughSignal.at(-1)??null,entryCandle=b.candlesThroughEntry.at(-1)!,x=excursion(trade,b.candlesDuringTrade);
 let prior=0;for(let i=b.candlesThroughEntry.length-1;i>=0;i--){const c=b.candlesThroughEntry[i],directional=trade.direction==="long"?c.close>c.open:c.close<c.open;if(!directional)break;prior++;}const bars=signalMs===null?null:b.entryIndex-b.signalIndex!,extended=prior>=3,timing:TradeEntryTiming=signalMs===null?"unavailable":extended?"extended":bars===0?"confirmed":bars===1?"confirmed":"late";
 const signalAvailable=Boolean(memory.signalContext&&trade.signal),directionConsistent=signalAvailable?memory.signalContext!.direction===trade.direction:null,signalScore=directionConsistent===null?null:directionConsistent?100:0,entryScore=signalMs===null?null:timing==="confirmed"?100:timing==="late"?60:timing==="extended"?35:50;
 const knownRisk=[trade.stop,trade.target,trade.positionSize,trade.riskPct,trade.leverage].filter(v=>v!==null).length,riskScore=knownRisk?Math.round(knownRisk/5*100):null,processKnown=[entry.quality,entry.planDiscipline,entry.mood,entry.tags.length?true:null,entry.notes.trim()?true:null].filter(Boolean).length,processScore=processKnown?processKnown*20:null,exitClass=exitTiming(trade.closeReason),exitScore=exitClass==="unavailable"?null:100;
 const findings:TradeReviewFinding[]=[];const add=(finding:TradeReviewFinding)=>findings.push(freeze(finding));if(signalAvailable)add({code:directionConsistent?"SIGNAL_DIRECTION_MATCH":"SIGNAL_DIRECTION_CONFLICT",category:"signal",severity:directionConsistent?"positive":"warning",title:directionConsistent?"Signal direction matched":"Signal direction differed",summary:directionConsistent?"The authoritative historical signal direction matched the recorded trade direction.":"The authoritative historical signal direction differed from the recorded trade direction.",evidence:freeze([point("Direction consistent",directionConsistent,signalMs,"signal")]),confidence:100,deterministic:true});
 if(signalMs!==null)add({code:bars===0?"ENTRY_ON_SIGNAL_CANDLE":"ENTRY_DELAYED",category:"entry",severity:bars===0?"positive":"neutral",title:bars===0?"Entry on confirmed signal candle":"Entry followed the signal candle",summary:bars===0?"Entry occurred on the confirmed signal candle.":`Entry occurred ${bars} candle${bars===1?"":"s"} after the confirmed signal candle.`,evidence:freeze([point("Bars from signal",bars,entryMs,"replay-memory")]),confidence:100,deterministic:true});if(extended)add({code:"ENTRY_DIRECTIONAL_EXTENSION",category:"entry",severity:"caution",title:"Directional extension at entry",summary:"Entry followed an extended directional move.",evidence:freeze([point("Consecutive directional candles",prior,entryMs,"replay-memory")]),confidence:100,deterministic:true});if(trade.stop===null)add({code:"RISK_COMPLIANCE_UNAVAILABLE",category:"risk",severity:"caution",title:"Historical risk compliance unavailable",summary:"Historical risk compliance could not be evaluated because the initial stop was unavailable.",evidence:freeze([point("Initial stop",null,null,"trade")]),confidence:100,deterministic:true});
 const outcomeClass=trade.pnl>0?"profit":trade.pnl<0?"loss":"flat";const observations:string[]=[];if(entry.quality==="good"&&outcomeClass==="loss")observations.push("User marked Good Trade; financial result was a loss.");if(entry.quality==="poor"&&outcomeClass==="profit")observations.push("User marked Poor Trade; financial result was a profit.");if(entry.planDiscipline==="completely"&&trade.riskPct===null)observations.push("User marked Completely followed plan; objective risk compliance was unavailable.");if(entry.mood==="fomo"&&extended)observations.push("Recorded mood was FOMO, and the entry occurred after an extended move.");
 const limitations:TradeReviewLimitation[]=[{code:"BRAIN_CONTEXT_UNAVAILABLE",message:"Historical DizyBrain evidence was not retained for this trade.",severity:"info"},{code:"CHART_CONTEXT_UNAVAILABLE",message:"Historical chart context was not retained for this trade.",severity:"info"},{code:"FLOW_CAPTURE_NOT_SUPPORTED",message:"Historical DizyFlow evidence was not retained for this trade.",severity:"info"},{code:"HIGHER_TIMEFRAME_UNAVAILABLE",message:"Historical higher-timeframe context was not retained.",severity:"info"},{code:"TERMINAL_CAPTURE_PROVENANCE",message:"Review uses terminal-captured, server-validated closed candles.",severity:"info"}];if(!memory.strategyContext)limitations.push({code:"STRATEGY_CONTEXT_UNAVAILABLE",message:"Historical strategy settings were unavailable.",severity:"caution"});if(trade.stop===null)limitations.push({code:"INITIAL_STOP_UNAVAILABLE",message:"Authoritative initial stop was unavailable.",severity:"caution"});if(trade.riskPct===null)limitations.push({code:"RISK_PERCENT_UNAVAILABLE",message:"Authoritative risk percentage was unavailable.",severity:"caution"});if(!b.candlesAfterExit.length)limitations.push({code:"POST_EXIT_CONTEXT_UNAVAILABLE",message:"No post-exit candles were retained; hindsight context is unavailable.",severity:"info"});if(memory.integrity.gapCount)limitations.push({code:"CANDLE_GAPS",message:`Retained memory contains ${memory.integrity.gapCount} candle gap(s); missing candles were not fabricated.`,severity:"caution"});limitations.sort((a,b)=>a.code.localeCompare(b.code));
 const evidence=freeze({replayMemory:true,candleCount:memory.candles.length,signalContext:signalAvailable,brainContext:false,strategyContext:Boolean(memory.strategyContext),chartContext:false,flowContext:memory.flowAvailability==="available",stopKnown:trade.stop!==null,targetKnown:trade.target!==null,positionSizeKnown:trade.positionSize!==null,riskPctKnown:trade.riskPct!==null,leverageKnown:trade.leverage!==null,feesKnown:trade.fees!==null,rMultipleKnown:trade.rMultiple!==null,journalQualityAssessment:entry.quality!==null,journalPlanAssessment:entry.planDiscipline!==null,journalMood:entry.mood!==null,journalNotes:Boolean(entry.notes.trim()),journalTags:entry.tags.length>0});
 let confidence=45;const reasons=["Replay Memory passed server integrity validation and covers entry and exit."];if(signalAvailable){confidence+=15;reasons.push("Authoritative historical signal identity is available.");}else reasons.push("Historical signal context is unavailable.");if(memory.strategyContext)confidence+=8;if(trade.stop!==null)confidence+=6;if(trade.riskPct!==null)confidence+=6;if(b.candlesAfterExit.length)confidence+=5;if(entry.quality||entry.planDiscipline||entry.mood)confidence+=5;if(memory.integrity.gapCount){confidence-=Math.min(20,memory.integrity.gapCount*5);reasons.push("Retained candle gaps reduce review confidence.");}confidence=Math.max(0,Math.min(100,confidence));reasons.push("Confidence measures evidence completeness, not probability of profit.");
 const setup=freeze({...component(memory.strategyContext?"acceptable":"unavailable",memory.strategyContext?70:null,[memory.strategyContext?"STRATEGY_VERSION_RETAINED":"STRATEGY_CONTEXT_UNAVAILABLE"],memory.strategyContext?70:0),strategyVersion:memory.strategyContext?.version??null,direction:trade.direction,configuredConfluenceThreshold:null});const signal=freeze({...component(signalAvailable?(directionConsistent?"strong":"weak"):"unavailable",signalScore,[signalAvailable?"AUTHORITATIVE_SIGNAL_REFERENCE":"SIGNAL_UNAVAILABLE"],signalAvailable?100:0),direction:memory.signalContext?.direction??null,presentOnExactCandle:Boolean(signalCandle),directionConsistent,ageMs:signalMs===null?null:entryMs-signalMs,barsFromSignal:bars,entryOnSignalCandle:bars===null?null:bars===0,confluenceScore:null,thresholdMet:null});const trend=freeze({...component("unavailable",null,["TREND_CONTEXT_UNAVAILABLE"],0,["No reproducible historical trend snapshot was retained."]),alignment:"unavailable" as const,directionAtSignal:null,directionAtEntry:null,higherTimeframeAvailable:false as const});const entryReview=freeze({...component(entryScore===null?"unavailable":entryScore>=80?"strong":entryScore>=50?"mixed":"weak",entryScore,[`ENTRY_${timing.toUpperCase()}`],100),timing,barsFromSignal:bars,millisecondsFromSignal:signalMs===null?null:entryMs-signalMs,distanceFromSignalClose:signalCandle?trade.direction==="long"?trade.entry-signalCandle.close:signalCandle.close-trade.entry:null,rangePosition:entryCandle.high===entryCandle.low?0.5:(trade.entry-entryCandle.low)/(entryCandle.high-entryCandle.low),priorDirectionalCandles:prior,extended});
 const stopDistance=trade.stop===null?null:Math.abs(trade.entry-trade.stop),targetDistance=trade.target===null?null:Math.abs(trade.target-trade.entry);const risk=freeze({...component(riskScore===null?"unavailable":riskScore>=80?"strong":riskScore>=40?"mixed":"weak",riskScore,[riskScore===null?"RISK_FACTS_UNAVAILABLE":"AUTHORITATIVE_RISK_FACTS_PARTIAL"],riskScore??0),stop:trade.stop,target:trade.target,positionSize:trade.positionSize,riskPct:trade.riskPct,leverage:trade.leverage,marginMode:trade.marginMode,stopDistance,targetDistance,plannedRewardRisk:stopDistance&&targetDistance?targetDistance/stopDistance:null,liquidation:exitClass==="liquidation"});const exit=freeze({...component(exitScore===null?"unavailable":"acceptable",exitScore,[`EXIT_${exitClass.toUpperCase().replaceAll("-","_")}`],exitScore??0),timing:exitClass,closeReason:trade.closeReason,exitPrice:trade.exit,profitRetainedPct:x.mfe>0?Math.max(0,(trade.direction==="long"?trade.exit-trade.entry:trade.entry-trade.exit))/x.mfe*100:null,hindsight:freeze({available:b.candlesAfterExit.length>0,favourableContinuationPct:null,adverseMovementPct:null})});const process=freeze({...component(processScore===null?"unavailable":"acceptable",processScore,[processScore===null?"JOURNAL_ASSESSMENT_UNAVAILABLE":"JOURNAL_ASSESSMENT_RECORDED"],processScore??0),quality:entry.quality,planDiscipline:entry.planDiscipline,mood:entry.mood,tags:freeze([...entry.tags]),notesPresent:Boolean(entry.notes.trim()),observations:freeze(observations)});const scores=freeze({setupEvidenceScore:setup.score,signalConsistencyScore:signal.score,trendAlignmentScore:trend.score,entryExecutionScore:entryReview.score,riskEvidenceScore:risk.score,exitExecutionScore:exit.score,processCompletenessScore:process.score,evidenceBasedExecutionScore:weighted([[setup.score,10],[signal.score,20],[trend.score,10],[entryReview.score,25],[risk.score,20],[exit.score,10],[process.score,5]])});
 const generatedFromHash=tradeReviewInputHash(entry,memory),id=tradeReviewId({journalEntryId:entry.id,tradeId:trade.tradeId,replayMemoryId:memory.id,marketKey:memory.marketKey,symbol:memory.symbol,timeframe:memory.timeframe,generatedFromHash});
 return freeze({id,schemaVersion:DIZYBRAIN_TRADE_REVIEW_SCHEMA_VERSION,engineVersion:DIZYBRAIN_TRADE_REVIEW_ENGINE_VERSION,createdAt,source:"historical-replay-memory",journalEntryId:entry.id,tradeId:trade.tradeId,replayMemoryId:memory.id,marketKey:memory.marketKey,symbol:memory.symbol,timeframe:memory.timeframe,signalTimeMs:signalMs,entryTimeMs:entryMs,exitTimeMs:exitMs,provenance:freeze({replayMemorySource:"terminal-closed-candle-buffer",replayMemoryServerValidated:true,replayMemoryContentHash:memory.integrity.contentHash,replayMemorySchemaVersion:memory.schemaVersion,replayMemoryValidationVersion:memory.captureProvenance.validationVersion,closedCandlesOnly:true,entryCovered:true,exitCovered:true,signalSnapshotSource:signalAvailable?"authoritative-trade-reference":"unavailable",brainSnapshotSource:"unavailable",chartContextSource:"unavailable",flowContextSource:memory.flowAvailability==="capture-not-supported"?"capture-not-supported":memory.flowAvailability==="available"?"captured-snapshot":"unavailable"}),evidence,setup,signal,trend,entry:entryReview,excursion:x,risk,exit,process,outcome:freeze({classification:outcomeClass,pnl:trade.pnl,pnlPct:trade.pnlPct,rMultiple:trade.rMultiple,fees:trade.fees,closeReason:trade.closeReason,mfe:x.mfe,mae:x.mae}),scores,findings:freeze(findings.sort((a,b)=>a.category.localeCompare(b.category)||a.code.localeCompare(b.code))),limitations:freeze(limitations),reviewConfidence:confidence,confidenceBand:confidenceBand(confidence),confidenceReasons:freeze(reasons),generatedFromHash});
}

export function validateDizyBrainTradeReview(value:unknown):DizyBrainTradeReview {if(!value||typeof value!=="object")fail("MALFORMED_REVIEW","Malformed trade review.");const v=value as DizyBrainTradeReview;if(v.schemaVersion!==1||v.engineVersion!==DIZYBRAIN_TRADE_REVIEW_ENGINE_VERSION||v.source!=="historical-replay-memory"||!/^dbr1_[a-f0-9]{40}$/.test(v.id)||!v.generatedFromHash?.match(/^[a-f0-9]{64}$/)||!Number.isInteger(v.reviewConfidence)||v.reviewConfidence<0||v.reviewConfidence>100||!Array.isArray(v.findings)||!Array.isArray(v.limitations)||"candles" in v)fail("MALFORMED_REVIEW","Stored trade review failed validation.");return freeze(v);}
