import "server-only";
import { mkdir, readFile, readdir, rename, stat, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { MAX_TRADE_REVIEW_BYTES,MAX_TRADE_REVIEW_BYTES_PER_USER,MAX_TRADE_REVIEWS_PER_USER,validateDizyBrainTradeReview,type DizyBrainTradeReview } from "./dizybrain-trade-review";
const root=()=>process.env.DATA_DIR||join(process.cwd(),".data");
const safe=(value:string)=>{if(!/^[a-zA-Z0-9_-]+$/.test(value))throw new TradeReviewStorageError("INVALID_IDENTIFIER","Invalid review identifier.");return value;};
const directory=(userId:string)=>join(root(),"dizybrain-reviews",safe(userId));const filename=(userId:string,id:string)=>join(directory(userId),`${safe(id)}.json`);
const queues=new Map<string,Promise<unknown>>();export async function withTradeReviewStorageTransaction<T>(id:string,fn:()=>Promise<T>){const prior=queues.get(id)??Promise.resolve();let release!:()=>void;const gate=new Promise<void>(r=>release=r),queued=prior.then(()=>gate);queues.set(id,queued);await prior;try{return await fn();}finally{release();if(queues.get(id)===queued)queues.delete(id);}}
export class TradeReviewStorageError extends Error {constructor(public code:string,message:string){super(message);}}
export async function createTradeReview(userId:string,review:DizyBrainTradeReview){return withTradeReviewStorageTransaction(userId,async()=>{const dir=directory(userId),target=filename(userId,review.id);await mkdir(dir,{recursive:true});try{const existing=validateDizyBrainTradeReview(JSON.parse(await readFile(target,"utf8")));if(existing.generatedFromHash!==review.generatedFromHash)throw new TradeReviewStorageError("CONTENT_CONFLICT","Deterministic review identity has different inputs.");return {review:existing,created:false};}catch(reason){if((reason as NodeJS.ErrnoException).code!=="ENOENT")throw reason;}const encoded=JSON.stringify(review,null,2)+"\n",bytes=Buffer.byteLength(encoded);if(bytes>MAX_TRADE_REVIEW_BYTES)throw new TradeReviewStorageError("REVIEW_TOO_LARGE","Trade review exceeds its size limit.");const files=(await readdir(dir)).filter(f=>/^dbr1_[a-f0-9]{40}\.json$/.test(f));if(files.length>=MAX_TRADE_REVIEWS_PER_USER)throw new TradeReviewStorageError("REVIEW_LIMIT","Trade-review count limit reached.");let total=0;for(const file of files)total+=(await stat(join(dir,file))).size;if(total+bytes>MAX_TRADE_REVIEW_BYTES_PER_USER)throw new TradeReviewStorageError("STORAGE_LIMIT","Trade-review storage limit reached.");const temp=`${target}.${process.pid}.${Date.now()}.tmp`;try{await writeFile(temp,encoded,{mode:0o600,flag:"wx"});await rename(temp,target);}catch(reason){await unlink(temp).catch(()=>undefined);throw reason;}return {review,created:true};});}
export async function readTradeReview(userId:string,id:string){try{const raw=await readFile(filename(userId,id),"utf8");if(Buffer.byteLength(raw)>MAX_TRADE_REVIEW_BYTES)throw new TradeReviewStorageError("MALFORMED_REVIEW","Stored review is oversized.");return validateDizyBrainTradeReview(JSON.parse(raw));}catch(reason){if((reason as NodeJS.ErrnoException).code==="ENOENT")return null;throw reason;}}
export async function deleteTradeReview(userId:string,id:string){return withTradeReviewStorageTransaction(userId,async()=>{try{await unlink(filename(userId,id));return true;}catch(reason){if((reason as NodeJS.ErrnoException).code==="ENOENT")return false;throw reason;}});}
