import "server-only";
import { mkdir, readFile, readdir, rename, stat, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { HISTORICAL_DIZYFLOW_LIMITS, validateHistoricalDizyFlowMemory, type HistoricalDizyFlowMemory } from "./historical-dizyflow";

const root=()=>process.env.DATA_DIR||join(process.cwd(),".data");
const safe=(value:string)=>{if(!/^[a-z0-9_-]{1,120}$/i.test(value))throw new HistoricalDizyFlowStorageError("INVALID_ID","Invalid Historical DizyFlow identifier.");return value};
const directory=(userId:string)=>join(root(),"historical-dizyflow",safe(userId));
const filename=(userId:string,id:string)=>join(directory(userId),`${safe(id)}.json`);
const queues=new Map<string,Promise<unknown>>();
async function serial<T>(userId:string,fn:()=>Promise<T>){const prior=queues.get(userId)??Promise.resolve();let release!:()=>void;const gate=new Promise<void>(r=>release=r),current=prior.then(()=>gate);queues.set(userId,current);await prior;try{return await fn()}finally{release();if(queues.get(userId)===current)queues.delete(userId)}}
export class HistoricalDizyFlowStorageError extends Error {constructor(public code:string,message:string){super(message)}}

export async function createHistoricalDizyFlowMemory(userId:string,memory:HistoricalDizyFlowMemory){return serial(userId,async()=>{const validated=validateHistoricalDizyFlowMemory(memory),dir=directory(userId),target=filename(userId,validated.id);await mkdir(dir,{recursive:true});try{const existing=validateHistoricalDizyFlowMemory(JSON.parse(await readFile(target,"utf8")));if(existing.contentHash!==validated.contentHash)throw new HistoricalDizyFlowStorageError("CONTENT_CONFLICT","This deterministic memory ID already has different content.");return {memory:existing,created:false}}catch(reason){if((reason as NodeJS.ErrnoException).code!=="ENOENT")throw reason}const encoded=`${JSON.stringify(validated,null,2)}\n`,bytes=Buffer.byteLength(encoded);if(bytes>HISTORICAL_DIZYFLOW_LIMITS.maximumMemoryBytes)throw new HistoricalDizyFlowStorageError("MEMORY_TOO_LARGE","Historical DizyFlow memory exceeds its byte limit.");const files=(await readdir(dir)).filter(x=>/^hdf1_[a-f0-9]{40}\.json$/.test(x));if(files.length>=HISTORICAL_DIZYFLOW_LIMITS.maximumMemoriesPerUser)throw new HistoricalDizyFlowStorageError("MEMORY_LIMIT","Historical DizyFlow memory count limit reached.");let total=0;for(const file of files)total+=(await stat(join(dir,file))).size;if(total+bytes>HISTORICAL_DIZYFLOW_LIMITS.maximumTotalBytesPerUser)throw new HistoricalDizyFlowStorageError("STORAGE_LIMIT","Historical DizyFlow storage limit reached.");const temp=`${target}.${process.pid}.${Date.now()}.tmp`;try{await writeFile(temp,encoded,{mode:0o600,flag:"wx"});await rename(temp,target)}catch(reason){await unlink(temp).catch(()=>undefined);throw reason}return {memory:validated,created:true}})}
export async function readHistoricalDizyFlowMemory(userId:string,id:string){try{const raw=await readFile(filename(userId,id),"utf8");if(Buffer.byteLength(raw)>HISTORICAL_DIZYFLOW_LIMITS.maximumMemoryBytes)throw new HistoricalDizyFlowStorageError("MEMORY_TOO_LARGE","Stored memory exceeds its byte limit.");return validateHistoricalDizyFlowMemory(JSON.parse(raw))}catch(reason){if((reason as NodeJS.ErrnoException).code==="ENOENT")return null;throw reason}}
export async function deleteHistoricalDizyFlowMemory(userId:string,id:string){return serial(userId,async()=>{try{await unlink(filename(userId,id));return true}catch(reason){if((reason as NodeJS.ErrnoException).code==="ENOENT")return false;throw reason}})}
/** Cleanup callers must supply the authoritative union of Paper, Journal and future Brain references. */
export async function cleanupUnreferencedHistoricalDizyFlow(userId:string,referencedIds:ReadonlySet<string>){return serial(userId,async()=>{const dir=directory(userId);let files:string[];try{files=await readdir(dir)}catch(reason){if((reason as NodeJS.ErrnoException).code==="ENOENT")return {deleted:0};throw reason}let deleted=0;for(const file of files.filter(x=>/^hdf1_[a-f0-9]{40}\.json$/.test(x))){const id=file.slice(0,-5);if(!referencedIds.has(id)){await unlink(join(dir,file));deleted++}}return {deleted}})}
