import type { HistoricalDizyFlowDraft, HistoricalDizyFlowEvent, HistoricalDizyFlowSample } from "./historical-dizyflow";

export type HistoricalDizyFlowCaptureState="buffering"|"active"|"awaiting-post-exit"|"finalizing"|"completed"|"interrupted"|"failed";
export type HistoricalDizyFlowCaptureIdentity=Readonly<{tradeId:string;marketKey:string;symbol:string;marketType:"spot"|"futures";entryTimeMs:number}>;
export type HistoricalDizyFlowCaptureConfig=Readonly<{enabled:boolean;preEntryMs:number;postExitMs:number;sampleCadenceMs:number;maximumSamples:number;maximumEvents:number}>;
export const DEFAULT_HISTORICAL_DIZYFLOW_CAPTURE_CONFIG:HistoricalDizyFlowCaptureConfig=Object.freeze({enabled:true,preEntryMs:30_000,postExitMs:15_000,sampleCadenceMs:1_000,maximumSamples:3_600,maximumEvents:1_000});
type Session={identity:HistoricalDizyFlowCaptureIdentity;state:HistoricalDizyFlowCaptureState;captureStartMs:number;exitTimeMs:number|null;captureEndMs:number|null;samples:HistoricalDizyFlowSample[];events:HistoricalDizyFlowEvent[];eventIds:Set<string>;lastSample:HistoricalDizyFlowSample|null;limitations:Set<string>;sampleLimitReached:boolean;eventLimitReached:boolean;skippedDuplicates:number};

/** One terminal/user manager. It retains only already-observed compact samples and never fetches history. */
export class HistoricalDizyFlowCaptureManager {
  private buffer:HistoricalDizyFlowSample[]=[];private session:Session|null=null;
  constructor(private readonly config=DEFAULT_HISTORICAL_DIZYFLOW_CAPTURE_CONFIG){}
  observe(sample:HistoricalDizyFlowSample,market:{marketKey:string;symbol:string},events:readonly HistoricalDizyFlowEvent[]=[]){this.buffer.push(sample);this.buffer=this.buffer.filter(x=>x.timeMs>=sample.timeMs-this.config.preEntryMs).slice(-Math.ceil(this.config.preEntryMs/this.config.sampleCadenceMs)-2);const session=this.session;if(!session||session.state==="completed"||session.state==="interrupted"||market.marketKey!==session.identity.marketKey||market.symbol!==session.identity.symbol)return false;if(session.captureEndMs!==null&&sample.timeMs>session.captureEndMs)return false;const transition=session.lastSample?.availability!==sample.availability;if(session.lastSample&&sample.timeMs-session.lastSample.timeMs<this.config.sampleCadenceMs&&!transition)return false;if(session.lastSample?.inputHash===sample.inputHash&&!transition){session.skippedDuplicates++;return false}this.retainSample(session,sample);for(const event of events)this.retainEvent(session,event);if(session.state==="awaiting-post-exit"&&session.captureEndMs!==null&&sample.timeMs>=session.captureEndMs)session.state="finalizing";return true}
  open(identity:HistoricalDizyFlowCaptureIdentity){if(!this.config.enabled)return false;if(this.session&&["active","awaiting-post-exit","finalizing"].includes(this.session.state))throw new Error("A Historical DizyFlow capture is already active.");const eligible=this.buffer.filter(x=>x.timeMs>=identity.entryTimeMs-this.config.preEntryMs&&x.timeMs<=identity.entryTimeMs),captureStartMs=eligible[0]?.timeMs??identity.entryTimeMs;this.session={identity,state:"active",captureStartMs,exitTimeMs:null,captureEndMs:null,samples:[],events:[],eventIds:new Set(),lastSample:null,limitations:new Set(eligible.length?[]:["pre-entry-unavailable"]),sampleLimitReached:false,eventLimitReached:false,skippedDuplicates:0};for(const sample of eligible)this.retainSample(this.session,sample);return true}
  partialClose(){return this.session?.state==="active"}
  fullClose(exitTimeMs:number){const session=this.requireActive();session.exitTimeMs=exitTimeMs;session.captureEndMs=exitTimeMs+this.config.postExitMs;session.state=this.config.postExitMs?"awaiting-post-exit":"finalizing";return session.state}
  interrupt(code="capture-interrupted"){if(this.session){this.session.limitations.add(code);this.session.state="interrupted"}}
  ready(nowMs:number){const session=this.session;if(session?.state==="awaiting-post-exit"&&session.captureEndMs!==null&&nowMs>=session.captureEndMs)session.state="finalizing";return session?.state==="finalizing"}
  finalise():HistoricalDizyFlowDraft {const s=this.session;if(!s||s.exitTimeMs===null||s.captureEndMs===null||!(s.state==="finalizing"||s.state==="interrupted"))throw new Error("Capture is not ready to finalize.");if(!s.samples.some(x=>x.timeMs<=s.identity.entryTimeMs))s.limitations.add("entry-not-covered");if(!s.samples.some(x=>x.timeMs>=s.exitTimeMs!))s.limitations.add("exit-not-covered");const end=s.state==="interrupted"?Math.max(s.exitTimeMs,s.samples.at(-1)?.timeMs??s.exitTimeMs):s.captureEndMs;s.state="completed";return Object.freeze({...s.identity,journalEntryId:null,exitTimeMs:s.exitTimeMs,captureStartMs:s.captureStartMs,captureEndMs:end,requestedPreEntryMs:this.config.preEntryMs,requestedPostExitMs:this.config.postExitMs,samples:Object.freeze([...s.samples]),events:Object.freeze([...s.events]),limitations:Object.freeze([...s.limitations].sort()),sampleLimitReached:s.sampleLimitReached,eventLimitReached:s.eventLimitReached})}
  status(){const s=this.session;return Object.freeze({state:s?.state??(this.config.enabled?"buffering":"completed"),tradeId:s?.identity.tradeId??null,marketKey:s?.identity.marketKey??null,symbol:s?.identity.symbol??null,sampleCount:s?.samples.length??0,eventCount:s?.events.length??0,skippedDuplicates:s?.skippedDuplicates??0,sampleLimitReached:s?.sampleLimitReached??false,eventLimitReached:s?.eventLimitReached??false})}
  private requireActive(){if(!this.session||this.session.state!=="active")throw new Error("No active Historical DizyFlow capture.");return this.session}
  private retainSample(s:Session,sample:HistoricalDizyFlowSample){if(s.samples.length>=this.config.maximumSamples){s.sampleLimitReached=true;s.limitations.add("sample-limit-reached");return}s.samples.push(sample);s.lastSample=sample}
  private retainEvent(s:Session,event:HistoricalDizyFlowEvent){if(s.eventIds.has(event.id))return;if(s.events.length>=this.config.maximumEvents){s.eventLimitReached=true;s.limitations.add("event-limit-reached");return}s.eventIds.add(event.id);s.events.push(event);s.events.sort((a,b)=>a.timeMs-b.timeMs||a.id.localeCompare(b.id))}
}
