import { JOURNAL_SCHEMA_VERSION, JOURNAL_TAG_LENGTH_MAX, JOURNAL_TAG_MAX, JOURNAL_TITLE_MAX, REFLECTION_PROMPTS, type JournalEntry, type JournalEntryType, type TradeSnapshot } from "./journal-model";

export class JournalValidationError extends Error { constructor(public field: string, message: string) { super(message); } }
const fail = (field:string, message:string):never => { throw new JournalValidationError(field, message); };
const text = (value:unknown, field:string, max:number, required=true) => { if(typeof value!=="string") return required?fail(field,`${field} is required.`):""; const clean=value.trim(); if(required&&!clean)return fail(field,`${field} is required.`); if(clean.length>max)return fail(field,`${field} is too long (maximum ${max} characters).`); return clean; };
const finite = (value:unknown, field:string, nullable=false) => value===null&&nullable?null:typeof value==="number"&&Number.isFinite(value)?value:fail(field,`${field} must be a finite number.`);
const oneOf = <T extends string>(value:unknown, field:string, values:readonly T[], nullable=true):T|null => value==null&&nullable?null:typeof value==="string"&&values.includes(value as T)?value as T:fail(field,`Invalid ${field}.`);
export const sanitiseTags=(value:unknown)=>{if(!Array.isArray(value))return [];if(value.length>JOURNAL_TAG_MAX)fail("tags",`Use no more than ${JOURNAL_TAG_MAX} tags.`);const result:string[]=[];for(const raw of value){const tag=text(raw,"tag",JOURNAL_TAG_LENGTH_MAX);if(!result.some(existing=>existing.toLocaleLowerCase()===tag.toLocaleLowerCase()))result.push(tag);}return result;};
export const validJournalMarketKey=(value:unknown):value is string=>typeof value==="string"&&/^mexc:(?:spot|futures):[A-Z0-9_]{1,40}$/.test(value);

export function validateTradeSnapshot(input:unknown):TradeSnapshot {
  if(!input||typeof input!=="object")fail("trade","Completed trade data is required."); const v=input as Record<string,unknown>;
  const direction=oneOf(v.direction,"direction",["long","short"] as const,false)!; const marginMode=oneOf(v.marginMode,"marginMode",["isolated","cross"] as const);
  const replay=v.replay&&typeof v.replay==="object"?v.replay as Record<string,unknown>:null; const brain=v.brain&&typeof v.brain==="object"?v.brain as Record<string,unknown>:null; const signal=v.signal&&typeof v.signal==="object"?v.signal as Record<string,unknown>:null;
  return Object.freeze({tradeId:text(v.tradeId,"tradeId",300),symbol:text(v.symbol,"symbol",40),market:text(v.market,"market",80),timeframe:text(v.timeframe,"timeframe",10),direction,
    entry:finite(v.entry,"entry")!,exit:finite(v.exit,"exit")!,stop:finite(v.stop,"stop",true),target:finite(v.target,"target",true),positionSize:finite(v.positionSize,"positionSize",true),riskPct:finite(v.riskPct,"riskPct",true),leverage:finite(v.leverage,"leverage",true),marginMode,
    fees:finite(v.fees,"fees",true),pnl:finite(v.pnl,"pnl")!,pnlPct:finite(v.pnlPct,"pnlPct")!,rMultiple:finite(v.rMultiple,"rMultiple",true),openTime:new Date(text(v.openTime,"openTime",40)).toISOString(),closeTime:new Date(text(v.closeTime,"closeTime",40)).toISOString(),closeReason:text(v.closeReason,"closeReason",80),strategyVersion:v.strategyVersion===null?null:text(v.strategyVersion,"strategyVersion",80),
    replay:replay?Object.freeze({sessionId:text(replay.sessionId,"replay.sessionId",400),marketKey:validJournalMarketKey(replay.marketKey)?replay.marketKey:fail("replay.marketKey","Invalid replay market key."),symbol:text(replay.symbol,"replay.symbol",40),timeframe:text(replay.timeframe,"replay.timeframe",10),entryTimeMs:finite(replay.entryTimeMs,"replay.entryTimeMs")!,available:Boolean(replay.available),source:oneOf(replay.source,"replay.source",["rolling-history","retained-memory","unavailable"] as const)??(replay.available?"rolling-history":"unavailable"),memoryId:replay.memoryId==null?null:text(replay.memoryId,"replay.memoryId",80),capturedRangeStartMs:replay.capturedRangeStartMs==null?null:finite(replay.capturedRangeStartMs,"replay.capturedRangeStartMs",true),capturedRangeEndMs:replay.capturedRangeEndMs==null?null:finite(replay.capturedRangeEndMs,"replay.capturedRangeEndMs",true),candleCount:replay.candleCount==null?null:finite(replay.candleCount,"replay.candleCount",true),integrityWarnings:Array.isArray(replay.integrityWarnings)?Object.freeze(replay.integrityWarnings.filter((x):x is string=>typeof x==="string").slice(0,20)):Object.freeze([]),brainAvailable:replay.brainAvailable===true,flowAvailability:oneOf(replay.flowAvailability,"replay.flowAvailability",["available","partially-available","unavailable","capture-not-supported","error"] as const)??"unavailable"}):null,
    brain:brain?Object.freeze({id:text(brain.id,"brain.id",120),capturedAt:new Date(text(brain.capturedAt,"brain.capturedAt",40)).toISOString(),summary:text(brain.summary,"brain.summary",500)}):null,
    signal:signal?Object.freeze({direction:oneOf(signal.direction,"signal.direction",["long","short"] as const,false)!,signalTime:new Date(text(signal.signalTime,"signal.signalTime",40)).toISOString(),label:text(signal.label,"signal.label",200)}):null,dizyBrainReview:Object.freeze({available:false,reviewId:null,engineVersion:null,generatedAt:null,generatedFromHash:null,reviewConfidence:null})});
}

export function journalCreateFields(input:unknown){if(!input||typeof input!=="object")fail("request","Invalid journal entry.");const v=input as Record<string,unknown>;const type=oneOf(v.type,"type",["trade-review","market-note","general"] as const,false) as JournalEntryType;const trade=type==="trade-review"?validateTradeSnapshot(v.trade):null;if(type!=="trade-review"&&v.trade)fail("trade","Only Trade Reviews can contain trade data.");let marketContext=null;if(type==="market-note"){const m=v.marketContext as Record<string,unknown>|undefined;if(!m)fail("marketContext","Market context is required.");const market=m!;marketContext=Object.freeze({symbol:text(market.symbol,"symbol",40),timeframe:text(market.timeframe,"timeframe",10)});}const title=text(v.title,"title",JOURNAL_TITLE_MAX,false);const notes=typeof v.notes==="string"?v.notes.slice(0,100_000):"";if(type!=="trade-review"&&!title&&!notes.trim())fail("notes","Add a title or notes before creating this entry.");return {schemaVersion:JOURNAL_SCHEMA_VERSION,type,title,archived:false,archivedAt:null,trade,marketContext,notes,tags:sanitiseTags(v.tags),quality:type==="trade-review"?oneOf(v.quality,"quality",["good","mixed","poor"] as const):null,planDiscipline:type==="trade-review"?oneOf(v.planDiscipline,"planDiscipline",["completely","mostly","no"] as const):null,mood:type==="trade-review"?oneOf(v.mood,"mood",["calm","confident","patient","hesitant","fearful","greedy","fomo","frustrated","revenge"] as const):null,dismissedPrompts:[]};}
export function journalEditableFields(input:unknown,entry:JournalEntry){if(!input||typeof input!=="object")fail("request","Invalid update.");const v=input as Record<string,unknown>;const dismissed=v.dismissedPrompts===undefined?entry.dismissedPrompts:Array.isArray(v.dismissedPrompts)?v.dismissedPrompts.filter((x):x is string=>typeof x==="string"&&REFLECTION_PROMPTS.includes(x)).slice(0,REFLECTION_PROMPTS.length):fail("dismissedPrompts","Invalid dismissed prompts.");return {...entry,title:v.title===undefined?entry.title:text(v.title,"title",JOURNAL_TITLE_MAX,false),notes:typeof v.notes==="string"?v.notes.slice(0,100_000):entry.notes,tags:v.tags===undefined?entry.tags:sanitiseTags(v.tags),dismissedPrompts:dismissed,quality:entry.type==="trade-review"&&v.quality!==undefined?oneOf(v.quality,"quality",["good","mixed","poor"] as const):entry.quality,planDiscipline:entry.type==="trade-review"&&v.planDiscipline!==undefined?oneOf(v.planDiscipline,"planDiscipline",["completely","mostly","no"] as const):entry.planDiscipline,mood:entry.type==="trade-review"&&v.mood!==undefined?oneOf(v.mood,"mood",["calm","confident","patient","hesitant","fearful","greedy","fomo","frustrated","revenge"] as const):entry.mood};}
