import type { JournalEntry, Mood, PlanDiscipline, TradeQuality } from "./journal-model";

export type JournalSampleLevel = "unavailable" | "very-small" | "limited" | "larger";
export type JournalStatsWarning = Readonly<{ code: "NO_DATA" | "VERY_SMALL_SAMPLE" | "LIMITED_SAMPLE" | "OVERLAPPING_TAGS"; level: JournalSampleLevel; message: string }>;
export type JournalStatsBucket = Readonly<{ key:string; label:string; sampleSize:number; wins:number; losses:number; flat:number; winRatePct:number|null; netPnl:number; averagePnl:number|null; averagePnlPct:number|null; averageR:number|null; rSampleSize:number; sampleLevel:JournalSampleLevel }>;
export type JournalTagStatsBucket = JournalStatsBucket;
export type JournalPeriodStats = Readonly<{ key:string; label:string; reviewedTrades:number; wins:number; losses:number; flat:number; netPnl:number; qualityCoverage:number; disciplineCoverage:number; sampleLevel:JournalSampleLevel }>;
export type JournalStatistics = Readonly<{ generatedAt:string; includesArchived:boolean; currencyLabel:string; reviewedTrades:number; wins:number; losses:number; flat:number; winRatePct:number|null; netPnl:number; averagePnl:number|null; averagePnlPct:number|null; averageR:number|null; rSampleSize:number; goodLosingTrades:number; poorWinningTrades:number; qualityCoverage:number; disciplineCoverage:number; moodCoverage:number; taggedTradeCoverage:number; notesCoverage:number; byQuality:readonly JournalStatsBucket[]; byPlanDiscipline:readonly JournalStatsBucket[]; byMood:readonly JournalStatsBucket[]; byTag:readonly JournalTagStatsBucket[]; overTime:readonly JournalPeriodStats[]; warnings:readonly JournalStatsWarning[] }>;

type Acc={key:string;label:string;n:number;wins:number;losses:number;flat:number;pnl:number;pnlPct:number;pnlPctN:number;r:number;rN:number;qualityN:number;disciplineN:number};
const acc=(key:string,label:string):Acc=>({key,label,n:0,wins:0,losses:0,flat:0,pnl:0,pnlPct:0,pnlPctN:0,r:0,rN:0,qualityN:0,disciplineN:0});
const finite=(value:unknown):value is number=>typeof value==="number"&&Number.isFinite(value);
export const journalSampleLevel=(n:number):JournalSampleLevel=>n===0?"unavailable":n<5?"very-small":n<20?"limited":"larger";
const add=(a:Acc,pnl:number,pnlPct:number|null,r:number|null,quality:boolean,discipline:boolean)=>{a.n++;a.pnl+=pnl;if(pnl>0)a.wins++;else if(pnl<0)a.losses++;else a.flat++;if(pnlPct!==null){a.pnlPct+=pnlPct;a.pnlPctN++;}if(r!==null){a.r+=r;a.rN++;}if(quality)a.qualityN++;if(discipline)a.disciplineN++;};
const bucket=(a:Acc):JournalStatsBucket=>({key:a.key,label:a.label,sampleSize:a.n,wins:a.wins,losses:a.losses,flat:a.flat,winRatePct:a.n?a.wins/a.n*100:null,netPnl:a.pnl,averagePnl:a.n?a.pnl/a.n:null,averagePnlPct:a.pnlPctN?a.pnlPct/a.pnlPctN:null,averageR:a.rN?a.r/a.rN:null,rSampleSize:a.rN,sampleLevel:journalSampleLevel(a.n)});
const coverage=(n:number,total:number)=>total?n/total*100:0;
const qualityLabels:Record<TradeQuality|string,string>={good:"Good Trade",mixed:"Mixed",poor:"Poor Trade",unassessed:"Not assessed"};
const disciplineLabels:Record<PlanDiscipline|string,string>={completely:"Completely",mostly:"Mostly",no:"No",unassessed:"Not assessed"};
const moodLabels:Record<Mood|string,string>={calm:"Calm",confident:"Confident",patient:"Patient",hesitant:"Hesitant",fearful:"Fearful",greedy:"Greedy",fomo:"FOMO",frustrated:"Frustrated",revenge:"Revenge",unrecorded:"Not recorded"};
const qualityKeys=["good","mixed","poor","unassessed"] as const,disciplineKeys=["completely","mostly","no","unassessed"] as const,moodKeys=["calm","confident","patient","hesitant","fearful","greedy","fomo","frustrated","revenge","unrecorded"] as const;
const monthKey=(iso:string)=>{const date=new Date(iso);return Number.isFinite(date.getTime())?date.toISOString().slice(0,7):null;};
const monthLabel=(key:string)=>new Intl.DateTimeFormat("en",{month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${key}-01T00:00:00.000Z`));

/** Pure bounded aggregation. Calendar months and labels use UTC; missing/non-finite facts remain unavailable. */
export function aggregateJournalStatistics(entries:readonly JournalEntry[],options:Readonly<{includeArchived?:boolean;generatedAt?:string}>={}):JournalStatistics{
 const includeArchived=options.includeArchived===true,total=acc("overall","Overall"),quality=new Map(qualityKeys.map(k=>[k,acc(k,qualityLabels[k])])),discipline=new Map(disciplineKeys.map(k=>[k,acc(k,disciplineLabels[k])])),mood=new Map(moodKeys.map(k=>[k,acc(k,moodLabels[k])])),tags=new Map<string,Acc>(),periods=new Map<string,Acc>();let qualityN=0,disciplineN=0,moodN=0,taggedN=0,notesN=0,goodLosingTrades=0,poorWinningTrades=0;
 for(const entry of entries){if(entry?.type!=="trade-review"||!entry.trade||(!includeArchived&&entry.archived))continue;if(!finite(entry.trade.pnl))continue;const pnl=entry.trade.pnl,pnlPct=finite(entry.trade.pnlPct)?entry.trade.pnlPct:null,r=finite(entry.trade.rMultiple)?entry.trade.rMultiple:null,q=qualityKeys.includes(entry.quality as never)?entry.quality!:"unassessed",d=disciplineKeys.includes(entry.planDiscipline as never)?entry.planDiscipline!:"unassessed",m=moodKeys.includes(entry.mood as never)?entry.mood!:"unrecorded",hasQ=q!=="unassessed",hasD=d!=="unassessed";add(total,pnl,pnlPct,r,hasQ,hasD);add(quality.get(q)!,pnl,pnlPct,r,hasQ,hasD);add(discipline.get(d)!,pnl,pnlPct,r,hasQ,hasD);add(mood.get(m)!,pnl,pnlPct,r,hasQ,hasD);if(hasQ)qualityN++;if(hasD)disciplineN++;if(m!=="unrecorded")moodN++;if(typeof entry.notes==="string"&&entry.notes.trim())notesN++;if(q==="good"&&pnl<0)goodLosingTrades++;if(q==="poor"&&pnl>0)poorWinningTrades++;
  const seen=new Set<string>();for(const raw of Array.isArray(entry.tags)?entry.tags:[]){if(typeof raw!=="string")continue;const label=raw.trim(),key=label.toLocaleLowerCase();if(!label||seen.has(key))continue;seen.add(key);let a=tags.get(key);if(!a){a=acc(key,label);tags.set(key,a);}add(a,pnl,pnlPct,r,hasQ,hasD);}if(seen.size)taggedN++;
  const key=monthKey(entry.trade.closeTime);if(key){let a=periods.get(key);if(!a){a=acc(key,monthLabel(key));periods.set(key,a);}add(a,pnl,pnlPct,r,hasQ,hasD);}
 }
 const overall=bucket(total),level=journalSampleLevel(total.n),warnings:JournalStatsWarning[]=level==="unavailable"?[{code:"NO_DATA",level,message:"No completed Trade Reviews are available for these statistics."}]:level==="very-small"?[{code:"VERY_SMALL_SAMPLE",level,message:"Small sample: treat this as a review prompt, not a reliable conclusion."}]:level==="limited"?[{code:"LIMITED_SAMPLE",level,message:"Limited sample: these patterns are descriptive and may change as more trades are reviewed."}]:[];if(tags.size)warnings.push({code:"OVERLAPPING_TAGS",level,message:"Tag buckets overlap because one trade can have multiple tags; overall totals count each trade once."});
 return {reviewedTrades:overall.sampleSize,wins:overall.wins,losses:overall.losses,flat:overall.flat,winRatePct:overall.winRatePct,netPnl:overall.netPnl,averagePnl:overall.averagePnl,averagePnlPct:overall.averagePnlPct,averageR:overall.averageR,rSampleSize:overall.rSampleSize,generatedAt:options.generatedAt??"1970-01-01T00:00:00.000Z",includesArchived:includeArchived,currencyLabel:"USDT simulation",goodLosingTrades,poorWinningTrades,qualityCoverage:coverage(qualityN,total.n),disciplineCoverage:coverage(disciplineN,total.n),moodCoverage:coverage(moodN,total.n),taggedTradeCoverage:coverage(taggedN,total.n),notesCoverage:coverage(notesN,total.n),byQuality:[...quality.values()].map(bucket),byPlanDiscipline:[...discipline.values()].map(bucket),byMood:[...mood.values()].map(bucket),byTag:[...tags.values()].map(bucket).sort((a,b)=>b.sampleSize-a.sampleSize||a.label.localeCompare(b.label)),overTime:[...periods.values()].sort((a,b)=>a.key.localeCompare(b.key)).map(a=>({key:a.key,label:a.label,reviewedTrades:a.n,wins:a.wins,losses:a.losses,flat:a.flat,netPnl:a.pnl,qualityCoverage:coverage(a.qualityN,a.n),disciplineCoverage:coverage(a.disciplineN,a.n),sampleLevel:journalSampleLevel(a.n)})),warnings};
}

export type JournalTagSort="sample-size"|"net-pnl"|"win-rate"|"alphabetical";
export function presentJournalTags(tags:readonly JournalTagStatsBucket[],sort:JournalTagSort="sample-size",search="",limit=50){const needle=search.trim().toLocaleLowerCase(),copy=tags.filter(tag=>!needle||tag.label.toLocaleLowerCase().includes(needle));copy.sort(sort==="net-pnl"?(a,b)=>b.netPnl-a.netPnl||a.label.localeCompare(b.label):sort==="win-rate"?(a,b)=>(b.winRatePct??-Infinity)-(a.winRatePct??-Infinity)||a.label.localeCompare(b.label):sort==="alphabetical"?(a,b)=>a.label.localeCompare(b.label):(a,b)=>b.sampleSize-a.sampleSize||a.label.localeCompare(b.label));return copy.slice(0,Math.max(0,Math.min(100,limit)));}
