import "server-only";
import { randomUUID } from "node:crypto";
import { mkdir,readFile,rename,writeFile } from "node:fs/promises";
import { join } from "node:path";

export type ManualSide="long"|"short";
export type ManualPosition={symbol:string;side:ManualSide;quantity:number;entryPrice:number;leverage:number;stopLoss:number|null;takeProfit:number|null;openedAt:string};
export type ManualFill={orderId:string;fillId:string;idempotencyKey:string;userId:string;symbol:string;side:ManualSide|"close";price:number;quantity:number;notional:number;fee:number;timestamp:string;realisedPnl:number;resultingBalance:number};
export type ManualAccount={version:1;cashBalance:number;startingBalance:number;realisedPnl:number;fees:number;positions:Record<string,ManualPosition>;fills:ManualFill[];idempotencyKeys:string[];settings:{commissionPct:number;slippagePct:number;allowAdding:boolean;confirmationRequired:boolean};updatedAt:string};
export const newManualAccount=():ManualAccount=>({version:1,cashBalance:10_000,startingBalance:10_000,realisedPnl:0,fees:0,positions:{},fills:[],idempotencyKeys:[],settings:{commissionPct:.06,slippagePct:.02,allowAdding:false,confirmationRequired:true},updatedAt:new Date(0).toISOString()});
const finite=(v:unknown,min:number,max:number)=>{const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:null};
const root=()=>process.env.DATA_DIR||join(process.cwd(),".data"),safe=(id:string)=>id.replace(/[^a-z0-9_-]/gi,""),path=(id:string)=>join(root(),"manual-paper",`${safe(id)}.json`);
export async function readManualAccount(userId:string){try{const raw=JSON.parse(await readFile(path(userId),"utf8")) as ManualAccount;if(raw.version!==1)throw new Error("schema");return raw;}catch{return newManualAccount();}}
async function writeManualAccount(userId:string,value:ManualAccount){await mkdir(join(root(),"manual-paper"),{recursive:true});const target=path(userId),temp=`${target}.${process.pid}.${Date.now()}.tmp`;await writeFile(temp,JSON.stringify(value,null,2)+"\n",{mode:0o600});await rename(temp,target);}
const queues=new Map<string,Promise<unknown>>();async function serial<T>(userId:string,fn:()=>Promise<T>):Promise<T>{const previous=queues.get(userId)??Promise.resolve();let release!:()=>void;const gate=new Promise<void>(r=>release=r);queues.set(userId,previous.then(()=>gate));await previous;try{return await fn();}finally{release();if(queues.get(userId)===gate)queues.delete(userId);}}
export async function latestPublicPrice(symbol:string){if(!/^[A-Z0-9]{1,20}_[A-Z0-9]{1,20}$/.test(symbol))throw new Error("Invalid symbol");const response=await fetch(`https://contract.mexc.com/api/v1/contract/ticker?symbol=${encodeURIComponent(symbol)}`,{signal:AbortSignal.timeout(5000),cache:"no-store"});if(!response.ok)throw new Error("Public price unavailable");const body=await response.json() as {data?:{fairPrice?:unknown;lastPrice?:unknown}};const price=finite(body.data?.fairPrice??body.data?.lastPrice,0.00000001,1e12);if(!price)throw new Error("Public price unavailable");return price;}
export async function submitManualOrder(userId:string,input:{idempotencyKey:string;symbol:string;side:ManualSide;sizeMode:"fixed"|"percent";amount:number;leverage?:number;stopLoss?:number|null;takeProfit?:number|null;confirmReverse?:boolean},marketPrice:number){return serial(userId,async()=>{const account=await readManualAccount(userId);if(!/^[a-zA-Z0-9_-]{16,100}$/.test(input.idempotencyKey))throw new Error("Invalid idempotency key");if(account.idempotencyKeys.includes(input.idempotencyKey))throw new Error("Duplicate idempotency key");const amount=finite(input.amount,.01,1_000_000),leverage=finite(input.leverage??1,1,20),price=finite(marketPrice,.00000001,1e12);if(!amount||!leverage||!price)throw new Error("Invalid order sizing");const existing=account.positions[input.symbol];if(existing?.side===input.side&&!account.settings.allowAdding)throw new Error("Same-side position already exists");if(existing&&existing.side!==input.side&&!input.confirmReverse)throw new Error("Reversal confirmation required");if(existing)closeAt(account,userId,input.symbol,price,input.idempotencyKey+":close");const base=input.sizeMode==="percent"?account.cashBalance*amount/100:amount,notional=base*leverage;if(notional<=0||notional>account.cashBalance*leverage)throw new Error("Insufficient manual paper equity");const slipped=price*(1+(input.side==="long"?1:-1)*account.settings.slippagePct/100),quantity=notional/slipped,fee=notional*account.settings.commissionPct/100;account.cashBalance-=fee;account.fees+=fee;const orderId=randomUUID(),timestamp=new Date().toISOString();account.positions[input.symbol]={symbol:input.symbol,side:input.side,quantity,entryPrice:slipped,leverage,stopLoss:input.stopLoss??null,takeProfit:input.takeProfit??null,openedAt:timestamp};account.fills.push({orderId,fillId:randomUUID(),idempotencyKey:input.idempotencyKey,userId,symbol:input.symbol,side:input.side,price:slipped,quantity,notional,fee,timestamp,realisedPnl:0,resultingBalance:account.cashBalance});account.idempotencyKeys.push(input.idempotencyKey);account.fills=account.fills.slice(-500);account.idempotencyKeys=account.idempotencyKeys.slice(-1000);account.updatedAt=timestamp;await writeManualAccount(userId,account);return account;});}
function closeAt(account:ManualAccount,userId:string,symbol:string,marketPrice:number,key:string){const position=account.positions[symbol];if(!position)throw new Error("No manual position");const slipped=marketPrice*(1+(position.side==="long"?-1:1)*account.settings.slippagePct/100),notional=position.quantity*slipped,fee=notional*account.settings.commissionPct/100,pnl=(slipped-position.entryPrice)*position.quantity*(position.side==="long"?1:-1);account.cashBalance+=pnl-fee;account.realisedPnl+=pnl;account.fees+=fee;account.fills.push({orderId:randomUUID(),fillId:randomUUID(),idempotencyKey:key,userId,symbol,side:"close",price:slipped,quantity:position.quantity,notional,fee,timestamp:new Date().toISOString(),realisedPnl:pnl,resultingBalance:account.cashBalance});delete account.positions[symbol];}
export async function closeManualPosition(userId:string,symbol:string,key:string,marketPrice:number){return serial(userId,async()=>{const account=await readManualAccount(userId);if(account.idempotencyKeys.includes(key))throw new Error("Duplicate idempotency key");closeAt(account,userId,symbol,marketPrice,key);account.idempotencyKeys.push(key);account.updatedAt=new Date().toISOString();await writeManualAccount(userId,account);return account;});}
export async function resetManualAccount(userId:string,confirmation:string){if(confirmation!=="RESET MANUAL PAPER")throw new Error("Reset confirmation required");return serial(userId,async()=>{const account=newManualAccount();account.updatedAt=new Date().toISOString();await writeManualAccount(userId,account);return account;});}
