import "server-only";
import { mkdir, open, readFile, readdir, rename, stat, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { MAX_REPLAY_MEMORIES_PER_USER, MAX_REPLAY_MEMORY_BYTES, MAX_REPLAY_MEMORY_BYTES_PER_USER, validateHistoricalReplayMemory, type HistoricalReplayMemory } from "./historical-replay-memory";
const root=()=>process.env.DATA_DIR||join(process.cwd(),".data");
const safe=(value:string)=>{const result=value.replace(/[^a-z0-9_-]/gi,"");if(!result||result!==value)throw new Error("Invalid replay-memory identifier.");return result;};
const directory=(userId:string)=>join(root(),"replay-memory",safe(userId));
const filename=(userId:string,id:string)=>join(directory(userId),`${safe(id)}.json`);
const queues=new Map<string,Promise<unknown>>();async function serial<T>(id:string,fn:()=>Promise<T>){const prior=queues.get(id)??Promise.resolve();let release!:()=>void;const gate=new Promise<void>(r=>release=r),queued=prior.then(()=>gate);queues.set(id,queued);await prior;try{return await fn();}finally{release();if(queues.get(id)===queued)queues.delete(id);}}
export class ReplayMemoryStorageError extends Error {constructor(public code:string,message:string){super(message);}}
export type ReplayMemoryMetadata=Readonly<{id:string;schemaVersion:number;validationVersion:number;contentHash:string;tradeId:string;marketKey:string;symbol:string;timeframe:string;entryTimeMs:number;exitTimeMs:number}>;
const stringField=(text:string,key:string)=>{const match=text.match(new RegExp(`"${key}"\\s*:\\s*"([^"\\\\]+)"`));return match?.[1]??null;};
const numberField=(text:string,key:string)=>{const match=text.match(new RegExp(`"${key}"\\s*:\\s*(-?\\d+)`));return match?Number(match[1]):null;};
/** Reads only bounded header/tail slices. Candle JSON is never parsed or returned. */
export async function readReplayMemoryMetadata(userId:string,id:string):Promise<ReplayMemoryMetadata|null>{let handle;try{const path=filename(userId,id);handle=await open(path,"r");const info=await handle.stat();if(info.size>MAX_REPLAY_MEMORY_BYTES)throw new ReplayMemoryStorageError("MALFORMED_MEMORY_METADATA","Replay memory is oversized.");const headSize=Math.min(info.size,16_384),tailSize=Math.min(info.size,32_768),head=Buffer.alloc(headSize),tail=Buffer.alloc(tailSize);await handle.read(head,0,headSize,0);await handle.read(tail,0,tailSize,Math.max(0,info.size-tailSize));const beforeCandles=head.toString("utf8").split(/"candles"\s*:/,1)[0],afterCandles=tail.toString("utf8");const metadata={id:stringField(beforeCandles,"id"),schemaVersion:numberField(beforeCandles,"schemaVersion"),validationVersion:numberField(afterCandles,"validationVersion"),contentHash:stringField(afterCandles,"contentHash"),tradeId:stringField(beforeCandles,"tradeId"),marketKey:stringField(beforeCandles,"marketKey"),symbol:stringField(beforeCandles,"symbol"),timeframe:stringField(beforeCandles,"timeframe"),entryTimeMs:numberField(beforeCandles,"entryTimeMs"),exitTimeMs:numberField(beforeCandles,"exitTimeMs")};if(metadata.id!==id||metadata.schemaVersion!==1||metadata.validationVersion!==2||!metadata.contentHash||!/^([a-f0-9]{64})$/.test(metadata.contentHash)||!metadata.tradeId||!metadata.marketKey||!metadata.symbol||!metadata.timeframe||!Number.isSafeInteger(metadata.entryTimeMs)||!Number.isSafeInteger(metadata.exitTimeMs))throw new ReplayMemoryStorageError("MALFORMED_MEMORY_METADATA","Replay-memory metadata is malformed.");return Object.freeze(metadata as ReplayMemoryMetadata);}catch(reason){if((reason as NodeJS.ErrnoException).code==="ENOENT")return null;throw reason;}finally{await handle?.close();}}
export async function createReplayMemory(userId:string,memory:HistoricalReplayMemory){return serial(userId,async()=>{const dir=directory(userId),target=filename(userId,memory.id);await mkdir(dir,{recursive:true});try{const existing=validateHistoricalReplayMemory(JSON.parse(await readFile(target,"utf8")));if(existing.integrity.contentHash!==memory.integrity.contentHash)throw new ReplayMemoryStorageError("CONTENT_CONFLICT","The deterministic replay-memory identity already has different candle content.");return {memory:existing,created:false};}catch(reason){if((reason as NodeJS.ErrnoException).code!=="ENOENT")throw reason;}
  const encoded=JSON.stringify(memory,null,2)+"\n",bytes=Buffer.byteLength(encoded);if(bytes>MAX_REPLAY_MEMORY_BYTES)throw new ReplayMemoryStorageError("MEMORY_TOO_LARGE","Replay memory exceeds its size limit.");const files=(await readdir(dir)).filter(name=>/^hrm1_[a-f0-9]{40}\.json$/.test(name));if(files.length>=MAX_REPLAY_MEMORIES_PER_USER)throw new ReplayMemoryStorageError("MEMORY_LIMIT","Replay-memory count limit reached.");let total=0;for(const file of files)total+=(await stat(join(dir,file))).size;if(total+bytes>MAX_REPLAY_MEMORY_BYTES_PER_USER)throw new ReplayMemoryStorageError("STORAGE_LIMIT","Replay-memory storage limit reached.");const temp=`${target}.${process.pid}.${Date.now()}.tmp`;try{await writeFile(temp,encoded,{mode:0o600,flag:"wx"});await rename(temp,target);}catch(reason){await unlink(temp).catch(()=>undefined);throw reason;}return {memory,created:true};});}
export async function readReplayMemory(userId:string,id:string){try{const raw=await readFile(filename(userId,id),"utf8");if(Buffer.byteLength(raw)>MAX_REPLAY_MEMORY_BYTES)throw new ReplayMemoryStorageError("MALFORMED_MEMORY","Replay memory is oversized.");return validateHistoricalReplayMemory(JSON.parse(raw));}catch(reason){if((reason as NodeJS.ErrnoException).code==="ENOENT")return null;throw reason;}}
export async function deleteReplayMemory(userId:string,id:string){return serial(userId,async()=>{try{await unlink(filename(userId,id));return true;}catch(reason){if((reason as NodeJS.ErrnoException).code==="ENOENT")return false;throw reason;}});}
