"use client";
import { useEffect,useState } from "react";
import type { BehaviourBucket, DizyBrainBehaviourProfile } from "../lib/dizybrain-behaviour";
const percent=(value:number|null)=>value===null?"—":`${value.toFixed(1)}%`;
function Table({caption,rows}:{caption:string;rows:readonly BehaviourBucket[]}){return <div className="stats-table-wrap"><table><caption className="sr-only">{caption}</caption><thead><tr><th>Recorded classification</th><th>Reviews</th><th>Eligible sample</th><th>Evidence completeness</th></tr></thead><tbody>{rows.map(row=><tr key={row.key}><th>{row.label}</th><td>{row.count} · {percent(row.percentage)}</td><td><span className={`sample ${row.sampleBand}`} title={row.sampleWarning??`${row.sampleBand} descriptive sample`}>{row.sampleBand}</span></td><td>{percent(row.averageEvidenceCompleteness)}</td></tr>)}</tbody></table></div>}
export default function JournalBehaviourView(){const [profile,setProfile]=useState<DizyBrainBehaviourProfile|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[archived,setArchived]=useState(false);useEffect(()=>{const controller=new AbortController();void fetch(`/api/dizybrain/behaviour${archived?"?archived=true":""}`,{signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error?.message??"Behaviour profile could not be loaded.");setProfile(body.profile);}).catch(reason=>{if(reason.name!=="AbortError")setError(reason.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[archived]);if(loading)return <section className="statistics-state" aria-live="polite">Building deterministic Behaviour profile…</section>;if(error)return <section className="statistics-state" role="alert">{error}</section>;if(!profile)return null;const findings=[...profile.findings.warning,...profile.findings.caution,...profile.findings.positive,...profile.findings.neutral];return <div className="statistics behaviour"><header className="statistics-header"><div><h1>DizyBrain Behaviour</h1><p>Deterministic patterns across your completed historical trade reviews.</p></div><label><input type="checkbox" checked={archived} onChange={event=>{setLoading(true);setError("");setArchived(event.target.checked)}}/> Include archived</label></header><p className="stats-disclaimer">These observations describe recorded history. They do not predict future results or establish causation.</p>{profile.sample.warning?<p className={`stats-warning ${profile.sample.band}`}>{profile.sample.warning}</p>:null}
 <section className="stats-section"><header><h2>Coverage &amp; sample quality</h2><p>Excluded evidence remains visible and never becomes weak execution.</p></header><div className="stats-cards">{Object.entries({"Journal Trade Reviews":profile.coverage.totalJournalTradeReviews,"Generated reviews":profile.coverage.generatedReviews,"Eligible current":profile.coverage.eligibleCurrentReviews,"Stale excluded":profile.coverage.staleReviews,"Missing":profile.coverage.missingReviews,"Invalid":profile.coverage.invalidReviews,"Archived excluded":profile.coverage.archivedExcluded,"Review coverage":percent(profile.coverage.reviewCoveragePct),"Quality assessed":percent(profile.coverage.qualityAssessmentCoveragePct),"Plan assessed":percent(profile.coverage.planAssessmentCoveragePct),"Mood recorded":percent(profile.coverage.moodCoveragePct),"Tags recorded":percent(profile.coverage.tagCoveragePct)}).map(([label,value])=><article key={label}><h3>{label}</h3><strong>{value}</strong></article>)}</div></section>
 <section className="stats-section"><header><h2>Observed strengths</h2><p>Process-focused recurring evidence, not a permanent label.</p></header>{profile.strengths.length?profile.strengths.map(x=><p key={x.code}>{x.label} <span className="sample">{x.qualification}</span></p>):<p className="stats-empty">No strength meets the conservative recurrence threshold.</p>}</section>
 <section className="stats-section"><header><h2>Review areas</h2><p>Descriptive prompts only; no recommendation or future claim.</p></header>{profile.reviewAreas.length?profile.reviewAreas.map(x=><p key={x.code}>{x.label} <span className="sample">{x.qualification}</span></p>):<p className="stats-empty">No review area meets the conservative recurrence threshold.</p>}</section>
 <section className="stats-section"><header><h2>Execution patterns</h2><p>Unavailable evidence is separate from weak execution.</p></header><h3>Entry timing</h3><Table caption="Entry timing distribution" rows={profile.execution.entry}/><h3>Risk execution</h3><Table caption="Risk execution distribution" rows={profile.execution.risk}/><h3>Exit execution</h3><Table caption="Exit execution distribution" rows={profile.execution.exit}/></section>
 <section className="stats-section"><header><h2>Recurring findings</h2><p>Stable finding codes count at most once per review.</p></header><div className="stats-table-wrap"><table><caption className="sr-only">Aggregated DizyBrain findings</caption><thead><tr><th>Finding</th><th>Severity</th><th>Occurrence</th><th>Markets</th><th>Confidence</th></tr></thead><tbody>{findings.map(x=><tr key={x.code}><th>{x.title}<small>{x.code}</small></th><td>{x.severity}</td><td>{x.occurrenceCount} · {percent(x.occurrencePct)} · {x.recurrence}</td><td>{x.symbols.join(", ")} · {x.timeframes.join(", ")}</td><td>{percent(x.averageReviewConfidence)}</td></tr>)}</tbody></table></div></section>
 <section className="stats-section"><header><h2>Process vs outcome</h2><p>Recorded decision quality and financial outcome are separate dimensions.</p></header><div className="stats-callouts"><p><strong>{profile.process.goodLosingTrades}</strong><br/>Good losing trades</p><p><strong>{profile.process.poorWinningTrades}</strong><br/>Poor winning trades</p></div><Table caption="User-assessed quality" rows={profile.process.quality}/><Table caption="User-recorded plan discipline" rows={profile.process.discipline}/></section>
 <section className="stats-section"><header><h2>Recorded mood, tags, symbols &amp; timeframes</h2><p>Moods are user-recorded. Tag totals overlap. These are reviewed-history summaries, not rankings.</p></header><div className="stats-cards">{[...profile.process.moods,...profile.markets.tags,...profile.markets.symbols,...profile.markets.timeframes].slice(0,24).map((x,index)=><article key={`${x.key}-${index}`}><h3>{x.label}</h3><strong>{x.count}</strong><small>{x.sampleBand} sample · average R {x.averageR??"—"} ({x.rSampleSize})</small></article>)}</div></section>
 <section className="stats-section"><header><h2>UTC time patterns</h2><p>Authoritative trade open time; no local-time assumption.</p></header><Table caption="UTC weekday distribution" rows={profile.timing.weekdays}/></section>
 <section className="stats-section"><header><h2>Behaviour over time</h2><p>Raw monthly values without smoothing, forecasting, or projected continuation.</p></header><div className="stats-table-wrap"><table><caption className="sr-only">Monthly Behaviour history</caption><thead><tr><th>UTC month</th><th>Reviews</th><th>Confidence</th><th>Confirmed entries</th><th>Extended entries</th><th>Warnings/cautions</th></tr></thead><tbody>{profile.trends.periods.map(x=><tr key={x.period}><th>{x.period}</th><td>{x.count} · {x.sampleBand}</td><td>{percent(x.averageReviewConfidence)}</td><td>{percent(x.confirmedEntryPct)}</td><td>{percent(x.extendedEntryPct)}</td><td>{x.cautionWarningFindings}</td></tr>)}</tbody></table></div></section>
 <section className="stats-section"><header><h2>Limitations</h2></header><ul>{profile.limitations.map(x=><li key={x.code}><b>{x.severity}:</b> {x.message}</li>)}</ul></section></div>}
