"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import type { JournalEntry, JournalEntryType, JournalListItem, Mood, PlanDiscipline, TradeQuality } from "../lib/journal-model";
import { REFLECTION_PROMPTS } from "../lib/journal-model";
import "./journal.css";
const qualityLabels:Record<TradeQuality,string>={good:"✅ Good Trade",mixed:"⚠️ Mixed",poor:"❌ Poor Trade"};
const planLabels:Record<PlanDiscipline,string>={completely:"✅ Completely",mostly:"⚠️ Mostly",no:"❌ No"};
const moods:Mood[]=["calm","confident","patient","hesitant","fearful","greedy","fomo","frustrated","revenge"];
const entryLabels:Record<JournalEntryType,string>={"trade-review":"Trade Review","market-note":"Market Note",general:"General Entry"};
const fmt=(value:number)=>`${value>=0?"+":""}${value.toFixed(2)}%`;
export default function JournalClient({readOnly,userName}:{readOnly:boolean;userName:string}){
 const [items,setItems]=useState<JournalListItem[]>([]),[selected,setSelected]=useState<JournalEntry|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[saved,setSaved]=useState(""),[error,setError]=useState("");
 const [search,setSearch]=useState(""),[type,setType]=useState(""),[symbol,setSymbol]=useState(""),[timeframe,setTimeframe]=useState(""),[tag,setTag]=useState(""),[result,setResult]=useState(""),[quality,setQuality]=useState(""),[plan,setPlan]=useState("");
 const notesRef=useRef<HTMLTextAreaElement>(null);
 const load=async()=>{setLoading(true);const response=await fetch("/api/journal");if(response.ok){const body=await response.json() as {entries:JournalListItem[]};setItems(body.entries);}else setError("DizyJournal is unavailable.");setLoading(false);};
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>{const id=new URLSearchParams(location.search).get("entry");if(id)void open(id,true);},0);return()=>window.clearTimeout(timer);},[]);
 async function open(id:string,focus=false){const response=await fetch(`/api/journal/${encodeURIComponent(id)}`);if(!response.ok)return setError("Journal entry could not be opened.");const body=await response.json() as {entry:JournalEntry};setSelected(body.entry);setError("");if(focus)setTimeout(()=>notesRef.current?.focus(),0);}
 async function create(type:JournalEntryType){if(readOnly)return;let body:Record<string,unknown>={type,notes:"",tags:[]};if(type==="market-note"){const symbol=prompt("Symbol (market note)")?.trim().toUpperCase(),timeframe=prompt("Timeframe")?.trim();if(!symbol||!timeframe)return;body={...body,marketContext:{symbol,timeframe}};}const response=await fetch("/api/journal",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)return setError(payload.error?.message??"Entry could not be created.");await load();setSelected(payload.entry);setTimeout(()=>notesRef.current?.focus(),0);}
 async function save(patch:Partial<JournalEntry>={}){if(!selected||readOnly)return;setSaving(true);setSaved("");const response=await fetch(`/api/journal/${selected.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...selected,...patch})});const payload=await response.json();setSaving(false);if(!response.ok)return setError(payload.error?.message??"Changes were not saved.");setSelected(payload.entry);setSaved("Saved");await load();}
 const values=useMemo(()=>({symbols:[...new Set(items.flatMap(x=>x.trade?.symbol??x.marketContext?.symbol??[]))].sort(),timeframes:[...new Set(items.flatMap(x=>x.trade?.timeframe??x.marketContext?.timeframe??[]))].sort(),tags:[...new Set(items.flatMap(x=>x.tags))].sort()}),[items]);
 const filtered=useMemo(()=>items.filter(x=>{const hay=`${x.trade?.symbol??x.marketContext?.symbol??""} ${x.notesPreview} ${x.tags.join(" ")}`.toLowerCase();return (!search||hay.includes(search.toLowerCase()))&&(!type||x.type===type)&&(!symbol||(x.trade?.symbol??x.marketContext?.symbol)===symbol)&&(!timeframe||(x.trade?.timeframe??x.marketContext?.timeframe)===timeframe)&&(!tag||x.tags.includes(tag))&&(!result||(result==="win"?(x.trade?.pnl??0)>0:result==="loss"?(x.trade?.pnl??0)<0:(x.trade?.pnl??1)===0))&&(!quality||x.quality===quality)&&(!plan||x.planDiscipline===plan)}),[items,search,type,symbol,timeframe,tag,result,quality,plan]);
 return <main className="journal-shell"><header className="journal-top"><a href="/terminal"><b>DizyTrades</b><small>Simulation workspace</small></a><nav><a href="/terminal">DizyCharts</a><strong>DizyJournal</strong><span>{userName}{readOnly?" · Viewer":""}</span></nav></header>
 <section className="journal-philosophy"><div><span>PROCESS OVER OUTCOME</span><h1>Judge your decisions, not your outcomes.</h1><p>A good trade is one that followed your trading plan.<br/>A profitable trade is simply one possible outcome.</p></div>{!readOnly?<div className="new-actions"><button onClick={()=>void create("general")}>+ General Entry</button><button onClick={()=>void create("market-note")}>+ Market Note</button></div>:<em>Viewer mode · read only</em>}</section>
 {error?<div className="journal-error" role="alert">{error}<button onClick={()=>setError("")}>Dismiss</button></div>:null}
 <div className="journal-layout"><aside aria-label="Journal filters"><h2>Journal</h2><p>{items.length} entries · newest first</p><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Notes, symbol or tag"/></label>{[["Entry type",type,setType,[["","All types"],["trade-review","Trade Review"],["market-note","Market Note"],["general","General"]]],["Symbol",symbol,setSymbol,[["","All symbols"],...values.symbols.map(x=>[x,x])]], ["Timeframe",timeframe,setTimeframe,[["","All timeframes"],...values.timeframes.map(x=>[x,x])]], ["Tag",tag,setTag,[["","All tags"],...values.tags.map(x=>[x,x])]], ["Result",result,setResult,[["","All results"],["win","Win"],["loss","Loss"],["flat","Flat"]]], ["Trade quality",quality,setQuality,[["","All qualities"],["good","Good Trade"],["mixed","Mixed"],["poor","Poor Trade"]]], ["Plan discipline",plan,setPlan,[["","All discipline"],["completely","Completely"],["mostly","Mostly"],["no","No"]]]].map(([label,value,setter,options])=><label key={label as string}>{label as string}<select value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}>{(options as string[][]).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>)}</aside>
 <section className="journal-list" aria-busy={loading}>{loading?<p>Loading journal…</p>:filtered.length?filtered.map(item=><button className={selected?.id===item.id?"entry-row selected":"entry-row"} onClick={()=>void open(item.id)} key={item.id}><time>{new Date(item.createdAt).toLocaleDateString()}</time><span className="entry-main"><b>{item.trade?`${item.trade.symbol} · ${item.trade.direction}`:item.marketContext?`${item.marketContext.symbol} · ${item.marketContext.timeframe}`:entryLabels[item.type]}</b><small>{item.notesPreview||"No notes yet"}</small><i>{item.tags.map(x=><em key={x}>{x}</em>)}</i></span><span className="entry-facts">{item.trade?<strong className={item.trade.pnl>=0?"gain":"loss"}>{fmt(item.trade.pnlPct)}</strong>:null}<small>{entryLabels[item.type]}</small><small>{item.quality?qualityLabels[item.quality]:"Not assessed"}</small><span aria-label={`Replay ${item.trade?.replayAvailable?"available":"unavailable"}; Brain ${item.trade?.brainAvailable?"available":"unavailable"}`}>{item.trade?.replayAvailable?"↻ Replay":""} {item.trade?.brainAvailable?"🧠 Brain":""}</span></span></button>):<div className="empty"><b>No entries match these filters.</b><p>Journal reviews focus on preparation, discipline, risk management, emotional control and consistency.</p></div>}</section>
 <section className="journal-detail">{selected?<Editor entry={selected} readOnly={readOnly} notesRef={notesRef} onChange={setSelected} onSave={save} saving={saving} saved={saved}/>:<div className="empty detail-empty"><b>Select an entry to review it.</b><p>Trade Reviews are created directly from a completed DizyPaper trade.</p></div>}</section></div></main>;
}
function Editor({entry,readOnly,notesRef,onChange,onSave,saving,saved}:{entry:JournalEntry;readOnly:boolean;notesRef:React.RefObject<HTMLTextAreaElement|null>;onChange:(e:JournalEntry)=>void;onSave:(p?:Partial<JournalEntry>)=>Promise<void>;saving:boolean;saved:string}){
 const set=<K extends keyof JournalEntry>(key:K,value:JournalEntry[K])=>onChange({...entry,[key]:value});const addTag=(raw:string)=>{const tag=raw.trim();if(tag&&!entry.tags.includes(tag))set("tags",[...entry.tags,tag]);};const supportive=entry.trade&&entry.quality==="good"&&entry.planDiscipline==="completely"&&entry.trade.pnl<0?"Excellent discipline. Good execution matters more than short-term results.":entry.trade&&entry.quality==="poor"&&entry.trade.pnl>0?"A profitable mistake is still a mistake.":null;
 return <div className="editor"><header><div><span>{entryLabels[entry.type]}</span><h2>{entry.trade?`${entry.trade.symbol} ${entry.trade.direction}`:entry.marketContext?.symbol??"Journal entry"}</h2><small>Created {new Date(entry.createdAt).toLocaleString()} · Edited {new Date(entry.editedAt).toLocaleString()}</small></div>{!readOnly?<button disabled={saving} onClick={()=>void onSave()}>{saving?"Saving…":"Save entry"}</button>:null}</header>{saved?<div className="save-status" role="status">✓ {saved}</div>:null}
 {entry.trade?<><section className="trade-summary"><h3>Immutable trade summary</h3><dl>{Object.entries({Market:entry.trade.market,Timeframe:entry.trade.timeframe,Direction:entry.trade.direction,Entry:entry.trade.entry,Exit:entry.trade.exit,Stop:entry.trade.stop??"—",Target:entry.trade.target??"Unavailable","Position size":entry.trade.positionSize??"Unavailable","Risk %":entry.trade.riskPct??"Unavailable",Leverage:entry.trade.leverage===null?"Unavailable":`${entry.trade.leverage}×`,"Margin mode":entry.trade.marginMode??"Unavailable",Fees:entry.trade.fees??"Unavailable",PnL:entry.trade.pnl,"PnL %":fmt(entry.trade.pnlPct),"R multiple":entry.trade.rMultiple??"Unavailable","Open time":new Date(entry.trade.openTime).toLocaleString(),"Close time":new Date(entry.trade.closeTime).toLocaleString(),"Close reason":entry.trade.closeReason,"Strategy version":entry.trade.strategyVersion??"Unavailable"}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="reference-row">{entry.trade.replay?.available?<a href={`/terminal?replayMarketKey=${encodeURIComponent(entry.trade.replay.marketKey)}&replaySymbol=${encodeURIComponent(entry.trade.replay.symbol)}&replayTimeframe=${entry.trade.replay.timeframe}&replayAt=${entry.trade.replay.entryTimeMs}`}>↻ Open Replay</a>:<span>Replay data is unavailable for this trade.</span>}{entry.trade.brain?<span>🧠 {entry.trade.brain.summary}</span>:<span>DizyBrain unavailable</span>}{entry.trade.signal?<span>Signal · {entry.trade.signal.label}</span>:null}</div></section><section><h3>Was this a good trade?</h3><p className="helper">A good trade is one that followed your trading plan regardless of whether it won or lost.</p><Choice values={qualityLabels} value={entry.quality} disabled={readOnly} onPick={v=>set("quality",v)}/><h3>Did you follow your trading plan?</h3><Choice values={planLabels} value={entry.planDiscipline} disabled={readOnly} onPick={v=>set("planDiscipline",v)}/>{supportive?<p className="supportive">{supportive}</p>:null}<label>Mood (optional)<select disabled={readOnly} value={entry.mood??""} onChange={e=>set("mood",(e.target.value||null) as Mood|null)}><option value="">Not selected</option>{moods.map(m=><option key={m}>{m}</option>)}</select></label></section></>:null}
 <section><label className="notes-label">Notes<textarea ref={notesRef} readOnly={readOnly} value={entry.notes} onChange={e=>set("notes",e.target.value)} placeholder="Trade plan, market read, why you entered, mistakes, lessons or general thoughts…"/></label>{entry.type==="trade-review"?<div className="prompts"><h3>Optional reflection prompts</h3>{REFLECTION_PROMPTS.filter(p=>!entry.dismissedPrompts.includes(p)).map(p=><span key={p}>{p}{!readOnly?<button aria-label={`Dismiss ${p}`} onClick={()=>set("dismissedPrompts",[...entry.dismissedPrompts,p])}>×</button>:null}</span>)}</div>:null}<label>Tags<div className="tags">{entry.tags.map(t=><span key={t}>{t}{!readOnly?<button aria-label={`Remove ${t}`} onClick={()=>set("tags",entry.tags.filter(x=>x!==t))}>×</button>:null}</span>)}{!readOnly?<input placeholder="Add tag + Enter" onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addTag(e.currentTarget.value);e.currentTarget.value="";}}}/>:null}</div></label></section></div>;
}
function Choice<T extends string>({values,value,disabled,onPick}:{values:Record<T,string>;value:T|null;disabled:boolean;onPick:(v:T)=>void}){return <div className="choices">{Object.entries(values).map(([v,l])=><button className={value===v?"active":""} disabled={disabled} aria-pressed={value===v} onClick={()=>onPick(v as T)} key={v}>{l as string}</button>)}</div>}
