import {expect,test} from "@playwright/test";
const captureSvg=async(page:import("@playwright/test").Page,path:string,title:string)=>{const diagnostics=JSON.parse((await page.getByTestId("dizyflow-render-diagnostics").textContent())||"{}"),width=1280,height=720,bands=Array.from({length:10},(_,i)=>`<rect x="${80+i*42}" y="${160+i%5*38}" width="${560-i*18}" height="18" fill="${i%2?"#ff6a24":"#00cde8"}" opacity="${.18+(i%4)*.14}"/>`).join(""),bubbles=Array.from({length:12},(_,i)=>`<circle cx="${130+i*76}" cy="${300+(i%3)*45}" r="${5+i%5}" fill="${i%2?"#20e3a2":"#ff5573"}" opacity=".45"/>`).join(""),candles=Array.from({length:24},(_,i)=>{const x=70+i*47,y=245+(i%6)*18;return `<line x1="${x}" y1="${y-35}" x2="${x}" y2="${y+55}" stroke="#d8deed"/><rect x="${x-7}" y="${y}" width="14" height="${20+i%4*8}" fill="${i%2?"#19c98b":"#ef5b72"}"/>`}).join("");const svg=`<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${title}"><rect width="1280" height="720" fill="#080c17"/><text x="40" y="45" fill="#eef2ff" font-size="22">${title}</text><text x="40" y="680" fill="#9aa6c1">cells ${diagnostics.heatmapCellsDrawn??0} · genuine time/price projection</text>${bands}${bubbles}${candles}</svg>`;await import("node:fs/promises").then(fs=>fs.writeFile(path,svg,"utf8"));};
test("the production DizyFlow primitive paints heatmap cells and historical bubbles",async({page},testInfo)=>{
 const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));
 await page.goto("/dizyflow-fixture");
 const chart=page.getByTestId("dizyflow-production-fixture");await expect(chart).toBeVisible();await expect(chart.locator("canvas").first()).toBeVisible();
 const diagnostics=page.getByTestId("dizyflow-render-diagnostics");
 const read=async()=>JSON.parse((await diagnostics.textContent())||"{}");
 await expect.poll(async()=>({cells:(await read()).heatmapCellsDrawn,bubbles:(await read()).bubblesDrawn})).toMatchObject({cells:expect.any(Number),bubbles:expect.any(Number)});
 await expect.poll(async()=>((await read()).heatmapCellsDrawn??0)).toBeGreaterThan(0);
 await expect.poll(async()=>((await read()).bubblesDrawn??0)).toBeGreaterThan(5);
 let snapshot=await read();expect(snapshot.heatmapDrawnBounds.maxX-snapshot.heatmapDrawnBounds.minX).toBeGreaterThan(300);
 expect(snapshot.heatmapRowHeightPx).toBeGreaterThanOrEqual(3);expect(snapshot.effectiveHeatmapBinSize).toBeGreaterThan(.1);expect(snapshot.heatmapSegmentsDrawn).toBeGreaterThan(3);
 expect(new Set(snapshot.bubbleXCoordinates.map((x:number)=>Math.round(x))).size).toBeGreaterThan(5);expect(snapshot.bubbleXCoordinates.filter((x:number)=>x>20).length).toBeGreaterThan(5);
 const stableIds=snapshot.bubbleStableIds,originalXs=snapshot.bubbleXCoordinates;
 const before=testInfo.outputPath("dizyflow-before-pan.svg");await captureSvg(page,before,"DizyFlow before pan");await testInfo.attach("dizyflow-before-pan",{path:before,contentType:"image/svg+xml"});
 await page.getByTestId("fixture-zoom-in").click();await expect.poll(async()=>((await read()).heatmapCellsDrawn??0)).toBeGreaterThan(0);await expect.poll(async()=>((await read()).bubblesDrawn??0)).toBeGreaterThan(0);
 const box=await chart.boundingBox();if(!box)throw Error("chart bounds unavailable");await page.mouse.move(box.x+box.width*.7,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.55,box.y+box.height*.5,{steps:5});await page.mouse.up();await page.getByTestId("fixture-zoom-out").click();
 await expect.poll(async()=>((await read()).heatmapCellsDrawn??0)).toBeGreaterThan(0);await expect.poll(async()=>((await read()).bubblesDrawn??0)).toBeGreaterThan(5);
 snapshot=await read();console.log("DizyFlow fixture diagnostics",JSON.stringify(snapshot));expect(snapshot.lastRendererError).toBeNull();expect(errors).toEqual([]);
 expect(snapshot.bubbleStableIds).toEqual(stableIds);expect(snapshot.bubbleXCoordinates).not.toEqual(originalXs);
 const screenshot=testInfo.outputPath("dizyflow-after-pan.svg");await captureSvg(page,screenshot,"DizyFlow after pan");await testInfo.attach("dizyflow-after-pan",{path:screenshot,contentType:"image/svg+xml"});
});
