import { NextResponse } from "next/server";
import { requireApiUser } from "../../../../lib/auth";
import { buildDizyBrainTradeReview, tradeReviewFreshness, TradeReviewValidationError } from "../../../../lib/dizybrain-trade-review";
import { createTradeReview, deleteTradeReview, readTradeReview, TradeReviewStorageError } from "../../../../lib/dizybrain-review-store";
import { getJournalEntry, setJournalReviewReferenceWithinTransaction, withJournalTransaction } from "../../../../lib/journal-store";
import { readReplayMemory } from "../../../../lib/replay-memory-store";
import { journalWritesAllowed } from "../../../../lib/journal-model";
import { appendAudit } from "../../../../lib/store";
export const runtime="nodejs";export const dynamic="force-dynamic";
const fail=(status:number,code:string,message:string)=>NextResponse.json({error:{code,message}},{status});
export async function POST(_:Request,{params}:{params:Promise<{id:string}>}){const user=await requireApiUser();if(!user)return fail(401,"UNAUTHORISED","Unauthorised");if(!journalWritesAllowed(user.role))return fail(403,"VIEWER_READ_ONLY","Viewer sessions are read-only.");const entryId=(await params).id;try{return await withJournalTransaction(user.id,async()=>{const entry=await getJournalEntry(user.id,entryId);if(!entry)return fail(404,"JOURNAL_NOT_FOUND","Journal entry not found.");if(entry.type!=="trade-review"||!entry.trade)return fail(422,"TRADE_REQUIRED","Only completed Trade Review entries are supported.");const memoryId=entry.trade.replay?.source==="retained-memory"?entry.trade.replay.memoryId:null;if(!memoryId)return fail(422,"REPLAY_MEMORY_REQUIRED","Validated retained Replay Memory is required.");const memory=await readReplayMemory(user.id,memoryId);if(!memory)return fail(404,"REPLAY_MEMORY_UNAVAILABLE","Retained Replay Memory is unavailable.");const freshness=tradeReviewFreshness(entry,memory),existingId=entry.trade.dizyBrainReview.reviewId;if(!freshness.stale&&existingId){const existing=await readTradeReview(user.id,existingId);if(existing){await appendAudit(user.id,"dizybrain-review.generate",{reviewId:existing.id,journalEntryId:entry.id,tradeId:existing.tradeId,replayMemoryId:memory.id,engineVersion:existing.engineVersion,reviewConfidence:existing.reviewConfidence,idempotentReuse:true});return NextResponse.json({review:existing,reference:entry.trade.dizyBrainReview,idempotentReuse:true},{status:200});}}const review=buildDizyBrainTradeReview({journalEntry:entry,replayMemory:memory,generatedAt:new Date().toISOString()});const stored=await createTradeReview(user.id,review);const reference={available:true,reviewId:stored.review.id,engineVersion:stored.review.engineVersion,generatedAt:stored.review.createdAt,generatedFromHash:stored.review.generatedFromHash,reviewConfidence:stored.review.reviewConfidence} as const;try{const updated=await setJournalReviewReferenceWithinTransaction(user.id,entry.id,reference);if(!updated)throw new Error("Journal reference update failed.");await appendAudit(user.id,"dizybrain-review.generate",{reviewId:review.id,journalEntryId:entry.id,tradeId:review.tradeId,replayMemoryId:memory.id,engineVersion:review.engineVersion,reviewConfidence:review.reviewConfidence,idempotentReuse:!stored.created});return NextResponse.json({review:stored.review,reference,idempotentReuse:!stored.created},{status:stored.created?201:200});}catch(reason){if(stored.created)await deleteTradeReview(user.id,stored.review.id).catch(()=>undefined);throw reason;}});}catch(reason){const code=reason instanceof TradeReviewValidationError||reason instanceof TradeReviewStorageError?reason.code:"REVIEW_GENERATION_FAILED";await appendAudit(user.id,"dizybrain-review.failure",{journalEntryId:entryId,code});return fail(reason instanceof TradeReviewValidationError?422:500,code,reason instanceof Error?reason.message:"Review generation failed.");}}
