import {NextResponse} from "next/server";
import {requireApiUser} from "../../../../lib/auth";
import {normalizeDepthSymbol} from "../../../../lib/order-flow/depth-collector";
import {acquireHeatmapTileBuild,throwIfHeatmapTileBuildAborted} from "../../../../lib/order-flow/heatmap-build-admission";
import {acquireLiquidityTape,releaseLiquidityTape} from "../../../../lib/order-flow/liquidity-tape";
export const dynamic="force-dynamic";export const runtime="nodejs";
const number=(value:string|null,min:number,max:number)=>{const parsed=Number(value);return value!==null&&Number.isFinite(parsed)&&parsed>=min&&parsed<=max?parsed:null};
const cache=new Map<string,{payload:string;bytes:number}>();let cacheBytes=0;const MAX_CACHE_BYTES=12*1024*1024;
const tileResponse=(payload:string,status:"hit"|"miss")=>new Response(payload,{headers:{"content-type":"application/json","cache-control":"private, no-store","x-dizyflow-tile-cache":status}});
const remember=(key:string,payload:string)=>{const bytes=Buffer.byteLength(payload);if(bytes>MAX_CACHE_BYTES)return;const previous=cache.get(key);if(previous)cacheBytes-=previous.bytes;cache.delete(key);cache.set(key,{payload,bytes});cacheBytes+=bytes;while(cacheBytes>MAX_CACHE_BYTES){const oldest=cache.keys().next().value;if(oldest===undefined)break;const item=cache.get(oldest)!;cache.delete(oldest);cacheBytes-=item.bytes}};
export async function GET(request:Request){if(!await requireApiUser())return NextResponse.json({error:"Unauthorised"},{status:401});const p=new URL(request.url).searchParams,symbol=normalizeDepthSymbol(p.get("symbol")??""),now=Date.now(),requestedFrom=number(p.get("fromMs"),0,now+86_400_000),requestedTo=number(p.get("toMs"),0,now+86_400_000),minPrice=number(p.get("minPrice"),1e-8,1e9),maxPrice=number(p.get("maxPrice"),1e-8,1e9),timeBucketMs=number(p.get("timeBucketMs"),5_000,600_000),priceStep=number(p.get("priceStep"),1e-8,1e7);if(!symbol||requestedFrom===null||requestedTo===null||minPrice===null||maxPrice===null||timeBucketMs===null||priceStep===null||requestedTo<=requestedFrom||maxPrice<=minPrice)return NextResponse.json({error:"Invalid tile parameters"},{status:400});let tape;try{tape=acquireLiquidityTape(symbol);await tape.initialize()}catch{return NextResponse.json({error:"Liquidity tape capacity reached"},{status:503})}try{const coverage=tape.coverage(),fromMs=Math.max(requestedFrom,coverage.archiveStartMs??requestedFrom),toMs=Math.min(requestedTo,coverage.archiveEndMs??requestedTo);if(coverage.archiveStartMs===null||coverage.archiveEndMs===null||toMs<=fromMs)return NextResponse.json({symbol,requestedFromMs:requestedFrom,requestedToMs:requestedTo,capturedFromMs:coverage.archiveStartMs,capturedToMs:coverage.archiveEndMs,timeBucketMs,priceStep,cells:[],endState:[],hasGaps:coverage.hasGaps},{headers:{"cache-control":"private, no-store","x-dizyflow-tile-cache":"miss"}});if(toMs-fromMs>24*60*60_000)return NextResponse.json({error:"Archive intersection exceeds tile limit"},{status:400});const key=[symbol,Math.floor(fromMs/5000)*5000,Math.ceil(toMs/5000)*5000,minPrice,maxPrice,timeBucketMs,priceStep].join(":");const hit=cache.get(key);if(hit){cache.delete(key);cache.set(key,hit);return tileResponse(hit.payload,"hit")}const releaseBuild=await acquireHeatmapTileBuild(request.signal);try{throwIfHeatmapTileBuildAborted(request.signal);const admittedHit=cache.get(key);if(admittedHit){cache.delete(key);cache.set(key,admittedHit);return tileResponse(admittedHit.payload,"hit")}const value=await tape.tiles(fromMs,toMs,minPrice,maxPrice,timeBucketMs,priceStep);throwIfHeatmapTileBuildAborted(request.signal);value.requestedFromMs=requestedFrom;value.requestedToMs=requestedTo;const payload=JSON.stringify(value);throwIfHeatmapTileBuildAborted(request.signal);remember(key,payload);return tileResponse(payload,"miss")}finally{releaseBuild()}}finally{releaseLiquidityTape(symbol)}}
