import test from "node:test";import assert from "node:assert/strict";
import {DepthCollector,normalizeMexcSnapshot,parseDepthPollMs} from "../app/lib/order-flow/depth-collector.ts";
import {depthConsumerActivity,stableDepthStatus} from "../app/lib/order-flow/lifecycle.ts";
const raw=(version=1,timestamp=Date.now())=>({success:true,code:0,data:{version,timestamp,bids:[[99,4,7],[100,2,3]],asks:[[102,5,9],[101,1,8]]}});
const response=value=>new Response(JSON.stringify(value),{status:200,headers:{"content-type":"application/json"}});

test("MEXC snapshots validate, normalize tuple fields, and sort both sides",()=>{const book=normalizeMexcSnapshot(raw(),"BTC_USDT");assert.deepEqual(book.bids.map(v=>v.price),[100,99]);assert.deepEqual(book.asks.map(v=>v.price),[101,102]);assert.deepEqual(book.bids[0],{price:100,orderCount:2,contractQuantity:3});});
test("invalid and incomplete upstream responses are rejected",()=>{for(const value of [{},{success:false,code:0,data:{}},{success:true,code:0,data:{version:1,timestamp:2,bids:[],asks:[]}}, {success:true,code:0,data:{version:1,timestamp:2,bids:[[1,2]],asks:[[2,1,1]]}}])assert.throws(()=>normalizeMexcSnapshot(value,"BTC_USDT"));});
test("collector prevents overlapping polls",async()=>{let release;const pending=new Promise(resolve=>release=resolve),collector=new DepthCollector("BTC_USDT",async()=>{await pending;return response(raw())});const first=collector.poll();assert.equal(await collector.poll(),false);release();assert.equal(await first,true);collector.stop();});
test("collector retains last valid snapshot and bounded low-memory history after errors",async()=>{let version=0,fail=false,now=1_800_000;const collector=new DepthCollector("BTC_USDT",async()=>{if(fail)throw Error("temporary failure");return response(raw(++version,now+=2000))},()=>now,undefined,{maxHistory:150});for(let i=0;i<181;i++)await collector.poll();assert.ok(collector.getHistory().length<=150);const latest=collector.getLatest();fail=true;await collector.poll();assert.deepEqual(collector.getLatest(),latest);assert.equal(collector.diagnostic().consecutiveFailures,1);collector.stop();});
test("snapshot age measures collector success rather than exchange clock skew",async()=>{let now=50_000;const collector=new DepthCollector("BTC_USDT",async()=>response(raw(1,1_000)),()=>now);await collector.poll();assert.equal(collector.diagnostic().snapshotAgeMs,0);now+=2_500;assert.equal(collector.diagnostic().snapshotAgeMs,2_500);collector.stop();});
test("stable depth states are meaningful and DOM and heatmap lifecycles are independent",()=>{assert.equal(stableDepthStatus({hasSnapshot:false,ageMs:0,endpointFailed:false}),"CONNECTING");assert.equal(stableDepthStatus({hasSnapshot:false,ageMs:0,endpointFailed:true}),"ERROR");assert.equal(stableDepthStatus({hasSnapshot:true,ageMs:100,endpointFailed:true}),"LIVE");assert.equal(stableDepthStatus({hasSnapshot:true,ageMs:6000,endpointFailed:false}),"STALE");assert.deepEqual(depthConsumerActivity({enabled:true,domVisible:false,heatmapVisible:true}),{dom:false,heatmap:true});assert.deepEqual(depthConsumerActivity({enabled:true,domVisible:true,heatmapVisible:false}),{dom:true,heatmap:false});});

test("depth interval defaults to 2000ms and clamps unsafe values",()=>{assert.equal(parseDepthPollMs(undefined),2000);assert.equal(parseDepthPollMs("10"),250);assert.equal(parseDepthPollMs("500"),500);assert.equal(parseDepthPollMs("bad"),2000)});
test("collector envelopes carry receipt health and history samples only once per interval",async()=>{let now=1000,version=0;const collector=new DepthCollector("BTC_USDT",async()=>response(raw(++version,1)),()=>now);await collector.poll();now=1250;await collector.poll();now=3000;await collector.poll();assert.equal(collector.getHistory().length,2);assert.equal(collector.getLatest().receivedAt,3000);assert.deepEqual(collector.getLatest().diagnostic,{snapshotAgeMs:0,consecutiveFailures:0,lastError:null,sequenceKnown:true,sequenceContinuous:null,snapshotComplete:true,recovering:false,sourceTimestampKnown:true})});

test("100,000 WS increments stay level-bounded and coalesce publications",async()=>{const collector=new DepthCollector("BTC_USDT",async()=>response(raw()),Date.now,undefined,{transport:"ws",maxLevels:100,maxHistory:5,historySampleMs:250});let publications=0,samples=0;collector.subscribe(()=>publications++);collector.subscribe(()=>samples++,"sample");for(let version=1;version<=100_000;version++)collector.applyWsUpdate({symbol:"BTC_USDT",version,engineTimeMs:version,bids:[{price:100_000-version,orderCount:1,contractQuantity:1}],asks:[{price:100_000+version,orderCount:1,contractQuantity:1}]});assert.equal(publications,0);await new Promise(resolve=>setTimeout(resolve,320));const diagnostic=collector.diagnostic();assert.ok(diagnostic.bids<=100);assert.ok(diagnostic.asks<=100);assert.ok(publications<=2);assert.ok(samples<=2);assert.ok(collector.getHistory().length<=5);collector.stop()});
