import test from "node:test";import assert from "node:assert/strict";
import {DepthCollector,normalizeMexcSnapshot} from "../app/lib/order-flow/depth-collector.ts";
import {stableDepthStatus} from "../app/lib/order-flow/lifecycle.ts";
const raw=(version=1,timestamp=Date.now())=>({success:true,code:0,data:{version,timestamp,bids:[[99,4,7],[100,2,3]],asks:[[102,5,9],[101,1,8]]}});
const response=value=>new Response(JSON.stringify(value),{status:200,headers:{"content-type":"application/json"}});

test("MEXC snapshots validate, normalize tuple fields, and sort both sides",()=>{const book=normalizeMexcSnapshot(raw(),"BTC_USDT");assert.deepEqual(book.bids.map(v=>v.price),[100,99]);assert.deepEqual(book.asks.map(v=>v.price),[101,102]);assert.deepEqual(book.bids[0],{price:100,orderCount:2,contractQuantity:3});});
test("invalid and incomplete upstream responses are rejected",()=>{for(const value of [{},{success:false,code:0,data:{}},{success:true,code:0,data:{version:1,timestamp:2,bids:[],asks:[]}}, {success:true,code:0,data:{version:1,timestamp:2,bids:[[1,2]],asks:[[2,1,1]]}}])assert.throws(()=>normalizeMexcSnapshot(value,"BTC_USDT"));});
test("collector prevents overlapping polls",async()=>{let release;const pending=new Promise(resolve=>release=resolve),collector=new DepthCollector("BTC_USDT",async()=>{await pending;return response(raw())});const first=collector.poll();assert.equal(await collector.poll(),false);release();assert.equal(await first,true);collector.stop();});
test("collector retains last valid snapshot and bounded 30-minute history after errors",async()=>{let version=0,fail=false,now=1_800_000;const collector=new DepthCollector("BTC_USDT",async()=>{if(fail)throw Error("temporary failure");return response(raw(++version,now++))},()=>now);for(let i=0;i<1810;i++)await collector.poll();assert.ok(collector.getHistory().length<=1800);const latest=collector.getLatest();fail=true;await collector.poll();assert.deepEqual(collector.getLatest(),latest);assert.equal(collector.diagnostic().consecutiveFailures,1);collector.stop();});
test("stable depth states are meaningful and independent consumers do not share state",()=>{assert.equal(stableDepthStatus({hasSnapshot:false,ageMs:0,endpointFailed:false}),"CONNECTING");assert.equal(stableDepthStatus({hasSnapshot:false,ageMs:0,endpointFailed:true}),"ERROR");assert.equal(stableDepthStatus({hasSnapshot:true,ageMs:100,endpointFailed:true}),"LIVE");assert.equal(stableDepthStatus({hasSnapshot:true,ageMs:6000,endpointFailed:false}),"STALE");const dom={status:"LIVE"},heatmap={status:"ERROR"};heatmap.status="CONNECTING";assert.equal(dom.status,"LIVE");});
