import test from "node:test";import assert from "node:assert/strict";
import {DepthCollector,normalizeMexcSnapshot,parseDepthPollMs,websocketDepthFresh} from "../app/lib/order-flow/depth-collector.ts";
import {capDepthEnvelopeForDom,DOM_DEPTH_LEVEL_CAP} from "../app/lib/order-flow/depth-presentation.ts";
import {depthConsumerActivity,latestReceiptTime,stableDepthStatus} from "../app/lib/order-flow/lifecycle.ts";
const raw=(version=1,timestamp=Date.now())=>({version,timestamp,bids:[[99,4,7],[100,2,3]],asks:[[102,5,9],[101,1,8]]});
const wrapped=(version=1,timestamp=Date.now())=>({success:true,code:0,data:raw(version,timestamp)});
const response=value=>new Response(JSON.stringify(value),{status:200,headers:{"content-type":"application/json"}});
const commits=versions=>({success:true,code:0,data:versions.map(version=>({version,bids:[[100,1,version]],asks:[[101,1,version]]}))});

test("MEXC snapshots accept the documented root payload, normalize tuple fields, and sort both sides",()=>{const book=normalizeMexcSnapshot(raw(),"BTC_USDT");assert.deepEqual(book.bids.map(v=>v.price),[100,99]);assert.deepEqual(book.asks.map(v=>v.price),[101,102]);assert.deepEqual(book.bids[0],{price:100,orderCount:2,contractQuantity:3});});
test("MEXC snapshots retain compatibility with wrapped contract responses",()=>{const timestamp=Date.now();assert.deepEqual(normalizeMexcSnapshot(wrapped(1,timestamp),"BTC_USDT"),normalizeMexcSnapshot(raw(1,timestamp),"BTC_USDT"));});
test("invalid and incomplete upstream responses are rejected",()=>{for(const value of [{},{success:false,code:0,data:raw()},{success:true,code:0,data:{version:1,timestamp:2,bids:[],asks:[]}}, {version:1,timestamp:2,bids:[[1,2]],asks:[[2,1,1]]}])assert.throws(()=>normalizeMexcSnapshot(value,"BTC_USDT"));});
test("collector prevents overlapping polls",async()=>{let release;const pending=new Promise(resolve=>release=resolve),collector=new DepthCollector("BTC_USDT",async()=>{await pending;return response(raw())});const first=collector.poll();assert.equal(await collector.poll(),false);release();assert.equal(await first,true);collector.stop();});
test("collector retains last valid snapshot and bounded low-memory history after errors",async()=>{let version=0,fail=false,now=1_800_000;const collector=new DepthCollector("BTC_USDT",async()=>{if(fail)throw Error("temporary failure");return response(raw(++version,now+=2000))},()=>now,undefined,{maxHistory:150});for(let i=0;i<181;i++)await collector.poll();assert.ok(collector.getHistory().length<=150);const latest=collector.getLatest();fail=true;await collector.poll();assert.deepEqual(collector.getLatest(),latest);assert.equal(collector.diagnostic().consecutiveFailures,1);collector.stop();});
test("snapshot age measures collector success rather than exchange clock skew",async()=>{let now=50_000;const collector=new DepthCollector("BTC_USDT",async()=>response(raw(1,1_000)),()=>now);await collector.poll();assert.equal(collector.diagnostic().snapshotAgeMs,0);now+=2_500;assert.equal(collector.diagnostic().snapshotAgeMs,2_500);collector.stop();});
test("shared DizyFlow freshness never moves backwards",()=>{assert.equal(latestReceiptTime(null,null),null);assert.equal(latestReceiptTime(null,1000),1000);assert.equal(latestReceiptTime(2000,null),2000);assert.equal(latestReceiptTime(2000,1500),2000);assert.equal(latestReceiptTime(2000,2500),2500);});
test("stable depth states are meaningful and DOM and heatmap lifecycles are independent",()=>{assert.equal(stableDepthStatus({hasSnapshot:false,ageMs:0,endpointFailed:false}),"CONNECTING");assert.equal(stableDepthStatus({hasSnapshot:false,ageMs:0,endpointFailed:true}),"ERROR");assert.equal(stableDepthStatus({hasSnapshot:true,ageMs:100,endpointFailed:true}),"LIVE");assert.equal(stableDepthStatus({hasSnapshot:true,ageMs:6000,endpointFailed:false}),"STALE");assert.deepEqual(depthConsumerActivity({enabled:true,domVisible:false,heatmapVisible:true}),{dom:false,heatmap:true});assert.deepEqual(depthConsumerActivity({enabled:true,domVisible:true,heatmapVisible:false}),{dom:true,heatmap:false});});

test("depth interval defaults to 2000ms and clamps unsafe values",()=>{assert.equal(parseDepthPollMs(undefined),2000);assert.equal(parseDepthPollMs("10"),250);assert.equal(parseDepthPollMs("500"),500);assert.equal(parseDepthPollMs("bad"),2000)});
test("collector envelopes carry receipt health and history samples only once per interval",async()=>{let now=1000,version=0;const collector=new DepthCollector("BTC_USDT",async()=>response(raw(++version,1)),()=>now);await collector.poll();now=1250;await collector.poll();now=3000;await collector.poll();assert.equal(collector.getHistory().length,2);assert.equal(collector.getLatest().receivedAt,3000);assert.deepEqual(collector.getLatest().diagnostic,{snapshotAgeMs:0,consecutiveFailures:0,lastError:null,sequenceKnown:true,sequenceContinuous:null,snapshotComplete:true,recovering:false,sourceTimestampKnown:true})});

test("incremental MEXC websocket depth cannot become authoritative before a REST snapshot seeds the book",async()=>{let now=10_000;const collector=new DepthCollector("BTC_USDT",async()=>response(raw(10,9_900)),()=>now,undefined,{transport:"ws",historySampleMs:10_000});collector.applyWsUpdate({symbol:"BTC_USDT",version:9,engineTimeMs:9_800,bids:[{price:100,orderCount:1,contractQuantity:2}],asks:[{price:101,orderCount:1,contractQuantity:3}]});await new Promise(resolve=>setTimeout(resolve,160));let diagnostic=collector.diagnostic();assert.equal(diagnostic.authoritativeSnapshotSeeded,false);assert.equal(diagnostic.sourceMode,"NO VALID BOOK");assert.equal(diagnostic.bids,0);assert.equal(diagnostic.asks,0);assert.equal(collector.getLatest(),null);assert.equal(await collector.poll(),true);diagnostic=collector.diagnostic();assert.equal(diagnostic.authoritativeSnapshotSeeded,true);assert.equal(diagnostic.bids,2);assert.equal(diagnostic.asks,2);assert.equal(diagnostic.sourceMode,"REST FALLBACK");collector.applyWsUpdate({symbol:"BTC_USDT",version:11,engineTimeMs:10_050,bids:[{price:100,orderCount:1,contractQuantity:4}],asks:[{price:101,orderCount:1,contractQuantity:5}]});await new Promise(resolve=>setTimeout(resolve,160));diagnostic=collector.diagnostic();assert.equal(diagnostic.sourceMode,"FULL DEPTH WS");assert.equal(diagnostic.authoritativeSnapshotSeeded,true);collector.stop()});

test("one MEXC version gap owns one commit recovery while later websocket deltas are buffered",async()=>{let now=10_000,releaseCommits;const commitGate=new Promise(resolve=>releaseCommits=resolve),urls=[];const collector=new DepthCollector("BTC_USDT",async url=>{urls.push(String(url));if(String(url).includes("/depth_commits/")){await commitGate;return response(commits([11,12]))}return response(raw(10,9_900))},()=>now,undefined,{transport:"ws",historySampleMs:10_000});await collector.poll();collector.applyWsUpdate({symbol:"BTC_USDT",version:13,engineTimeMs:10_010,bids:[{price:100,orderCount:1,contractQuantity:13}],asks:[{price:101,orderCount:1,contractQuantity:13}]});collector.applyWsUpdate({symbol:"BTC_USDT",version:14,engineTimeMs:10_020,bids:[{price:100,orderCount:1,contractQuantity:14}],asks:[{price:101,orderCount:1,contractQuantity:14}]});collector.applyWsUpdate({symbol:"BTC_USDT",version:15,engineTimeMs:10_030,bids:[{price:100,orderCount:1,contractQuantity:15}],asks:[{price:101,orderCount:1,contractQuantity:15}]});let diagnostic=collector.diagnostic();assert.equal(diagnostic.versionGaps,1);assert.equal(diagnostic.restRecoveries,1);assert.equal(diagnostic.sourceMode,"REST FALLBACK");releaseCommits();await new Promise(resolve=>setTimeout(resolve,220));diagnostic=collector.diagnostic();assert.equal(diagnostic.versionGaps,1);assert.equal(diagnostic.restRecoveries,1);assert.equal(diagnostic.sourceMode,"FULL DEPTH WS");assert.equal(collector.getLatest().snapshot.version,15);assert.equal(collector.getLatest().snapshot.bids.find(level=>level.price===100)?.contractQuantity,15);assert.equal(urls.filter(url=>url.includes("/depth_commits/")).length,1);collector.stop()});

test("100,000 WS increments stay level-bounded and coalesce publications",async()=>{const collector=new DepthCollector("BTC_USDT",async()=>response(raw()),Date.now,undefined,{transport:"ws",maxLevels:100,maxHistory:5,historySampleMs:250});await collector.poll();let publications=0,samples=0;collector.subscribe(()=>publications++);collector.subscribe(()=>samples++,"sample");const initialVersion=collector.diagnostic().lastVersion;for(let offset=1;offset<=100_000;offset++){const version=initialVersion+offset;collector.applyWsUpdate({symbol:"BTC_USDT",version,engineTimeMs:version,bids:[{price:100_000-offset,orderCount:1,contractQuantity:1}],asks:[{price:100_000+offset,orderCount:1,contractQuantity:1}]})}assert.equal(publications,0);await new Promise(resolve=>setTimeout(resolve,320));const diagnostic=collector.diagnostic();assert.ok(diagnostic.bids<=100);assert.ok(diagnostic.asks<=100);assert.ok(publications<=2);assert.ok(samples<=2);assert.ok(collector.getHistory().length<=5);collector.stop()});

test("silent websocket freshness expires and a successful REST health poll republishes",async()=>{let now=1_000;const collector=new DepthCollector("BTC_USDT",async()=>response(raw(10,now)),()=>now,undefined,{transport:"ws",wsSilenceMs:1_000,historySampleMs:250});await collector.poll();collector.applyWsUpdate({symbol:"BTC_USDT",version:11,engineTimeMs:now,bids:[{price:100,orderCount:1,contractQuantity:2}],asks:[{price:101,orderCount:1,contractQuantity:3}]});await new Promise(resolve=>setTimeout(resolve,160));assert.equal(websocketDepthFresh(1_000,1_500,1_000),true);assert.equal(websocketDepthFresh(1_000,2_001,1_000),false);now=5_000;await collector.poll();assert.equal(collector.getLatest().receivedAt,5_000);assert.equal(collector.getLatest().snapshot.version,10);assert.equal(collector.diagnostic().restRecoveries,1);assert.equal(collector.diagnostic().sourceMode,"REST FALLBACK");collector.stop()});

test("DOM envelopes remain capped while the shared collector can retain a broader book",()=>{const levels=Array.from({length:250},(_,i)=>({price:100+i,orderCount:1,contractQuantity:i+1})),envelope={snapshot:{symbol:"BTC_USDT",version:1,engineTimeMs:1,bids:[...levels].reverse(),asks:levels},receivedAt:2,diagnostic:{snapshotAgeMs:0,consecutiveFailures:0,lastError:null,sequenceKnown:true,sequenceContinuous:true,snapshotComplete:true,recovering:false,sourceTimestampKnown:true}};const compact=capDepthEnvelopeForDom(envelope);assert.equal(compact.snapshot.bids.length,DOM_DEPTH_LEVEL_CAP);assert.equal(compact.snapshot.asks.length,DOM_DEPTH_LEVEL_CAP);assert.equal(envelope.snapshot.bids.length,250)});