import test from "node:test";
import assert from "node:assert/strict";
import { loadDizyBrainBehaviourProfile } from "../app/lib/dizybrain-behaviour-loader.ts";
import { tradeReviewInputHashFromMemoryMetadata } from "../app/lib/dizybrain-trade-review.ts";

const memory={id:"hrm1_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",schemaVersion:1,validationVersion:2,contentHash:"b".repeat(64),tradeId:"trade-1",marketKey:"mexc:futures:BTC_USDT",symbol:"BTC_USDT",timeframe:"1m",entryTimeMs:1704067200000,exitTimeMs:1704067260000};
const component={assessment:"unavailable",evidenceCompleteness:50,qualityScore:null,reasonCodes:[],confidence:50,limitations:[]};
function fixture(overrides={}){let entry={id:"journal-1",schemaVersion:4,type:"trade-review",createdAt:"2024-01-01T00:00:00Z",editedAt:"2024-01-01T00:00:00Z",title:"",archived:false,archivedAt:null,notes:"note",tags:["Breakout"],dismissedPrompts:[],quality:"good",planDiscipline:"completely",mood:"calm",marketContext:null,trade:{tradeId:memory.tradeId,symbol:memory.symbol,market:"MEXC Futures",timeframe:memory.timeframe,direction:"long",entry:100,exit:101,stop:null,target:null,positionSize:null,riskPct:null,leverage:null,marginMode:null,fees:null,pnl:1,pnlPct:1,rMultiple:1,openTime:new Date(memory.entryTimeMs).toISOString(),closeTime:new Date(memory.exitTimeMs).toISOString(),closeReason:"manual",strategyVersion:null,replay:{sessionId:"journal-replay|trade-1",marketKey:memory.marketKey,symbol:memory.symbol,timeframe:memory.timeframe,entryTimeMs:memory.entryTimeMs,available:true,source:"retained-memory",memoryId:memory.id,capturedRangeStartMs:memory.entryTimeMs,capturedRangeEndMs:memory.exitTimeMs,candleCount:2,integrityWarnings:[],brainAvailable:false,flowAvailability:"capture-not-supported"},brain:null,signal:null,dizyBrainReview:{available:false,reviewId:null,engineVersion:null,generatedAt:null,generatedFromHash:null,reviewConfidence:null}}};entry={...entry,...overrides,trade:{...entry.trade,...overrides.trade}};const generatedFromHash=tradeReviewInputHashFromMemoryMetadata(entry,{id:memory.id,contentHash:memory.contentHash}),review={id:"dbr1_"+"c".repeat(40),journalEntryId:entry.id,tradeId:memory.tradeId,replayMemoryId:memory.id,marketKey:memory.marketKey,symbol:memory.symbol,timeframe:memory.timeframe,entryTimeMs:memory.entryTimeMs,exitTimeMs:memory.exitTimeMs,engineVersion:"historical-trade-review/1.1.0",reviewContentHash:"d".repeat(64),generatedFromHash,provenance:{replayMemoryContentHash:memory.contentHash,replayMemorySchemaVersion:1,replayMemoryValidationVersion:2},confidenceBand:"moderate",reviewConfidence:70,setup:component,signal:{...component,directionConsistent:null},trend:{...component,alignment:"unavailable"},entry:{...component,timing:"confirmed"},risk:component,exit:component,process:component,scores:{setupEvidenceCompleteness:50,signalEvidenceCompleteness:50,trendEvidenceCompleteness:50,entryEvidenceCompleteness:50,riskEvidenceCompleteness:50,exitEvidenceCompleteness:50,processEvidenceCompleteness:50},evidence:{brainContext:false,flowContext:false,stopKnown:false},outcome:{classification:"profit",pnl:1,rMultiple:1},findings:[],limitations:[]};entry={...entry,trade:{...entry.trade,dizyBrainReview:{available:true,reviewId:review.id,engineVersion:review.engineVersion,generatedAt:"2024-01-02T00:00:00Z",generatedFromHash,reviewConfidence:70}}};return {entry,review};}
const run=async(entries,options={})=>{const base=fixture(),calls={reviews:0,metadata:0};const result=await loadDizyBrainBehaviourProfile("owner",options.filters??{},"2024-02-01T00:00:00Z",{readJournal:async()=>({version:4,entries}),readTradeReview:async(_user,id)=>{calls.reviews++;if(options.reviewError)throw new Error();if(options.missingReview)return null;const found=options.review??base.review;return id===found.id?found:null;},readReplayMemoryMetadata:async(user)=>{calls.metadata++;if(user!=="owner"||options.missingMetadata)return null;if(options.metadataError)throw new Error();return options.metadata??memory;}});return {...result,calls};};

test("matching current metadata includes one review and reads lightweight metadata once",async()=>{const {entry,review}=fixture(),result=await run([entry],{review});assert.equal(result.profile.coverage.eligibleCurrentReviews,1);assert.equal(result.diagnostics.filesRead,1);assert.equal(result.diagnostics.metadataReads,1);assert.equal("candles" in memory,false);});
test("missing review and malformed files are excluded separately",async()=>{const {entry}=fixture(),missing=await run([entry],{missingReview:true}),invalid=await run([entry],{reviewError:true});assert.equal(missing.profile.coverage.missingReviews,1);assert.equal(invalid.profile.coverage.invalidReviews,1);assert.equal(missing.profile.observations.length,0);});
test("missing, mismatched, and malformed Replay metadata cannot affect aggregation",async()=>{const {entry,review}=fixture(),missing=await run([entry],{review,missingMetadata:true}),stale=await run([entry],{review,metadata:{...memory,contentHash:"e".repeat(64)}}),invalid=await run([entry],{review,metadataError:true});assert.equal(missing.profile.coverage.staleReviews,1);assert.equal(stale.profile.coverage.staleReviews,1);assert.equal(invalid.profile.coverage.invalidReviews,1);for(const value of [missing,stale,invalid])assert.equal(value.profile.coverage.eligibleCurrentReviews,0);});
test("Journal memory mismatch and changed process fields exclude evidence",async()=>{const base=fixture(),wrong=fixture({trade:{replay:{...base.entry.trade.replay,memoryId:"hrm1_"+"f".repeat(40)}}}),process={...base.entry,mood:"fomo"},mismatch=await run([wrong.entry],{review:wrong.review}),stale=await run([process],{review:base.review});assert.equal(mismatch.profile.coverage.invalidReviews,1);assert.equal(stale.profile.coverage.staleReviews,1);});
test("duplicate references contribute once, read once, and conflicting duplicates are order invariant",async()=>{const {entry,review}=fixture(),same=await run([entry,{...entry}],{review});assert.equal(same.profile.coverage.eligibleCurrentReviews,1);assert.equal(same.diagnostics.filesRead,1);assert.equal(same.profile.coverage.duplicateReviewReferences,1);const conflict={...entry,mood:"fomo"},a=await run([entry,conflict],{review}),b=await run([conflict,entry],{review});assert.equal(a.profile.coverage.eligibleCurrentReviews,0);assert.equal(a.profile.coverage.invalidReviews,1);assert.equal(a.diagnostics.filesRead,0);assert.deepEqual(a.profile,b.profile);});
test("unsupported and archived records are excluded without entering aggregates",async()=>{const base=fixture(),unsupported={...base.review,engineVersion:"historical-trade-review/0.1.0"},bad=await run([base.entry],{review:unsupported}),archived={...base.entry,archived:true,archivedAt:"2024-01-03T00:00:00Z"},off=await run([archived],{review:base.review}),on=await run([archived],{review:base.review,filters:{includeArchived:true}});assert.equal(bad.profile.coverage.unsupportedReviews,1);assert.equal(off.profile.coverage.archivedExcluded,1);assert.equal(off.profile.coverage.eligibleCurrentReviews,0);assert.equal(on.profile.coverage.eligibleCurrentReviews,1);});
