import test from "node:test";import assert from "node:assert/strict";
import {FlowAggregator,aggregateTrades,bubbleComposition} from "../app/lib/order-flow/aggregator.ts";import {FlowRenderStore} from "../app/lib/order-flow/render-store.ts";import {DEFAULT_ORDER_FLOW_SETTINGS,sanitiseOrderFlowSettings} from "../app/lib/order-flow/settings.ts";import {buildDomRows} from "../app/lib/order-flow/dom.ts";import {fractionalLogicalIndex} from "../app/lib/order-flow/time-projection.ts";import {stableLabelLane} from "../app/lib/chart/world-projection.ts";import {sliderToAmount} from "../app/lib/manual-paper-sizing.ts";
const book=(quantity=1)=>({valid:true,version:1,bids:[{price:100,contractQuantity:quantity,orderCount:1}],asks:[{price:101,contractQuantity:quantity,orderCount:1}]});
test("book capture records tick changes without time bucketing",()=>{const flow=new FlowAggregator({priceStep:1});flow.captureBook(book(1),1,1100);flow.captureBook(book(3),1,1500);assert.equal(flow.heatmap.length,4);assert.deepEqual(flow.heatmap.filter(v=>v.priceTick===100).map(v=>v.bidQuantity),[1,3])});
test("history and cell limits prune bounded capture",()=>{const flow=new FlowAggregator({historyMs:1000,maxCells:2,timeBucketMs:1000,priceStep:1});flow.captureBook(book(),1,1000);flow.captureBook(book(),1,3000);assert.ok(flow.heatmap.every(v=>v.timestampMs>=2000));assert.ok(flow.heatmap.length<=2)});
test("raw trades deduplicate and aggregate only at render coordinates",()=>{const flow=new FlowAggregator({priceStep:1});const deal=(tradeId,side,notional)=>({tradeId,side,notional,timeMs:1000,price:100,symbol:"BTC_USDT",baseQuantity:1});assert.equal(flow.addDeal(deal("a","buy",60)),true);assert.equal(flow.addDeal(deal("a","buy",60)),false);flow.addDeal(deal("b","sell",40));const dot=aggregateTrades(flow.trades,()=>20,()=>30)[0];assert.deepEqual(bubbleComposition(dot),{total:100,buyRatio:.6,sellRatio:.4,delta:20,aggressorPercent:.6,dominant:"buy"})});
test("render store batches notifications into one requested frame",()=>{const callbacks=[];const original=globalThis.requestAnimationFrame;globalThis.requestAnimationFrame=fn=>{callbacks.push(fn);return callbacks.length};try{const store=new FlowRenderStore(DEFAULT_ORDER_FLOW_SETTINGS);let calls=0;store.subscribe(()=>calls++);store.update({enabled:true});store.update({bookValid:true});assert.equal(callbacks.length,1);callbacks[0]();assert.equal(calls,1)}finally{globalThis.requestAnimationFrame=original}});
test("DOM sorts asks above midpoint, bids below, and calculates cumulative notional",()=>{const rows=buildDomRows({valid:true,version:1,asks:[{price:103,contractQuantity:1,orderCount:1},{price:101,contractQuantity:2,orderCount:1}],bids:[{price:98,contractQuantity:1,orderCount:1},{price:100,contractQuantity:2,orderCount:1}]},1,10);assert.deepEqual(rows.asks.map(v=>v.price),[101,103]);assert.deepEqual(rows.bids.map(v=>v.price),[100,98]);assert.equal(rows.bids[1].cumulativeNotional,298)});
test("settings migrate disabled but visually useful and clamp every exposed group",()=>{const migrated=sanitiseOrderFlowSettings({heatmap:{opacity:9,rangeBps:2},dom:{levels:42},alerts:{maximumVisible:20},bubbles:{minimumRadius:-2}});assert.equal(migrated.enabled,false);assert.equal(migrated.heatmapVisible,true);assert.equal(migrated.bubblesVisible,true);assert.equal(migrated.heatmap.opacity,1);assert.equal(migrated.heatmap.rangeBps,10);assert.equal(migrated.dom.levels,10);assert.equal(migrated.alerts.maximumVisible,3);assert.equal(migrated.bubbles.minimumRadius,1)});
test("fractional projection supports every native timeframe and label lanes ignore viewport",()=>{for(const frame of ["1m","5m","15m","30m","1h","4h","8h","1d","1w","1M"]){const value=fractionalLogicalIndex(30_000,0,4,frame);assert.ok(value>=3.5&&value<4.5)}const model={id:"signal:1700",time:1700,price:63000,lane:stableLabelLane("signal:1700",11,4)};for(const range of [{from:0,to:20},{from:100,to:120}])assert.deepEqual({...model,lane:stableLabelLane(model.id,11,4)},model,JSON.stringify(range))});
test("Manual Paper slider conversions share ticket sizing semantics",()=>{assert.equal(sliderToAmount(25,1000,"fixed-margin",5),250);assert.equal(sliderToAmount(25,1000,"fixed-notional",5),1250);assert.equal(sliderToAmount(25,1000,"equity-percent",5),25)});

test("DOM width defaults to 230 and sanitises into its accessible range",()=>{assert.equal(DEFAULT_ORDER_FLOW_SETTINGS.dom.width,230);assert.equal(sanitiseOrderFlowSettings({dom:{width:1}}).dom.width,190);assert.equal(sanitiseOrderFlowSettings({dom:{width:999}}).dom.width,380)});

test("removed depth emits an explicit zero transition",()=>{const flow=new FlowAggregator({priceStep:1});flow.captureBook(book(),1,1000,200);flow.captureBook({...book(),bids:[{price:99,contractQuantity:2,orderCount:1}]},1,2000,200);assert.equal(flow.heatmap.find(v=>v.timestampMs===2000&&v.priceTick===100).bidQuantity,0)});
test("bubble retention is independent of short heatmap history",()=>{const flow=new FlowAggregator({historyMs:500,maxBubbles:2,priceStep:1});const deal=(tradeId,timeMs)=>({tradeId,timeMs,side:"buy",notional:10,price:100+timeMs,symbol:"BTC_USDT",baseQuantity:1,contractQuantity:1});flow.addDeal(deal("old",1000));flow.captureBook(book(),1,10000);assert.equal(flow.trades.length,1);flow.addDeal(deal("two",2000));flow.addDeal(deal("three",3000));assert.deepEqual(flow.trades.map(v=>v.timestampMs),[2000,3000])});

test("development visual fixture has persistent bands, removals, and zoom-cluster trades",async()=>{const {createDizyFlowVisualFixture}=await import("../app/lib/order-flow/visual-fixture.ts"),fixture=createDizyFlowVisualFixture(0);assert.equal(fixture.candles.length,24);assert.ok(fixture.liquidity.some(v=>v.bidQuantity===0&&v.askQuantity===0));const zoomedOut=aggregateTrades(fixture.trades,()=>10,()=>10),zoomedIn=aggregateTrades(fixture.trades,t=>t/1000,p=>p*100);assert.ok(zoomedOut.length<zoomedIn.length)});
