import test from "node:test";
import assert from "node:assert/strict";
import { BEHAVIOUR_LIMITS, behaviourSampleBand, buildDizyBrainBehaviourProfile, isRecurring, validateBehaviourFilters } from "../app/lib/dizybrain-behaviour.ts";

const component=(assessment="unavailable",evidenceCompleteness=50)=>({assessment,evidenceCompleteness,qualityScore:null,reasonCodes:[],confidence:50,limitations:[]});
function joined(index,{timing="extended",severity="warning",quality="poor",pnl=1,tag="Breakout"}={}){const time=Date.parse(`2024-01-${String(index+1).padStart(2,"0")}T12:00:00Z`),base=component();return {archived:false,quality,planDiscipline:"completely",mood:"fomo",tags:[tag,tag.toLowerCase()],notesPresent:true,review:{id:`review-${index}`,engineVersion:"historical-trade-review/1.1.0",reviewContentHash:String(index).padStart(64,"a"),exitTimeMs:time,entryTimeMs:time-3_600_000,symbol:"BTC_USDT",timeframe:"1m",marketKey:"mexc:futures:BTC_USDT",confidenceBand:"moderate",reviewConfidence:70,setup:base,signal:{...base,directionConsistent:true},trend:{...base,alignment:"aligned"},entry:{...base,timing},risk:base,exit:base,process:base,scores:{setupEvidenceCompleteness:50,signalEvidenceCompleteness:50,trendEvidenceCompleteness:50,entryEvidenceCompleteness:50,riskEvidenceCompleteness:50,exitEvidenceCompleteness:50,processEvidenceCompleteness:50},evidence:{brainContext:false,flowContext:false,stopKnown:false},outcome:{classification:pnl>0?"profit":"loss",pnl,rMultiple:index%2?1:null},findings:[{code:"ENTRY_EXTENDED",category:"entry",severity,title:"Extended entry"}],limitations:[]}};}

test("sample bands use documented boundaries",()=>{assert.deepEqual([0,1,4,5,19,20,49,50].map(behaviourSampleBand),["unavailable","very-small","very-small","limited","limited","developing","developing","broader"]);});
test("filter validation is bounded and UTC",()=>{assert.equal(validateBehaviourFilters({symbol:" btc_usdt ",archived:"true"}).symbol,"BTC_USDT");assert.throws(()=>validateBehaviourFilters({from:"01/02/2024"}),/UTC date/);assert.throws(()=>validateBehaviourFilters({unknown:"x"}),/Unsupported/);});
test("recurrence thresholds are conservative",()=>{assert.equal(isRecurring(4,4),false);assert.equal(isRecurring(5,3),true);assert.equal(isRecurring(20,4),false);});
test("profile is deterministic, deduplicates tags and findings, and separates process from outcome",()=>{const trades=Array.from({length:5},(_,i)=>joined(i,{pnl:i===0?-1:1,quality:i===0?"good":"poor"})),options={reviewedTrades:trades,generatedAt:"2024-02-01T00:00:00Z"},a=buildDizyBrainBehaviourProfile(options),b=buildDizyBrainBehaviourProfile(options);assert.deepEqual(a,b);assert.equal(a.findings.warning[0].occurrenceCount,5);assert.equal(a.findings.warning[0].recurrence,"recurring");assert.equal(a.markets.tags[0].count,5);assert.equal(a.coverage.eligibleCurrentReviews,5);assert.equal(a.process.goodLosingTrades,1);assert.equal(a.process.poorWinningTrades,4);assert.equal(a.execution.risk.find(x=>x.key==="unavailable").count,5);assert.equal(a.reviewAreas.length,1);assert.ok(a.observations.every(x=>!/will|caused|should|guarantee|psychological/i.test(x.summary)));assert.doesNotThrow(()=>JSON.stringify(a));});
test("hash ignores source ordering and tag casing order but responds to assessment data",()=>{const one=joined(1),two=joined(2),generatedAt="2024-02-01T00:00:00Z",a=buildDizyBrainBehaviourProfile({reviewedTrades:[two,one],generatedAt}),b=buildDizyBrainBehaviourProfile({reviewedTrades:[one,two],generatedAt}),changed=buildDizyBrainBehaviourProfile({reviewedTrades:[one,{...two,mood:"calm"}],generatedAt});assert.equal(a.generatedFromHash,b.generatedFromHash);assert.notEqual(a.generatedFromHash,changed.generatedFromHash);assert.ok(a.observations.length<=BEHAVIOUR_LIMITS.observations);});
test("global and filtered coverage use explicit independent denominators",()=>{const trades=Array.from({length:10},(_,i)=>joined(i)),generatedAt="2024-02-01T00:00:00Z",full=buildDizyBrainBehaviourProfile({reviewedTrades:trades,generatedAt,coverage:{totalJournalTradeReviews:100,generatedReviews:80,currentValidReviews:70,filteredCandidateReviews:10}}),partial=buildDizyBrainBehaviourProfile({reviewedTrades:trades.slice(0,5),generatedAt,coverage:{totalJournalTradeReviews:100,generatedReviews:80,currentValidReviews:70,filteredCandidateReviews:10}}),zero=buildDizyBrainBehaviourProfile({reviewedTrades:[],generatedAt,coverage:{totalJournalTradeReviews:100,generatedReviews:80,currentValidReviews:70,filteredCandidateReviews:0}});assert.equal(full.coverage.reviewCoveragePct,80);assert.equal(full.coverage.currentReviewCoveragePct,70);assert.equal(full.coverage.filteredCurrentCoveragePct,100);assert.equal(partial.coverage.filteredCurrentCoveragePct,50);assert.equal(zero.coverage.filteredCurrentCoveragePct,null);});
test("date and symbol filters change only the filtered eligible sample",()=>{const btc=joined(0),eth={...joined(1),review:{...joined(1).review,symbol:"ETH_USDT"}},generatedAt="2024-02-01T00:00:00Z",symbol=buildDizyBrainBehaviourProfile({reviewedTrades:[btc,eth],filters:{symbol:"BTC_USDT"},generatedAt,coverage:{totalJournalTradeReviews:100,generatedReviews:90,currentValidReviews:80,filteredCandidateReviews:1}}),date=buildDizyBrainBehaviourProfile({reviewedTrades:[btc,eth],filters:{from:"2024-01-02",to:"2024-01-02"},generatedAt,coverage:{totalJournalTradeReviews:100,generatedReviews:90,currentValidReviews:80,filteredCandidateReviews:1}});for(const profile of [symbol,date]){assert.equal(profile.coverage.eligibleCurrentReviews,1);assert.equal(profile.coverage.filteredCurrentCoveragePct,100);assert.equal(profile.coverage.currentReviewCoveragePct,80);assert.equal(profile.coverage.reviewCoveragePct,90);}});
