import test from "node:test";import assert from "node:assert/strict";
import {FlowAggregator,aggregateTrades,automaticPriceStep,bubbleComposition,bubbleThreshold} from "../app/lib/order-flow/aggregator.ts";import {FlowRenderStore} from "../app/lib/order-flow/render-store.ts";import {DEFAULT_ORDER_FLOW_SETTINGS,sanitiseOrderFlowSettings} from "../app/lib/order-flow/settings.ts";import {buildDomRows} from "../app/lib/order-flow/dom.ts";import {fractionalLogicalIndex,timestampToLogicalPosition} from "../app/lib/order-flow/time-projection.ts";import {stableLabelLane} from "../app/lib/chart/world-projection.ts";import {sliderToAmount} from "../app/lib/manual-paper-sizing.ts";
const book=(quantity=1)=>({valid:true,version:1,bids:[{price:100,contractQuantity:quantity,orderCount:1}],asks:[{price:101,contractQuantity:quantity,orderCount:1}]});
test("book capture records tick changes without time bucketing",()=>{const flow=new FlowAggregator({priceStep:1});flow.captureBook(book(1),1,1100);flow.captureBook(book(3),1,1500);assert.equal(flow.heatmap.length,4);assert.deepEqual(flow.heatmap.filter(v=>v.priceTick===100).map(v=>v.bidQuantity),[1,3])});
test("history and cell limits prune bounded capture",()=>{const flow=new FlowAggregator({historyMs:1000,maxCells:2,timeBucketMs:1000,priceStep:1});flow.captureBook(book(),1,1000);flow.captureBook(book(),1,3000);assert.ok(flow.heatmap.every(v=>v.timestampMs>=2000));assert.ok(flow.heatmap.length<=2)});
test("raw trades deduplicate and aggregate in stable data-space buckets",()=>{const flow=new FlowAggregator({priceStep:1});const deal=(tradeId,side,notional)=>({tradeId,side,notional,timeMs:1000,price:100,symbol:"BTC_USDT",baseQuantity:1});assert.equal(flow.addDeal(deal("a","buy",60)),true);assert.equal(flow.addDeal(deal("a","buy",60)),false);flow.addDeal(deal("b","sell",40));const dot=aggregateTrades(flow.trades,"BTC_USDT",1000,1)[0];assert.deepEqual(bubbleComposition(dot),{total:100,buyRatio:.6,sellRatio:.4,delta:20,aggressorPercent:.6,dominant:"buy"})});
test("render store batches notifications into one deferred task",async()=>{const store=new FlowRenderStore(DEFAULT_ORDER_FLOW_SETTINGS);let calls=0;const unsubscribe=store.subscribe(()=>calls++);try{store.update({enabled:true});store.update({bookValid:true});assert.equal(calls,0);await new Promise(resolve=>setTimeout(resolve,10));assert.equal(calls,1)}finally{unsubscribe();store.destroy()}});
test("DOM sorts asks above midpoint, bids below, and calculates cumulative notional",()=>{const rows=buildDomRows({valid:true,version:1,asks:[{price:103,contractQuantity:1,orderCount:1},{price:101,contractQuantity:2,orderCount:1}],bids:[{price:98,contractQuantity:1,orderCount:1},{price:100,contractQuantity:2,orderCount:1}]},1,10);assert.deepEqual(rows.asks.map(v=>v.price),[101,103]);assert.deepEqual(rows.bids.map(v=>v.price),[100,98]);assert.equal(rows.bids[1].cumulativeNotional,298)});
test("settings migrate disabled but visually useful and clamp every exposed group",()=>{const migrated=sanitiseOrderFlowSettings({heatmap:{opacity:9,rangeBps:2},dom:{levels:42},alerts:{maximumVisible:20},bubbles:{minimumRadius:-2}});assert.equal(migrated.enabled,false);assert.equal(migrated.heatmapVisible,true);assert.equal(migrated.bubblesVisible,true);assert.equal(migrated.heatmap.opacity,1);assert.equal(migrated.heatmap.rangeBps,10);assert.equal(migrated.dom.levels,10);assert.equal(migrated.alerts.maximumVisible,3);assert.equal(migrated.bubbles.minimumRadius,1)});
test("fractional projection supports every native timeframe and label lanes ignore viewport",()=>{for(const frame of ["1m","5m","15m","30m","1h","4h","8h","1d","1w","1M"]){const value=fractionalLogicalIndex(30_000,0,4,frame);assert.ok(value>=3.5&&value<4.5)}const model={id:"signal:1700",time:1700,price:63000,lane:stableLabelLane("signal:1700",11,4)};for(const range of [{from:0,to:20},{from:100,to:120}])assert.deepEqual({...model,lane:stableLabelLane(model.id,11,4)},model,JSON.stringify(range))});
test("Manual Paper slider conversions share ticket sizing semantics",()=>{assert.equal(sliderToAmount(25,1000,"fixed-margin",5),250);assert.equal(sliderToAmount(25,1000,"fixed-notional",5),1250);assert.equal(sliderToAmount(25,1000,"equity-percent",5),25)});

test("DOM width defaults to 260 and sanitises into its accessible range",()=>{assert.equal(DEFAULT_ORDER_FLOW_SETTINGS.dom.width,260);assert.equal(sanitiseOrderFlowSettings({dom:{width:1}}).dom.width,260);assert.equal(sanitiseOrderFlowSettings({dom:{width:999}}).dom.width,380)});

test("removed depth emits an explicit zero transition",()=>{const flow=new FlowAggregator({priceStep:1});flow.captureBook(book(),1,1000,200);flow.captureBook({...book(),bids:[{price:99,contractQuantity:2,orderCount:1}]},1,2000,200);assert.equal(flow.heatmap.find(v=>v.timestampMs===2000&&v.priceTick===100).bidQuantity,0)});
test("bubble retention is independent of short heatmap history",()=>{const flow=new FlowAggregator({historyMs:500,maxBubbles:2,priceStep:1});const deal=(tradeId,timeMs)=>({tradeId,timeMs,side:"buy",notional:10,price:100+timeMs,symbol:"BTC_USDT",baseQuantity:1,contractQuantity:1});flow.addDeal(deal("old",1000));flow.captureBook(book(),1,10000);assert.equal(flow.trades.length,1);flow.addDeal(deal("two",2000));flow.addDeal(deal("three",3000));assert.deepEqual(flow.trades.map(v=>v.timestampMs),[2000,3000])});

test("development visual fixture has persistent bands, removals, and zoom-cluster trades",async()=>{const {createDizyFlowVisualFixture}=await import("../app/lib/order-flow/visual-fixture.ts"),fixture=createDizyFlowVisualFixture(0);assert.equal(fixture.candles.length,24);assert.ok(fixture.liquidity.some(v=>v.bidQuantity===0&&v.askQuantity===0));const zoomedOut=aggregateTrades(fixture.trades,"BTC_USDT",1000,.1),zoomedIn=aggregateTrades(fixture.trades,"BTC_USDT",1000,.1);assert.deepEqual(zoomedOut.map(v=>v.id),zoomedIn.map(v=>v.id))});
test("disabled adaptive filtering keeps every bubble above the explicit minimum",()=>{assert.equal(bubbleThreshold([10,20,1000],{adaptive:false,minimumSamples:1,percentile:.9,minimumNotional:0}),0);assert.equal(bubbleThreshold([10,20,1000],{adaptive:false,minimumSamples:1,percentile:.9,minimumNotional:15}),15)});
test("events project into known and current intervals but not the future",()=>{const minute=60_000,base=Date.UTC(2026,0,1),candles=Array.from({length:3},(_,i)=>({time:base/1000+i*60})),now=base+4.25*minute;assert.equal(timestampToLogicalPosition(candles,base+.5*minute,"1m",now),0);assert.equal(timestampToLogicalPosition(candles,base+3.5*minute,"1m",now),3);assert.equal(timestampToLogicalPosition(candles,base+5*minute,"1m",now),null);const monthly=[{time:base/1000}],projected=timestampToLogicalPosition(monthly,Date.UTC(2026,1,15),"1M",Date.UTC(2026,1,20));assert.equal(projected!==null&&projected>0,true)});
test("automatic price steps prefer contract priceUnit and fall back to priceScale",()=>{assert.equal(automaticPriceStep({priceUnit:"0.25",priceScale:2}),.25);assert.equal(automaticPriceStep({priceScale:3}),.001)});

test("BTC-scale heatmap bins span several pixels and removals terminate bands",async()=>{const {buildHeatmapSegments,effectiveHeatmapPriceStep}=await import("../app/lib/order-flow/heatmap.ts"),{createDizyFlowVisualFixture}=await import("../app/lib/order-flow/visual-fixture.ts"),fixture=createDizyFlowVisualFixture(1_000_000),step=effectiveHeatmapPriceStep(1200/600,.1),segments=buildHeatmapSegments(fixture.liquidity,step,1_000_000,1_000_000+24*15*60_000,fixture.liquidity.at(-1).timestampMs);assert.ok(step>=8&&step<=10);assert.ok(segments.length>8);assert.ok(segments.every(v=>v.toMs<=fixture.liquidity.at(-1).timestampMs));assert.ok(segments.some(v=>v.toMs===1_000_000+15*15*60_000))});
test("bubble identity is data-space stable across viewport projections",async()=>{const {createDizyFlowVisualFixture}=await import("../app/lib/order-flow/visual-fixture.ts"),fixture=createDizyFlowVisualFixture(0),groups=aggregateTrades(fixture.trades,"BTC_USDT",1000,.1),ids=groups.map(v=>v.id),panA=groups.map(v=>v.timeMs/1000),panB=groups.map(v=>v.timeMs/500-40);assert.ok(groups.length>=5);assert.deepEqual(groups.map(v=>v.id),ids);assert.notDeepEqual(panA,panB)});
test("candle completion and timeframe projection updates do not recreate retained render data",async()=>{const {createDizyFlowVisualFixture}=await import("../app/lib/order-flow/visual-fixture.ts"),fixture=createDizyFlowVisualFixture(1_000_000),store=new FlowRenderStore(DEFAULT_ORDER_FLOW_SETTINGS),heatmap=fixture.liquidity,trades=fixture.trades;store.update({generation:"BTC_USDT",heatmap,trades,captureEnded:2_000_000});store.update({bookValid:true});assert.strictEqual(store.getSnapshot().heatmap,heatmap);assert.strictEqual(store.getSnapshot().trades,trades);store.update({generation:"BTC_USDT"});assert.strictEqual(store.getSnapshot().heatmap,heatmap);assert.strictEqual(store.getSnapshot().trades,trades)});

test("volume bubble settings sanitise independent opacity and aggregation controls",()=>{
 const settings=sanitiseOrderFlowSettings({bubbles:{buyColour:"#112233",sellColour:"#445566",outlineColour:"#778899",opacity:2,outlineOpacity:-1,timeBucketMs:2000,priceMode:"fixed",fixedPriceStep:.25,minimumNotional:4321,adaptive:true,percentile:.91,minimumRadius:6,maximumRadius:30,maximumRetained:9000}});
 assert.deepEqual({buyColour:settings.bubbles.buyColour,sellColour:settings.bubbles.sellColour,outlineColour:settings.bubbles.outlineColour,opacity:settings.bubbles.opacity,outlineOpacity:settings.bubbles.outlineOpacity,timeBucketMs:settings.bubbles.timeBucketMs,priceMode:settings.bubbles.priceMode,fixedPriceStep:settings.bubbles.fixedPriceStep,minimumNotional:settings.bubbles.minimumNotional,adaptive:settings.bubbles.adaptive,percentile:settings.bubbles.percentile,minimumRadius:settings.bubbles.minimumRadius,maximumRadius:settings.bubbles.maximumRadius,maximumRetained:settings.bubbles.maximumRetained},{buyColour:"#112233",sellColour:"#445566",outlineColour:"#778899",opacity:1,outlineOpacity:0,timeBucketMs:2000,priceMode:"fixed",fixedPriceStep:.25,minimumNotional:4321,adaptive:true,percentile:.91,minimumRadius:6,maximumRadius:30,maximumRetained:9000});
 assert.equal(sanitiseOrderFlowSettings({bubbles:{outlineOpacity:4}}).bubbles.outlineOpacity,1);
});

test("render-store bubble setting updates are immediate and retain captured bubbles",()=>{
 const store=new FlowRenderStore(DEFAULT_ORDER_FLOW_SETTINGS),trades=[{tradeId:"kept",timestampMs:1,price:2,quantity:3,notional:6,side:"buy"}];
 store.update({trades});const changed={...DEFAULT_ORDER_FLOW_SETTINGS,bubbles:{...DEFAULT_ORDER_FLOW_SETTINGS.bubbles,opacity:.75,outlineOpacity:.1,buyColour:"#123456"}};
 store.updateSettings(changed);
 assert.strictEqual(store.getSnapshot().trades,trades);assert.strictEqual(store.getSnapshot().settings,changed);assert.equal(store.getSnapshot().settings.bubbles.opacity,.75);
 store.destroy();
});

test("production five-minute capture reproduces the narrow 15-minute stripe",()=>{const chartWidth=1180,visibleCandles=96,candleMs=15*60_000,width=5*60_000/(visibleCandles*candleMs)*chartWidth;assert.ok(width<5,`former stripe was ${width}px`)});
test("two-hour genuine tape occupies the expected 15-minute chart width",()=>{const width=2*60*60_000/(96*15*60_000)*1180;assert.ok(width>90&&width<110)});
test("compact changes convert contracts once and preserve removals",()=>{const flow=new FlowAggregator({historyMs:6*60*60_000,maxCells:20_000});flow.ingestCompact([{timestampMs:1000,priceTick:100,bidContracts:5,askContracts:0},{timestampMs:2000,priceTick:100,bidContracts:0,askContracts:0}],.5,.01);assert.deepEqual(flow.heatmap.map(v=>[v.price,v.bidQuantity]),[[50,.05],[50,0]])});
test("native DizyFlow SVG artifacts reject raster wrappers",async()=>{const fs=await import("node:fs/promises"),path=await import("node:path");for(const dir of ["docs/artifacts/dizyflow-live-retention","docs/artifacts/dizyflow-liquidity-tape"]){const names=await fs.readdir(dir);for(const name of names.filter(v=>v.endsWith(".svg"))){const svg=await fs.readFile(path.join(dir,name),"utf8");assert.doesNotMatch(svg,/<image|data:image|\.png|\.jpe?g/i,name);assert.match(svg,/<(?:rect|line|path|circle)\b/,name)}}});
