import test from "node:test";
import assert from "node:assert/strict";
import { captureHistoricalReplayMemory } from "../app/lib/historical-replay-memory.ts";
import { buildDizyBrainTradeReview,historicalTradeCandleBoundaries,tradeReviewInputHash } from "../app/lib/dizybrain-trade-review.ts";
const base=1_700_000_040,candles=Array.from({length:9},(_,i)=>({time:base+i*60,open:100+i,high:102+i,low:99+i,close:101+i,volume:10}));
function fixture(direction="long"){const signalTimeMs=(base+120)*1000,entryTimeMs=(base+180)*1000,exitTimeMs=(base+360)*1000,tradeId="jt1|fixture";const memory=captureHistoricalReplayMemory({tradeId,replaySessionId:`journal-replay|${tradeId}`,marketKey:"mexc:futures:BTC_USDT",symbol:"BTC_USDT",timeframe:"1m",signalTimeMs,entryTimeMs,exitTimeMs,entryPrice:103.5,exitPrice:106.5,direction,strategyVersion:"paper-v1",candles,capturedAtMs:(base+600)*1000});const trade={tradeId,symbol:"BTC_USDT",market:"MEXC Futures",timeframe:"1m",direction,entry:103.5,exit:106.5,stop:101,target:108,positionSize:2,riskPct:1,leverage:3,marginMode:null,fees:null,pnl:direction==="long"?6:-6,pnlPct:direction==="long"?2.9:-2.9,rMultiple:null,openTime:new Date(entryTimeMs).toISOString(),closeTime:new Date(exitTimeMs).toISOString(),closeReason:"manual",strategyVersion:"paper-v1",replay:{sessionId:`journal-replay|${tradeId}`,marketKey:memory.marketKey,symbol:memory.symbol,timeframe:memory.timeframe,entryTimeMs,available:true,source:"retained-memory",memoryId:memory.id,capturedRangeStartMs:memory.rangeStartMs,capturedRangeEndMs:memory.rangeEndMs,candleCount:memory.candles.length,integrityWarnings:[],brainAvailable:false,flowAvailability:"capture-not-supported"},brain:null,signal:{direction,signalTime:new Date(signalTimeMs).toISOString(),label:"confirmed"},dizyBrainReview:{available:false,reviewId:null,engineVersion:null,generatedAt:null,generatedFromHash:null,reviewConfidence:null}};return {memory,entry:{id:"journal-1",schemaVersion:4,type:"trade-review",createdAt:"2024-01-01T00:00:00Z",editedAt:"2024-01-01T00:00:00Z",title:"ignored",archived:false,archivedAt:null,notes:"private note",tags:["breakout"],dismissedPrompts:[],quality:"good",planDiscipline:"completely",mood:"fomo",trade,marketContext:null}};}
const build=(entry,memory)=>buildDizyBrainTradeReview({journalEntry:entry,replayMemory:memory,generatedAt:"2024-02-01T00:00:00Z"});
test("review is deterministic, serializable, and ignores title/archive/note text",()=>{const {entry,memory}=fixture(),a=build(entry,memory),b=build({...entry,title:"changed",archived:true,notes:"another note"},memory);assert.deepEqual(a,b);assert.equal(a.generatedFromHash,tradeReviewInputHash(entry,memory));assert.doesNotThrow(()=>JSON.stringify(a));assert.equal("candles" in a,false);assert.equal(JSON.stringify(a).includes("private note"),false);});
test("process fields change hash while outcomes do not change process or entry scores",()=>{const {entry,memory}=fixture(),a=build(entry,memory);assert.notEqual(tradeReviewInputHash(entry,memory),tradeReviewInputHash({...entry,mood:"calm"},memory));const b=build({...entry,trade:{...entry.trade,pnl:-999,pnlPct:-99}},memory);assert.equal(a.entry.score,b.entry.score);assert.equal(a.process.score,b.process.score);assert.notEqual(a.outcome.classification,b.outcome.classification);});
test("bounded prefixes terminate exactly and excursions use entry through exit only",()=>{const {entry,memory}=fixture(),b=historicalTradeCandleBoundaries(memory),review=build(entry,memory);assert.equal(b.candlesThroughSignal.at(-1).time*1000,memory.signalTimeMs);assert.equal(b.candlesThroughEntry.at(-1).time*1000,memory.entryTimeMs);assert.equal(b.candlesThroughExit.at(-1).time*1000,memory.exitTimeMs);assert.ok(b.candlesAfterExit.every(c=>c.time*1000>memory.exitTimeMs));assert.equal(review.excursion.mfe,4.5);assert.equal(review.excursion.mae,1.5);});
test("short excursion is direction aware and R is unavailable without stop",()=>{const {entry,memory}=fixture("short"),review=build(entry,memory);assert.equal(review.excursion.mfe,1.5);assert.equal(review.excursion.mae,4.5);assert.equal(build({...entry,trade:{...entry.trade,stop:null}},memory).excursion.mfeR,null);});
test("trade and replay identity mismatches fail safely",()=>{const {entry,memory}=fixture();assert.throws(()=>build({...entry,trade:{...entry.trade,symbol:"ETH_USDT"}},memory),/do not match exactly/);assert.throws(()=>build({...entry,trade:{...entry.trade,replay:{...entry.trade.replay,memoryId:"hrm1_bad"}}},memory),/does not reference/);});
