import test from "node:test";
import assert from "node:assert/strict";
import {buildDizyFlowIntelligenceSnapshot,DEFAULT_DIZYFLOW_CONFIG,DizyFlowLiveHistory,normalizeOrderFlowInput,toDizyFlowEvidenceReference} from "../app/lib/order-flow/intelligence.ts";

const now=1_800_000_000_000;
const input=(overrides={})=>({marketKey:"mexc:futures:BTC_USDT",symbol:"BTC_USDT",marketType:"futures",exchange:"mexc",exchangeTimeMs:now-10,receivedTimeMs:now,referencePrice:100,referencePriceSource:"mark",tickSize:.1,quantityStep:.01,bids:[{price:99.9,quantity:2},{price:99.8,quantity:2},{price:99.7,quantity:2},{price:99.6,quantity:20}],asks:[{price:100.1,quantity:2},{price:100.2,quantity:2},{price:100.3,quantity:2},{price:100.4,quantity:2}],recentTrades:[{id:"a",timeMs:now-2000,price:100.1,quantity:1,side:"buy-aggressor"},{id:"b",timeMs:now-1000,price:100.2,quantity:2,side:"sell-aggressor"},{id:null,timeMs:now-500,price:100,quantity:1,side:"unknown"}],feed:{connected:true,snapshotComplete:true,sequenceKnown:true,sequenceContinuous:true,sourceTimestampKnown:true,ageMs:10,stale:false,bidLevelCount:4,askLevelCount:4,recentTradeCount:3,warnings:[]},...overrides});
const build=(current=input(),history=[])=>buildDizyFlowIntelligenceSnapshot({current,history,generatedAt:new Date(now).toISOString()});

test("normalization sorts, merges duplicate levels, deduplicates trades, and retains unknown side",()=>{const value=normalizeOrderFlowInput(input({bids:[{price:99.8,quantity:1},{price:99.9,quantity:2},{price:99.8,quantity:3}],recentTrades:[input().recentTrades[2],input().recentTrades[2]]}));assert.deepEqual(value.bids,[{price:99.9,quantity:2},{price:99.8,quantity:4}]);assert.equal(value.recentTrades.length,1);assert.equal(value.recentTrades[0].side,"unknown")});
test("normalization rejects invalid values, crossed books and missing identity",()=>{assert.throws(()=>normalizeOrderFlowInput(input({marketKey:""})),/identity/);assert.throws(()=>normalizeOrderFlowInput(input({bids:[{price:0,quantity:1}]})),/positive/);assert.throws(()=>normalizeOrderFlowInput(input({asks:[{price:99,quantity:1}]})),/crossed/)});
test("normalization enforces bounded book and trade arrays",()=>{const config={...DEFAULT_DIZYFLOW_CONFIG,maxLevelsPerSide:2,maxTrades:1};const value=normalizeOrderFlowInput(input(),config);assert.equal(value.bids.length,2);assert.equal(value.recentTrades.length,1)});
test("spread, ticks, depth bands and centred imbalance are deterministic",()=>{const value=build();assert.equal(value.spread.absolute,.2);assert.equal(value.spread.ticks,2);assert.equal(value.depth.bands.length,4);assert.equal(value.depth.bands[0].bidNotional,199.8);assert.equal(value.imbalance.formula,"(bidNotional-askNotional)/(bidNotional+askNotional)");assert.ok(value.imbalance.bands.every(x=>x.value===null||(x.value>=-1&&x.value<=1)))});
test("wall candidates are median-relative, bounded and described without intent",()=>{const value=build();assert.ok(value.walls.candidates.some(x=>x.side==="bid"&&x.price===99.6));assert.ok(value.walls.candidates.filter(x=>x.side==="bid").length<=DEFAULT_DIZYFLOW_CONFIG.maxWallsPerSide);assert.doesNotMatch(JSON.stringify(value),/manipulat|spoof|iceberg|will hold|predicts continuation/i)});
test("trade flow retains all aggressor classes and finds multi-level sweep only with continuity",()=>{const value=build();assert.deepEqual([value.trades.buyAggressorVolume,value.trades.sellAggressorVolume,value.trades.unknownVolume],[1,2,1]);const swept=build(input({recentTrades:[{id:"1",timeMs:now-1000,price:100.1,quantity:2,side:"buy-aggressor"},{id:"2",timeMs:now,price:100.2,quantity:2,side:"buy-aggressor"}]}));assert.equal(swept.sweeps.candidates[0].direction,"upward-ask");assert.equal(build(input({feed:{...input().feed,stale:true}})).sweeps.candidates.length,0)});
test("confidence reflects evidence quality rather than imbalance",()=>{const bidHeavy=build(),askHeavy=build(input({bids:input().asks.map(x=>({price:200-x.price,quantity:x.quantity})),asks:input().bids.map(x=>({price:200-x.price,quantity:x.quantity})).sort((a,b)=>a.price-b.price)}));assert.equal(bidHeavy.intelligenceConfidence,askHeavy.intelligenceConfidence);assert.equal(build(input({feed:{...input().feed,connected:false}})).confidenceBand,"insufficient");assert.notEqual(build(input({feed:{...input().feed,stale:true}})).confidenceBand,"high")});
test("hash normalizes source ordering and changes with evidence",()=>{const a=build(),b=build(input({bids:[...input().bids].reverse(),asks:[...input().asks].reverse(),recentTrades:[...input().recentTrades].reverse()}));assert.equal(a.inputHash,b.inputHash);assert.notEqual(a.inputHash,build(input({bids:[{price:99.9,quantity:99},...input().bids.slice(1)]})).inputHash)});
test("history is bounded and resets on market, symbol and discontinuity",()=>{const history=new DizyFlowLiveHistory({...DEFAULT_DIZYFLOW_CONFIG,maxHistory:2});history.push(input({receivedTimeMs:now-2}));history.push(input({receivedTimeMs:now-1}));history.push(input());assert.equal(history.size(),2);history.push(input({marketKey:"mexc:futures:ETH_USDT",symbol:"ETH_USDT",bids:[{price:99,quantity:1}],asks:[{price:101,quantity:1}]}));assert.equal(history.size(),1);history.push(input({feed:{...input().feed,sequenceContinuous:false}}));assert.equal(history.size(),1)});
test("live DizyBrain reference is compact and snapshot remains JSON serializable",()=>{const snapshot=build(),reference=toDizyFlowEvidenceReference(snapshot);assert.equal(reference.inputHash,snapshot.inputHash);assert.equal("bids" in reference,false);assert.doesNotThrow(()=>JSON.stringify(snapshot))});
test("disconnected and stale feeds emit no current findings and disclose limitations",()=>{for(const current of [input({feed:{...input().feed,connected:false}}),input({feed:{...input().feed,stale:true}})])assert.equal(build(current).findings.length,0);assert.ok(build(input({recentTrades:[]})).limitations.some(x=>x.code==="TRADE_FLOW_UNAVAILABLE"))});
