import test from "node:test";import assert from "node:assert/strict";
import {aggregateRecentTrades,buildDomRows,calculateBookMarketState,flashStrength,liquidityWidths,navigationIndex,queueAhead,virtualWindow} from "../app/lib/order-flow/dom.ts";
const level=(price,contractQuantity)=>({price,contractQuantity,orderCount:1});
test("DOM reports valid, crossed, one-sided, empty and invalid books",()=>{assert.deepEqual(calculateBookMarketState({valid:true,version:1,bids:[level(99,1)],asks:[level(101,1)]}),{kind:"valid",bestBid:99,bestAsk:101,midpoint:100,spread:2});assert.equal(calculateBookMarketState({valid:true,version:1,bids:[level(101,1)],asks:[level(100,1)]}).kind,"crossed");assert.equal(calculateBookMarketState({valid:true,version:1,bids:[level(99,1)],asks:[]}).kind,"one-sided");assert.equal(calculateBookMarketState({valid:true,version:1,bids:[],asks:[]}).kind,"empty");assert.equal(calculateBookMarketState({valid:false,version:1,bids:[],asks:[]}).kind,"invalid")});
test("DOM stable keys, ordering, grouping, cumulative totals and reused clusters",()=>{const rows=buildDomRows({valid:true,version:1,bids:[level(99.9,1),level(99.8,1),level(99.7,20)],asks:[level(100.1,1),level(100.2,1),level(100.3,20)]},1,10,"0.1",{enabled:true,multiple:4,minimumSamples:3});assert.deepEqual(rows.bids.map(v=>v.price),[99.9,99.8,99.7]);assert.deepEqual(rows.asks.map(v=>v.price),[100.1,100.2,100.3]);assert.equal(rows.bids[2].cumulativeContractQuantity,22);assert.equal(rows.bids[0].key,"bid:99.9");assert.equal(rows.bids[2].largeCluster,true)});
test("linear/log liquidity widths compare per side or total",()=>{const {bids,asks}=buildDomRows({valid:true,version:1,bids:[level(99,10)],asks:[level(101,20)]},1,10);assert.equal(liquidityWidths(bids,asks,"linear","per-side",false).get(bids[0].key),1);assert.ok(Math.abs(liquidityWidths(bids,asks,"linear","total",false).get(bids[0].key)-99/202)<1e-12);assert.ok(liquidityWidths(bids,asks,"logarithmic","total",false).get(bids[0].key)>99/202)});
test("virtualisation bounds rows with overscan and keyboard navigation",()=>{assert.deepEqual(virtualWindow(1000,200,100,20,3),{start:8,end:19,offset:160,visible:5,overscan:3});assert.equal(navigationIndex(0,"ArrowUp",10,4),0);assert.equal(navigationIndex(1,"PageDown",10,4),5);assert.equal(navigationIndex(4,"End",10,4),9);assert.equal(navigationIndex(4,"Home",10,4),0)});
test("recent public trades aggregate by grouped price and decay",()=>{const now=10_000,trades=[{tradeId:"a",timestampMs:9900,price:100.01,quantity:2,notional:200,side:"buy"},{tradeId:"b",timestampMs:9950,price:100.02,quantity:3,notional:300,side:"buy"},{tradeId:"c",timestampMs:9950,price:101,quantity:1,notional:101,side:"sell"}];const flashes=aggregateRecentTrades(trades,.1,now,1000);assert.equal(flashes.length,2);assert.equal(flashes.find(v=>v.side==="buy").quantity,5);assert.ok(flashStrength(flashes[0],now,1000)>flashStrength(flashes[0],now+500,1000));assert.equal(flashStrength(flashes[0],now,1000,true),0)});
test("queue estimate is visible size only and rejects invalid rows",()=>{const row=buildDomRows({valid:true,version:1,bids:[level(99,5)],asks:[]},.01,10).bids[0];assert.equal(queueAhead(row,"contracts"),5);assert.equal(queueAhead(row,"base"),.05);assert.equal(queueAhead(row,"usdt"),4.95);assert.equal(queueAhead(undefined,"contracts"),null);assert.equal(queueAhead({price:-1,contractQuantity:1,baseQuantity:1,notional:1},"contracts"),null)});
