import assert from "node:assert/strict";
import { mkdtempSync, rmSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import test from "node:test";
import { SqliteExecutionRiskStore, ExecutionRiskStoreError, validateExecutionRiskPolicy } from "../app/lib/execution/internal/risk-store.ts";
import { evaluateExecutionRisk } from "../app/lib/execution/internal/risk.ts";

const now=new Date("2026-08-13T12:00:00Z");
const base={userId:"userA",accountId:"account1",enabled:true,reviewAt:"2026-09-01T00:00:00Z",allowedSymbols:["BTC_USDT","ETH_USDT"],maximumLeverage:10,maximumOrderNotional:10_000,maximumGrossNotional:100_000,maximumDailyDrawdownUsdt:1000,maximumDailyDrawdownFraction:.1,maximumOrderMarginFractionOfAvailable:.5};
const intent={userId:"userA",accountId:"account1",symbol:"BTC_USDT",leverage:5,reduceOnly:false};
const preview={estimatedNotional:1000,estimatedMargin:200};
const prereq={accountState:{positions:[]},referencePrices:new Map(),riskSnapshot:{userId:"userA",accountId:"account1",observedAt:now.toISOString(),equity:10_000,availableMargin:1000,dayStartEquity:10_000}};

test("fresh store defaults to exact-pair denial and CAS revisions persist",()=>{const s=new SqliteExecutionRiskStore(":memory:");assert.equal(evaluateExecutionRisk(s,intent,prereq,preview,now).reason,"ACCOUNT_NOT_AUTHORIZED");const one=s.replace(0,base,now);assert.equal(one.revision,1);assert.equal(s.read("userB","account1"),null);assert.equal(s.read("userA","account2"),null);assert.throws(()=>s.replace(0,base,now),e=>e.code==="EXECUTION_RISK_CONFLICT");const two=s.replace(1,{...base,enabled:false},now);assert.equal(two.revision,2);assert.equal(s.read("userA","account1").enabled,false);});
test("policy cannot loosen global ceilings or accept unbounded values",()=>{for(const change of [{maximumLeverage:21},{maximumOrderNotional:50001},{allowedSymbols:["XRP_USDT"]},{maximumDailyDrawdownFraction:1.1}])assert.throws(()=>validateExecutionRiskPolicy({...base,...change,policyVersion:"execution-risk-policy/1.0.0",revision:1,updatedAt:now.toISOString()}),ExecutionRiskStoreError);});
test("authorization, snapshot, drawdown and margin decisions are fail closed at boundaries",()=>{const decide=(policy={},p={})=>{const s=new SqliteExecutionRiskStore(":memory:");s.replace(0,{...base,...policy},now);return evaluateExecutionRisk(s,intent,{...prereq,...p},preview,now)};assert.equal(decide({enabled:false}).reason,"ACCOUNT_AUTHORIZATION_DISABLED");assert.equal(decide({reviewAt:"2026-01-01T00:00:00Z"}).reason,"ACCOUNT_AUTHORIZATION_EXPIRED");assert.equal(decide({allowedSymbols:["ETH_USDT"]}).reason,"ACCOUNT_SYMBOL_NOT_AUTHORIZED");assert.equal(decide({maximumLeverage:4}).reason,"ACCOUNT_LEVERAGE_LIMIT_EXCEEDED");assert.equal(decide({maximumOrderNotional:999}).reason,"ACCOUNT_ORDER_NOTIONAL_LIMIT_EXCEEDED");assert.equal(decide({}, {riskSnapshot:null}).reason,"RISK_SNAPSHOT_MISSING");assert.equal(decide({}, {riskSnapshot:{...prereq.riskSnapshot,userId:"other"}}).reason,"RISK_SNAPSHOT_IDENTITY_MISMATCH");assert.equal(decide({}, {riskSnapshot:{...prereq.riskSnapshot,equity:NaN}}).reason,"RISK_SNAPSHOT_INVALID");assert.equal(decide({}, {riskSnapshot:{...prereq.riskSnapshot,observedAt:"2026-08-13T12:00:31Z"}}).reason,"RISK_SNAPSHOT_STALE");assert.equal(decide({}, {riskSnapshot:{...prereq.riskSnapshot,equity:9000}}).ok,true);assert.equal(decide({}, {riskSnapshot:{...prereq.riskSnapshot,equity:8999}}).reason,"ACCOUNT_DAILY_DRAWDOWN_LIMIT_EXCEEDED");assert.equal(decide({}, {riskSnapshot:{...prereq.riskSnapshot,availableMargin:400}}).ok,true);assert.equal(decide({}, {riskSnapshot:{...prereq.riskSnapshot,availableMargin:399}}).reason,"ACCOUNT_ORDER_MARGIN_LIMIT_EXCEEDED");});
test("gross exposure values every position and reduce-only orders use reference valuation",()=>{const s=new SqliteExecutionRiskStore(":memory:");s.replace(0,{...base,maximumGrossNotional:4000},now);const positions=[{symbol:"BTC_USDT",side:"short",quantity:.02},{symbol:"ETH_USDT",side:"long",quantity:1}];const refs=new Map([["BTC_USDT",{price:50_000,observedAt:now.toISOString()}],["ETH_USDT",{price:2_000,observedAt:now.toISOString()}]]);assert.equal(evaluateExecutionRisk(s,intent,{...prereq,accountState:{positions},referencePrices:refs},preview,now).ok,true);const reduction={...preview,quantity:.02,referencePrice:50_000,estimatedNotional:2_000};assert.equal(evaluateExecutionRisk(s,{...intent,reduceOnly:true},{...prereq,accountState:{positions},referencePrices:refs},reduction,now).projectedGrossNotional,2000);const expensiveLimit={...reduction,estimatedNotional:3_000};assert.equal(evaluateExecutionRisk(s,{...intent,reduceOnly:true},{...prereq,accountState:{positions},referencePrices:refs},expensiveLimit,now).projectedGrossNotional,2000);const tight=new SqliteExecutionRiskStore(":memory:");tight.replace(0,{...base,maximumGrossNotional:1_500},now);assert.equal(evaluateExecutionRisk(tight,{...intent,reduceOnly:true},{...prereq,accountState:{positions},referencePrices:refs},expensiveLimit,now).reason,"ACCOUNT_GROSS_EXPOSURE_LIMIT_EXCEEDED");refs.delete("ETH_USDT");assert.equal(evaluateExecutionRisk(s,intent,{...prereq,accountState:{positions},referencePrices:refs},preview,now).reason,"POSITION_REFERENCE_PRICE_MISSING");});
test("open store rejects deleted or atomically replaced backing files",()=>{const dir=mkdtempSync(join(tmpdir(),"risk-"));const path=join(dir,"risk.sqlite");try{const s=new SqliteExecutionRiskStore(path);s.read("userA","account1");const replacement=join(dir,"replacement");writeFileSync(replacement,"bad");renameSync(replacement,path);assert.throws(()=>s.read("userA","account1"),e=>e.code==="EXECUTION_RISK_UNAVAILABLE");}finally{rmSync(dir,{recursive:true,force:true});}});
