import test from "node:test";
import assert from "node:assert/strict";
import { journalCreateFields, journalEditableFields, JournalValidationError } from "../app/lib/journal-validation.ts";
import { toJournalListItem } from "../app/lib/journal-model.ts";
import { journalWritesAllowed } from "../app/lib/journal-model.ts";
import { replayReferenceForTrade, tradeSnapshotFromPaper } from "../app/lib/journal-trade-import.ts";
import { createJournalEntry } from "../app/lib/journal-store.ts";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const trade={tradeId:"trade-1",symbol:"BTC_USDT",market:"MEXC Futures",timeframe:"15m",direction:"long",entry:100,exit:98,stop:98,target:104,positionSize:2,riskPct:1,leverage:2,marginMode:null,fees:null,pnl:-4,pnlPct:-.4,rMultiple:-1,openTime:"2026-01-01T00:00:00.000Z",closeTime:"2026-01-01T01:00:00.000Z",closeReason:"SL",strategyVersion:null,replay:{sessionId:"paper-trade-1",symbol:"BTC_USDT",timeframe:"15m",entryTimeMs:1767225600000,available:true},brain:null,signal:{direction:"long",signalTime:"2026-01-01T00:00:00.000Z",label:"DizySignals confirmed-candle long"}};
test("trade reviews validate immutable execution facts and keep only references",()=>{const fields=journalCreateFields({type:"trade-review",trade,notes:" lesson ",tags:["Breakout","Breakout"]});assert.equal(fields.trade.tradeId,"trade-1");assert.deepEqual(fields.tags,["Breakout"]);assert.equal("candles" in fields.trade.replay,false);assert.ok(Object.isFrozen(fields.trade));});
test("general and market entries do not accept trade snapshots",()=>{assert.throws(()=>journalCreateFields({type:"general",trade}),JournalValidationError);const market=journalCreateFields({type:"market-note",marketContext:{symbol:"ETH_USDT",timeframe:"1h"}});assert.deepEqual(market.marketContext,{symbol:"ETH_USDT",timeframe:"1h"});});
test("edits cannot mutate structured trade facts",()=>{const now="2026-01-01T00:00:00.000Z",entry={id:"entry",...journalCreateFields({type:"trade-review",trade}),createdAt:now,editedAt:now};const edited=journalEditableFields({notes:"Reviewed",trade:{entry:999},quality:"good",planDiscipline:"completely"},entry);assert.equal(edited.trade.entry,100);assert.equal(edited.notes,"Reviewed");assert.equal(edited.quality,"good");});
test("list projection excludes detailed immutable trade data",()=>{const now="2026-01-01T00:00:00.000Z",entry={id:"entry",...journalCreateFields({type:"trade-review",trade,notes:"A".repeat(200)}),createdAt:now,editedAt:now};const item=toJournalListItem(entry);assert.equal(item.notesPreview.length,140);assert.equal(item.trade.replayAvailable,true);assert.equal("entry" in item.trade,false);});

const paper={id:"old-trade",direction:"long",signalTime:1_700_000_000,entryTime:1_700_000_900,exitTime:1_700_001_800,entry:100,exit:98,stop:98,pnl:-20,pnlPct:-2,result:"loss",exitReason:"SL",remainingQuantity:0,realisedPnl:-20};
const candle=time=>({time,open:100,high:101,low:99,close:100,volume:1});
const context=(overrides={})=>({symbol:"BTC_USDT",market:"BTC / USDT",timeframe:"15m",replay:{symbol:"BTC_USDT",timeframe:"15m",candles:[candle(paper.entryTime-900),candle(paper.entryTime),candle(paper.entryTime+900)]},...overrides});
test("unrecorded paper facts remain unavailable without inference or historical Brain contamination",()=>{const snapshot=tradeSnapshotFromPaper(paper,context());assert.equal(snapshot.positionSize,null);assert.equal(snapshot.fees,null);assert.equal(snapshot.marginMode,null);assert.equal(snapshot.target,null);assert.equal(snapshot.rMultiple,null);assert.equal(snapshot.strategyVersion,null);assert.equal(snapshot.brain,null);assert.notEqual(snapshot.positionSize,Math.abs(paper.pnl)/Math.abs(paper.entry-paper.stop));assert.equal(snapshot.signal.direction,paper.direction);assert.equal(snapshot.signal.signalTime,new Date(paper.signalTime*1000).toISOString());});
test("authoritative simulator facts are copied when present",()=>{const snapshot=tradeSnapshotFromPaper({...paper,target:104,positionSize:10,riskPct:1,leverage:2,rMultiple:-1},context());assert.equal(snapshot.positionSize,10);assert.equal(snapshot.target,104);assert.equal(snapshot.rMultiple,-1);assert.equal(snapshot.fees,null);});
test("Replay availability requires exact identity and entry timestamp coverage",()=>{assert.equal(replayReferenceForTrade(paper,context()).available,true);assert.equal(replayReferenceForTrade(paper,context({replay:{symbol:"BTC_USDT",timeframe:"15m",candles:[candle(paper.entryTime+900)]}})).available,false);assert.equal(replayReferenceForTrade(paper,context({replay:{symbol:"BTC_USDT",timeframe:"15m",candles:[candle(paper.entryTime-1800)]}})).available,false);assert.equal(replayReferenceForTrade(paper,context({replay:{symbol:"ETH_USDT",timeframe:"15m",candles:[candle(paper.entryTime)]}})).available,false);assert.equal(replayReferenceForTrade(paper,context({replay:{symbol:"BTC_USDT",timeframe:"1h",candles:[candle(paper.entryTime)]}})).available,false);});
test("duplicate completed trades remain protected per user",async()=>{const old=process.env.DATA_DIR,dir=await mkdtemp(join(tmpdir(),"dizyjournal-"));process.env.DATA_DIR=dir;try{await createJournalEntry("duplicate-user",{type:"trade-review",trade});await assert.rejects(()=>createJournalEntry("duplicate-user",{type:"trade-review",trade}),/TRADE_ALREADY_JOURNALED/);}finally{if(old===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=old;await rm(dir,{recursive:true,force:true});}});
test("viewer sessions cannot write",()=>{assert.equal(journalWritesAllowed("viewer"),false);assert.equal(journalWritesAllowed("owner"),true);});
