import test from "node:test";
import assert from "node:assert/strict";
import { journalCreateFields, journalEditableFields, JournalValidationError } from "../app/lib/journal-validation.ts";
import { toJournalListItem } from "../app/lib/journal-model.ts";

const trade={tradeId:"trade-1",symbol:"BTC_USDT",market:"MEXC Futures",timeframe:"15m",direction:"long",entry:100,exit:98,stop:98,target:104,positionSize:2,riskPct:1,leverage:2,marginMode:"simulated",fees:0,pnl:-4,pnlPct:-.4,rMultiple:-1,openTime:"2026-01-01T00:00:00.000Z",closeTime:"2026-01-01T01:00:00.000Z",closeReason:"SL",strategyVersion:"v1",replay:{sessionId:"paper-trade-1",symbol:"BTC_USDT",timeframe:"15m",entryTimeMs:1767225600000,available:true},brain:{id:"brain-1",capturedAt:"2026-01-01T00:00:00.000Z",summary:"BUY · Bullish bias"},signal:{direction:"long",signalTime:"2026-01-01T00:00:00.000Z",label:"Confirmed long signal"}};
test("trade reviews validate immutable execution facts and keep only references",()=>{const fields=journalCreateFields({type:"trade-review",trade,notes:" lesson ",tags:["Breakout","Breakout"]});assert.equal(fields.trade.tradeId,"trade-1");assert.deepEqual(fields.tags,["Breakout"]);assert.equal("candles" in fields.trade.replay,false);assert.ok(Object.isFrozen(fields.trade));});
test("general and market entries do not accept trade snapshots",()=>{assert.throws(()=>journalCreateFields({type:"general",trade}),JournalValidationError);const market=journalCreateFields({type:"market-note",marketContext:{symbol:"ETH_USDT",timeframe:"1h"}});assert.deepEqual(market.marketContext,{symbol:"ETH_USDT",timeframe:"1h"});});
test("edits cannot mutate structured trade facts",()=>{const now="2026-01-01T00:00:00.000Z",entry={id:"entry",...journalCreateFields({type:"trade-review",trade}),createdAt:now,editedAt:now};const edited=journalEditableFields({notes:"Reviewed",trade:{entry:999},quality:"good",planDiscipline:"completely"},entry);assert.equal(edited.trade.entry,100);assert.equal(edited.notes,"Reviewed");assert.equal(edited.quality,"good");});
test("list projection excludes detailed immutable trade data",()=>{const now="2026-01-01T00:00:00.000Z",entry={id:"entry",...journalCreateFields({type:"trade-review",trade,notes:"A".repeat(200)}),createdAt:now,editedAt:now};const item=toJournalListItem(entry);assert.equal(item.notesPreview.length,140);assert.equal(item.trade.replayAvailable,true);assert.equal("entry" in item.trade,false);});
