import test from "node:test";
import assert from "node:assert/strict";
import { aggregateJournalStatistics, journalSampleLevel, presentJournalTags } from "../app/lib/journal-statistics.ts";

const baseTrade={tradeId:"t",symbol:"BTC_USDT",market:"MEXC Futures",timeframe:"15m",direction:"long",entry:100,exit:101,stop:null,target:null,positionSize:null,riskPct:null,leverage:null,marginMode:null,fees:null,pnl:1,pnlPct:1,rMultiple:null,openTime:"2026-01-01T00:00:00.000Z",closeTime:"2026-01-01T01:00:00.000Z",closeReason:"manual",strategyVersion:null,replay:null,brain:null,signal:null};
const entry=(id,overrides={})=>({id,schemaVersion:2,type:"trade-review",createdAt:"2026-01-01T00:00:00.000Z",editedAt:"2026-01-01T00:00:00.000Z",title:"",archived:false,archivedAt:null,notes:"",tags:[],dismissedPrompts:[],quality:null,planDiscipline:null,mood:null,trade:{...baseTrade,tradeId:id},marketContext:null,...overrides});

test("zero trades serializes an unavailable descriptive boundary",()=>{const stats=aggregateJournalStatistics([]);assert.equal(stats.reviewedTrades,0);assert.equal(stats.winRatePct,null);assert.equal(stats.averagePnl,null);assert.equal(stats.averageR,null);assert.equal(stats.warnings[0].code,"NO_DATA");assert.doesNotThrow(()=>JSON.stringify(stats));});
test("core outcomes, means, coverage and authoritative R samples are honest",()=>{const stats=aggregateJournalStatistics([entry("w",{quality:"poor",planDiscipline:"mostly",mood:"calm",notes:"note",tags:["Setup"],trade:{...baseTrade,tradeId:"w",pnl:10,pnlPct:5,rMultiple:2}}),entry("l",{quality:"good",trade:{...baseTrade,tradeId:"l",pnl:-4,pnlPct:-2,rMultiple:null}}),entry("f",{trade:{...baseTrade,tradeId:"f",pnl:0,pnlPct:0,rMultiple:-0}})]);assert.deepEqual([stats.wins,stats.losses,stats.flat],[1,1,1]);assert.ok(Math.abs(stats.winRatePct-100/3)<1e-12);assert.equal(stats.netPnl,6);assert.equal(stats.averagePnl,2);assert.equal(stats.averagePnlPct,1);assert.equal(stats.averageR,1);assert.equal(stats.rSampleSize,2);assert.equal(stats.goodLosingTrades,1);assert.equal(stats.poorWinningTrades,1);assert.ok(Math.abs(stats.qualityCoverage-200/3)<1e-12);assert.ok(Math.abs(stats.disciplineCoverage-100/3)<1e-12);assert.ok(Math.abs(stats.moodCoverage-100/3)<1e-12);assert.ok(Math.abs(stats.taggedTradeCoverage-100/3)<1e-12);assert.ok(Math.abs(stats.notesCoverage-100/3)<1e-12);});
test("quality and discipline always include explicit unassessed buckets",()=>{const stats=aggregateJournalStatistics([entry("a",{quality:"good",planDiscipline:"completely"}),entry("b",{quality:"mixed",planDiscipline:"mostly"}),entry("c",{quality:"poor",planDiscipline:"no"}),entry("d")]);assert.deepEqual(stats.byQuality.map(x=>[x.key,x.sampleSize]),[["good",1],["mixed",1],["poor",1],["unassessed",1]]);assert.deepEqual(stats.byPlanDiscipline.map(x=>[x.key,x.sampleSize]),[["completely",1],["mostly",1],["no",1],["unassessed",1]]);});
test("every supported mood and missing mood has a bucket and sample warning",()=>{const moods=["calm","confident","patient","hesitant","fearful","greedy","fomo","frustrated","revenge"];const stats=aggregateJournalStatistics([...moods.map((m,i)=>entry(String(i),{mood:m})),entry("none")]);assert.deepEqual(stats.byMood.map(x=>x.key),[...moods,"unrecorded"]);assert.ok(stats.byMood.every(x=>x.sampleLevel==="very-small"));assert.equal(stats.warnings[0].code,"LIMITED_SAMPLE");});
test("tags aggregate case-insensitively without double counting overall trades",()=>{const stats=aggregateJournalStatistics([entry("a",{tags:["Breakout","calm"]}),entry("b",{tags:["breakout","BREAKOUT"]})]);assert.equal(stats.reviewedTrades,2);assert.equal(stats.byTag.find(x=>x.key==="breakout").sampleSize,2);assert.equal(stats.byTag.find(x=>x.key==="breakout").label,"Breakout");assert.equal(stats.byTag.reduce((n,x)=>n+x.sampleSize,0),3);assert.equal(stats.taggedTradeCoverage,100);assert.equal(stats.warnings.at(-1).code,"OVERLAPPING_TAGS");});
test("tag presentation supports all sorts, search and a bounded limit",()=>{const tags=aggregateJournalStatistics([entry("a",{tags:["Zulu","Alpha"],trade:{...baseTrade,tradeId:"a",pnl:-1}}),entry("b",{tags:["Zulu","Beta"],trade:{...baseTrade,tradeId:"b",pnl:4}})]).byTag;assert.equal(presentJournalTags(tags)[0].label,"Zulu");assert.equal(presentJournalTags(tags,"alphabetical")[0].label,"Alpha");assert.equal(presentJournalTags(tags,"net-pnl")[0].label,"Beta");assert.deepEqual(presentJournalTags(tags,"sample-size","alp",1).map(x=>x.label),["Alpha"]);assert.equal(presentJournalTags(tags,"sample-size","",1).length,1);});
test("scope excludes archived, non-trades, missing snapshots and malformed PnL",()=>{const archived=entry("archived",{archived:true}),market=entry("market",{type:"market-note"}),general=entry("general",{type:"general",trade:null}),missing=entry("missing",{trade:null}),bad=entry("bad",{trade:{...baseTrade,pnl:Number.NaN}});assert.equal(aggregateJournalStatistics([archived,market,general,missing,bad]).reviewedTrades,0);assert.equal(aggregateJournalStatistics([archived],{includeArchived:true}).reviewedTrades,1);});
test("monthly close-time grouping is UTC, ordered, and omits empty periods",()=>{const stats=aggregateJournalStatistics([entry("feb",{trade:{...baseTrade,closeTime:"2026-02-01T00:00:00-05:00"}}),entry("jan",{trade:{...baseTrade,closeTime:"2026-01-31T23:30:00Z"}})]);assert.deepEqual(stats.overTime.map(x=>x.key),["2026-01","2026-02"]);assert.equal(stats.overTime[0].reviewedTrades,1);});
test("sample thresholds are stable",()=>{assert.deepEqual([journalSampleLevel(0),journalSampleLevel(1),journalSampleLevel(4),journalSampleLevel(5),journalSampleLevel(19),journalSampleLevel(20)],["unavailable","very-small","very-small","limited","limited","larger"]);});
test("statistics API is authenticated, user-scoped, read-only and validates archived",async()=>{const {readFile}=await import("node:fs/promises");const source=await readFile(new URL("../app/api/journal/statistics/route.ts",import.meta.url),"utf8");assert.match(source,/requireApiUser\(\)/);assert.match(source,/readJournal\(user\.id\)/);assert.match(source,/user\.role===\"viewer\"/);assert.match(source,/value!==\"true\"&&value!==\"false\"/);assert.doesNotMatch(source,/export async function (POST|PATCH|DELETE)/);assert.doesNotMatch(source,/replay|dizybrain/i);});
