import test from "node:test";
import assert from "node:assert/strict";
import {simulatePaperMarketDepthFill} from "../app/lib/manual-paper-depth.ts";

const contract={symbol:"BTC_USDT",displayName:"BTCUSDT SWAP",contractSize:.001,minLeverage:1,maxLeverage:125,priceUnit:.1,volUnit:1,minVol:1,maxVol:1_000_000,makerFeeRate:.0002,takerFeeRate:.0006,maintenanceMarginRate:.004,initialMarginRate:.008,positionOpenType:3,riskLimitType:"BY_VOLUME"};
const depth=(bids,asks,receivedAt=Date.now())=>({snapshot:{symbol:"BTC_USDT",version:42,engineTimeMs:receivedAt,bids,asks},receivedAt,diagnostic:{snapshotAgeMs:0,consecutiveFailures:0,lastError:null,sourceMode:"REST FALLBACK",snapshotComplete:true}});

test("visible ask walking produces a deterministic weighted market entry",()=>{const result=simulatePaperMarketDepthFill({side:"long",requestedContractVolume:5_000,referencePrice:100,contract,depth:depth([{price:99.9,orderCount:1,contractQuantity:10_000}],[{price:100.1,orderCount:2,contractQuantity:2_000},{price:100.2,orderCount:3,contractQuantity:4_000}]),observedAt:Date.now()});assert.equal(result.fillStatus,"full");assert.equal(result.filledContractVolume,5_000);assert.equal(result.unfilledContractVolume,0);assert.equal(result.levelsConsumed,2);assert.equal(result.executionPrice,100.2);assert.equal(result.quantity,5);assert.equal(result.notional,501);assert.equal(result.source,"dizyflow-public-depth");assert.equal(result.calculationMethod,"visible-book-walk");assert.ok(result.priceImpactBps>0)});

test("visible bid walking records partial fills instead of inventing liquidity",()=>{const result=simulatePaperMarketDepthFill({side:"short",requestedContractVolume:5_000,referencePrice:100,contract,depth:depth([{price:99.9,orderCount:2,contractQuantity:1_200},{price:99.8,orderCount:3,contractQuantity:800}],[{price:100.1,orderCount:1,contractQuantity:10_000}]),observedAt:Date.now()});assert.equal(result.fillStatus,"partial");assert.equal(result.filledContractVolume,2_000);assert.equal(result.unfilledContractVolume,3_000);assert.equal(result.executionPrice,99.8);assert.equal(result.bookSide,"bid");assert.equal(result.levelsConsumed,2)});

test("depth entries reject stale, incomplete and sub-minimum visible books",()=>{const good=depth([{price:99.9,orderCount:1,contractQuantity:10}],[{price:100.1,orderCount:1,contractQuantity:10}],1_000);assert.throws(()=>simulatePaperMarketDepthFill({side:"long",requestedContractVolume:5,referencePrice:100,contract,depth:good,observedAt:20_000,maxAgeMs:1_000}),/DEPTH_STALE/);assert.throws(()=>simulatePaperMarketDepthFill({side:"long",requestedContractVolume:5,referencePrice:100,contract,depth:{...good,snapshot:{...good.snapshot,asks:[]}},observedAt:1_001}),/DEPTH_INCOMPLETE/);assert.throws(()=>simulatePaperMarketDepthFill({side:"long",requestedContractVolume:5,referencePrice:100,contract:{...contract,minVol:5},depth:depth([{price:99.9,orderCount:1,contractQuantity:10}],[{price:100.1,orderCount:1,contractQuantity:4}]),observedAt:Date.now()}),/DEPTH_LIQUIDITY_BELOW_MINIMUM/)});

test("Manual Paper uses actual visible fills for position size, fees, margin and backup",async()=>{const {mkdtemp,rm}=await import("node:fs/promises"),{tmpdir}=await import("node:os"),{join}=await import("node:path"),{submitManualOrder,updateManualSettings}=await import("../app/lib/manual-paper.ts"),{validateManualPaperBackup}=await import("../app/lib/manual-paper-backup.ts"),prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),"dizy-paper-depth-"));process.env.DATA_DIR=root;try{await updateManualSettings("depth-owner",{slippagePct:9});const book=depth([{price:99.9,orderCount:1,contractQuantity:10_000}],[{price:100.1,orderCount:2,contractQuantity:2_000},{price:100.2,orderCount:3,contractQuantity:4_000}]);const account=await submitManualOrder("depth-owner",{idempotencyKey:"depth-entry-full-001",symbol:"BTC_USDT",side:"long",sizeMode:"fixed-notional",amount:500,leverage:10},100,"fair",contract,undefined,book),position=account.positions.BTC_USDT,fill=account.fills.at(-1);assert.equal(position.entryPrice,100.2);assert.equal(position.contractVolume,5_000);assert.equal(position.entryDepthFill.fillStatus,"full");assert.equal(fill.entryDepthFill.snapshotVersion,42);assert.equal(position.margin,50.1);assert.ok(Math.abs(fill.fee-fill.notional*contract.takerFeeRate)<1e-12);assert.notEqual(position.entryPrice,109);const restored=validateManualPaperBackup(account,"depth-owner");assert.equal(restored.positions.BTC_USDT.entryDepthFill.source,"dizyflow-public-depth");assert.equal(restored.fills.at(-1).entryDepthFill.levelsConsumed,2)}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}});

test("Manual Paper opens only the visible partial entry volume",async()=>{const {mkdtemp,rm}=await import("node:fs/promises"),{tmpdir}=await import("node:os"),{join}=await import("node:path"),{submitManualOrder}=await import("../app/lib/manual-paper.ts"),prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),"dizy-paper-depth-partial-"));process.env.DATA_DIR=root;try{const book=depth([{price:99.9,orderCount:1,contractQuantity:10_000}],[{price:100.1,orderCount:2,contractQuantity:1_000},{price:100.2,orderCount:3,contractQuantity:1_000}]);const account=await submitManualOrder("depth-partial",{idempotencyKey:"depth-entry-partial1",symbol:"BTC_USDT",side:"long",sizeMode:"fixed-notional",amount:500,leverage:10},100,"fair",contract,undefined,book),position=account.positions.BTC_USDT;assert.equal(position.entryDepthFill.fillStatus,"partial");assert.equal(position.entryDepthFill.requestedContractVolume,5_000);assert.equal(position.contractVolume,2_000);assert.equal(position.quantity,2);assert.equal(position.entryDepthFill.unfilledContractVolume,3_000);assert.ok(position.margin<25)}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}});

test("backup restore rejects contradictory visible-depth evidence",async()=>{const {mkdtemp,rm}=await import("node:fs/promises"),{tmpdir}=await import("node:os"),{join}=await import("node:path"),{submitManualOrder}=await import("../app/lib/manual-paper.ts"),{validateManualPaperBackup}=await import("../app/lib/manual-paper-backup.ts"),prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),"dizy-paper-depth-tamper-"));process.env.DATA_DIR=root;try{const book=depth([{price:99.9,orderCount:1,contractQuantity:10_000}],[{price:100.1,orderCount:2,contractQuantity:2_000},{price:100.2,orderCount:3,contractQuantity:4_000}]),account=await submitManualOrder("depth-tamper",{idempotencyKey:"depth-tamper-open01",symbol:"BTC_USDT",side:"long",sizeMode:"fixed-notional",amount:500,leverage:10},100,"fair",contract,undefined,book),volumeMismatch=structuredClone(account),statusMismatch=structuredClone(account),notionalMismatch=structuredClone(account);volumeMismatch.positions.BTC_USDT.entryDepthFill.unfilledContractVolume=1;statusMismatch.fills.at(-1).entryDepthFill.fillStatus="partial";notionalMismatch.fills.at(-1).entryDepthFill.notional+=10;assert.throws(()=>validateManualPaperBackup(volumeMismatch,"depth-tamper"),/volume totals do not reconcile/);assert.throws(()=>validateManualPaperBackup(statusMismatch,"depth-tamper"),/fill status contradicts/);assert.throws(()=>validateManualPaperBackup(notionalMismatch,"depth-tamper"),/notional does not reconcile/)}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}});
