import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
const rules={symbol:"BTC_USDT",displayName:"BTC_USDT",contractSize:1,minLeverage:1,maxLeverage:125,priceUnit:.1,volUnit:1,minVol:1,maxVol:1000,makerFeeRate:.0002,takerFeeRate:.0006,maintenanceMarginRate:.004,initialMarginRate:.008,positionOpenType:3,riskLimitType:"BY_VOLUME"};
const levels=pairs=>pairs.map(([price,contractQuantity])=>({price,orderCount:1,contractQuantity}));
const book=(bids,asks,receivedAt=Date.now())=>({snapshot:{symbol:"BTC_USDT",version:143,engineTimeMs:receivedAt,bids:levels(bids),asks:levels(asks)},receivedAt,diagnostic:{snapshotAgeMs:0,consecutiveFailures:0,lastError:null,sourceMode:"REST FALLBACK",snapshotComplete:true}});
async function isolated(name,fn){const prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),name));process.env.DATA_DIR=root;try{return await fn()}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}}
async function open(user,exits={}){const {submitManualOrder}=await import("../app/lib/manual-paper.ts");return submitManualOrder(user,{idempotencyKey:user+"-open-order-0001",symbol:"BTC_USDT",side:"long",sizeMode:"fixed-notional",amount:500,leverage:20,...exits},100,"fair",rules,undefined,book([[99,20]],[[100,20]]))}
test("partial stop exit persists after price rebound until residual depth executes",()=>isolated("dizy-auto-stop-",async()=>{const {markManualPosition}=await import("../app/lib/manual-paper.ts");let account=await open("auto-stop",{stopLoss:99});account=await markManualPosition("auto-stop","BTC_USDT",98,"fair",undefined,[],book([[97.9,3]],[[98.1,20]]),rules,true);assert.equal(account.positions.BTC_USDT.contractVolume,2);assert.equal(account.positions.BTC_USDT.pendingRiskExit.reason,"stop");assert.equal(account.positions.BTC_USDT.pendingRiskExit.triggerPrice,98);let fill=account.fills.at(-1);assert.equal(fill.exitDepthFill.fillStatus,"partial");assert.equal(fill.riskExitTrigger.reason,"stop");assert.equal(fill.closeReason,undefined);account=await markManualPosition("auto-stop","BTC_USDT",101,"fair",undefined,[],book([[100.9,20]],[[101.1,20]]),rules,true);assert.equal(account.positions.BTC_USDT,undefined);fill=account.fills.at(-1);assert.equal(fill.closeReason,"stop");assert.equal(fill.riskExitTrigger.triggerPrice,98)}));
test("triggered stop persists without depth instead of using fallback slippage",()=>isolated("dizy-auto-pending-",async()=>{const {markManualPosition}=await import("../app/lib/manual-paper.ts"),{validateManualPaperBackup}=await import("../app/lib/manual-paper-backup.ts");let account=await open("auto-pending",{stopLoss:99}),before=account.fills.length;account=await markManualPosition("auto-pending","BTC_USDT",98,"last",undefined,[],null,null,true);assert.equal(account.fills.length,before);assert.equal(account.positions.BTC_USDT.pendingRiskExit.reason,"stop");assert.equal(account.positions.BTC_USDT.pendingRiskExit.priceSource,"last");const restored=validateManualPaperBackup(account,"auto-pending");assert.equal(restored.positions.BTC_USDT.pendingRiskExit.triggerPrice,98);const tampered=structuredClone(account);tampered.positions.BTC_USDT.pendingRiskExit.reason="manual";assert.throws(()=>validateManualPaperBackup(tampered,"auto-pending"),/reason/)}));
test("take-profit trigger closes through visible depth with immutable trigger evidence",()=>isolated("dizy-auto-target-",async()=>{const {markManualPosition}=await import("../app/lib/manual-paper.ts");let account=await open("auto-target",{takeProfit:105});account=await markManualPosition("auto-target","BTC_USDT",106,"fair",undefined,[],book([[105.9,20]],[[106.1,20]]),rules,true);assert.equal(account.positions.BTC_USDT,undefined);const fill=account.fills.at(-1);assert.equal(fill.closeReason,"target");assert.equal(fill.riskExitTrigger.reason,"target");assert.equal(fill.exitDepthFill.executionContext,"exit")}));
test("liquidation penalties apply only to filled depth and pending liquidation cannot recover away",()=>isolated("dizy-auto-liquidation-",async()=>{const {markManualPosition}=await import("../app/lib/manual-paper.ts");let account=await open("auto-liquidation"),trigger=Math.max(.1,account.positions.BTC_USDT.estimatedLiquidation-1);account=await markManualPosition("auto-liquidation","BTC_USDT",trigger,"fair",undefined,[],book([[trigger-.1,2]],[[trigger+.1,20]]),rules,true);assert.equal(account.positions.BTC_USDT.contractVolume,3);assert.equal(account.positions.BTC_USDT.pendingRiskExit.reason,"liquidation");let fill=account.fills.at(-1);assert.ok(fill.liquidationPenalty>0);assert.equal(fill.closeReason,undefined);account=await markManualPosition("auto-liquidation","BTC_USDT",100,"fair",undefined,[],book([[99.9,20]],[[100.1,20]]),rules,true);assert.equal(account.positions.BTC_USDT,undefined);fill=account.fills.at(-1);assert.equal(fill.closeReason,"liquidation");assert.equal(fill.riskExitTrigger.triggerPrice,trigger);assert.ok(fill.liquidationPenalty>0)}));
