import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {parseMexcContractMetadata} from "../app/lib/mexc-contract-metadata.ts";

const contract=symbol=>parseMexcContractMetadata({success:true,data:[{symbol,displayNameEn:symbol+" SWAP",positionOpenType:3,contractSize:1,minLeverage:1,maxLeverage:50,priceUnit:.1,volUnit:1,minVol:1,maxVol:1000,makerFeeRate:.0002,takerFeeRate:.0006,maintenanceMarginRate:.01,initialMarginRate:.02,riskLimitType:"BY_VOLUME"}]},symbol);
const levels=(price,volume)=>[{price,orderCount:1,contractQuantity:volume}];
const book=(symbol,price=100,volume=1000)=>({snapshot:{symbol,version:1,engineTimeMs:Date.now(),bids:levels(price,volume),asks:levels(price,volume)},receivedAt:Date.now(),diagnostic:{snapshotAgeMs:0,consecutiveFailures:0,lastError:null,sourceMode:"REST FALLBACK",snapshotComplete:true}});
async function isolated(name,fn){const prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),name));process.env.DATA_DIR=root;try{return await fn()}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}}
const open=(submit,user,symbol,marginMode,notional)=>submit(user,{idempotencyKey:"open-"+symbol.toLowerCase().replaceAll("_","")+"-000001",symbol,side:"long",sizeMode:"fixed-notional",amount:notional,leverage:50,marginMode},100,"fair",contract(symbol),undefined,book(symbol));

test("cross marks re-audit every shared-pool liquidation while isolated liquidation stays fenced",()=>isolated("dizy-margin-life-",async()=>{const {submitManualOrder,markManualPosition}=await import("../app/lib/manual-paper.ts"),user="margin-life-user";let account=await open(submitManualOrder,user,"BTC_USDT","cross",40000);account=await open(submitManualOrder,user,"ETH_USDT","cross",40000);const base=account.positions.BTC_USDT.estimatedLiquidation;account=await markManualPosition(user,"ETH_USDT",110,"fair");const rescued=account.positions.BTC_USDT.estimatedLiquidation;account=await markManualPosition(user,"ETH_USDT",90,"fair");const pressured=account.positions.BTC_USDT.estimatedLiquidation;assert.ok(rescued<base,"expected "+rescued+" < "+base);assert.ok(pressured>base,"expected "+pressured+" > "+base);assert.equal(account.positions.BTC_USDT.marginAudit.calculationMethod,"cross-shared-usdt-pool-v1");assert.equal(account.positions.BTC_USDT.marginAudit.supportingCrossPositionCount,2)}));

test("isolated liquidation does not move when a cross position gains or loses",()=>isolated("dizy-margin-iso-",async()=>{const {submitManualOrder,markManualPosition}=await import("../app/lib/manual-paper.ts"),user="margin-isolated-user";let account=await open(submitManualOrder,user,"BTC_USDT","isolated",1000);account=await open(submitManualOrder,user,"ETH_USDT","cross",40000);const base=account.positions.BTC_USDT.estimatedLiquidation;account=await markManualPosition(user,"ETH_USDT",110,"fair");assert.ok(Math.abs(account.positions.BTC_USDT.estimatedLiquidation-base)<1e-10);account=await markManualPosition(user,"ETH_USDT",90,"fair");assert.ok(Math.abs(account.positions.BTC_USDT.estimatedLiquidation-base)<1e-10);assert.equal(account.positions.BTC_USDT.marginAudit.collateralAvailableToPosition,account.positions.BTC_USDT.margin)}));

test("isolated close losses are capped to assigned margin and survive backup validation",()=>isolated("dizy-margin-cap-",async()=>{const {submitManualOrder,closeManualPosition}=await import("../app/lib/manual-paper.ts"),{validateManualPaperBackup}=await import("../app/lib/manual-paper-backup.ts"),user="margin-cap-user";let account=await open(submitManualOrder,user,"BTC_USDT","isolated",1000),before=account.cashBalance,margin=account.positions.BTC_USDT.margin;account=await closeManualPosition(user,"BTC_USDT","close-btcusdt-000001",1);const fill=account.fills.at(-1);assert.equal(fill.marginSettlement.capped,true);assert.ok(Math.abs((before-account.cashBalance)-margin)<1e-8);assert.equal(fill.marginSettlement.calculationMethod,"isolated-position-loss-cap-v1");assert.doesNotThrow(()=>validateManualPaperBackup(account,user));const copy=structuredClone(account);copy.fills.at(-1).marginSettlement.cashAfter+=1;assert.throws(()=>validateManualPaperBackup(copy,user),/settlement|reconcile/i)}));

test("backup validation rejects contradictory cross-pool evidence",()=>isolated("dizy-margin-backup-",async()=>{const {submitManualOrder}=await import("../app/lib/manual-paper.ts"),{validateManualPaperBackup}=await import("../app/lib/manual-paper-backup.ts"),user="margin-backup-user";const account=await open(submitManualOrder,user,"BTC_USDT","cross",40000);assert.doesNotThrow(()=>validateManualPaperBackup(account,user));const accountCopy=structuredClone(account);accountCopy.marginSnapshot.crossEquity+=1;assert.throws(()=>validateManualPaperBackup(accountCopy,user),/cross equity/i);const positionCopy=structuredClone(account);positionCopy.positions.BTC_USDT.marginAudit.collateralAvailableToPosition+=1;assert.throws(()=>validateManualPaperBackup(positionCopy,user),/cross collateral/i)}));
