import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,readFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createManualReduceOnlyPlan,finaliseManualReduceOnly} from "../app/lib/manual-paper-reduce-only.ts";

const rules={symbol:"BTC_USDT",displayName:"BTC_USDT",contractSize:1,minLeverage:1,maxLeverage:125,priceUnit:.1,volUnit:1,minVol:1,maxVol:1000,makerFeeRate:.0002,takerFeeRate:.0006,maintenanceMarginRate:.004,initialMarginRate:.008,positionOpenType:3,riskLimitType:"BY_VOLUME"};
const levels=pairs=>pairs.map(([price,contractQuantity])=>({price,orderCount:1,contractQuantity}));
const book=(bids=[[99.9,50]],asks=[[100.1,50]],receivedAt=Date.now())=>({snapshot:{symbol:"BTC_USDT",version:177,engineTimeMs:receivedAt,bids:levels(bids),asks:levels(asks)},receivedAt,diagnostic:{snapshotAgeMs:0,consecutiveFailures:0,lastError:null,sourceMode:"REST FALLBACK",snapshotComplete:true}});
async function isolated(name,fn){const prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),name));process.env.DATA_DIR=root;try{return await fn()}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}}
async function open(user,options={}){const {submitManualOrder}=await import("../app/lib/manual-paper.ts");return submitManualOrder(user,{idempotencyKey:user+"-open-order-0001",symbol:"BTC_USDT",side:"long",sizeMode:"fixed-notional",amount:500,leverage:20,...options},100,"fair",rules,undefined,book())}
const target=position=>({expectedTradeId:position.tradeId,expectedSide:position.side});

test("reduce-only plans cap quantity and reconcile immutable evidence",()=>{const plan=createManualReduceOnlyPlan({source:"partial-close",target:{expectedTradeId:"trade-1",expectedSide:"long"},positionTradeId:"trade-1",positionSide:"long",positionQuantity:5,requestedQuantity:9,acceptedQuantity:5});assert.equal(plan.capped,true);assert.equal(plan.acceptedQuantity,5);const evidence=finaliseManualReduceOnly(plan,3);assert.equal(evidence.result,"reduced");assert.equal(evidence.remainingQuantity,2);assert.throws(()=>createManualReduceOnlyPlan({source:"manual-close",target:{expectedTradeId:"stale",expectedSide:"long"},positionTradeId:"trade-1",positionSide:"long",positionQuantity:5,requestedQuantity:5}),/STALE_REDUCE_ONLY_TARGET/);assert.throws(()=>createManualReduceOnlyPlan({source:"manual-close",target:{expectedTradeId:"trade-1",expectedSide:"short"},positionTradeId:"trade-1",positionSide:"long",positionQuantity:5,requestedQuantity:5}),/REDUCE_ONLY_SIDE_MISMATCH/)});

test("stale client close cannot mutate a replacement or current position",()=>isolated("dizy-reduce-stale-",async()=>{const {closeManualPosition}=await import("../app/lib/manual-paper.ts");const account=await open("reduce-stale"),before=account.fills.length,position=account.positions.BTC_USDT;await assert.rejects(()=>closeManualPosition("reduce-stale","BTC_USDT","reduce-stale-close-0001",100,book(),rules,{expectedTradeId:"old-trade",expectedSide:position.side}),error=>error?.code==="STALE_REDUCE_ONLY_TARGET");const current=(await import("../app/lib/manual-paper.ts")).readManualAccount;const unchanged=await current("reduce-stale");assert.equal(unchanged.positions.BTC_USDT.tradeId,position.tradeId);assert.equal(unchanged.positions.BTC_USDT.quantity,position.quantity);assert.equal(unchanged.fills.length,before)}));

test("oversized explicit partial close is capped to the remaining position",()=>isolated("dizy-reduce-cap-",async()=>{const {partialCloseManualPosition}=await import("../app/lib/manual-paper.ts"),{validateManualPaperBackup}=await import("../app/lib/manual-paper-backup.ts");let account=await open("reduce-cap"),position=account.positions.BTC_USDT;account=await partialCloseManualPosition("reduce-cap","BTC_USDT","reduce-cap-close-0001",100,{quantity:999},book(),rules,target(position));assert.equal(account.positions.BTC_USDT,undefined);const fill=account.fills.at(-1);assert.equal(fill.reduceOnly.source,"partial-close");assert.equal(fill.reduceOnly.requestedQuantity,999);assert.equal(fill.reduceOnly.acceptedQuantity,5);assert.equal(fill.reduceOnly.filledQuantity,5);assert.equal(fill.reduceOnly.remainingQuantity,0);assert.equal(fill.reduceOnly.capped,true);assert.equal(fill.reduceOnly.result,"closed");assert.equal(validateManualPaperBackup(account,"reduce-cap").fills.at(-1).reduceOnly.expectedTradeId,position.tradeId);for(const mutate of [copy=>copy.fills.at(-1).reduceOnly.expectedTradeId="other",copy=>copy.fills.at(-1).reduceOnly.remainingQuantity=2,copy=>copy.fills.at(-1).reduceOnly.capped=false]){const copy=structuredClone(account);mutate(copy);assert.throws(()=>validateManualPaperBackup(copy,"reduce-cap"),/reduceOnly|reduce-only|targets a different trade|reconcile|capped state/)}}));

test("reverse closes reduce-only and stale old trade requests cannot touch the new side",()=>isolated("dizy-reduce-reverse-",async()=>{const {reverseManualPosition,closeManualPosition}=await import("../app/lib/manual-paper.ts");let account=await open("reduce-reverse"),old=account.positions.BTC_USDT;account=await reverseManualPosition("reduce-reverse","BTC_USDT","reduce-reverse-order-0001",100,book([[99.9,50]],[[100.1,50]]),rules,target(old));const closeFill=account.fills.findLast(fill=>fill.side==="close");assert.equal(closeFill.reduceOnly.source,"reverse");assert.equal(closeFill.reduceOnly.expectedTradeId,old.tradeId);const replacement=account.positions.BTC_USDT;assert.equal(replacement.side,"short");assert.notEqual(replacement.tradeId,old.tradeId);await assert.rejects(()=>closeManualPosition("reduce-reverse","BTC_USDT","reduce-reverse-stale-0001",100,book(),rules,target(old)),error=>error?.code==="STALE_REDUCE_ONLY_TARGET");const unchanged=await (await import("../app/lib/manual-paper.ts")).readManualAccount("reduce-reverse");assert.equal(unchanged.positions.BTC_USDT.tradeId,replacement.tradeId);assert.equal(unchanged.positions.BTC_USDT.side,"short")}));

test("opposite ticket replacement and automatic risk exits preserve reduce-only provenance",()=>isolated("dizy-reduce-sources-",async()=>{const {submitManualOrder,markManualPosition}=await import("../app/lib/manual-paper.ts");let account=await open("reduce-sources"),old=account.positions.BTC_USDT;account=await submitManualOrder("reduce-sources",{idempotencyKey:"reduce-sources-sell-0001",symbol:"BTC_USDT",side:"short",sizeMode:"fixed-notional",amount:200,leverage:20,confirmReverse:true,expectedTradeId:old.tradeId,expectedSide:old.side},100,"fair",rules,undefined,book([[99.9,50]],[[100.1,50]]));const replacementClose=account.fills.findLast(fill=>fill.side==="close");assert.equal(replacementClose.reduceOnly.source,"opposite-order-replacement");assert.equal(account.positions.BTC_USDT.side,"short");await rm(process.env.DATA_DIR,{recursive:true,force:true});account=await open("reduce-risk",{stopLoss:99});account=await markManualPosition("reduce-risk","BTC_USDT",98,"fair",undefined,[],book([[97.9,50]],[[98.1,50]]),rules,true);const riskFill=account.fills.at(-1);assert.equal(riskFill.reduceOnly.source,"risk-exit");assert.equal(riskFill.reduceOnly.result,"closed");assert.equal(riskFill.riskExitTrigger.reason,"stop")}));

test("HTTP and ticket boundaries bind client exits to trade identity",async()=>{const [route,ticket,core,roadmap]=await Promise.all([readFile("app/api/manual-paper/route.ts","utf8"),readFile("app/manual-paper-ticket.tsx","utf8"),readFile("app/lib/manual-paper.ts","utf8"),readFile("ROADMAP.md","utf8")]);assert.match(route,/reduceOnlyTarget\(body\)/);assert.match(route,/expectedTradeId:body\.expectedTradeId/);assert.match(ticket,/expectedTradeId: position\?\.tradeId/);assert.match(ticket,/actionPosition\?\.tradeId/);assert.match(ticket,/reduce-only \$\{fill\.reduceOnly\.source\}/);assert.match(core,/opposite-order-replacement/);assert.match(core,/STALE_REDUCE_ONLY_TARGET/);assert.match(roadmap,/- \[x\] reduce-only semantics/)});
