import test from "node:test";
import assert from "node:assert/strict";
import {simulatePaperMarketDepthFill} from "../app/lib/manual-paper-depth.ts";

const contract={symbol:"BTC_USDT",displayName:"BTCUSDT SWAP",contractSize:.001,minLeverage:1,maxLeverage:125,priceUnit:.1,volUnit:1,minVol:1,maxVol:1_000_000,makerFeeRate:.0002,takerFeeRate:.0006,maintenanceMarginRate:.004,initialMarginRate:.008,positionOpenType:3,riskLimitType:"BY_VOLUME"};
const depth=(bids,asks,receivedAt=Date.now())=>({snapshot:{symbol:"BTC_USDT",version:77,engineTimeMs:receivedAt,bids,asks},receivedAt,diagnostic:{snapshotAgeMs:0,consecutiveFailures:0,lastError:null,sourceMode:"REST FALLBACK",snapshotComplete:true}});
const entryBook=depth([{price:99.9,orderCount:1,contractQuantity:20_000}],[{price:100.1,orderCount:1,contractQuantity:20_000}]);

test("closing longs walks bids and closing shorts walks asks",()=>{const longExit=simulatePaperMarketDepthFill({side:"long",opening:false,requestedContractVolume:2_000,openContractVolume:2_000,referencePrice:100,contract,depth:depth([{price:99.9,orderCount:1,contractQuantity:2_000}],[{price:100.1,orderCount:1,contractQuantity:2_000}])}),shortExit=simulatePaperMarketDepthFill({side:"short",opening:false,requestedContractVolume:2_000,openContractVolume:2_000,referencePrice:100,contract,depth:depth([{price:99.9,orderCount:1,contractQuantity:2_000}],[{price:100.1,orderCount:1,contractQuantity:2_000}])});assert.equal(longExit.executionContext,"exit");assert.equal(longExit.bookSide,"bid");assert.equal(longExit.executionPrice,99.9);assert.equal(shortExit.bookSide,"ask");assert.equal(shortExit.executionPrice,100.1);assert.equal(longExit.remainingPositionContractVolume,0);assert.equal(longExit.openPositionContractVolume,2_000)});

test("a thin full-close request protects a valid minimum remainder",()=>{const rules={...contract,minVol:5};const result=simulatePaperMarketDepthFill({side:"long",opening:false,requestedContractVolume:12,openContractVolume:12,minimumRemainingContractVolume:5,referencePrice:100,contract:rules,depth:depth([{price:99.9,orderCount:1,contractQuantity:9}],[{price:100.1,orderCount:1,contractQuantity:20}])});assert.equal(result.fillStatus,"partial");assert.equal(result.filledContractVolume,7);assert.equal(result.unfilledContractVolume,5);assert.equal(result.remainingPositionContractVolume,5)});

test("manual full-close request records a partial exit and keeps the trade open",async()=>{const {mkdtemp,rm}=await import("node:fs/promises"),{tmpdir}=await import("node:os"),{join}=await import("node:path"),{submitManualOrder,closeManualPosition,completedManualTrade}=await import("../app/lib/manual-paper.ts"),{validateManualPaperBackup}=await import("../app/lib/manual-paper-backup.ts"),prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),"dizy-paper-depth-exit-"));process.env.DATA_DIR=root;try{let account=await submitManualOrder("depth-exit",{idempotencyKey:"depth-exit-open-001",symbol:"BTC_USDT",side:"long",sizeMode:"fixed-notional",amount:500,leverage:10},100,"fair",contract,undefined,entryBook),opened=account.positions.BTC_USDT,originalMargin=opened.margin,originalEntryFee=opened.entryFee;const exitBook=depth([{price:99.9,orderCount:1,contractQuantity:2_000}],[{price:100.1,orderCount:1,contractQuantity:20_000}]);account=await closeManualPosition("depth-exit","BTC_USDT","depth-exit-close01",100,exitBook,contract);const fill=account.fills.at(-1),remaining=account.positions.BTC_USDT;assert.equal(fill.exitDepthFill.fillStatus,"partial");assert.equal(fill.exitDepthFill.executionContext,"exit");assert.equal(fill.exitDepthFill.filledContractVolume,2_000);assert.equal(fill.closeReason,undefined);assert.equal(remaining.contractVolume,3_000);assert.equal(remaining.quantity,3);assert.ok(remaining.margin<originalMargin);assert.ok(remaining.entryFee<originalEntryFee);assert.equal(await completedManualTrade("depth-exit",opened.tradeId),null);const restored=validateManualPaperBackup(account,"depth-exit");assert.equal(restored.fills.at(-1).exitDepthFill.remainingPositionContractVolume,3_000);const finalBook=depth([{price:99.8,orderCount:1,contractQuantity:10_000}],[{price:100.2,orderCount:1,contractQuantity:20_000}]);account=await closeManualPosition("depth-exit","BTC_USDT","depth-exit-close02",100,finalBook,contract);assert.equal(account.positions.BTC_USDT,undefined);assert.equal(account.fills.at(-1).closeReason,"manual");assert.equal(account.fills.at(-1).exitDepthFill.fillStatus,"full");assert.ok(await completedManualTrade("depth-exit",opened.tradeId))}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}});

test("a fully filled 50 percent request remains an open trade",async()=>{const {mkdtemp,rm}=await import("node:fs/promises"),{tmpdir}=await import("node:os"),{join}=await import("node:path"),{submitManualOrder,partialCloseManualPosition}=await import("../app/lib/manual-paper.ts"),prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),"dizy-paper-depth-partial-exit-"));process.env.DATA_DIR=root;try{let account=await submitManualOrder("depth-partial-exit",{idempotencyKey:"depth-partial-open1",symbol:"BTC_USDT",side:"long",sizeMode:"fixed-notional",amount:500,leverage:10},100,"fair",contract,undefined,entryBook);const book=depth([{price:99.9,orderCount:1,contractQuantity:10_000}],[{price:100.1,orderCount:1,contractQuantity:20_000}]);account=await partialCloseManualPosition("depth-partial-exit","BTC_USDT","depth-partial-close1",100,{percentage:50},book,contract);const fill=account.fills.at(-1);assert.equal(fill.exitDepthFill.fillStatus,"full");assert.equal(fill.exitDepthFill.requestedContractVolume,2_500);assert.equal(fill.exitDepthFill.filledContractVolume,2_500);assert.equal(fill.closeReason,undefined);assert.equal(account.positions.BTC_USDT.contractVolume,2_500)}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}});

test("manual exit depth rejects an unfillable sub-minimum remainder without mutation",async()=>{const {mkdtemp,rm}=await import("node:fs/promises"),{tmpdir}=await import("node:os"),{join}=await import("node:path"),{submitManualOrder,closeManualPosition,readManualAccount,ManualPaperError}=await import("../app/lib/manual-paper.ts"),prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),"dizy-paper-depth-min-remnant-"));process.env.DATA_DIR=root;const rules={...contract,minVol:5};try{let account=await submitManualOrder("depth-min-remnant",{idempotencyKey:"depth-min-open-0001",symbol:"BTC_USDT",side:"long",sizeMode:"fixed-notional",amount:.9,leverage:2},100,"fair",rules,undefined,entryBook);assert.equal(account.positions.BTC_USDT.contractVolume,9);const before=account.cashBalance,book=depth([{price:99.9,orderCount:1,contractQuantity:8}],[{price:100.1,orderCount:1,contractQuantity:20}]);await assert.rejects(()=>closeManualPosition("depth-min-remnant","BTC_USDT","depth-min-close001",100,book,rules),error=>error instanceof ManualPaperError&&error.code==="DEPTH_LIQUIDITY_BELOW_MINIMUM");account=await readManualAccount("depth-min-remnant");assert.equal(account.positions.BTC_USDT.contractVolume,9);assert.equal(account.cashBalance,before)}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}});
