import test from "node:test";
import assert from "node:assert/strict";
import {
  calculatePaperFundingPayment,
  dueMexcFundingSettlements,
  parseMexcFundingHistory,
  parseMexcFundingRate,
} from "../app/lib/manual-paper-funding.ts";

const currentPayload={success:true,data:{symbol:"BTC_USDT",fundingRate:.001,maxFundingRate:.003,minFundingRate:-.003,collectCycle:8,nextSettleTime:2_000_000_000_000}};
const historyPayload=(settleTime)=>({success:true,data:{resultList:[{symbol:"BTC_USDT",fundingRate:.001,settleTime}]}});
const contract={symbol:"BTC_USDT",displayName:"BTCUSDT SWAP",contractSize:.001,minLeverage:1,maxLeverage:125,priceUnit:.1,volUnit:1,minVol:1,maxVol:1_000_000,makerFeeRate:.0002,takerFeeRate:.0006,maintenanceMarginRate:.004,initialMarginRate:.008,positionOpenType:3,riskLimitType:"BY_VOLUME"};

test("MEXC funding snapshots retain settlement cadence and provenance",()=>{const snapshot=parseMexcFundingRate(currentPayload,"BTC_USDT",1_900_000_000_000);assert.equal(snapshot.collectCycleHours,8);assert.equal(snapshot.source,"mexc-public-funding-rate");const history=parseMexcFundingHistory(historyPayload(1_950_000_000_000),"BTC_USDT");assert.equal(history[0].source,"mexc-public-funding-history");assert.equal(dueMexcFundingSettlements(history,1_900_000_000_000,null,1_960_000_000_000).length,1)});

test("positive funding charges longs and credits shorts",()=>{assert.equal(calculatePaperFundingPayment({side:"long",quantity:2,observedPrice:100,fundingRate:.001}).calculatedCashDelta,-.2);assert.equal(calculatePaperFundingPayment({side:"short",quantity:2,observedPrice:100,fundingRate:.001}).calculatedCashDelta,.2)});

test("Manual Paper applies each settled funding event once and preserves it through backup",async()=>{const {mkdtemp,rm}=await import("node:fs/promises"),{tmpdir}=await import("node:os"),{join}=await import("node:path"),{submitManualOrder,syncManualFunding,closeManualPosition}=await import("../app/lib/manual-paper.ts"),{validateManualPaperBackup}=await import("../app/lib/manual-paper-backup.ts"),prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),"dizy-paper-funding-"));process.env.DATA_DIR=root;try{let account=await submitManualOrder("funding-owner",{idempotencyKey:"funding-open-000001",symbol:"BTC_USDT",side:"long",sizeMode:"fixed-notional",amount:100,leverage:10},100,"fair",contract,parseMexcFundingRate(currentPayload,"BTC_USDT",Date.now()));const position=account.positions.BTC_USDT,opened=Date.parse(position.openedAt);await new Promise(resolve=>setTimeout(resolve,5));const settlement={symbol:"BTC_USDT",fundingRate:.001,settleTime:opened+1,source:"mexc-public-funding-history"};account=await syncManualFunding("funding-owner","BTC_USDT",100,"fair",undefined,[settlement]);assert.equal(account.fundingPayments.length,1);assert.ok(account.fundingPnl<0);assert.equal(account.positions.BTC_USDT.fundingPnl,account.fundingPnl);const once=account.fundingPnl;account=await syncManualFunding("funding-owner","BTC_USDT",100,"fair",undefined,[settlement]);assert.equal(account.fundingPayments.length,1);assert.equal(account.fundingPnl,once);const restored=validateManualPaperBackup(account,"funding-owner");assert.equal(restored.fundingPayments[0].source,"mexc-public-funding-history");account=await closeManualPosition("funding-owner","BTC_USDT","funding-close-00001",101);const closed=account.fills.at(-1);assert.equal(closed.fundingPnl,once);assert.ok(Math.abs(closed.netPnl-((closed.grossPnl??0)-(closed.entryFee??0)-closed.fee+once))<1e-12)}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}});

test("pre-funding v3 backups migrate with empty funding history",async()=>{const {newManualAccount}=await import("../app/lib/manual-paper.ts"),{validateManualPaperBackup}=await import("../app/lib/manual-paper-backup.ts"),legacy=newManualAccount();legacy.version=3;delete legacy.migration;delete legacy.fundingPnl;delete legacy.fundingPayments;const restored=validateManualPaperBackup(legacy,"legacy-owner");assert.equal(restored.fundingPnl,0);assert.deepEqual(restored.fundingPayments,[])});

test("funding history requests are cached and use the maximum public page size",async()=>{const {readFile}=await import("node:fs/promises"),source=await readFile(new URL("../app/lib/manual-paper.ts",import.meta.url),"utf8");assert.match(source,/fundingHistoryCache/);assert.match(source,/page_size=1000/);assert.match(source,/now-cached.at<30_000/)});

test("a 100 percent partial close records entry fee, exit fee and cumulative funding",async()=>{const {mkdtemp,rm}=await import("node:fs/promises"),{tmpdir}=await import("node:os"),{join}=await import("node:path"),{submitManualOrder,syncManualFunding,partialCloseManualPosition}=await import("../app/lib/manual-paper.ts"),prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),"dizy-paper-funding-full-partial-"));process.env.DATA_DIR=root;try{let account=await submitManualOrder("funding-full-partial",{idempotencyKey:"funding-full-open-001",symbol:"BTC_USDT",side:"long",sizeMode:"fixed-notional",amount:100,leverage:10},100,"fair",contract,parseMexcFundingRate(currentPayload,"BTC_USDT",Date.now()));const opened=Date.parse(account.positions.BTC_USDT.openedAt);await new Promise(resolve=>setTimeout(resolve,5));account=await syncManualFunding("funding-full-partial","BTC_USDT",100,"fair",undefined,[{symbol:"BTC_USDT",fundingRate:.001,settleTime:opened+1,source:"mexc-public-funding-history"}]);const fundingPnl=account.positions.BTC_USDT.fundingPnl;account=await partialCloseManualPosition("funding-full-partial","BTC_USDT","funding-full-close-01",101,{percentage:100});const fill=account.fills.at(-1);assert.equal(fill.closeReason,"manual");assert.equal(fill.fundingPnl,fundingPnl);assert.ok(fill.entryFee>0);assert.ok(fill.exitFee>0);assert.ok(Math.abs(fill.netPnl-((fill.grossPnl??0)-fill.entryFee-fill.exitFee+fundingPnl))<1e-12);assert.equal(account.positions.BTC_USDT,undefined)}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}});

test("reversal closes the old trade net of entry fee and starts a fresh fee basis",async()=>{const {mkdtemp,rm}=await import("node:fs/promises"),{tmpdir}=await import("node:os"),{join}=await import("node:path"),{submitManualOrder,syncManualFunding,reverseManualPosition}=await import("../app/lib/manual-paper.ts"),prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),"dizy-paper-funding-reverse-audit-"));process.env.DATA_DIR=root;try{let account=await submitManualOrder("funding-reverse-audit",{idempotencyKey:"funding-reverse-open1",symbol:"BTC_USDT",side:"long",sizeMode:"fixed-notional",amount:100,leverage:10},100,"fair",contract,parseMexcFundingRate(currentPayload,"BTC_USDT",Date.now()));const opened=Date.parse(account.positions.BTC_USDT.openedAt);await new Promise(resolve=>setTimeout(resolve,5));account=await syncManualFunding("funding-reverse-audit","BTC_USDT",100,"fair",undefined,[{symbol:"BTC_USDT",fundingRate:.001,settleTime:opened+1,source:"mexc-public-funding-history"}]);account=await reverseManualPosition("funding-reverse-audit","BTC_USDT","funding-reverse-do-01",101);const [closeFill,openFill]=account.fills.slice(-2),next=account.positions.BTC_USDT;assert.equal(closeFill.closeReason,"reversal");assert.ok(closeFill.entryFee>0);assert.ok(closeFill.exitFee>0);assert.ok(Math.abs(closeFill.netPnl-((closeFill.grossPnl??0)-closeFill.entryFee-closeFill.exitFee+(closeFill.fundingPnl??0)))<1e-12);assert.equal(next.entryFee,openFill.entryFee);assert.equal(next.fundingPnl,0);assert.notEqual(next.tradeId,closeFill.tradeId)}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}});
