import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
const rules={symbol:"BTC_USDT",displayName:"BTC_USDT",contractSize:1,minLeverage:1,maxLeverage:125,priceUnit:.1,volUnit:1,minVol:1,maxVol:1000,makerFeeRate:.0002,takerFeeRate:.0006,maintenanceMarginRate:.004,initialMarginRate:.008,positionOpenType:3,riskLimitType:"BY_VOLUME"};
const levels=pairs=>pairs.map(([price,contractQuantity])=>({price,orderCount:1,contractQuantity}));
const book=(bids,asks,receivedAt=Date.now())=>({snapshot:{symbol:"BTC_USDT",version:144,engineTimeMs:receivedAt,bids:levels(bids),asks:levels(asks)},receivedAt,diagnostic:{snapshotAgeMs:0,consecutiveFailures:0,lastError:null,sourceMode:"REST FALLBACK",snapshotComplete:true}});
async function isolated(name,fn){const prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),name));process.env.DATA_DIR=root;try{return await fn()}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}}
async function openLong(user,extra={}){const {submitManualOrder}=await import("../app/lib/manual-paper.ts");return submitManualOrder(user,{idempotencyKey:user+"-open-order-0001",symbol:"BTC_USDT",side:"long",sizeMode:"fixed-notional",amount:500,leverage:5,...extra},100,"fair",rules,undefined,book([[99,20]],[[100,20]]))}
test("opposite ticket order consumes close liquidity before opening its requested replacement size",()=>isolated("dizy-opposite-sequential-",async()=>{const {submitManualOrder}=await import("../app/lib/manual-paper.ts");let account=await openLong("opposite-seq"),oldTrade=account.positions.BTC_USDT.tradeId;account=await submitManualOrder("opposite-seq",{idempotencyKey:"opposite-order-0002",symbol:"BTC_USDT",side:"short",sizeMode:"fixed-notional",amount:300,leverage:5,confirmReverse:true},100,"fair",rules,undefined,book([[99.9,5],[99.8,3]],[[100.1,20]]));const closeFill=account.fills.at(-2),openFill=account.fills.at(-1);assert.equal(closeFill.tradeId,oldTrade);assert.equal(closeFill.closeReason,"reversal");assert.equal(closeFill.exitDepthFill.filledContractVolume,5);assert.equal(account.positions.BTC_USDT.side,"short");assert.equal(account.positions.BTC_USDT.contractVolume,3);assert.equal(account.positions.BTC_USDT.entryPrice,99.8);assert.equal(openFill.entryDepthFill.priorConsumedContractVolume,5)}));
test("thin close liquidity leaves the original side open and creates no opposite ticket position",()=>isolated("dizy-opposite-partial-",async()=>{const {submitManualOrder}=await import("../app/lib/manual-paper.ts");let account=await openLong("opposite-partial"),oldTrade=account.positions.BTC_USDT.tradeId,before=account.fills.length;account=await submitManualOrder("opposite-partial",{idempotencyKey:"opposite-order-0003",symbol:"BTC_USDT",side:"short",sizeMode:"fixed-notional",amount:300,leverage:5,confirmReverse:true},100,"fair",rules,undefined,book([[99.9,3]],[[100.1,20]]));assert.equal(account.positions.BTC_USDT.side,"long");assert.equal(account.positions.BTC_USDT.tradeId,oldTrade);assert.equal(account.positions.BTC_USDT.contractVolume,2);assert.equal(account.fills.length,before+1);assert.equal(account.fills.at(-1).exitDepthFill.fillStatus,"partial");assert.equal(account.fills.at(-1).closeReason,undefined)}));
test("pending automatic risk exit blocks opposite ticket replacement and Reverse",()=>isolated("dizy-pending-block-",async()=>{const {markManualPosition,reverseManualPosition,submitManualOrder}=await import("../app/lib/manual-paper.ts");let account=await openLong("pending-block",{stopLoss:99});account=await markManualPosition("pending-block","BTC_USDT",98,"fair",undefined,[],null,null,true);assert.equal(account.positions.BTC_USDT.pendingRiskExit.reason,"stop");await assert.rejects(()=>submitManualOrder("pending-block",{idempotencyKey:"opposite-order-0004",symbol:"BTC_USDT",side:"short",sizeMode:"fixed-notional",amount:300,leverage:5,confirmReverse:true},98,"fair",rules,undefined,book([[97.9,20]],[[98.1,20]])),error=>error?.code==="RISK_EXIT_PENDING");await assert.rejects(()=>reverseManualPosition("pending-block","BTC_USDT","reverse-pending-001",98,book([[97.9,20]],[[98.1,20]]),rules),error=>error?.code==="RISK_EXIT_PENDING") }));
