import test from "node:test";
import assert from "node:assert/strict";
import {buildPaperMarginAccountSnapshot,buildPaperPositionMarginAudit,settlePaperMarginCash} from "../app/lib/manual-paper-margin-model.ts";

const position=(overrides={})=>({symbol:"BTC_USDT",side:"long",quantity:10,entryPrice:100,markPrice:100,margin:100,marginMode:"cross",maintenanceMarginRate:.01,liquidationPenaltyRate:.001,...overrides});

test("single-asset margin snapshot fences isolated collateral from the cross pool",()=>{const isolated=position({symbol:"ISO_USDT",marginMode:"isolated",markPrice:50}),crossLong=position({symbol:"LONG_USDT",markPrice:110}),crossShort=position({symbol:"SHORT_USDT",side:"short",markPrice:90}),snapshot=buildPaperMarginAccountSnapshot(1000,[isolated,crossLong,crossShort],123);assert.equal(snapshot.isolatedReservedMargin,100);assert.equal(snapshot.crossPoolCash,900);assert.equal(snapshot.crossUnrealisedPnl,200);assert.equal(snapshot.crossEquity,1100);assert.equal(snapshot.crossInitialMargin,200);assert.equal(snapshot.crossAvailableEquity,900);assert.equal(snapshot.crossPositionCount,2);assert.equal(snapshot.capturedAt,123);assert.equal(snapshot.settlementAsset,"USDT")});

test("position audits distinguish fenced isolated support from the shared cross pool",()=>{const isolated=position({symbol:"ISO_USDT",marginMode:"isolated"}),cross=position({symbol:"CROSS_USDT",markPrice:110}),other=position({symbol:"OTHER_USDT",side:"short",markPrice:90}),snapshot=buildPaperMarginAccountSnapshot(1000,[isolated,cross,other],456),isolatedAudit=buildPaperPositionMarginAudit(isolated,snapshot),crossAudit=buildPaperPositionMarginAudit(cross,snapshot);assert.equal(isolatedAudit.calculationMethod,"isolated-position-collateral-v1");assert.equal(isolatedAudit.collateralAvailableToPosition,isolated.margin);assert.equal(isolatedAudit.supportingCrossPositionCount,1);assert.equal(crossAudit.calculationMethod,"cross-shared-usdt-pool-v1");assert.equal(crossAudit.supportingCrossPositionCount,2);assert.equal(crossAudit.collateralAvailableToPosition,snapshot.crossPoolCash+crossAudit.otherCrossUnrealisedPnl-crossAudit.otherCrossMaintenanceRequirement-crossAudit.otherCrossLiquidationReserve)});

test("loss settlement caps isolated loss and protects isolated collateral from cross loss",()=>{const isolated=settlePaperMarginCash({cashBalance:1000,marginMode:"isolated",allocatedMargin:100,isolatedReservedMargin:100,requestedCashDelta:-500}),cross=settlePaperMarginCash({cashBalance:1000,marginMode:"cross",allocatedMargin:200,isolatedReservedMargin:300,requestedCashDelta:-900});assert.equal(isolated.cashAfter,900);assert.equal(isolated.appliedCashDelta,-100);assert.equal(isolated.capped,true);assert.equal(cross.cashAfter,300);assert.equal(cross.appliedCashDelta,-700);assert.equal(cross.protectedCollateral,300);assert.equal(cross.capped,true)});
