import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import { copyFileSync,mkdtempSync,renameSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { ModernMexcReduceOnlyWriter,MEXC_EXECUTION_BASE_URL,MEXC_ORDER_CREATE_PATH,MEXC_EXTERNAL_ORDER_PATH,MEXC_EXECUTION_RECV_WINDOW_SECONDS,assertMexcWriteAuthority,createMexcExecutionFetchTransport,mexcExternalOid,readMexcExecutionCredentials } from "../app/lib/execution/internal/mexc-execution-writer.ts";
import { SqliteMexcExecutionLifecycleStore } from "../app/lib/execution/internal/mexc-execution-lifecycle-store.ts";
import { composeMexcPreWriteAuthority } from "../app/lib/execution/internal/mexc-write-authority.ts";

const credentials={accessKey:"write-access-fixture",secretKey:"write-secret-fixture-long",generation:"generation-1"};
const intent={userId:"user-1",accountId:"account-1",intentId:"intent-id-315",idempotencyKey:"intent-315",symbol:"BTC_USDT",side:"long",orderType:"limit",positionMode:"one-way",positionId:"991",marginMode:"isolated",positionVolume:3,volume:1,price:65000,referencePrice:65000,estimatedNotional:65,leverage:1,reduceOnly:true,bindingGeneration:"binding-1",writeCredentialGeneration:"generation-1",rolloutRevision:2,riskRevision:3,reconciliationRevision:4};
const enabled={LIVE_TRADING_ENABLED:"true",MEXC_WRITE_PROVIDER_ENABLED:"true"};
const switches={armed:true,globalDisabled:false,disabledUserIds:new Set(),disabledAccountKeys:new Set(),providerStateFresh:true,maintenance:false,emergencyStop:false};
const prepared={intentId:intent.intentId,idempotencyKey:intent.idempotencyKey,state:"prepared",executed:false,duplicate:false,reason:"SYNTHETIC_PROVIDER_OUTCOME",preview:{symbol:intent.symbol,side:intent.side,orderType:intent.orderType,quantity:0.001,normalizedContractVolume:intent.volume,referencePrice:intent.referencePrice,estimatedNotional:intent.estimatedNotional,estimatedMargin:65,policyVersion:"execution-preview-policy/1.0.0",price:intent.price,leverage:intent.leverage,reduceOnly:true}};
const authorityEvidence={caller:{userId:intent.userId,accountId:intent.accountId,totpAssured:true},ownership:{userId:intent.userId,accountId:intent.accountId,bindingGeneration:intent.bindingGeneration,freshUntil:"2023-11-14T22:14:00.000Z"},reconciliation:{userId:intent.userId,accountId:intent.accountId,revision:intent.reconciliationRevision,positionId:intent.positionId,positionSide:"short",positionMode:intent.positionMode,marginMode:intent.marginMode,positionVolume:intent.positionVolume,freshUntil:"2023-11-14T22:14:00.000Z",clean:true},risk:{userId:intent.userId,accountId:intent.accountId,revision:intent.riskRevision,enabled:true},rollout:{userId:intent.userId,accountId:intent.accountId,revision:intent.rolloutRevision,bindingGeneration:intent.bindingGeneration,riskRevision:intent.riskRevision,armed:true},switches,airlock:{userId:intent.userId,accountId:intent.accountId,intentId:intent.intentId,idempotencyKey:intent.idempotencyKey,result:prepared},network:{mexcEgressAllowlisted:true}};
const evidenceFor=(nextIntent)=>({...authorityEvidence,ownership:{...authorityEvidence.ownership,bindingGeneration:nextIntent.bindingGeneration},reconciliation:{...authorityEvidence.reconciliation,revision:nextIntent.reconciliationRevision,positionSide:nextIntent.side==="long"?"short":"long",marginMode:nextIntent.marginMode},risk:{...authorityEvidence.risk,revision:nextIntent.riskRevision},rollout:{...authorityEvidence.rollout,revision:nextIntent.rolloutRevision,bindingGeneration:nextIntent.bindingGeneration,riskRevision:nextIntent.riskRevision},airlock:{...authorityEvidence.airlock,intentId:nextIntent.intentId,idempotencyKey:nextIntent.idempotencyKey,result:{...prepared,intentId:nextIntent.intentId,idempotencyKey:nextIntent.idempotencyKey,preview:{...prepared.preview,side:nextIntent.side,orderType:nextIntent.orderType,normalizedContractVolume:nextIntent.volume,price:nextIntent.price}}}});
const context=(nextIntent=intent,nextCredentials=credentials,evidence=evidenceFor(nextIntent),environment=enabled)=>()=>({credentials:nextCredentials,environment,evidence});
const execute=(writer,nextIntent=intent,nextCredentials=credentials,evidence=evidenceFor(nextIntent),environment=enabled)=>writer.execute(nextIntent,context(nextIntent,nextCredentials,evidence,environment));
const response=(id,overrides={})=>({status:200,body:JSON.stringify({success:true,code:0,data:{orderId:id,externalOid:mexcExternalOid(intent),symbol:"BTC_USDT",side:2,vol:1,positionId:"991",positionMode:2,openType:1,...overrides}})});

test("modern create signs and sends the identical canonical close-short body then immediately reconciles",async()=>{const calls=[],store=new SqliteMexcExecutionLifecycleStore(":memory:"),now=()=>1700000000000,writer=new ModernMexcReduceOnlyWriter(async request=>{calls.push(request);return calls.length===1?response("order-1"):response("order-1")},store,now,0);const result=await execute(writer);assert.equal(result.state,"reconciled");assert.equal(calls[0].url,MEXC_EXECUTION_BASE_URL+MEXC_ORDER_CREATE_PATH);assert.equal(calls[0].method,"POST");assert.deepEqual(JSON.parse(calls[0].body),{symbol:"BTC_USDT",price:65000,vol:1,side:2,type:1,openType:1,leverage:1,externalOid:mexcExternalOid(intent),positionId:"991",positionMode:2,reduceOnly:true});assert.equal(calls[0].headers["Request-Time"],"1700000000000");assert.equal(calls[0].headers["Recv-Window"],String(MEXC_EXECUTION_RECV_WINDOW_SECONDS));assert.equal(calls[0].headers.Signature,createHmac("sha256",credentials.secretKey).update(credentials.accessKey+calls[0].headers["Request-Time"]+calls[0].body).digest("hex"));assert.equal(calls[1].url,`${MEXC_EXECUTION_BASE_URL}${MEXC_EXTERNAL_ORDER_PATH}/BTC_USDT/${mexcExternalOid(intent)}`);assert.equal(calls[1].method,"GET");assert.doesNotMatch(JSON.stringify(result),/write-access|write-secret|Signature/);store.close();});

test("ambiguous create reconciles before any retry and restart never produces a second POST",async()=>{const dir=mkdtempSync(join(tmpdir(),"mexc-writer-")),path=join(dir,"l.sqlite");try{let posts=0,gets=0,store=new SqliteMexcExecutionLifecycleStore(path),writer=new ModernMexcReduceOnlyWriter(async request=>{if(request.method==="POST"){posts++;throw new Error("network");}gets++;return response("recovered-1")},store,()=>1700000000000,0);assert.equal((await execute(writer)).state,"reconciled");store.close();store=new SqliteMexcExecutionLifecycleStore(path);writer=new ModernMexcReduceOnlyWriter(async request=>{if(request.method==="POST")posts++;else gets++;return response("recovered-1")},store,()=>1700000001000,0);assert.equal((await execute(writer)).state,"reconciled");assert.equal(posts,1);assert.equal(gets,1);store.close();}finally{rmSync(dir,{recursive:true,force:true});}});

test("ambiguous delivery remains GET-reconcilable after write authority is revoked or rotated",async t=>{
  const cases={
    "activation disabled":state=>state.environment={...state.environment,LIVE_TRADING_ENABLED:"false",MEXC_WRITE_PROVIDER_ENABLED:"false"},
    "kill switch":state=>state.evidence={...state.evidence,switches:{...state.evidence.switches,emergencyStop:true}},
    "credential generation rotated":state=>state.credentials={...state.credentials,generation:"generation-2"},
    "account quarantined":(state,store)=>store.quarantineAccount(intent.userId,intent.accountId,"post-ambiguity-quarantine",new Date(1700000000000).toISOString()),
  };
  for(const [name,revoke] of Object.entries(cases))await t.test(name,async()=>{
    const store=new SqliteMexcExecutionLifecycleStore(":memory:");let posts=0,gets=0,recoveryAvailable=false;
    const transport=async request=>{if(request.method==="POST"){posts++;throw new Error("ambiguous-network");}gets++;if(!recoveryAvailable)throw new Error("recovery-unavailable");return response("recovered-after-revocation");};
    const writer=new ModernMexcReduceOnlyWriter(transport,store,()=>1700000000000,0);
    await assert.rejects(execute(writer),error=>error.kind==="indeterminate");assert.equal(posts,1);assert.equal(gets,1);
    const state={credentials,evidence:evidenceFor(intent),environment:enabled};revoke(state,store);recoveryAvailable=true;
    const result=await writer.execute(intent,()=>({credentials:state.credentials,environment:state.environment,evidence:state.evidence}));
    assert.equal(result.state,"reconciled");assert.equal(posts,1,"recovery must never authorize a second POST");assert.equal(gets,2);store.close();
  });
});

test("provider divergence sticks quarantine to the exact account",async()=>{const store=new SqliteMexcExecutionLifecycleStore(":memory:"),writer=new ModernMexcReduceOnlyWriter(async request=>request.method==="POST"?response("accepted"):response("different"),store,()=>1700000000000,0);await assert.rejects(execute(writer),error=>error.kind==="quarantined");assert.equal(store.isAccountQuarantined("user-1","account-1"),true);assert.equal(store.isAccountQuarantined("user-1","account-2"),false);await assert.rejects(execute(writer,{...intent,idempotencyKey:"next"}),error=>error.kind==="quarantined");store.close();});

test("credentials and activation fail closed and cannot alias Account Companion",()=>{const base={MEXC_EXECUTION_ACCESS_KEY:"write-access-fixture",MEXC_EXECUTION_SECRET_KEY:"write-secret-fixture-long",MEXC_EXECUTION_CREDENTIAL_GENERATION:"g"};assert.deepEqual(readMexcExecutionCredentials(base),{accessKey:"write-access-fixture",secretKey:"write-secret-fixture-long",generation:"g"});for(const env of [{},{...base,MEXC_EXECUTION_SECRET_KEY:undefined},{...base,OWNER_MEXC_READONLY_API_KEY:"write-access-fixture"},{...base,OWNER_MEXC_READONLY_API_SECRET:"write-secret-fixture-long"},{...base,NEXT_PUBLIC_MEXC_EXECUTION_SECRET:"leaked"},{...base,NEXT_PUBLIC_MEXC_EXECUTION_ACCESS_KEY:"leaked"},{...base,NEXT_PUBLIC_mexc_execution_access_key:"leaked"},{...base,PUBLIC_MEXC_EXECUTION_CREDENTIAL_GENERATION:"leaked"}])assert.throws(()=>readMexcExecutionCredentials(env));const authority={callerAssured:true,ownerBound:true,ownershipFresh:true,reconciliationClean:true,riskEnabled:true,rolloutArmed:true,killSwitchesClear:true,airlockPrepared:true,networkAllowlisted:true};assert.throws(()=>assertMexcWriteAuthority({LIVE_TRADING_ENABLED:"false",MEXC_WRITE_PROVIDER_ENABLED:"true"},authority));assert.throws(()=>assertMexcWriteAuthority({LIVE_TRADING_ENABLED:"true",MEXC_WRITE_PROVIDER_ENABLED:"true"},{...authority,killSwitchesClear:false}));assert.throws(()=>assertMexcWriteAuthority({LIVE_TRADING_ENABLED:"true",MEXC_WRITE_PROVIDER_ENABLED:"true"},{}));assert.doesNotThrow(()=>assertMexcWriteAuthority({LIVE_TRADING_ENABLED:"true",MEXC_WRITE_PROVIDER_ENABLED:"true"},authority));});

test("final submit context preserves server-only credential separation checks",async t=>{
  const cases={
    "read-only key alias":{...enabled,OWNER_MEXC_READONLY_API_KEY:credentials.accessKey},
    "read-only secret alias":{...enabled,OWNER_MEXC_READONLY_API_SECRET:credentials.secretKey},
    "public execution exposure":{...enabled,NEXT_PUBLIC_MEXC_EXECUTION_ACCESS_KEY:"leaked-browser-value"},
  };
  for(const [name,environment] of Object.entries(cases))await t.test(name,async()=>{
    let posts=0;const store=new SqliteMexcExecutionLifecycleStore(":memory:"),writer=new ModernMexcReduceOnlyWriter(async request=>{if(request.method==="POST")posts++;return response("never")},store,()=>1700000000000,0);
    await assert.rejects(writer.execute(intent,context(intent,credentials,evidenceFor(intent),environment)),error=>error.kind==="validation");assert.equal(posts,0);store.close();
  });
});

test("writer only accepts bounded one-way limit reductions",async()=>{for(const changed of [{reduceOnly:false},{positionMode:"hedge"},{orderType:"market"},{volume:4},{positionVolume:0},{side:"open-long"}]){let calls=0;const store=new SqliteMexcExecutionLifecycleStore(":memory:"),writer=new ModernMexcReduceOnlyWriter(async()=>{calls++;return response("never")},store,()=>0,0);await assert.rejects(execute(writer,{...intent,...changed}),error=>error.kind==="validation");assert.equal(calls,0);store.close();}});

test("pre-write authority is derived from kill switches, opposing position evidence, and the exact prepared limit preview",()=>{const authority=composeMexcPreWriteAuthority(intent,authorityEvidence,1700000000000);assert.ok(Object.values(authority).every(Boolean));for(const changed of [{account:true},{maintenance:true},{emergencyStop:true},{armed:false},{providerStateFresh:false}]){const next={...switches};if(changed.account)next.disabledAccountKeys=new Set([JSON.stringify([intent.userId,intent.accountId])]);else Object.assign(next,changed);assert.equal(composeMexcPreWriteAuthority(intent,{...authorityEvidence,switches:next},1700000000000).killSwitchesClear,false);}assert.equal(composeMexcPreWriteAuthority(intent,{...authorityEvidence,airlock:{...authorityEvidence.airlock,result:{...prepared,preview:{...prepared.preview,normalizedContractVolume:2}}}},1700000000000).airlockPrepared,false);assert.equal(composeMexcPreWriteAuthority(intent,{...authorityEvidence,airlock:{...authorityEvidence.airlock,result:{...prepared,preview:{...prepared.preview,orderType:"market"}}}},1700000000000).airlockPrepared,false);assert.equal(composeMexcPreWriteAuthority(intent,{...authorityEvidence,reconciliation:{...authorityEvidence.reconciliation,positionSide:"long"}},1700000000000).reconciliationClean,false);assert.equal(composeMexcPreWriteAuthority(intent,{...authorityEvidence,reconciliation:{...authorityEvidence.reconciliation,marginMode:"cross"}},1700000000000).reconciliationClean,false);});

test("short/sell reduction serializes close-long side 4",async()=>{const calls=[],store=new SqliteMexcExecutionLifecycleStore(":memory:"),shortIntent={...intent,idempotencyKey:"short-reduce",side:"short"},writer=new ModernMexcReduceOnlyWriter(async request=>{calls.push(request);return response("short-1",{externalOid:mexcExternalOid(shortIntent),side:4})},store,()=>1700000000000,0);await execute(writer,shortIntent);assert.equal(JSON.parse(calls[0].body).side,4);store.close();});

test("stable externalOid quarantines authority revision and generation rotations before POST",async()=>{for(const changed of [{rolloutRevision:20},{riskRevision:30},{reconciliationRevision:40},{bindingGeneration:"binding-2"},{writeCredentialGeneration:"generation-2"}]){let posts=0;const store=new SqliteMexcExecutionLifecycleStore(":memory:"),writer=new ModernMexcReduceOnlyWriter(async request=>{if(request.method==="POST")posts++;return response("one")},store,()=>1700000000000,0);await execute(writer);const rotated={...intent,...changed};assert.equal(mexcExternalOid(rotated),mexcExternalOid(intent));const rotatedCredentials=changed.writeCredentialGeneration?{...credentials,generation:changed.writeCredentialGeneration}:credentials;await assert.rejects(execute(writer,rotated,rotatedCredentials),error=>error.kind==="quarantined");assert.equal(posts,1);store.close();}});

test("source contains only the current create write endpoint and explicitly excludes legacy submit",async()=>{const {readFile}=await import("node:fs/promises"),source=await readFile(new URL("../app/lib/execution/internal/mexc-execution-writer.ts",import.meta.url),"utf8");assert.match(source,/\/api\/v1\/private\/order\/create/);assert.doesNotMatch(source,/\/api\/v1\/private\/order\/submit/);assert.equal((source.match(/method:\s*"POST"/g)||[]).length,1);});

test("real transport is bounded to api.mexc.com and remains injectable",async()=>{const calls=[],transport=createMexcExecutionFetchTransport(async(url,init)=>{calls.push({url,init});return new Response('{"ok":true}',{status:200})});assert.deepEqual(await transport({url:MEXC_EXECUTION_BASE_URL+MEXC_ORDER_CREATE_PATH,method:"POST",headers:{safe:"header"},body:"{}",timeoutMs:100}),{status:200,body:'{"ok":true}'});assert.equal(calls[0].init.redirect,"error");await assert.rejects(transport({url:"https://attacker.invalid/order",method:"POST",headers:{},body:"{}",timeoutMs:100}));});

test("two stores atomically claim one logical delivery",async()=>{const dir=mkdtempSync(join(tmpdir(),"mexc-cas-")),path=join(dir,"l.sqlite");try{let posts=0;let release;const blocked=new Promise(resolve=>{release=resolve});const transport=async request=>{if(request.method==="POST"){posts++;await blocked;return response("one")}return response("one")};const a=new SqliteMexcExecutionLifecycleStore(path),b=new SqliteMexcExecutionLifecycleStore(path),wa=new ModernMexcReduceOnlyWriter(transport,a,()=>1700000000000,0),wb=new ModernMexcReduceOnlyWriter(transport,b,()=>1700000000000,0);const first=execute(wa);await new Promise(resolve=>setTimeout(resolve,25));const second=execute(wb);await new Promise(resolve=>setTimeout(resolve,25));assert.equal(posts,1);release();await first;await second.catch(()=>undefined);assert.equal(posts,1);a.close();b.close();}finally{rmSync(dir,{recursive:true,force:true});}});

test("queued requests obtain fresh authority and credential generation after the writer wait",async t=>{
  const cases={
    "kill switch":state=>state.evidence={...state.evidence,switches:{...state.evidence.switches,emergencyStop:true}},
    "ownership binding":state=>state.evidence={...state.evidence,ownership:{...state.evidence.ownership,bindingGeneration:"revoked-binding"}},
    "reconciliation revision":state=>state.evidence={...state.evidence,reconciliation:{...state.evidence.reconciliation,revision:999}},
    "reconciliation freshness":state=>state.evidence={...state.evidence,reconciliation:{...state.evidence.reconciliation,freshUntil:"2020-01-01T00:00:00.000Z"}},
    "risk revision":state=>state.evidence={...state.evidence,risk:{...state.evidence.risk,revision:999}},
    "risk disabled":state=>state.evidence={...state.evidence,risk:{...state.evidence.risk,enabled:false}},
    "rollout revision":state=>state.evidence={...state.evidence,rollout:{...state.evidence.rollout,revision:999}},
    "rollout binding":state=>state.evidence={...state.evidence,rollout:{...state.evidence.rollout,bindingGeneration:"revoked-binding"}},
    "rollout disarmed":state=>state.evidence={...state.evidence,rollout:{...state.evidence.rollout,armed:false}},
    "egress attestation":state=>state.evidence={...state.evidence,network:{mexcEgressAllowlisted:false}},
    "live activation":state=>state.environment={...state.environment,LIVE_TRADING_ENABLED:"false"},
    "provider activation":state=>state.environment={...state.environment,MEXC_WRITE_PROVIDER_ENABLED:"false"},
    "credential generation":state=>state.credentials={...state.credentials,generation:"generation-2"},
    "quarantine":(state,store)=>store.quarantineAccount(state.intent.userId,state.intent.accountId,"queued-revocation",new Date(1700000000000).toISOString()),
  };
  for(const [name,revoke] of Object.entries(cases))await t.test(name,async()=>{
    const store=new SqliteMexcExecutionLifecycleStore(":memory:");let release;const blocked=new Promise(resolve=>{release=resolve});let posts=0;
    const transport=async request=>{if(request.method==="POST"){posts++;if(posts===1)await blocked;}return response("queued-order",{externalOid:JSON.parse(request.body??"{}").externalOid??mexcExternalOid(intent)});};
    const writer=new ModernMexcReduceOnlyWriter(transport,store,()=>1700000000000,0);
    const secondIntent={...intent,intentId:`second-${name.replaceAll(" ","-")}`,idempotencyKey:`second-${name.replaceAll(" ","-")}`};
    const state={intent:secondIntent,credentials,evidence:evidenceFor(secondIntent),environment:enabled};let providerReads=0;
    const first=execute(writer);while(posts===0)await new Promise(resolve=>setTimeout(resolve,1));
    const second=writer.execute(secondIntent,()=>{providerReads++;return {credentials:state.credentials,environment:state.environment,evidence:state.evidence};});
    await new Promise(resolve=>setTimeout(resolve,5));assert.equal(providerReads,0,"provider must not run while queued");
    revoke(state,store);release();await first;
    await assert.rejects(second);assert.equal(providerReads,1);assert.equal(posts,1,"revoked queued request must not POST");
    const lifecycle=store.read((await import("../app/lib/execution/internal/mexc-execution-writer.ts")).mexcExecutionIdentityDigest(secondIntent));
    assert.equal(lifecycle?.state,"reserved","known non-delivery must not be marked submitting/indeterminate");store.close();
  });
});

test("valid older lifecycle replacement permanently poisons the store instance",async()=>{const dir=mkdtempSync(join(tmpdir(),"mexc-replace-")),path=join(dir,"live.sqlite"),old=join(dir,"old.sqlite");try{const store=new SqliteMexcExecutionLifecycleStore(path),writer=new ModernMexcReduceOnlyWriter(async request=>request.method==="POST"?response("one"):response("one"),store,()=>1700000000000,0);await execute(writer);store.close();copyFileSync(path,old);const reopened=new SqliteMexcExecutionLifecycleStore(path);assert.equal(reopened.isAccountQuarantined("user-1","account-1"),false);renameSync(old,path);assert.throws(()=>reopened.isAccountQuarantined("user-1","account-1"));assert.throws(()=>reopened.isAccountQuarantined("user-1","account-1"));assert.throws(()=>reopened.read("a".repeat(64)));reopened.close();}finally{rmSync(dir,{recursive:true,force:true});}});