import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import { copyFileSync,mkdtempSync,renameSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { ModernMexcReduceOnlyWriter,MEXC_EXECUTION_BASE_URL,MEXC_ORDER_CREATE_PATH,MEXC_EXTERNAL_ORDER_PATH,MEXC_EXECUTION_RECV_WINDOW_SECONDS,assertMexcWriteAuthority,createMexcExecutionFetchTransport,mexcExternalOid,readMexcExecutionCredentials } from "../app/lib/execution/internal/mexc-execution-writer.ts";
import { SqliteMexcExecutionLifecycleStore } from "../app/lib/execution/internal/mexc-execution-lifecycle-store.ts";
import { composeMexcPreWriteAuthority } from "../app/lib/execution/internal/mexc-write-authority.ts";

const credentials={accessKey:"write-access-fixture",secretKey:"write-secret-fixture-long",generation:"generation-1"};
const intent={userId:"user-1",accountId:"account-1",idempotencyKey:"intent-315",symbol:"BTC_USDT",positionSide:"long",positionMode:"one-way",positionId:"991",marginMode:"isolated",positionVolume:3,volume:1,price:65000,leverage:1,reduceOnly:true,bindingGeneration:"generation-1",rolloutRevision:2,riskRevision:3,reconciliationRevision:4};
const response=(id,overrides={})=>({status:200,body:JSON.stringify({success:true,code:0,data:{orderId:id,externalOid:mexcExternalOid(intent),symbol:"BTC_USDT",side:4,vol:1,positionId:"991",positionMode:2,openType:1,...overrides}})});

test("modern create signs and sends the identical canonical body then immediately reconciles",async()=>{const calls=[],store=new SqliteMexcExecutionLifecycleStore(":memory:"),now=()=>1700000000000,writer=new ModernMexcReduceOnlyWriter(async request=>{calls.push(request);return calls.length===1?response("order-1"):response("order-1")},store,now,0);const result=await writer.execute(intent,credentials);assert.equal(result.state,"reconciled");assert.equal(calls[0].url,MEXC_EXECUTION_BASE_URL+MEXC_ORDER_CREATE_PATH);assert.equal(calls[0].method,"POST");assert.deepEqual(JSON.parse(calls[0].body),{symbol:"BTC_USDT",price:65000,vol:1,side:4,type:1,openType:1,leverage:1,externalOid:mexcExternalOid(intent),positionId:"991",positionMode:2,reduceOnly:true});assert.equal(calls[0].headers["Request-Time"],"1700000000000");assert.equal(calls[0].headers["Recv-Window"],String(MEXC_EXECUTION_RECV_WINDOW_SECONDS));assert.equal(calls[0].headers.Signature,createHmac("sha256",credentials.secretKey).update(credentials.accessKey+calls[0].headers["Request-Time"]+calls[0].body).digest("hex"));assert.equal(calls[1].url,`${MEXC_EXECUTION_BASE_URL}${MEXC_EXTERNAL_ORDER_PATH}/BTC_USDT/${mexcExternalOid(intent)}`);assert.equal(calls[1].method,"GET");assert.doesNotMatch(JSON.stringify(result),/write-access|write-secret|Signature/);store.close();});

test("ambiguous create reconciles before any retry and restart never produces a second POST",async()=>{const dir=mkdtempSync(join(tmpdir(),"mexc-writer-")),path=join(dir,"l.sqlite");try{let posts=0,gets=0,store=new SqliteMexcExecutionLifecycleStore(path),writer=new ModernMexcReduceOnlyWriter(async request=>{if(request.method==="POST"){posts++;throw new Error("network");}gets++;return response("recovered-1")},store,()=>1700000000000,0);assert.equal((await writer.execute(intent,credentials)).state,"reconciled");store.close();store=new SqliteMexcExecutionLifecycleStore(path);writer=new ModernMexcReduceOnlyWriter(async request=>{if(request.method==="POST")posts++;else gets++;return response("recovered-1")},store,()=>1700000001000,0);assert.equal((await writer.execute(intent,credentials)).state,"reconciled");assert.equal(posts,1);assert.equal(gets,1);store.close();}finally{rmSync(dir,{recursive:true,force:true});}});

test("provider divergence sticks quarantine to the exact account",async()=>{const store=new SqliteMexcExecutionLifecycleStore(":memory:"),writer=new ModernMexcReduceOnlyWriter(async request=>request.method==="POST"?response("accepted"):response("different"),store,()=>1700000000000,0);await assert.rejects(writer.execute(intent,credentials),error=>error.kind==="quarantined");assert.equal(store.isAccountQuarantined("user-1","account-1"),true);assert.equal(store.isAccountQuarantined("user-1","account-2"),false);await assert.rejects(writer.execute({...intent,idempotencyKey:"next"},credentials),error=>error.kind==="quarantined");store.close();});

test("credentials and activation fail closed and cannot alias Account Companion",()=>{const base={MEXC_EXECUTION_ACCESS_KEY:"write-access-fixture",MEXC_EXECUTION_SECRET_KEY:"write-secret-fixture-long",MEXC_EXECUTION_CREDENTIAL_GENERATION:"g"};assert.deepEqual(readMexcExecutionCredentials(base),{accessKey:"write-access-fixture",secretKey:"write-secret-fixture-long",generation:"g"});for(const env of [{},{...base,MEXC_EXECUTION_SECRET_KEY:undefined},{...base,OWNER_MEXC_READONLY_API_KEY:"write-access-fixture"},{...base,OWNER_MEXC_READONLY_API_SECRET:"write-secret-fixture-long"},{...base,NEXT_PUBLIC_MEXC_EXECUTION_SECRET:"leaked"}])assert.throws(()=>readMexcExecutionCredentials(env));const authority={callerAssured:true,ownerBound:true,ownershipFresh:true,reconciliationClean:true,riskEnabled:true,rolloutArmed:true,killSwitchesClear:true,networkAllowlisted:true};assert.throws(()=>assertMexcWriteAuthority({LIVE_TRADING_ENABLED:"false",MEXC_WRITE_PROVIDER_ENABLED:"true"},authority));assert.throws(()=>assertMexcWriteAuthority({LIVE_TRADING_ENABLED:"true",MEXC_WRITE_PROVIDER_ENABLED:"true"},{...authority,killSwitchesClear:false}));assert.throws(()=>assertMexcWriteAuthority({LIVE_TRADING_ENABLED:"true",MEXC_WRITE_PROVIDER_ENABLED:"true"},{}));assert.doesNotThrow(()=>assertMexcWriteAuthority({LIVE_TRADING_ENABLED:"true",MEXC_WRITE_PROVIDER_ENABLED:"true"},authority));});

test("writer only accepts bounded one-way reductions",async()=>{for(const changed of [{reduceOnly:false},{positionMode:"hedge"},{volume:4},{positionVolume:0},{positionSide:"open-long"}]){let calls=0;const store=new SqliteMexcExecutionLifecycleStore(":memory:"),writer=new ModernMexcReduceOnlyWriter(async()=>{calls++;return response("never")},store,()=>0,0);await assert.rejects(writer.execute({...intent,...changed},credentials),error=>error.kind==="validation");assert.equal(calls,0);store.close();}});

test("pre-write authority is derived from exact fresh server evidence",()=>{const evidence={caller:{userId:"user-1",accountId:"account-1",totpAssured:true},ownership:{userId:"user-1",accountId:"account-1",bindingGeneration:"generation-1",freshUntil:"2023-11-14T22:14:00.000Z"},reconciliation:{userId:"user-1",accountId:"account-1",revision:4,positionId:"991",positionSide:"long",positionMode:"one-way",positionVolume:3,freshUntil:"2023-11-14T22:14:00.000Z",clean:true},risk:{userId:"user-1",accountId:"account-1",revision:3,enabled:true},rollout:{userId:"user-1",accountId:"account-1",revision:2,armed:true},switches:{global:false,user:false},network:{mexcEgressAllowlisted:true}};const authority=composeMexcPreWriteAuthority(intent,evidence,1700000000000);assert.ok(Object.values(authority).every(Boolean));assert.equal(composeMexcPreWriteAuthority(intent,{...evidence,reconciliation:{...evidence.reconciliation,positionId:"992"}},1700000000000).reconciliationClean,false);});

test("source contains only the current create write endpoint and explicitly excludes legacy submit",async()=>{const {readFile}=await import("node:fs/promises"),source=await readFile(new URL("../app/lib/execution/internal/mexc-execution-writer.ts",import.meta.url),"utf8");assert.match(source,/\/api\/v1\/private\/order\/create/);assert.doesNotMatch(source,/\/api\/v1\/private\/order\/submit/);assert.equal((source.match(/method:\s*"POST"/g)||[]).length,1);});

test("real transport is bounded to api.mexc.com and remains injectable",async()=>{const calls=[],transport=createMexcExecutionFetchTransport(async(url,init)=>{calls.push({url,init});return new Response('{"ok":true}',{status:200})});assert.deepEqual(await transport({url:MEXC_EXECUTION_BASE_URL+MEXC_ORDER_CREATE_PATH,method:"POST",headers:{safe:"header"},body:"{}",timeoutMs:100}),{status:200,body:'{"ok":true}'});assert.equal(calls[0].init.redirect,"error");await assert.rejects(transport({url:"https://attacker.invalid/order",method:"POST",headers:{},body:"{}",timeoutMs:100}));});

test("two stores atomically claim one logical delivery",async()=>{const dir=mkdtempSync(join(tmpdir(),"mexc-cas-")),path=join(dir,"l.sqlite");try{let posts=0;let release;const blocked=new Promise(resolve=>{release=resolve});const transport=async request=>{if(request.method==="POST"){posts++;await blocked;return response("one")}return response("one")};const a=new SqliteMexcExecutionLifecycleStore(path),b=new SqliteMexcExecutionLifecycleStore(path),wa=new ModernMexcReduceOnlyWriter(transport,a,()=>1700000000000,0),wb=new ModernMexcReduceOnlyWriter(transport,b,()=>1700000000000,0);const first=wa.execute(intent,credentials);await new Promise(resolve=>setTimeout(resolve,25));const second=wb.execute(intent,credentials);await new Promise(resolve=>setTimeout(resolve,25));assert.equal(posts,1);release();await first;await second.catch(()=>undefined);assert.equal(posts,1);a.close();b.close();}finally{rmSync(dir,{recursive:true,force:true});}});

test("valid older lifecycle replacement permanently poisons the store instance",async()=>{const dir=mkdtempSync(join(tmpdir(),"mexc-replace-")),path=join(dir,"live.sqlite"),old=join(dir,"old.sqlite");try{const store=new SqliteMexcExecutionLifecycleStore(path),writer=new ModernMexcReduceOnlyWriter(async request=>request.method==="POST"?response("one"):response("one"),store,()=>1700000000000,0);await writer.execute(intent,credentials);store.close();copyFileSync(path,old);const reopened=new SqliteMexcExecutionLifecycleStore(path);assert.equal(reopened.isAccountQuarantined("user-1","account-1"),false);renameSync(old,path);assert.throws(()=>reopened.isAccountQuarantined("user-1","account-1"));assert.throws(()=>reopened.isAccountQuarantined("user-1","account-1"));assert.throws(()=>reopened.read("a".repeat(64)));reopened.close();}finally{rmSync(dir,{recursive:true,force:true});}});
