import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import { mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { ModernMexcReduceOnlyWriter,MEXC_EXECUTION_BASE_URL,MEXC_ORDER_CREATE_PATH,MEXC_EXTERNAL_ORDER_PATH,MEXC_EXECUTION_RECV_WINDOW_MS,assertMexcWriteAuthority,createMexcExecutionFetchTransport,mexcExternalOid,readMexcExecutionCredentials } from "../app/lib/execution/internal/mexc-execution-writer.ts";
import { SqliteMexcExecutionLifecycleStore } from "../app/lib/execution/internal/mexc-execution-lifecycle-store.ts";

const credentials={accessKey:"write-access-fixture",secretKey:"write-secret-fixture",generation:"generation-1"};
const intent={userId:"user-1",accountId:"account-1",idempotencyKey:"intent-315",symbol:"BTC_USDT",positionSide:"long",positionMode:"hedge",marginMode:"isolated",positionVolume:3,volume:1,price:65000,leverage:1,reduceOnly:true,bindingGeneration:"generation-1",rolloutRevision:2,riskRevision:3,reconciliationRevision:4};
const response=(id)=>({status:200,body:JSON.stringify({success:true,code:0,data:{orderId:id}})});

test("modern create signs and sends the identical canonical body then immediately reconciles",async()=>{const calls=[],store=new SqliteMexcExecutionLifecycleStore(":memory:"),now=()=>1700000000000,writer=new ModernMexcReduceOnlyWriter(async request=>{calls.push(request);return calls.length===1?response("order-1"):response("order-1")},store,now,0);const result=await writer.execute(intent,credentials);assert.equal(result.state,"reconciled");assert.equal(calls[0].url,MEXC_EXECUTION_BASE_URL+MEXC_ORDER_CREATE_PATH);assert.equal(calls[0].method,"POST");assert.deepEqual(JSON.parse(calls[0].body),{symbol:"BTC_USDT",price:65000,vol:1,side:2,type:1,openType:1,leverage:1,externalOid:mexcExternalOid(intent),reduceOnly:true});assert.equal(calls[0].headers["Request-Time"],"1700000000000");assert.equal(calls[0].headers["Recv-Window"],String(MEXC_EXECUTION_RECV_WINDOW_MS));assert.equal(calls[0].headers.Signature,createHmac("sha256",credentials.secretKey).update(credentials.accessKey+calls[0].headers["Request-Time"]+calls[0].body).digest("hex"));assert.equal(calls[1].url,`${MEXC_EXECUTION_BASE_URL}${MEXC_EXTERNAL_ORDER_PATH}/BTC_USDT/${mexcExternalOid(intent)}`);assert.equal(calls[1].method,"GET");assert.doesNotMatch(JSON.stringify(result),/write-access|write-secret|Signature/);store.close();});

test("ambiguous create reconciles before any retry and restart never produces a second POST",async()=>{const dir=mkdtempSync(join(tmpdir(),"mexc-writer-")),path=join(dir,"l.sqlite");try{let posts=0,gets=0,store=new SqliteMexcExecutionLifecycleStore(path),writer=new ModernMexcReduceOnlyWriter(async request=>{if(request.method==="POST"){posts++;throw new Error("network");}gets++;return response("recovered-1")},store,()=>1700000000000,0);assert.equal((await writer.execute(intent,credentials)).state,"reconciled");store.close();store=new SqliteMexcExecutionLifecycleStore(path);writer=new ModernMexcReduceOnlyWriter(async request=>{if(request.method==="POST")posts++;else gets++;return response("recovered-1")},store,()=>1700000001000,0);assert.equal((await writer.execute(intent,credentials)).state,"reconciled");assert.equal(posts,1);assert.equal(gets,1);store.close();}finally{rmSync(dir,{recursive:true,force:true});}});

test("provider divergence sticks quarantine to the exact account",async()=>{const store=new SqliteMexcExecutionLifecycleStore(":memory:"),writer=new ModernMexcReduceOnlyWriter(async request=>request.method==="POST"?response("accepted"):response("different"),store,()=>1700000000000,0);await assert.rejects(writer.execute(intent,credentials),error=>error.kind==="quarantined");assert.equal(store.isAccountQuarantined("user-1","account-1"),true);assert.equal(store.isAccountQuarantined("user-1","account-2"),false);await assert.rejects(writer.execute({...intent,idempotencyKey:"next"},credentials),error=>error.kind==="quarantined");store.close();});

test("credentials and activation fail closed and cannot alias Account Companion",()=>{const base={MEXC_EXECUTION_ACCESS_KEY:"w",MEXC_EXECUTION_SECRET_KEY:"s",MEXC_EXECUTION_CREDENTIAL_GENERATION:"g"};assert.deepEqual(readMexcExecutionCredentials(base),{accessKey:"w",secretKey:"s",generation:"g"});for(const env of [{},{...base,MEXC_EXECUTION_SECRET_KEY:undefined},{...base,OWNER_MEXC_READONLY_API_KEY:"w"},{...base,OWNER_MEXC_READONLY_API_SECRET:"s"}])assert.throws(()=>readMexcExecutionCredentials(env));const authority={callerAssured:true,ownerBound:true,ownershipFresh:true,reconciliationClean:true,riskEnabled:true,rolloutArmed:true,killSwitchesClear:true,networkAllowlisted:true};assert.throws(()=>assertMexcWriteAuthority({LIVE_TRADING_ENABLED:"false",MEXC_WRITE_PROVIDER_ENABLED:"true"},authority));assert.throws(()=>assertMexcWriteAuthority({LIVE_TRADING_ENABLED:"true",MEXC_WRITE_PROVIDER_ENABLED:"true"},{...authority,killSwitchesClear:false}));assert.doesNotThrow(()=>assertMexcWriteAuthority({LIVE_TRADING_ENABLED:"true",MEXC_WRITE_PROVIDER_ENABLED:"true"},authority));});

test("writer only accepts provable hedge-mode reductions",async()=>{for(const changed of [{reduceOnly:false},{positionMode:"unknown"},{volume:4},{positionVolume:0},{positionSide:"open-long"}]){let calls=0;const store=new SqliteMexcExecutionLifecycleStore(":memory:"),writer=new ModernMexcReduceOnlyWriter(async()=>{calls++;return response("never")},store,()=>0,0);await assert.rejects(writer.execute({...intent,...changed},credentials),error=>error.kind==="validation");assert.equal(calls,0);store.close();}});

test("source contains only the current create write endpoint and explicitly excludes legacy submit",async()=>{const {readFile}=await import("node:fs/promises"),source=await readFile(new URL("../app/lib/execution/internal/mexc-execution-writer.ts",import.meta.url),"utf8");assert.match(source,/\/api\/v1\/private\/order\/create/);assert.doesNotMatch(source,/\/api\/v1\/private\/order\/submit/);assert.equal((source.match(/method:\s*"POST"/g)||[]).length,1);});

test("real transport is bounded to api.mexc.com and remains injectable",async()=>{const calls=[],transport=createMexcExecutionFetchTransport(async(url,init)=>{calls.push({url,init});return new Response('{"ok":true}',{status:200})});assert.deepEqual(await transport({url:MEXC_EXECUTION_BASE_URL+MEXC_ORDER_CREATE_PATH,method:"POST",headers:{safe:"header"},body:"{}",timeoutMs:100}),{status:200,body:'{"ok":true}'});assert.equal(calls[0].init.redirect,"error");await assert.rejects(transport({url:"https://attacker.invalid/order",method:"POST",headers:{},body:"{}",timeoutMs:100}));});
