import assert from "node:assert/strict";
import { createDecipheriv, createHmac } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { assertMfaConfiguration, beginMfaEnrollment, closeAuthDatabaseForTests, completeMfaChallenge, confirmMfaEnrollment, consumeRateLimit, createAccount, createDatabaseSession, createEmailVerificationTokenForUser, createMfaChallenge, databaseSession, disableMfa, getAuthDatabase, getMfaStatus, regenerateRecoveryCodes, verifyCurrentMfa, verifyEmailToken } from "../app/lib/auth-db.ts";
const key=Buffer.alloc(32,7),now=1_800_000_000_000;
function code(secret,time=now){const c=Buffer.alloc(8);c.writeBigUInt64BE(BigInt(Math.floor(time/30000)));const h=createHmac("sha1",secret).update(c).digest(),o=h[19]&15;return String((h.readUInt32BE(o)&0x7fffffff)%1e6).padStart(6,"0")}
async function fixture(fn){const root=await mkdtemp(join(tmpdir(),"dizy-mfa-")),prior={data:process.env.DATA_DIR,key:process.env.MFA_ENCRYPTION_KEY,node:process.env.NODE_ENV};process.env.DATA_DIR=root;process.env.MFA_ENCRYPTION_KEY=key.toString("base64url");process.env.NODE_ENV="test";closeAuthDatabaseForTests();try{const user=await createAccount({email:"mfa@example.test",password:"correct-horse-battery"});verifyEmailToken(createEmailVerificationTokenForUser(user.id).token);await fn(user)}finally{closeAuthDatabaseForTests();if(prior.data===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior.data;if(prior.key===undefined)delete process.env.MFA_ENCRYPTION_KEY;else process.env.MFA_ENCRYPTION_KEY=prior.key;if(prior.node===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=prior.node;await rm(root,{recursive:true,force:true})}}
function secret(){const row=getAuthDatabase().prepare("SELECT secret_ciphertext,nonce,auth_tag FROM mfa_credentials").get(),d=createDecipheriv("aes-256-gcm",key,row.nonce);d.setAAD(Buffer.from("dizytrades:mfa:v1"));d.setAuthTag(row.auth_tag);return Buffer.concat([d.update(row.secret_ciphertext),d.final()])}
test("pending enrollment encrypts its secret and valid TOTP activates MFA",()=>fixture(async user=>{const plaintext=beginMfaEnrollment(user.id),row=getAuthDatabase().prepare("SELECT state,secret_ciphertext FROM mfa_credentials").get();assert.equal(row.state,"pending");assert.equal(Buffer.from(row.secret_ciphertext).includes(Buffer.from(plaintext)),false);assert.equal(confirmMfaEnrollment(user.id,"000000",now),null);const recovery=confirmMfaEnrollment(user.id,code(secret()),now);assert.equal(recovery.length,10);assert.deepEqual(getMfaStatus(user.id),{enabled:true,pending:false})}));
test("challenge is fresh, expiring and single use; recovery is single use",()=>fixture(async user=>{beginMfaEnrollment(user.id);const recovery=confirmMfaEnrollment(user.id,code(secret()),now),challenge=createMfaChallenge(user.id,now);assert.equal(completeMfaChallenge(challenge+"x",code(secret()),now),null);assert.equal(completeMfaChallenge(challenge,code(secret()),now+300001),null);const good=createMfaChallenge(user.id,now);assert.equal(completeMfaChallenge(good,code(secret()),now).user.id,user.id);assert.equal(completeMfaChallenge(good,code(secret()),now),null);const rc=createMfaChallenge(user.id,now);assert.equal(completeMfaChallenge(rc,recovery[0],now).recoveryUsed,true);assert.equal(completeMfaChallenge(createMfaChallenge(user.id,now),recovery[0],now),null)}));
test("recovery regeneration invalidates old codes and disable revokes sessions",()=>fixture(async user=>{beginMfaEnrollment(user.id);const old=confirmMfaEnrollment(user.id,code(secret()),now),token=createDatabaseSession(user,3600);assert.equal(verifyCurrentMfa(user.id,old[0],now),true);const next=regenerateRecoveryCodes(user.id);assert.equal(next.length,10);assert.equal(verifyCurrentMfa(user.id,old[1],now),false);assert.equal(databaseSession(token),null);const token2=createDatabaseSession(user,3600);assert.equal(disableMfa(user.id),true);assert.equal(databaseSession(token2),null)}));
test("production MFA encryption key fails closed",()=>fixture(async user=>{process.env.NODE_ENV="production";delete process.env.MFA_ENCRYPTION_KEY;assert.throws(()=>beginMfaEnrollment(user.id),/MFA_ENCRYPTION_KEY/);process.env.MFA_ENCRYPTION_KEY="short";assert.throws(()=>beginMfaEnrollment(user.id),/MFA_ENCRYPTION_KEY/)}));
test("active MFA cannot be downgraded by beginning password-only enrollment again",()=>fixture(async user=>{beginMfaEnrollment(user.id);const recovery=confirmMfaEnrollment(user.id,code(secret()),now),before=getAuthDatabase().prepare("SELECT state,hex(secret_ciphertext) secret,(SELECT count(*) FROM mfa_recovery_codes WHERE user_id=?) recovery_count FROM mfa_credentials WHERE user_id=?").get(user.id,user.id);assert.throws(()=>beginMfaEnrollment(user.id),/MFA_ALREADY_ACTIVE/);const after=getAuthDatabase().prepare("SELECT state,hex(secret_ciphertext) secret,(SELECT count(*) FROM mfa_recovery_codes WHERE user_id=?) recovery_count FROM mfa_credentials WHERE user_id=?").get(user.id,user.id);assert.deepEqual(after,before);assert.equal(verifyCurrentMfa(user.id,recovery[0],now),true)}));
test("exact configured SESSION_SECRET reuse as the MFA key fails closed",()=>fixture(async()=>{process.env.NODE_ENV="production";process.env.SESSION_SECRET=process.env.MFA_ENCRYPTION_KEY;assert.throws(()=>assertMfaConfiguration(),/must not reuse/);delete process.env.SESSION_SECRET}));
test("persisted MFA proof buckets are bounded without proof material in keys",()=>fixture(async user=>{const keys=[`mfa:disable:user:${user.id}`,"mfa:disable:ip:203.0.113.20"];for(let i=0;i<5;i++)assert.equal(consumeRateLimit(keys,5,60_000),false);assert.equal(consumeRateLimit(keys,5,60_000),true);const rows=getAuthDatabase().prepare("SELECT bucket FROM auth_attempts").all();assert.equal(rows.length,2);assert.equal(JSON.stringify(rows).includes("123456"),false)}));
