import test from "node:test";import assert from "node:assert/strict";import {parseDepthLevels,parseDepthMessage,parseDepthSnapshot,parseDepthCommits} from "../app/lib/order-flow/mexc-depth.ts";import {OrderBook} from "../app/lib/order-flow/order-book.ts";import {calculateImbalance} from "../app/lib/order-flow/imbalance.ts";import {FlowAggregator,bubbleRadius} from "../app/lib/order-flow/aggregator.ts";import {fractionalLogicalIndex,normalizeExchangeTimestamp,containingCandleIndex,candleCloseMs} from "../app/lib/order-flow/time-projection.ts";import {parseMexcDeals,parseMexcRecentDeals} from "../app/lib/market/realtime.ts";
test("MEXC depth tuple uses documented price, count, quantity ordering",()=>{const level=parseDepthLevels([[411.8,10,1]])[0];assert.deepEqual(level,{price:411.8,orderCount:10,contractQuantity:1})});
test("official snapshot and recovery commits preserve tuple semantics",()=>{const snapshot=parseDepthSnapshot({data:{version:7,timestamp:10,bids:[[411.8,10,1]],asks:[]}},"SOL_USDT");assert.equal(snapshot?.bids[0].contractQuantity,1);const commits=parseDepthCommits({data:[{version:8,ts:11,bids:[],asks:[[412,2,3]]}]},"SOL_USDT");assert.equal(commits[0].asks[0].orderCount,2);assert.equal(commits[0].asks[0].contractQuantity,3)});
test("depth rejects wrong symbols and malformed values",()=>{assert.equal(parseDepthMessage({channel:"push.depth",symbol:"ETH_USDT",data:{version:1,cts:2,bids:[],asks:[]}},"BTC_USDT"),null);assert.deepEqual(parseDepthLevels([[0,1,2],[1,-1,2],null]),[])});
test("book applies absolute sequential quantities and deletes zero",()=>{const b=new OrderBook();b.snapshot({symbol:"BTC_USDT",version:1,engineTimeMs:1,bids:[{price:10,orderCount:1,contractQuantity:2}],asks:[]});assert.equal(b.update({symbol:"BTC_USDT",version:2,engineTimeMs:2,bids:[{price:10,orderCount:0,contractQuantity:0}],asks:[]}),"applied");assert.equal(b.view().bids.length,0);assert.equal(b.update({symbol:"BTC_USDT",version:2,engineTimeMs:2,bids:[],asks:[]}),"ignored");assert.equal(b.update({symbol:"BTC_USDT",version:4,engineTimeMs:4,bids:[],asks:[]}),"gap");assert.equal(b.view().valid,false)});
test("book preserves and drains updates received before its snapshot",()=>{const b=new OrderBook();assert.equal(b.update({symbol:"BTC_USDT",version:3,engineTimeMs:3,bids:[{price:9,orderCount:1,contractQuantity:4}],asks:[]}),"buffered");assert.equal(b.update({symbol:"BTC_USDT",version:2,engineTimeMs:2,bids:[{price:10,orderCount:1,contractQuantity:3}],asks:[]}),"buffered");b.snapshot({symbol:"BTC_USDT",version:1,engineTimeMs:1,bids:[],asks:[]});assert.equal(b.view().version,3);assert.equal(b.view().valid,true);assert.deepEqual(b.view().bids.map(level=>level.contractQuantity),[3,4])});
test("commit recovery bridges a gap without discarding the last valid book",()=>{const b=new OrderBook();b.snapshot({symbol:"BTC_USDT",version:1,engineTimeMs:1,bids:[{price:10,orderCount:1,contractQuantity:1}],asks:[]});assert.equal(b.update({symbol:"BTC_USDT",version:3,engineTimeMs:3,bids:[],asks:[]}),"gap");assert.equal(b.view().bids.length,1);assert.equal(b.update({symbol:"BTC_USDT",version:2,engineTimeMs:2,bids:[],asks:[]}),"applied");assert.equal(b.view().version,3);assert.equal(b.view().valid,true)});
test("deal fields, side and contract conversion are preserved",()=>{const [d]=parseMexcDeals({channel:"push.deal",symbol:"BTC_USDT",data:{p:100,v:3,T:2,O:1,i:"abc",t:10,cts:11}},"BTC_USDT",.01);assert.equal(d.side,"sell");assert.equal(d.tradeId,"abc");assert.equal(d.baseQuantity,.03);assert.equal(d.notional,3);assert.equal(d.engineTimeMs,11);assert.equal(d.timeMs,11)});
test("imbalance supports empty and level selections",()=>{assert.equal(calculateImbalance({valid:true,version:1,bids:[],asks:[]},1,{kind:"levels",value:10})?.imbalance,0);const value=calculateImbalance({valid:true,version:1,bids:[{price:10,orderCount:1,contractQuantity:2}],asks:[{price:11,orderCount:1,contractQuantity:1}]},1,{kind:"levels",value:10})?.imbalance??0;assert.ok(Math.abs(value-(100/31*9))<Number.EPSILON*20)});
test("aggregation deduplicates and projection is fractional",()=>{const a=new FlowAggregator();const d={symbol:"BTC_USDT",price:10,timeMs:30_000,volume:1,tradeId:"1",contractQuantity:1,side:"buy",openClose:null,engineTimeMs:30_000,selfTrade:null,baseQuantity:1,notional:10};assert.equal(a.addDeal(d),true);assert.equal(a.addDeal(d),false);assert.equal(a.bubbles[0].buyNotional,10);assert.equal(fractionalLogicalIndex(30_000,0,4,"1m"),4.5);assert.equal(bubbleRadius(1,10),0)});

test("commit parser sorts ascending and removes duplicate versions",()=>{const commits=parseDepthCommits({data:[{version:4,ts:4,bids:[],asks:[]},{version:2,ts:2,bids:[],asks:[]},{version:4,ts:5,bids:[],asks:[]}]},"BTC_USDT");assert.deepEqual(commits.map(v=>v.version),[2,4])});
test("bridge accepts exact contiguous versions and rejects a missing version",()=>{const update=version=>({symbol:"BTC_USDT",version,engineTimeMs:version,bids:[],asks:[]});const exact=new OrderBook();exact.snapshot(update(10));assert.equal(exact.bridge([update(12),update(11),update(12)]),true);assert.equal(exact.view().version,12);const missing=new OrderBook();missing.snapshot(update(10));assert.equal(missing.bridge([update(12)]),false);assert.equal(missing.view().version,10)});
test("exchange timestamp normalisation accepts seconds and milliseconds",()=>{const now=Date.UTC(2026,6,27);assert.equal(normalizeExchangeTimestamp(now/1000,now),now);assert.equal(normalizeExchangeTimestamp(now,now),now);assert.equal(normalizeExchangeTimestamp(1,now),null);assert.equal(normalizeExchangeTimestamp(now+600_000,now),null)});
test("projection rejects out-of-range events instead of clamping",()=>{const base=Date.UTC(2026,0,1)/1000,candles=[{time:base},{time:base+300}];assert.equal(containingCandleIndex(candles,(base-1)*1000,"5m"),-1);assert.equal(containingCandleIndex(candles,(base+600)*1000,"5m"),-1);assert.equal(containingCandleIndex([{time:base},{time:base+900}],(base+600)*1000,"5m"),-1)});
test("events project to containing native candles",()=>{const base=Date.UTC(2026,0,1)/1000;for(const frame of ["1m","5m","15m","1h","4h","1d","1M"]){const close=candleCloseMs(base,frame),event=base*1000+(close-base*1000)/2;assert.equal(containingCandleIndex([{time:base}],event,frame),0,frame);assert.equal(containingCandleIndex([{time:base}],close,frame),-1,`${frame} close is exclusive`)}});

test("trade aggregates retain notional delta and VWAP coordinates",()=>{const flow=new FlowAggregator({priceStep:100});const deal=(id,side,notional,timeMs,price)=>({tradeId:id,side,notional,timeMs,price,symbol:"BTC_USDT",baseQuantity:notional/price,contractQuantity:notional/price});flow.addDeal(deal("a","buy",100,1000,100),5000,100);flow.addDeal(deal("b","sell",300,3000,110),5000,100);const dot=flow.bubbles[0];assert.equal(dot.timeMs,2500);assert.equal(dot.price,107.5);assert.equal(dot.buyNotional-dot.sellNotional,-200)});
test("recent REST deals share websocket composite IDs and contract notional",()=>{const payload={data:[{p:100,v:3,T:1,t:1700000000000}]};const [rest]=parseMexcRecentDeals(payload,"BTC_USDT",.01);const [ws]=parseMexcDeals({channel:"push.deal",symbol:"BTC_USDT",data:payload.data},"BTC_USDT",.01);assert.equal(rest.notional,3);const flow=new FlowAggregator();assert.equal(flow.addDeal(rest),true);assert.equal(flow.addDeal(ws),false)});
test("feed age classification never initiates recovery for a merely stale valid book",async()=>{const {feedAgeStatus}=await import("../app/lib/order-flow/lifecycle.ts");assert.equal(feedAgeStatus(1000),"Live");assert.equal(feedAgeStatus(3000),"Delayed");assert.equal(feedAgeStatus(6000),"Stale")});
