import test from "node:test";
import assert from "node:assert/strict";
import { authoritativeRiskPrice, displayPrice, emptyPriceSnapshot, markPriceFreshness, mergePriceSnapshot, parseMexcPriceMessage } from "../app/lib/market/price-sources.ts";
import { sanitiseTerminalSettings } from "../app/lib/config.ts";

const key="mexc:futures:BTC_USDT";
test("MEXC Fair and Index messages validate positive finite values and exchange timestamps",()=>{assert.deepEqual(parseMexcPriceMessage({channel:"push.fair.price",data:{symbol:"BTC_USDT",fairPrice:"99.5",timestamp:123}},key,"BTC_USDT",999),{instrumentKey:key,fairPrice:{value:99.5,exchangeTimestampMs:123000,state:"live"}});assert.equal(parseMexcPriceMessage({channel:"push.index.price",data:{symbol:"BTC_USDT",indexPrice:"NaN"}},key,"BTC_USDT"),null);assert.equal(parseMexcPriceMessage({channel:"push.fair.price",data:{symbol:"ETH_USDT",fairPrice:99}},key,"BTC_USDT"),null);});
test("malformed updates preserve last valid values and unavailable sources remain explicit",()=>{let value=emptyPriceSnapshot(key);value=mergePriceSnapshot(value,parseMexcPriceMessage({data:{symbol:"BTC_USDT",lastPrice:100,fairPrice:99}},key,"BTC_USDT",1000));value=mergePriceSnapshot(value,parseMexcPriceMessage({channel:"push.fair.price",data:{symbol:"BTC_USDT",fairPrice:-1}},key,"BTC_USDT",2000));assert.equal(value.fairPrice.value,99);assert.equal(value.indexPrice.state,"unavailable");assert.equal(markPriceFreshness(value,32_000,30_000).fairPrice.state,"stale");});
test("display selection never changes authoritative Fair risk price",()=>{const snapshot=mergePriceSnapshot(emptyPriceSnapshot(key),parseMexcPriceMessage({data:{symbol:"BTC_USDT",lastPrice:100,fairPrice:99,indexPrice:98}},key,"BTC_USDT",1000));assert.equal(displayPrice(snapshot,"index").value,98);assert.deepEqual(authoritativeRiskPrice(snapshot),{value:99,exchangeTimestampMs:1000,state:"live",source:"fair"});});
test("risk price uses an explicit Last fallback only when Fair is unavailable",()=>{const snapshot=mergePriceSnapshot(emptyPriceSnapshot(key),parseMexcPriceMessage({data:{symbol:"BTC_USDT",lastPrice:100}},key,"BTC_USDT",1000));assert.deepEqual(authoritativeRiskPrice(snapshot),{value:100,exchangeTimestampMs:1000,state:"fallback",source:"last"});assert.equal(authoritativeRiskPrice(emptyPriceSnapshot(key)).state,"unavailable");});
test("display source defaults, persists, and sanitises through profiles",()=>{assert.equal(sanitiseTerminalSettings({}).view.selectedDisplayPriceSource,"last");assert.equal(sanitiseTerminalSettings({view:{selectedDisplayPriceSource:"fair"}}).view.selectedDisplayPriceSource,"fair");assert.equal(sanitiseTerminalSettings({view:{selectedDisplayPriceSource:"bogus"}}).view.selectedDisplayPriceSource,"last");});
