import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { authenticateDatabaseUserDetailed, closeAuthDatabaseForTests, createDatabaseSession, createPasswordResetTokenForEmail, databaseSession, getAuthDatabase, getMfaStatus, migratePrivilegedAccounts, resetPasswordWithToken } from "../app/lib/auth-db.ts";
import { authenticateUserDetailed } from "../app/lib/auth-authentication.ts";
import { createSessionToken, parseSessionToken, VIEWER_USER } from "../app/lib/auth-session.ts";

const oldOwner="owner migration password",oldFriend="friend migration password",nextFriend="friend replacement password";
let root;
test.beforeEach(async()=>{root=await mkdtemp(join(tmpdir(),"dizy-privileged-"));process.env.DATA_DIR=root;process.env.NODE_ENV="test";process.env.ROB_EMAIL="owner-migration@example.test";process.env.FRIEND_EMAIL="friend-migration@example.test";process.env.ROB_PASSWORD=oldOwner;process.env.FRIEND_PASSWORD=oldFriend;process.env.ROB_NAME="Configured Owner";process.env.FRIEND_NAME="Configured Admin";process.env.LEGACY_AUTH_FALLBACK_ENABLED="true";process.env.ALLOW_TEST_PLAINTEXT_PASSWORDS="true";process.env.LIVE_TRADING_ENABLED="false";closeAuthDatabaseForTests()});
test.afterEach(async()=>{closeAuthDatabaseForTests();for(const key of ["ROB_EMAIL","FRIEND_EMAIL","ROB_PASSWORD","FRIEND_PASSWORD","ROB_NAME","FRIEND_NAME","LEGACY_AUTH_FALLBACK_ENABLED","ALLOW_TEST_PLAINTEXT_PASSWORDS"])delete process.env[key];await rm(root,{recursive:true,force:true})});

test("migration creates stable verified owner/admin identities with modern hashes and is restart-safe",async()=>{assert.equal((await migratePrivilegedAccounts()).status,"migrated");const rows=getAuthDatabase().prepare("SELECT id,email,display_name,role,email_verified_at,password_hash FROM users ORDER BY id").all();assert.deepEqual(rows.map(({id,role})=>({id,role})),[{id:"friend",role:"admin"},{id:"rob",role:"owner"}]);assert.ok(rows.every(row=>row.email_verified_at&&row.password_hash.startsWith("scrypt$v=1$")));const bytes=await readFile(join(root,"auth.sqlite"));assert.equal(bytes.includes(Buffer.from(oldOwner)),false);assert.equal(bytes.includes(Buffer.from(oldFriend)),false);const originalHash=rows.find(row=>row.id==="friend").password_hash;getAuthDatabase().prepare("UPDATE users SET password_hash=? WHERE id='friend'").run("scrypt$changed-authoritative");closeAuthDatabaseForTests();delete process.env.ROB_PASSWORD;delete process.env.FRIEND_PASSWORD;assert.equal((await migratePrivilegedAccounts()).status,"completed");assert.equal(getAuthDatabase().prepare("SELECT password_hash FROM users WHERE id='friend'").get().password_hash,"scrypt$changed-authoritative");assert.notEqual(originalHash,"scrypt$changed-authoritative")});

test("completed migration rejects legacy privileged sessions while preserving viewer sessions",async()=>{const owner={id:"rob",name:"Configured Owner",email:process.env.ROB_EMAIL,role:"owner"};const legacyOwner=createSessionToken(owner,3600),viewer=createSessionToken(VIEWER_USER,3600);assert.deepEqual(parseSessionToken(legacyOwner),owner);assert.deepEqual(parseSessionToken(viewer),VIEWER_USER);assert.equal((await migratePrivilegedAccounts()).status,"migrated");assert.equal(parseSessionToken(legacyOwner),null);assert.deepEqual(parseSessionToken(viewer),VIEWER_USER);delete process.env.ROB_PASSWORD;delete process.env.FRIEND_PASSWORD;closeAuthDatabaseForTests();assert.equal((await migratePrivilegedAccounts()).status,"completed");assert.equal(parseSessionToken(legacyOwner),null)});

test("Nick-style reset revokes sessions and the old environment password cannot bypass the database",async()=>{await migratePrivilegedAccounts();const login=await authenticateUserDetailed(process.env.FRIEND_EMAIL,oldFriend);assert.equal(login.status,"authenticated");assert.equal(login.user.id,"friend");assert.equal(login.credentialSource,"database");assert.deepEqual(getMfaStatus("friend"),{enabled:false,pending:false});const token=createDatabaseSession(login.user,3600);assert.ok(databaseSession(token));const reset=createPasswordResetTokenForEmail(process.env.FRIEND_EMAIL);assert.ok(reset);assert.equal(await resetPasswordWithToken(reset.token,nextFriend),true);assert.equal(databaseSession(token),null);assert.equal((await authenticateUserDetailed(process.env.FRIEND_EMAIL,oldFriend)).status,"invalid");assert.equal((await authenticateDatabaseUserDetailed(process.env.FRIEND_EMAIL,nextFriend)).status,"authenticated");assert.equal((await migratePrivilegedAccounts()).status,"completed");assert.equal((await authenticateUserDetailed(process.env.FRIEND_EMAIL,oldFriend)).status,"invalid")});

test("completed migration keeps database emails authoritative and protects the bootstrap alias",async()=>{await migratePrivilegedAccounts();const bootstrapEmail=process.env.FRIEND_EMAIL;const changedEmail="friend-changed@example.test";getAuthDatabase().prepare("UPDATE users SET email=?,email_normalized=? WHERE id='friend'").run(changedEmail,changedEmail);process.env.FRIEND_EMAIL="stale-config@example.test";delete process.env.ROB_PASSWORD;delete process.env.FRIEND_PASSWORD;assert.equal((await migratePrivilegedAccounts()).status,"completed");assert.equal((await authenticateUserDetailed(changedEmail,oldFriend)).status,"authenticated");assert.equal((await authenticateUserDetailed(bootstrapEmail,oldFriend)).status,"invalid");assert.equal((await authenticateUserDetailed("friend",oldFriend)).status,"invalid")});

test("completed migration does not require bootstrap environment identity values",async()=>{await migratePrivilegedAccounts();for(const key of ["ROB_EMAIL","FRIEND_EMAIL","ROB_PASSWORD","FRIEND_PASSWORD"])delete process.env[key];closeAuthDatabaseForTests();assert.equal((await migratePrivilegedAccounts()).status,"completed");assert.equal((await authenticateUserDetailed("owner-migration@example.test",oldOwner)).status,"authenticated")});

test("conflicting public identity fails closed without insertion or elevation",async()=>{const db=getAuthDatabase();db.prepare("INSERT INTO users(id,username,username_normalized,email,email_normalized,password_hash,display_name,role,created_at,email_verified_at) VALUES('public','rob','rob',?,?,'scrypt$invalid','Public','user',datetime('now'),datetime('now'))").run(process.env.ROB_EMAIL,process.env.ROB_EMAIL);await assert.rejects(migratePrivilegedAccounts(),/CONFLICT/);assert.equal(db.prepare("SELECT role FROM users WHERE id='public'").get().role,"user");assert.equal(db.prepare("SELECT count(*) n FROM users WHERE id IN ('rob','friend')").get().n,0);assert.equal(db.prepare("SELECT count(*) n FROM privileged_account_migrations").get().n,0)});
