import type { CanvasRenderingTarget2D } from "fancy-canvas";
import type { IPrimitivePaneRenderer,IPrimitivePaneView,ISeriesPrimitive,Logical,SeriesAttachedParameter,Time } from "lightweight-charts";
import type { Candle } from "../strategy.ts";
import { aggregateTrades,bubbleComposition,bubbleRadius,bubbleThreshold } from "../order-flow/aggregator.ts";
import { percentile } from "../order-flow/normalisation.ts";
import { candleCloseMs,timestampToLogicalPosition } from "../order-flow/time-projection.ts";
import type { FlowRenderDiagnostics,FlowRenderStore } from "../order-flow/render-store.ts";
import type { CandleTimeframe } from "../market/types.ts";

type Attached=SeriesAttachedParameter<Time,"Candlestick">;
const rgba=(hex:string,alpha:number)=>{const value=parseInt(hex.slice(1),16);return `rgba(${value>>16},${value>>8&255},${value&255},${alpha})`};
const blendHex=(from:string,to:string,ratio:number)=>{const a=parseInt(from.slice(1),16),b=parseInt(to.slice(1),16),mix=(shift:number)=>Math.round(((a>>shift)&255)*(1-ratio)+((b>>shift)&255)*ratio);return `rgb(${mix(16)},${mix(8)},${mix(0)})`};
class FlowRenderer implements IPrimitivePaneRenderer {constructor(private owner:DizyFlowPrimitive){}draw(target:CanvasRenderingTarget2D){/* Lightweight Charts projections are CSS/media pixels, so every primitive dimension is painted in media space. */target.useMediaCoordinateSpace(({context,mediaSize})=>this.owner.paint(context,mediaSize.width,mediaSize.height));}}
class FlowPaneView implements IPrimitivePaneView {private painter:FlowRenderer;constructor(owner:DizyFlowPrimitive){this.painter=new FlowRenderer(owner)}zOrder(){return "bottom" as const}renderer(){return this.painter}}

/** One stable bottom-pane primitive. All retained input remains in time/price coordinates. */
export class DizyFlowPrimitive implements ISeriesPrimitive<Time> {
 private attachedApi:Attached|null=null;private unsubscribe:(()=>void)|null=null;private candles:readonly Candle[]=[];private timeframe:CandleTimeframe="15m";private projectionGeneration=0;private views:readonly IPrimitivePaneView[]=[new FlowPaneView(this)];
 constructor(private store:FlowRenderStore){}
 attached(param:Attached){this.attachedApi=param;this.unsubscribe=this.store.subscribe(param.requestUpdate);this.store.updateDiagnostics({primitiveAttached:true});param.requestUpdate()}
 detached(){this.unsubscribe?.();this.unsubscribe=null;this.attachedApi=null;this.store.updateDiagnostics({primitiveAttached:false})}
 paneViews(){return this.views}
 setProjection(candles:readonly Candle[],timeframe:CandleTimeframe,generation:number,series:{count:number;finalTime:number|null;generation:number}){const finalTime=candles.at(-1)?.time??null;if(generation!==series.generation||candles.length!==series.count||finalTime!==series.finalTime||generation<this.projectionGeneration)return false;this.candles=candles;this.timeframe=timeframe;this.projectionGeneration=generation;this.store.updateDiagnostics({candleCount:candles.length});this.attachedApi?.requestUpdate();return true}
 paint(context:CanvasRenderingContext2D,width:number,height:number){
  const api=this.attachedApi,s=this.store.getSnapshot(),settings=s.settings,base:Partial<FlowRenderDiagnostics>={renderEnabled:s.enabled,heatmapVisible:settings.heatmapVisible,bubblesVisible:settings.bubblesVisible,candleCount:this.candles.length,heatmapObservationsRetained:s.heatmap.length,rawTradesRetained:s.trades.length,currentPriceStep:settings.heatmap.priceMode==="fixed"?settings.heatmap.fixedPriceStep:s.priceStep,lastRendererError:null};
  try{
   if(!api||!s.enabled||!this.candles.length){this.store.updateDiagnostics({...base,failure:!api?"primitive detached":!s.enabled?"render disabled":"no candles"});return}const range=api.chart.timeScale().getVisibleLogicalRange();if(!range){this.store.updateDiagnostics({...base,failure:"visible logical range unavailable"});return}
   const diagnostics:Partial<FlowRenderDiagnostics>={...base,paintCallCount:this.store.getDiagnostics().paintCallCount+1,visibleLogicalRange:{from:Number(range.from),to:Number(range.to)},heatmapCandidateCells:0,heatmapProjectedCells:0,heatmapCellsDrawn:0,bubbleGroupsProduced:0,bubblesRejectedBelowThreshold:0,bubblesRejectedByTimeProjection:0,bubblesRejectedByPriceProjection:0,bubblesDrawn:0,heatmapDrawnBounds:null,bubbleXCoordinates:[],failure:null};
   const from=Math.max(0,Math.floor(range.from)-1),to=Math.min(this.candles.length-1,Math.ceil(range.to)+1),start=(this.candles[from]?.time??0)*1000,atLiveEdge=range.to>=this.candles.length-.5,end=atLiveEdge?Date.now():candleCloseMs(this.candles[to]?.time??0,this.timeframe);
   const projectX=(timestampMs:number)=>{const logical=timestampToLogicalPosition(this.candles,timestampMs,this.timeframe);if(logical===null||logical<range.from-1||logical>range.to+1)return null;const coordinate=api.chart.timeScale().logicalToCoordinate(logical as Logical);return coordinate!==null&&Number.isFinite(Number(coordinate))&&Number(coordinate)>=0&&Number(coordinate)<=width?Number(coordinate):null};
   context.save();try{context.beginPath();context.rect(0,0,width,height);context.clip();
    if(settings.heatmapVisible){const step=settings.heatmap.priceMode==="fixed"?settings.heatmap.fixedPriceStep:s.priceStep,byTick=new Map<number,Array<(typeof s.heatmap)[number]>>();for(const item of s.heatmap){const list=byTick.get(item.priceTick)??[];list.push(item);byTick.set(item.priceTick,list)}const quantities=s.heatmap.flatMap(v=>[v.bidQuantity,v.askQuantity]).filter(v=>v>0),clip=percentile(quantities,settings.heatmap.percentile)||1;let minX=Infinity,maxX=-Infinity;
     for(const [tick,items] of byTick){items.sort((a,b)=>a.timestampMs-b.timestampMs);for(let i=0;i<items.length;i++){const item=items[i],until=items[i+1]?.timestampMs??end;if(until<=start||item.timestampMs>=end)continue;diagnostics.heatmapCandidateCells=(diagnostics.heatmapCandidateCells??0)+1;const x1=projectX(Math.max(start,item.timestampMs)),x2=projectX(Math.min(end-1,until)),price=tick*step,y=api.series.priceToCoordinate(price),y2=api.series.priceToCoordinate(price+step);if(x1===null||x2===null||y===null||y2===null||!Number.isFinite(Number(y))||!Number.isFinite(Number(y2)))continue;diagnostics.heatmapProjectedCells=(diagnostics.heatmapProjectedCells??0)+1;for(const side of ["bid","ask"] as const){if(settings.heatmap.side!=="both"&&settings.heatmap.side!==(side==="bid"?"bids":"asks"))continue;const quantity=side==="bid"?item.bidQuantity:item.askQuantity;if(quantity<=0||quantity*price<settings.heatmap.minimumNotional)continue;const normal=settings.heatmap.intensity==="log"?Math.log1p(Math.min(quantity,clip))/Math.log1p(clip):Math.min(quantity,clip)/clip,alpha=settings.heatmap.opacity*Math.min(1,settings.heatmap.intensityMultiplier*Math.pow(normal,settings.heatmap.gamma)),left=Math.min(x1,x2),top=Math.min(Number(y),Number(y2))-1,cellWidth=Math.max(1,Math.abs(x2-x1)),cellHeight=Math.max(2,Math.abs(Number(y2)-Number(y))+2);context.fillStyle=rgba(side==="bid"?settings.heatmap.bidColour:settings.heatmap.askColour,alpha);context.fillRect(left,top,cellWidth,cellHeight);minX=Math.min(minX,left);maxX=Math.max(maxX,left+cellWidth);diagnostics.heatmapCellsDrawn=(diagnostics.heatmapCellsDrawn??0)+1;}}}if(Number.isFinite(minX))diagnostics.heatmapDrawnBounds={minX,maxX};}
    if(settings.bubblesVisible){const visible=s.trades.filter(v=>v.timestampMs>=start&&v.timestampMs<end),timeRejected=s.trades.length-visible.length;diagnostics.bubblesRejectedByTimeProjection=timeRejected;let priceRejected=0;const groups=aggregateTrades(visible,projectX,p=>{const y=api.series.priceToCoordinate(p);if(y===null||!Number.isFinite(Number(y))){priceRejected++;return null}return Number(y)}),totals=groups.map(v=>v.buyNotional+v.sellNotional),threshold=bubbleThreshold(totals,settings.bubbles);diagnostics.bubbleGroupsProduced=groups.length;diagnostics.bubblesRejectedByPriceProjection=priceRejected;const xs:number[]=[];for(const bubble of groups){const x=projectX(bubble.timeMs),y=api.series.priceToCoordinate(bubble.price),composition=bubbleComposition(bubble),radius=bubbleRadius(composition.total,threshold,settings.bubbles.minimumRadius,settings.bubbles.maximumRadius);if(!radius){diagnostics.bubblesRejectedBelowThreshold=(diagnostics.bubblesRejectedBelowThreshold??0)+1;continue}if(x===null){diagnostics.bubblesRejectedByTimeProjection=(diagnostics.bubblesRejectedByTimeProjection??0)+1;continue}if(y===null||!Number.isFinite(Number(y))){diagnostics.bubblesRejectedByPriceProjection=(diagnostics.bubblesRejectedByPriceProjection??0)+1;continue}context.globalAlpha=settings.bubbles.opacity;context.fillStyle=blendHex(settings.bubbles.sellColour,settings.bubbles.buyColour,composition.buyRatio);context.beginPath();context.arc(x,Number(y),radius,0,Math.PI*2);context.fill();context.globalAlpha=1;context.strokeStyle=settings.bubbles.outlineColour;context.stroke();xs.push(x);diagnostics.bubblesDrawn=(diagnostics.bubblesDrawn??0)+1}diagnostics.bubbleXCoordinates=xs;}
   }finally{context.restore()}
   if(this.store.getDiagnostics().sourceFeedConnected===false)diagnostics.failure="source feed disconnected";else if(!s.heatmap.length&&!s.trades.length)diagnostics.failure="no depth observations received; no trades received";else if(s.heatmap.length&&!(diagnostics.heatmapProjectedCells??0))diagnostics.failure="observations retained but projection failed";else if((diagnostics.heatmapProjectedCells??0)>0&&!(diagnostics.heatmapCellsDrawn??0))diagnostics.failure="cells projected but painting produced no cells";else if(s.trades.length&&!(diagnostics.bubbleGroupsProduced??0))diagnostics.failure="trades projected outside the visible candle range";else if((diagnostics.bubbleGroupsProduced??0)>0&&!(diagnostics.bubblesDrawn??0))diagnostics.failure="trades received but filtered by threshold or projection";
   this.store.updateDiagnostics(diagnostics);
  }catch(error){this.store.updateDiagnostics({...base,lastRendererError:error instanceof Error?error.message:String(error),failure:"renderer error"});}
 }
}
