import type { CanvasRenderingTarget2D } from "fancy-canvas";
import type { IPrimitivePaneRenderer,IPrimitivePaneView,ISeriesPrimitive,SeriesAttachedParameter,Time } from "lightweight-charts";
import type { Candle } from "../strategy.ts";
import { aggregateTrades,bubbleComposition,bubbleRadius,bubbleThreshold } from "../order-flow/aggregator.ts";
import { percentile } from "../order-flow/normalisation.ts";
import { buildHeatmapSegments,effectiveHeatmapPriceStep } from "../order-flow/heatmap.ts";
import { candleCloseMs,timestampToLogicalPosition } from "../order-flow/time-projection.ts";
import type { FlowRenderDiagnostics,FlowRenderStore } from "../order-flow/render-store.ts";
import type { CandleTimeframe } from "../market/types.ts";

type Attached=SeriesAttachedParameter<Time,"Candlestick">;
const rgba=(hex:string,alpha:number)=>{const value=parseInt(hex.slice(1),16);return `rgba(${value>>16},${value>>8&255},${value&255},${alpha})`};
const blendHex=(from:string,to:string,ratio:number)=>{const a=parseInt(from.slice(1),16),b=parseInt(to.slice(1),16),mix=(shift:number)=>Math.round(((a>>shift)&255)*(1-ratio)+((b>>shift)&255)*ratio);return `rgb(${mix(16)},${mix(8)},${mix(0)})`};
class FlowRenderer implements IPrimitivePaneRenderer {constructor(private owner:DizyFlowPrimitive){}draw(target:CanvasRenderingTarget2D){/* Lightweight Charts projections are CSS/media pixels, so every primitive dimension is painted in media space. */target.useMediaCoordinateSpace(({context,mediaSize})=>this.owner.paint(context,mediaSize.width,mediaSize.height));}}
class FlowPaneView implements IPrimitivePaneView {private painter:FlowRenderer;constructor(owner:DizyFlowPrimitive){this.painter=new FlowRenderer(owner)}zOrder(){return "bottom" as const}renderer(){return this.painter}}

/** One stable bottom-pane primitive. All retained input remains in time/price coordinates. */
export class DizyFlowPrimitive implements ISeriesPrimitive<Time> {
 private attachedApi:Attached|null=null;private unsubscribe:(()=>void)|null=null;private candles:readonly Candle[]=[];private timeframe:CandleTimeframe="15m";private projectionGeneration=0;private views:readonly IPrimitivePaneView[]=[new FlowPaneView(this)];
 constructor(private store:FlowRenderStore){}
 attached(param:Attached){this.attachedApi=param;this.unsubscribe=this.store.subscribe(param.requestUpdate);this.store.updateDiagnostics({primitiveAttached:true});param.requestUpdate()}
 detached(){this.unsubscribe?.();this.unsubscribe=null;this.attachedApi=null;this.store.updateDiagnostics({primitiveAttached:false})}
 paneViews(){return this.views}
 setProjection(candles:readonly Candle[],timeframe:CandleTimeframe,generation:number,series:{count:number;finalTime:number|null;generation:number}){const finalTime=candles.at(-1)?.time??null;if(generation!==series.generation||candles.length!==series.count||finalTime!==series.finalTime||generation<this.projectionGeneration)return false;this.candles=candles;this.timeframe=timeframe;this.projectionGeneration=generation;this.store.updateDiagnostics({candleCount:candles.length});this.attachedApi?.requestUpdate();return true}
 paint(context:CanvasRenderingContext2D,width:number,height:number){
  const api=this.attachedApi,s=this.store.getSnapshot(),settings=s.settings,prices=s.heatmap.map(v=>v.price),heatTimes=s.heatmap.map(v=>v.timestampMs),tradeTimes=s.trades.map(v=>v.timestampMs),base:Partial<FlowRenderDiagnostics>={renderEnabled:s.enabled,heatmapVisible:settings.heatmapVisible,bubblesVisible:settings.bubblesVisible,candleCount:this.candles.length,heatmapObservationsRetained:s.heatmap.length,rawTradesRetained:s.trades.length,currentPriceStep:s.priceStep,capturedDepthPriceRange:prices.length?{min:Math.min(...prices),max:Math.max(...prices)}:null,firstHeatmapTimestamp:heatTimes.length?Math.min(...heatTimes):null,lastHeatmapTimestamp:heatTimes.length?Math.max(...heatTimes):null,firstTradeTimestamp:tradeTimes.length?Math.min(...tradeTimes):null,lastTradeTimestamp:tradeTimes.length?Math.max(...tradeTimes):null,lastRendererError:null};
  try{
   if(!api||!s.enabled||!this.candles.length){this.store.updateDiagnostics({...base,failure:!api?"primitive detached":!s.enabled?"render disabled":"no candles"});return}const range=api.chart.timeScale().getVisibleLogicalRange();if(!range){this.store.updateDiagnostics({...base,failure:"visible logical range unavailable"});return}
   const topPrice=api.series.coordinateToPrice(0),bottomPrice=api.series.coordinateToPrice(height),visiblePrices=topPrice!==null&&bottomPrice!==null?{min:Math.min(topPrice,bottomPrice),max:Math.max(topPrice,bottomPrice)}:null,pricePerPixel=visiblePrices?(visiblePrices.max-visiblePrices.min)/Math.max(1,height):s.priceStep,displayStep=settings.heatmap.priceMode==="fixed"?settings.heatmap.fixedPriceStep:effectiveHeatmapPriceStep(pricePerPixel,s.priceStep),rowY1=api.series.priceToCoordinate(64_000),rowY2=api.series.priceToCoordinate(64_000+displayStep),rowHeight=rowY1===null||rowY2===null?0:Math.abs(Number(rowY2)-Number(rowY1));
   const diagnostics:Partial<FlowRenderDiagnostics>={...base,paintCallCount:this.store.getDiagnostics().paintCallCount+1,visibleLogicalRange:{from:Number(range.from),to:Number(range.to)},visibleChartPriceRange:visiblePrices,exchangeTickSize:s.priceStep,effectiveHeatmapBinSize:displayStep,heatmapRowHeightPx:rowHeight,heatmapCandidateCells:0,heatmapProjectedCells:0,heatmapCellsDrawn:0,bubbleGroupsProduced:0,bubblesRejectedBelowThreshold:0,bubblesRejectedByTimeProjection:0,bubblesRejectedByPriceProjection:0,bubblesDrawn:0,heatmapDrawnBounds:null,bubbleXCoordinates:[],bubbleStableIds:[],stableBubbleGroupsRetained:0,bubbleGroupsVisible:0,heatmapSegmentsRetained:0,heatmapSegmentsProjected:0,heatmapSegmentsDrawn:0,rejectionReasons:{time:0,price:0,threshold:0},failure:null};
   const from=Math.max(0,Math.floor(range.from)-1),to=Math.min(this.candles.length-1,Math.ceil(range.to)+1),start=(this.candles[from]?.time??0)*1000,atLiveEdge=range.to>=this.candles.length-.5,end=atLiveEdge?Math.max(candleCloseMs(this.candles[to]?.time??0,this.timeframe),s.captureEnded??0):candleCloseMs(this.candles[to]?.time??0,this.timeframe);
   const projectX=(timestampMs:number)=>{const logical=timestampToLogicalPosition(this.candles,timestampMs,this.timeframe);if(logical===null||logical<range.from-1||logical>range.to+1)return null;const span=Number(range.to)-Number(range.from);return span>0?(logical-Number(range.from))/span*width:null};
   context.save();try{context.beginPath();context.rect(0,0,width,height);context.clip();
    if(settings.heatmapVisible&&s.captureEnded!==null){const segments=buildHeatmapSegments(s.heatmap,displayStep,start,end,s.captureEnded),quantities=segments.flatMap(v=>[v.bidQuantity,v.askQuantity]).filter(v=>v>0),clip=percentile(quantities,settings.heatmap.percentile)||1;diagnostics.heatmapCandidateCells=segments.length;diagnostics.heatmapSegmentsRetained=segments.length;let minX=Infinity,maxX=-Infinity;
     for(const segment of segments){const x1=projectX(segment.fromMs),x2=projectX(segment.toMs-1),y=api.series.priceToCoordinate(segment.price),y2=api.series.priceToCoordinate(segment.price+displayStep);if(x1===null||x2===null||y===null||y2===null)continue;diagnostics.heatmapProjectedCells=(diagnostics.heatmapProjectedCells??0)+1;diagnostics.heatmapSegmentsProjected=(diagnostics.heatmapSegmentsProjected??0)+1;for(const side of ["bid","ask"] as const){if(settings.heatmap.side!=="both"&&settings.heatmap.side!==(side==="bid"?"bids":"asks"))continue;const quantity=side==="bid"?segment.bidQuantity:segment.askQuantity;if(quantity<=0||quantity*segment.price<settings.heatmap.minimumNotional)continue;const normal=settings.heatmap.intensity==="log"?Math.log1p(Math.min(quantity,clip))/Math.log1p(clip):Math.min(quantity,clip)/clip,alpha=settings.heatmap.opacity*Math.min(1,settings.heatmap.intensityMultiplier*Math.pow(normal,settings.heatmap.gamma)),left=Math.min(x1,x2),top=Math.min(Number(y),Number(y2)),cellWidth=Math.max(1,Math.abs(x2-x1)),cellHeight=Math.max(3,Math.abs(Number(y2)-Number(y)));context.fillStyle=rgba(side==="bid"?settings.heatmap.bidColour:settings.heatmap.askColour,alpha);context.fillRect(left,top,cellWidth,cellHeight);minX=Math.min(minX,left);maxX=Math.max(maxX,left+cellWidth);diagnostics.heatmapCellsDrawn=(diagnostics.heatmapCellsDrawn??0)+1;diagnostics.heatmapSegmentsDrawn=(diagnostics.heatmapSegmentsDrawn??0)+1;}}if(Number.isFinite(minX))diagnostics.heatmapDrawnBounds={minX,maxX};}
    if(settings.bubblesVisible){const bubbleStep=settings.bubbles.priceMode==="fixed"?settings.bubbles.fixedPriceStep:s.priceStep,groups=aggregateTrades(s.trades,s.generation||"UNKNOWN",settings.bubbles.timeBucketMs,bubbleStep),visible=groups.filter(v=>v.timeMs>=start&&v.timeMs<end),totals=groups.map(v=>v.buyNotional+v.sellNotional),threshold=bubbleThreshold(totals,settings.bubbles),xs:number[]=[];diagnostics.bubbleGroupsProduced=groups.length;diagnostics.stableBubbleGroupsRetained=groups.length;diagnostics.bubbleGroupsVisible=visible.length;diagnostics.bubbleStableIds=groups.map(v=>v.id);for(const bubble of visible){const x=projectX(bubble.timeMs),y=api.series.priceToCoordinate(bubble.price),composition=bubbleComposition(bubble),radius=bubbleRadius(composition.total,threshold,settings.bubbles.minimumRadius,settings.bubbles.maximumRadius);if(!radius){diagnostics.bubblesRejectedBelowThreshold=(diagnostics.bubblesRejectedBelowThreshold??0)+1;continue}if(x===null){diagnostics.bubblesRejectedByTimeProjection=(diagnostics.bubblesRejectedByTimeProjection??0)+1;continue}if(y===null||!Number.isFinite(Number(y))){diagnostics.bubblesRejectedByPriceProjection=(diagnostics.bubblesRejectedByPriceProjection??0)+1;continue}context.save();context.globalAlpha=settings.bubbles.opacity;context.fillStyle=blendHex(settings.bubbles.sellColour,settings.bubbles.buyColour,composition.buyRatio);context.beginPath();context.arc(x,Number(y),radius,0,Math.PI*2);context.fill();context.globalAlpha=Math.min(settings.bubbles.opacity*1.5,1);context.strokeStyle=settings.bubbles.outlineColour;context.stroke();context.restore();xs.push(x);diagnostics.bubblesDrawn=(diagnostics.bubblesDrawn??0)+1}diagnostics.bubbleXCoordinates=xs;diagnostics.rejectionReasons={time:groups.length-visible.length,price:diagnostics.bubblesRejectedByPriceProjection??0,threshold:diagnostics.bubblesRejectedBelowThreshold??0};}
   }finally{context.restore()}
   if(this.store.getDiagnostics().sourceFeedConnected===false)diagnostics.failure="source feed disconnected";else if(!s.heatmap.length&&!s.trades.length)diagnostics.failure="no depth observations received; no trades received";else if(s.heatmap.length&&!(diagnostics.heatmapProjectedCells??0))diagnostics.failure="observations retained but projection failed";else if(s.trades.length&&!(diagnostics.bubbleGroupsProduced??0))diagnostics.failure="trades projected outside the visible candle range";
   this.store.updateDiagnostics(diagnostics);
  }catch(error){this.store.updateDiagnostics({...base,lastRendererError:error instanceof Error?error.message:String(error),failure:"renderer error"});}
 }
}
