import type { CanvasRenderingTarget2D } from "fancy-canvas";
import type { IPrimitivePaneRenderer,IPrimitivePaneView,ISeriesPrimitive,SeriesAttachedParameter,Time } from "lightweight-charts";
import type { Candle } from "../strategy.ts";
import { aggregateTrades,bubbleComposition,bubbleRadius,bubbleThreshold } from "../order-flow/aggregator.ts";
import { percentile } from "../order-flow/normalisation.ts";
import { effectiveHeatmapPriceStep } from "../order-flow/heatmap.ts";
import { candleCloseMs,timestampToLogicalPosition } from "../order-flow/time-projection.ts";
import type { FlowRenderDiagnostics,FlowRenderStore } from "../order-flow/render-store.ts";
import type { CandleTimeframe } from "../market/types.ts";

type Attached=SeriesAttachedParameter<Time,"Candlestick">;
const blendHex=(from:string,to:string,ratio:number)=>{const a=parseInt(from.slice(1),16),b=parseInt(to.slice(1),16),mix=(shift:number)=>Math.round(((a>>shift)&255)*(1-ratio)+((b>>shift)&255)*ratio);return `rgb(${mix(16)},${mix(8)},${mix(0)})`};
const HEAT_STOPS=[[0,"#07152f"],[.2,"#064fb5"],[.42,"#00cde8"],[.65,"#ffe34d"],[.83,"#ff6a24"],[1,"#fffbd1"]] as const;
const heatColour=(value:number)=>{const n=Math.max(0,Math.min(1,value));let i=1;while(i<HEAT_STOPS.length&&n>HEAT_STOPS[i][0])i++;const [a,ac]=HEAT_STOPS[i-1],[b,bc]=HEAT_STOPS[Math.min(i,HEAT_STOPS.length-1)];return blendHex(ac,bc,b===a?0:(n-a)/(b-a))};
class FlowRenderer implements IPrimitivePaneRenderer {constructor(private owner:DizyFlowPrimitive){}draw(target:CanvasRenderingTarget2D){/* Lightweight Charts projections are CSS/media pixels, so every primitive dimension is painted in media space. */target.useMediaCoordinateSpace(({context,mediaSize})=>this.owner.paint(context,mediaSize.width,mediaSize.height));}}
class FlowPaneView implements IPrimitivePaneView {private painter:FlowRenderer;constructor(owner:DizyFlowPrimitive){this.painter=new FlowRenderer(owner)}zOrder(){return "bottom" as const}renderer(){return this.painter}}

/** One stable bottom-pane primitive. All retained input remains in time/price coordinates. */
export class DizyFlowPrimitive implements ISeriesPrimitive<Time> {
 private attachedApi:Attached|null=null;private unsubscribe:(()=>void)|null=null;private candles:readonly Candle[]=[];private timeframe:CandleTimeframe="15m";private projectionGeneration=0;private heatSurface:HTMLCanvasElement|null=null;private heatSignature="";private heatStaticSignature="";private fullRebuilds=0;private incrementalPatches=0;private surfaceReuses=0;private retainedMetrics:Partial<FlowRenderDiagnostics>={};private views:readonly IPrimitivePaneView[]=[new FlowPaneView(this)];
 constructor(private store:FlowRenderStore){}
 attached(param:Attached){this.attachedApi=param;this.unsubscribe=this.store.subscribe(param.requestUpdate);this.store.updateDiagnostics({primitiveAttached:true});param.requestUpdate()}
 detached(){this.unsubscribe?.();this.unsubscribe=null;this.attachedApi=null;this.store.updateDiagnostics({primitiveAttached:false})}
 paneViews(){return this.views}
 setProjection(candles:readonly Candle[],timeframe:CandleTimeframe,generation:number,series:{count:number;finalTime:number|null;generation:number}){const finalTime=candles.at(-1)?.time??null;if(generation!==series.generation||candles.length!==series.count||finalTime!==series.finalTime||generation<this.projectionGeneration)return false;this.candles=candles;this.timeframe=timeframe;this.projectionGeneration=generation;this.store.updateDiagnostics({candleCount:candles.length});this.attachedApi?.requestUpdate();return true}
 paint(context:CanvasRenderingContext2D,width:number,height:number){
  const api=this.attachedApi,s=this.store.getSnapshot(),settings=s.settings,prices=s.heatmapTiles.map(v=>v.price),heatTimes=s.heatmapTiles.flatMap(v=>[v.fromMs,v.toMs]),tradeTimes=s.trades.map(v=>v.timestampMs),base:Partial<FlowRenderDiagnostics>={renderEnabled:s.enabled,heatmapVisible:settings.heatmapVisible,bubblesVisible:settings.bubblesVisible,candleCount:this.candles.length,heatmapObservationsRetained:s.heatmapTiles.length,rawTradesRetained:s.trades.length,currentPriceStep:s.priceStep,capturedDepthPriceRange:prices.length?{min:Math.min(...prices),max:Math.max(...prices)}:null,firstHeatmapTimestamp:heatTimes.length?Math.min(...heatTimes):null,lastHeatmapTimestamp:heatTimes.length?Math.max(...heatTimes):null,firstTradeTimestamp:tradeTimes.length?Math.min(...tradeTimes):null,lastTradeTimestamp:tradeTimes.length?Math.max(...tradeTimes):null,lastRendererError:null};
  try{
   if(!api||!s.enabled||!this.candles.length){this.store.updateDiagnostics({...base,failure:!api?"primitive detached":!s.enabled?"render disabled":"no candles"});return}const range=api.chart.timeScale().getVisibleLogicalRange();if(!range){this.store.updateDiagnostics({...base,failure:"visible logical range unavailable"});return}
   const topPrice=api.series.coordinateToPrice(0),bottomPrice=api.series.coordinateToPrice(height),visiblePrices=topPrice!==null&&bottomPrice!==null?{min:Math.min(topPrice,bottomPrice),max:Math.max(topPrice,bottomPrice)}:null,pricePerPixel=visiblePrices?(visiblePrices.max-visiblePrices.min)/Math.max(1,height):s.priceStep,displayStep=settings.heatmap.priceMode==="manual"||settings.heatmap.priceMode==="fixed"?settings.heatmap.fixedPriceStep:settings.heatmap.priceMode==="none"?s.priceStep:effectiveHeatmapPriceStep(pricePerPixel,s.priceStep),rowY1=api.series.priceToCoordinate(64_000),rowY2=api.series.priceToCoordinate(64_000+displayStep),rowHeight=rowY1===null||rowY2===null?0:Math.abs(Number(rowY2)-Number(rowY1));
   const diagnostics:Partial<FlowRenderDiagnostics>={...base,paintCallCount:this.store.getDiagnostics().paintCallCount+1,visibleLogicalRange:{from:Number(range.from),to:Number(range.to)},visibleChartPriceRange:visiblePrices,exchangeTickSize:s.priceStep,effectiveHeatmapBinSize:displayStep,heatmapRowHeightPx:rowHeight,heatmapCandidateCells:0,heatmapProjectedCells:0,heatmapCellsDrawn:0,bubbleGroupsProduced:0,bubblesRejectedBelowThreshold:0,bubblesRejectedByTimeProjection:0,bubblesRejectedByPriceProjection:0,bubblesDrawn:0,heatmapDrawnBounds:null,bubbleXCoordinates:[],bubbleStableIds:[],stableBubbleGroupsRetained:0,bubbleGroupsVisible:0,heatmapSegmentsRetained:0,heatmapSegmentsProjected:0,heatmapSegmentsDrawn:0,rejectionReasons:{time:0,price:0,threshold:0},failure:null};
   const from=Math.max(0,Math.floor(range.from)-1),to=Math.min(this.candles.length-1,Math.ceil(range.to)+1),start=(this.candles[from]?.time??0)*1000,atLiveEdge=range.to>=this.candles.length-.5,end=atLiveEdge?Math.max(candleCloseMs(this.candles[to]?.time??0,this.timeframe),s.captureEnded??0):candleCloseMs(this.candles[to]?.time??0,this.timeframe);
   if(visiblePrices)this.store.requestHistory({from:start,to:end,minPrice:visiblePrices.min,maxPrice:visiblePrices.max,effectiveTimeBucketMs:Math.max(5000,Math.ceil((end-start)/Math.max(1,width)/5000)*5000),effectivePriceStep:displayStep});
   const projectX=(timestampMs:number)=>{const logical=timestampToLogicalPosition(this.candles,timestampMs,this.timeframe);if(logical===null||logical<range.from-1||logical>range.to+1)return null;const span=Number(range.to)-Number(range.from);return span>0?(logical-Number(range.from))/span*width:null};
   context.save();try{context.beginPath();context.rect(0,0,width,height);context.clip();
    const staticSignature=JSON.stringify([width,height,Number(range.from).toFixed(3),Number(range.to).toFixed(3),visiblePrices?.min.toPrecision(8),visiblePrices?.max.toPrecision(8),displayStep,settings.heatmap]);
    const heatSignature=`${staticSignature}:${s.generation}:${s.heatmapTiles.length}:${s.captureEnded}`;
    const canRetain=typeof document!=="undefined";if(canRetain&&(!this.heatSurface||this.heatSurface.width!==Math.ceil(width)||this.heatSurface.height!==Math.ceil(height))){this.heatSurface=document.createElement("canvas");this.heatSurface.width=Math.ceil(width);this.heatSurface.height=Math.ceil(height);this.heatSignature=""}
    const rebuildHeatmap=!canRetain||heatSignature!==this.heatSignature;const liveOnly=this.heatStaticSignature===staticSignature&&this.heatSignature!=="";
    const ctx=rebuildHeatmap&&this.heatSurface?(this.heatSurface.getContext("2d")??context):context;if(rebuildHeatmap&&ctx!==context)ctx.clearRect(0,0,width,height);
    if(settings.heatmapVisible&&rebuildHeatmap){const segments=s.heatmapTiles.filter(v=>v.toMs>=start&&v.fromMs<=end),quantities=segments.flatMap(v=>[v.bidQuantity,v.askQuantity]).filter(v=>v>0),lowClip=percentile(quantities,settings.heatmap.lowerPercentile)||0,clip=percentile(quantities,settings.heatmap.upperPercentile)||0;diagnostics.heatmapCandidateCells=segments.length;diagnostics.heatmapSegmentsRetained=segments.length;let minX=Infinity,maxX=-Infinity,minAlpha=Infinity;
     for(const segment of segments){const x1=projectX(segment.fromMs),x2=projectX(segment.toMs-1),y=api.series.priceToCoordinate(segment.price),y2=api.series.priceToCoordinate(segment.price+s.priceStep);if(x1===null||x2===null||y===null||y2===null)continue;diagnostics.heatmapProjectedCells=(diagnostics.heatmapProjectedCells??0)+1;diagnostics.heatmapSegmentsProjected=(diagnostics.heatmapSegmentsProjected??0)+1;for(const side of ["bid","ask"] as const){if(settings.heatmap.side!=="both"&&settings.heatmap.side!==(side==="bid"?"bids":"asks"))continue;const quantity=side==="bid"?segment.bidQuantity:segment.askQuantity;if(quantity<=0||quantity*segment.price<settings.heatmap.minimumNotional)continue;let normal=clip-lowClip<=Number.EPSILON?.55:Math.max(0,Math.min(1,(quantity-lowClip)/(clip-lowClip)));if(settings.heatmap.intensity==="log")normal=Math.log1p(normal*9)/Math.log(10);normal=Math.max(0,Math.min(1,(normal-.5)*settings.heatmap.contrast+.5));normal=Math.min(1,settings.heatmap.brightness*settings.heatmap.intensityMultiplier*Math.pow(normal,settings.heatmap.gamma));const alpha=settings.heatmap.opacity*Math.max(.28,normal),left=Math.min(x1,x2),top=Math.min(Number(y),Number(y2)),cellWidth=Math.max(1,Math.abs(x2-x1)),cellHeight=Math.max(1,Math.abs(Number(y2)-Number(y)));ctx.fillStyle=heatColour(Math.max(.14,normal)).replace("rgb","rgba").replace(")",`,${alpha})`);ctx.fillRect(left,top,cellWidth,cellHeight);minAlpha=Math.min(minAlpha,alpha);minX=Math.min(minX,left);maxX=Math.max(maxX,left+cellWidth);diagnostics.heatmapCellsDrawn=(diagnostics.heatmapCellsDrawn??0)+1;diagnostics.heatmapSegmentsDrawn=(diagnostics.heatmapSegmentsDrawn??0)+1;}}if(Number.isFinite(minX))diagnostics.heatmapDrawnBounds={minX,maxX};if(segments.length&&Number.isFinite(minAlpha)&&minAlpha<.1)diagnostics.failure="heatmap cells are below visible alpha";}
    if(rebuildHeatmap){this.heatSignature=heatSignature;this.heatStaticSignature=staticSignature;if(liveOnly)this.incrementalPatches++;else this.fullRebuilds++;this.retainedMetrics={heatmapCandidateCells:diagnostics.heatmapCandidateCells,heatmapProjectedCells:diagnostics.heatmapProjectedCells,heatmapCellsDrawn:diagnostics.heatmapCellsDrawn,heatmapSegmentsRetained:diagnostics.heatmapSegmentsRetained,heatmapSegmentsProjected:diagnostics.heatmapSegmentsProjected,heatmapSegmentsDrawn:diagnostics.heatmapSegmentsDrawn,heatmapDrawnBounds:diagnostics.heatmapDrawnBounds};}else{this.surfaceReuses++;Object.assign(diagnostics,this.retainedMetrics);}
    if(settings.heatmapVisible&&this.heatSurface)context.drawImage(this.heatSurface,0,0,width,height);
    diagnostics.retainedFullRebuilds=this.fullRebuilds;diagnostics.retainedIncrementalPatches=this.incrementalPatches;diagnostics.retainedSurfaceReuses=this.surfaceReuses;diagnostics.effectiveTimeSliceMs=Math.max(5000,Math.ceil((end-start)/Math.max(1,width)/5000)*5000);
    if(settings.bubblesVisible){const bubbleStep=settings.bubbles.priceMode==="fixed"?settings.bubbles.fixedPriceStep:s.priceStep,groups=aggregateTrades(s.trades,s.generation||"UNKNOWN",settings.bubbles.timeBucketMs,bubbleStep),visible=groups.filter(v=>v.timeMs>=start&&v.timeMs<end),totals=groups.map(v=>v.buyNotional+v.sellNotional),threshold=bubbleThreshold(totals,settings.bubbles),xs:number[]=[];diagnostics.bubbleGroupsProduced=groups.length;diagnostics.stableBubbleGroupsRetained=groups.length;diagnostics.bubbleGroupsVisible=visible.length;diagnostics.bubbleStableIds=groups.map(v=>v.id);for(const bubble of visible){const x=projectX(bubble.timeMs),y=api.series.priceToCoordinate(bubble.price),composition=bubbleComposition(bubble),radius=bubbleRadius(composition.total,threshold,settings.bubbles.minimumRadius,settings.bubbles.maximumRadius);if(!radius){diagnostics.bubblesRejectedBelowThreshold=(diagnostics.bubblesRejectedBelowThreshold??0)+1;continue}if(x===null){diagnostics.bubblesRejectedByTimeProjection=(diagnostics.bubblesRejectedByTimeProjection??0)+1;continue}if(y===null||!Number.isFinite(Number(y))){diagnostics.bubblesRejectedByPriceProjection=(diagnostics.bubblesRejectedByPriceProjection??0)+1;continue}context.save();context.globalAlpha=settings.bubbles.opacity;context.fillStyle=blendHex(settings.bubbles.sellColour,settings.bubbles.buyColour,composition.buyRatio);context.beginPath();context.arc(x,Number(y),radius,0,Math.PI*2);context.fill();context.globalAlpha=settings.bubbles.outlineOpacity;context.strokeStyle=settings.bubbles.outlineColour;context.stroke();context.restore();xs.push(x);diagnostics.bubblesDrawn=(diagnostics.bubblesDrawn??0)+1}diagnostics.bubbleXCoordinates=xs;diagnostics.rejectionReasons={time:groups.length-visible.length,price:diagnostics.bubblesRejectedByPriceProjection??0,threshold:diagnostics.bubblesRejectedBelowThreshold??0};}
   }finally{context.restore()}
   if(this.store.getDiagnostics().sourceFeedConnected===false)diagnostics.failure="source feed disconnected";else if(!s.heatmap.length&&!s.trades.length)diagnostics.failure="no depth observations received; no trades received";else if(s.heatmapTiles.length&&!(diagnostics.heatmapProjectedCells??0))diagnostics.failure="observations retained but projection failed";else if(s.trades.length&&!(diagnostics.bubbleGroupsProduced??0))diagnostics.failure="trades projected outside the visible candle range";
   this.store.updateDiagnostics(diagnostics);
  }catch(error){this.store.updateDiagnostics({...base,lastRendererError:error instanceof Error?error.message:String(error),failure:"renderer error"});}
 }
}
