export const MAX_DRAWINGS = 250;
export const MAX_DRAWING_TEXT = 300;
export type DrawingPoint = { time: number; price: number };
export type DrawingStyle = { colour: string; lineWidth: number; lineStyle: "solid"|"dashed"|"dotted"; opacity: number; fillColour?: string; fillOpacity?: number; textColour?: string };
type Base = { id:string; name:string; visible:boolean; locked:boolean; createdAt:string; updatedAt:string; style:DrawingStyle };
export type Extension = "none"|"left"|"right"|"both";
export type TrendLineDrawing=Base&{type:"trendLine";points:[DrawingPoint,DrawingPoint];extension:Extension};
export type RayDrawing=Base&{type:"ray";points:[DrawingPoint,DrawingPoint];extension:"right"};
export type HorizontalLineDrawing=Base&{type:"horizontalLine";point:DrawingPoint;extension:Extension};
export type VerticalLineDrawing=Base&{type:"verticalLine";point:DrawingPoint};
export type ParallelChannelDrawing=Base&{type:"parallelChannel";points:[DrawingPoint,DrawingPoint,DrawingPoint]};
export type RectangleDrawing=Base&{type:"rectangle";points:[DrawingPoint,DrawingPoint]};
export type FibonacciDrawing=Base&{type:"fibonacci";points:[DrawingPoint,DrawingPoint];ratios:number[]};
export type TextDrawing=Base&{type:"text";point:DrawingPoint;text:string;textSize:number};
export type MeasurementDrawing=Base&{type:"measurement";points:[DrawingPoint,DrawingPoint]};
export type Drawing=TrendLineDrawing|RayDrawing|HorizontalLineDrawing|VerticalLineDrawing|ParallelChannelDrawing|RectangleDrawing|FibonacciDrawing|TextDrawing|MeasurementDrawing;
export type DrawingType=Drawing["type"];

const TYPES=new Set(["trendLine","ray","horizontalLine","verticalLine","parallelChannel","rectangle","fibonacci","text","measurement"]);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const COLOUR=/^#[0-9a-f]{6}$/i;
const finite=(n:unknown,min=-1e15,max=1e15)=>typeof n==="number"&&Number.isFinite(n)&&n>=min&&n<=max?n:null;
const point=(v:unknown):DrawingPoint|null=>{if(!v||typeof v!=="object")return null;const x=v as Record<string,unknown>,time=finite(x.time,0),price=finite(x.price,-1e12,1e12);return time===null||price===null?null:{time,price};};
const colour=(v:unknown,fallback:string)=>typeof v==="string"&&COLOUR.test(v)?v:fallback;
export function sanitiseText(value:unknown){return typeof value==="string"?value.replace(/[\u0000-\u001f\u007f]/g,"").slice(0,MAX_DRAWING_TEXT):"";}
export function defaultStyle(type:DrawingType):DrawingStyle { const map:Record<DrawingType,DrawingStyle>={trendLine:{colour:"#3b82f6",lineWidth:2,lineStyle:"solid",opacity:1},ray:{colour:"#3b82f6",lineWidth:2,lineStyle:"solid",opacity:1},horizontalLine:{colour:"#f59e0b",lineWidth:2,lineStyle:"solid",opacity:1},verticalLine:{colour:"#8b7bb8",lineWidth:1,lineStyle:"dashed",opacity:.8},parallelChannel:{colour:"#22d3ee",lineWidth:2,lineStyle:"solid",opacity:1,fillColour:"#22d3ee",fillOpacity:.08},rectangle:{colour:"#3b82f6",lineWidth:2,lineStyle:"solid",opacity:1,fillColour:"#3b82f6",fillOpacity:.1},fibonacci:{colour:"#fbbf24",lineWidth:1,lineStyle:"solid",opacity:1},text:{colour:"#111827",lineWidth:1,lineStyle:"solid",opacity:.95,textColour:"#f8fafc"},measurement:{colour:"#22c55e",lineWidth:2,lineStyle:"dashed",opacity:1}};return map[type]; }
function style(v:unknown,type:DrawingType):DrawingStyle {const d=defaultStyle(type),x=v&&typeof v==="object"?v as Record<string,unknown>:{};return {colour:colour(x.colour,d.colour),lineWidth:finite(x.lineWidth,1,5)??d.lineWidth,lineStyle:["solid","dashed","dotted"].includes(String(x.lineStyle))?x.lineStyle as DrawingStyle["lineStyle"]:d.lineStyle,opacity:finite(x.opacity,0,1)??d.opacity,...(d.fillColour||x.fillColour?{fillColour:colour(x.fillColour,d.fillColour??d.colour),fillOpacity:finite(x.fillOpacity,0,1)??d.fillOpacity??.1}:{}),...(d.textColour||x.textColour?{textColour:colour(x.textColour,d.textColour??"#ffffff")}: {})};}
export function sanitiseDrawing(value:unknown):Drawing|null {if(!value||typeof value!=="object")return null;const x=value as Record<string,unknown>,type=x.type as DrawingType;if(!TYPES.has(type)||typeof x.id!=="string"||!UUID.test(x.id))return null;const now=new Date().toISOString(),base={id:x.id,name:sanitiseText(x.name).slice(0,80)||type,visible:x.visible!==false,locked:x.locked===true,createdAt:typeof x.createdAt==="string"&&!Number.isNaN(Date.parse(x.createdAt))?x.createdAt:now,updatedAt:typeof x.updatedAt==="string"&&!Number.isNaN(Date.parse(x.updatedAt))?x.updatedAt:now,style:style(x.style,type)};const pts=Array.isArray(x.points)?x.points.map(point):[];const ext=["none","left","right","both"].includes(String(x.extension))?x.extension as Extension:"none";if(type==="horizontalLine"||type==="verticalLine"||type==="text"){const p=point(x.point);if(!p)return null;if(type==="horizontalLine")return {...base,type,point:p,extension:ext};if(type==="verticalLine")return {...base,type,point:p};return {...base,type,point:p,text:sanitiseText(x.text),textSize:finite(x.textSize,8,36)??12};}if(type==="parallelChannel"){if(pts.length!==3||pts.some(p=>!p))return null;return {...base,type,points:pts as [DrawingPoint,DrawingPoint,DrawingPoint]};}if(pts.length!==2||pts.some(p=>!p))return null;const pair=pts as [DrawingPoint,DrawingPoint];if(type==="trendLine")return {...base,type,points:pair,extension:ext};if(type==="ray")return {...base,type,points:pair,extension:"right"};if(type==="rectangle")return {...base,type,points:pair};if(type==="measurement")return {...base,type,points:pair};const ratios=Array.isArray(x.ratios)?x.ratios.map(v=>finite(v,-10,10)).filter((v):v is number=>v!==null).slice(0,20):[0,.236,.382,.5,.618,.786,1];return {...base,type:"fibonacci",points:pair,ratios:ratios.length?ratios:[0,.5,1]};}
export function createDrawing(type:DrawingType,input:Partial<Drawing>):Drawing|null {const now=new Date().toISOString();return sanitiseDrawing({...input,type,id:crypto.randomUUID(),name:input.name??type,visible:true,locked:false,createdAt:now,updatedAt:now,style:{...defaultStyle(type),...input.style}});}
export function drawingPoints(d:Drawing):DrawingPoint[]{return "points" in d?d.points:[d.point];}
export function translateDrawing(d:Drawing,delta:DrawingPoint):Drawing {const move=(p:DrawingPoint)=>({time:p.time+delta.time,price:p.price+delta.price});return "points" in d?{...d,points:d.points.map(move) as never,updatedAt:new Date().toISOString()}:{...d,point:move(d.point),updatedAt:new Date().toISOString()};}
export function measurement(d:MeasurementDrawing){const price=d.points[1].price-d.points[0].price;return {price,time:d.points[1].time-d.points[0].time,percentage:d.points[0].price===0?0:price/d.points[0].price*100};}
