import type { Candle } from "../strategy";
export const MAX_USER_INDICATORS=30;
export type Source="close"|"open"|"high"|"low"|"HL2"|"HLC3";
type Common={id:string;visible:boolean;width:number};
export type UserIndicator=(Common&{type:"sma"|"ema";length:number;source:Source;colour:string})|(Common&{type:"bollinger";length:number;multiplier:number;basisColour:string;upperColour:string;lowerColour:string;fillColour:string;fillOpacity:number})|(Common&{type:"rsi";length:number;colour:string;overbought:number;oversold:number})|(Common&{type:"macd";fastLength:number;slowLength:number;signalLength:number;macdColour:string;signalColour:string;positiveColour:string;negativeColour:string})|(Common&{type:"atr";length:number;colour:string});
export type IndicatorPoint={time:number;value:number};
const source=(c:Candle,s:Source)=>s==="HL2"?(c.high+c.low)/2:s==="HLC3"?(c.high+c.low+c.close)/3:c[s];
export function sma(c:Candle[],length:number,s:Source="close"){return c.map((v,i)=>i<length-1?null:{time:v.time,value:c.slice(i-length+1,i+1).reduce((n,x)=>n+source(x,s),0)/length}).filter((v):v is IndicatorPoint=>v!==null)}
export function ema(c:Candle[],length:number,s:Source="close"){if(c.length<length)return [];const out:IndicatorPoint[]=[],k=2/(length+1);let value=c.slice(0,length).reduce((n,x)=>n+source(x,s),0)/length;out.push({time:c[length-1].time,value});for(let i=length;i<c.length;i++){value=source(c[i],s)*k+value*(1-k);out.push({time:c[i].time,value})}return out}
export function bollinger(c:Candle[],length:number,multiplier=2){return sma(c,length).map((basis,i)=>{const values=c.slice(i,i+length).map(x=>x.close),variance=values.reduce((n,v)=>n+(v-basis.value)**2,0)/length,deviation=Math.sqrt(variance)*multiplier;return {time:basis.time,basis:basis.value,upper:basis.value+deviation,lower:basis.value-deviation}})}
export function rsi(c:Candle[],length=14){if(c.length<=length)return [];let gain=0,loss=0;for(let i=1;i<=length;i++){const d=c[i].close-c[i-1].close;gain+=Math.max(0,d);loss+=Math.max(0,-d)}gain/=length;loss/=length;const out:IndicatorPoint[]=[];const push=(i:number)=>out.push({time:c[i].time,value:loss===0?100:100-100/(1+gain/loss)});push(length);for(let i=length+1;i<c.length;i++){const d=c[i].close-c[i-1].close;gain=(gain*(length-1)+Math.max(0,d))/length;loss=(loss*(length-1)+Math.max(0,-d))/length;push(i)}return out}
export function macd(c:Candle[],fast=12,slow=26,signal=9){const f=new Map(ema(c,fast).map(p=>[p.time,p.value])),line=ema(c,slow).map(p=>({time:p.time,value:(f.get(p.time)??p.value)-p.value})),synthetic=line.map(p=>({time:p.time,open:p.value,high:p.value,low:p.value,close:p.value,volume:0}) satisfies Candle),signals=ema(synthetic,signal),sm=new Map(signals.map(p=>[p.time,p.value]));return line.filter(p=>sm.has(p.time)).map(p=>({time:p.time,macd:p.value,signal:sm.get(p.time)!,histogram:p.value-sm.get(p.time)!}))}
export function atr(c:Candle[],length=14){if(c.length<length+1)return [];const tr=c.map((x,i)=>i===0?x.high-x.low:Math.max(x.high-x.low,Math.abs(x.high-c[i-1].close),Math.abs(x.low-c[i-1].close)));let value=tr.slice(1,length+1).reduce((a,b)=>a+b,0)/length;const out=[{time:c[length].time,value}];for(let i=length+1;i<c.length;i++){value=(value*(length-1)+tr[i])/length;out.push({time:c[i].time,value})}return out}
const UUID=/^[0-9a-f-]{36}$/i,COLOUR=/^#[0-9a-f]{6}$/i,num=(v:unknown,min:number,max:number,d:number)=>typeof v==="number"&&Number.isFinite(v)?Math.min(max,Math.max(min,v)):d,col=(v:unknown,d:string)=>typeof v==="string"&&COLOUR.test(v)?v:d;
export function sanitiseIndicator(v:unknown):UserIndicator|null{if(!v||typeof v!=="object")return null;const x=v as Record<string,unknown>;if(typeof x.id!=="string"||!UUID.test(x.id)||!["sma","ema","bollinger","rsi","macd","atr"].includes(String(x.type)))return null;const base={id:x.id,visible:x.visible!==false,width:num(x.width,1,5,2)};if(x.type==="sma"||x.type==="ema")return {...base,type:x.type,length:num(x.length,2,500,20),source:["close","open","high","low","HL2","HLC3"].includes(String(x.source))?x.source as Source:"close",colour:col(x.colour,"#60a5fa")};if(x.type==="bollinger")return {...base,type:"bollinger",length:num(x.length,2,500,20),multiplier:num(x.multiplier,.1,10,2),basisColour:col(x.basisColour,"#fbbf24"),upperColour:col(x.upperColour,"#60a5fa"),lowerColour:col(x.lowerColour,"#60a5fa"),fillColour:col(x.fillColour,"#3b82f6"),fillOpacity:num(x.fillOpacity,0,1,.08)};if(x.type==="rsi")return {...base,type:"rsi",length:num(x.length,2,100,14),colour:col(x.colour,"#a78bfa"),overbought:num(x.overbought,51,99,70),oversold:num(x.oversold,1,49,30)};if(x.type==="atr")return {...base,type:"atr",length:num(x.length,2,100,14),colour:col(x.colour,"#fb923c")};const fast=num(x.fastLength,2,499,12),slow=Math.max(fast+1,num(x.slowLength,3,500,26));return {...base,type:"macd",fastLength:fast,slowLength:slow,signalLength:num(x.signalLength,2,100,9),macdColour:col(x.macdColour,"#60a5fa"),signalColour:col(x.signalColour,"#f59e0b"),positiveColour:col(x.positiveColour,"#22c55e"),negativeColour:col(x.negativeColour,"#ef4444")}}
