import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader, { Brand, GitHubIcon } from "@/app/marketing/site-header";
import { SCHOOL_DISPLAY_NAME } from "@/app/lib/branding";

export const metadata: Metadata = {
  title: "Why DizyTrades Exists | DizyTrades",
  description: "The founder story behind DizyTrades: learn from failure, test the claim, trade the plan and build a repeatable process instead of selling certainty.",
  openGraph: {
    title: "Why DizyTrades Exists | DizyTrades",
    description: "DizyTrades was built from trading mistakes, experience around opaque signal and referral models, and a desire to make disciplined decisions easier to repeat and review.",
    type: "website",
  },
};

export default function AboutPage() {
  return <div className="marketing-shell"><SiteHeader /><main>
    <section className="hero" aria-labelledby="about-title"><div className="hero-glow" aria-hidden="true" /><div className="eyebrow"><i /> WHY DIZYTRADES EXISTS</div><h1 id="about-title">Built from mistakes.<br /><span>Built for process.</span></h1><p>I needed the product. And, if I&apos;m truthful, I needed the project too. DizyTrades started as a tool for making the decisions I wanted to make when emotion, frustration and hindsight were not allowed to rewrite the plan.</p><div className="hero-actions"><Link className="button primary" href="/explore">Open View-Only Terminal <span aria-hidden="true">→</span></Link><Link className="button secondary" href="/school">Open {SCHOOL_DISPLAY_NAME}</Link><Link className="text-action" href="/">Back to Everything Dizy™</Link></div><div className="trust-row"><span><i /> Test the claim</span><span><i /> Trade the plan</span><span><i /> Review the result</span><span><i /> Learn and repeat</span></div></section>

    <section className="workflow section" aria-labelledby="founder-note-title"><div><div className="section-kicker">FOUNDER NOTE</div><h2 id="founder-note-title">I built the tool I wanted to use.</h2><p>I have been learning about trading since around 2014. Over that time I have made most of the mistakes traders are warned about: doubting a strategy after losses, overriding it emotionally, chasing missed moves, increasing size or leverage out of frustration and turning one bad decision into several.</p><p>I also spent time around trading education, signal businesses and broker-referral models. I saw how easily presentation could look like proof, and how quickly the incentive to acquire the next customer could become more important than whether the existing customer had a useful process.</p><p>DizyTrades is my attempt to build the opposite: not a promise that losses disappear, but a workspace where ideas can be inspected, simulated, replayed, measured and improved.</p></div><ol><li><b>01</b><span><strong>Learn from failure</strong><small>Losses and mistakes are evidence. Hiding them makes the next decision worse; reviewing them can make the process better.</small></span></li><li><b>02</b><span><strong>Remove emotion from the repeatable parts</strong><small>Risk, invalidation, assumptions and strategy rules should not quietly change because the last trade hurt.</small></span></li><li><b>03</b><span><strong>Make claims testable</strong><small>A screenshot is not a track record. Signals, simulation assumptions and historical context should be open to inspection.</small></span></li><li><b>04</b><span><strong>Keep learning</strong><small>DizyTrades is not here to declare the process finished. It is here to preserve what happened so the next iteration has better evidence.</small></span></li></ol></section>

    <section className="safety section" aria-labelledby="not-title"><div><div><div className="section-kicker">WHAT IT IS NOT</div><h2 id="not-title">No magic signal.<br />No autopilot promise.</h2></div></div><div className="safety-grid"><article><b>NO CERTAINTY FOR SALE</b><strong>Markets can still prove you wrong.</strong><p>DizyTrades does not promise profits, guaranteed signals or a way to remove uncertainty from trading. The objective is a better decision process, not a fantasy win rate.</p></article><article><b>NO BLIND AUTOPILOT</b><strong>Decision support first.</strong><p>The platform is designed to show how I would approach a market without emotion: evidence, risk, invalidation, simulation and review. Guarded execution remains a separate locked programme, not a licence to stop thinking.</p></article><article><b>NO LIFESTYLE THEATRE</b><strong>Evidence before appearance.</strong><p>No rented-Lambo logic, no pretending a flashy result proves a method. If a claim matters, the useful question is whether the process and evidence survive inspection.</p></article></div><p className="safety-callout"><i /> <b>Experience comes from failure. Perfection comes from proper process.</b></p></section>

    <section className="developers section" aria-labelledby="principle-title"><div className="developer-mark"><GitHubIcon /></div><div><div className="section-kicker">THE PRINCIPLE</div><h2 id="principle-title">Don&apos;t trust the screenshot.<br />Test the claim.</h2><p>That principle applies to trading and to the software itself. DizyTrades is built in the open, with deterministic tests, explicit evidence boundaries and a public roadmap. The goal is not to ask for blind trust; it is to make the important parts inspectable.</p><p>You are allowed to be wrong. You are not allowed to turn being wrong into being reckless.</p><div className="developer-actions"><a className="button primary" href="https://github.com/DizygoticCode/DizyTrades" target="_blank" rel="noopener noreferrer">Inspect the Repository</a><Link className="button secondary" href="/explore">Explore DizyTrades</Link></div></div></section>

    <section className="final-cta"><div className="eyebrow">EVERYTHING DIZY™</div><h2>Trade the plan.<br />Not the emotion.</h2><p>DizyTrades began as something I wanted for myself. If the same evidence-first process helps other people learn, practise and make more deliberate decisions too, even better. Hunt opportunity. Do not chase it.</p><div><Link className="button primary" href="/explore">Open View-Only Terminal</Link><Link className="button secondary" href="/school">Explore {SCHOOL_DISPLAY_NAME}</Link></div></section>
  </main><footer className="site-footer"><div className="footer-top"><Brand /><div><b>PRODUCT</b><Link href="/explore">Terminal</Link><Link href="/research">DizyQuant</Link><Link href="/account">DizyAccount</Link><Link href="/scanner">DizyScanner</Link><Link href="/structure">DizyStructure</Link><Link href="/performance">DizyPerformance</Link><Link href="/dex">DizyDEX</Link><Link href="/school">{SCHOOL_DISPLAY_NAME}</Link></div><div><b>ACCOUNT</b><Link href="/login">Sign In</Link><Link href="/signup">Create Account</Link><Link href="/about">About DizyTrades</Link></div><div><b>DEVELOPERS</b><a href="https://github.com/DizygoticCode/DizyTrades" target="_blank" rel="noopener noreferrer"><GitHubIcon /> GitHub</a><a href="https://github.com/DizygoticCode/DizyTrades/issues" target="_blank" rel="noopener noreferrer">Issues</a><a href="https://github.com/DizygoticCode/DizyTrades#readme" target="_blank" rel="noopener noreferrer">Documentation</a></div></div><div className="risk"><p><b>Risk disclaimer:</b> Cryptocurrency markets are volatile. DizyTrades provides research, education and simulation tools—not financial advice. Simulated results do not guarantee future performance. Live execution is disabled.</p><span>© {new Date().getFullYear()} DizyTrades · Everything Dizy™</span></div></footer></div>;
}
