"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import type { IChartApi,ISeriesApi,UTCTimestamp } from "lightweight-charts";
import { createDrawing,drawingPoints,measurement,type Drawing,type DrawingPoint,type DrawingType } from "./lib/chart/drawings";
type Tool="cursor"|"select"|DrawingType;
const TOOLS:[Tool,string][]=[["cursor","Cursor / pan"],["select","Select object"],["trendLine","Trend line"],["ray","Ray"],["horizontalLine","Horizontal line"],["verticalLine","Vertical line"],["parallelChannel","Parallel channel"],["rectangle","Rectangle"],["fibonacci","Fibonacci retracement"],["text","Text note"],["measurement","Measure"]];
export function ChartToolsLayer({chart,series,exchange,symbol,timeframe,readOnly}:{chart:()=>IChartApi|null;series:()=>ISeriesApi<"Candlestick">|null;exchange:string;symbol:string;timeframe:string;readOnly:boolean}){
 const canvas=useRef<HTMLCanvasElement>(null),[tool,setTool]=useState<Tool>("cursor"),[drawings,setDrawings]=useState<Drawing[]>([]),[selected,setSelected]=useState<string|null>(null),[save,setSave]=useState("Saving"),[canUndo,setCanUndo]=useState(false),[canRedo,setCanRedo]=useState(false),history=useRef<Drawing[][]>([]),redo=useRef<Drawing[][]>([]),draft=useRef<DrawingPoint[]>([]),preview=useRef<DrawingPoint|null>(null),version=useRef(0),raf=useRef(0);
 const point=useCallback((event:React.PointerEvent):DrawingPoint|null=>{const c=canvas.current,ch=chart(),s=series();if(!c||!ch||!s)return null;const r=c.getBoundingClientRect(),x=event.clientX-r.left,y=event.clientY-r.top,time=ch.timeScale().coordinateToTime(x),price=s.coordinateToPrice(y);return time==null||price==null?null:{time:Number(time),price:Number(price)}},[chart,series]);
 const render=useCallback(()=>{cancelAnimationFrame(raf.current);raf.current=requestAnimationFrame(()=>{const c=canvas.current,ch=chart(),s=series();if(!c||!ch||!s)return;const r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr);const x=c.getContext("2d");if(!x)return;x.scale(dpr,dpr);x.clearRect(0,0,r.width,r.height);x.save();x.beginPath();x.rect(0,0,Math.max(0,r.width-ch.priceScale("right").width()),r.height);x.clip();const all=drawings;for(const d of all){if(!d.visible)continue;const pts=drawingPoints(d).map(p=>({x:ch.timeScale().timeToCoordinate(p.time as UTCTimestamp),y:s.priceToCoordinate(p.price)}));if(pts.some(p=>p.x==null||p.y==null))continue;const p=pts.map(v=>({x:Number(v.x),y:Number(v.y)}));x.globalAlpha=d.style.opacity;x.strokeStyle=d.style.colour;x.fillStyle=d.style.fillColour??d.style.colour;x.lineWidth=d.style.lineWidth;x.setLineDash(d.style.lineStyle==="dashed"?[7,5]:d.style.lineStyle==="dotted"?[2,4]:[]);x.beginPath();if(d.type==="horizontalLine"){x.moveTo(0,p[0].y);x.lineTo(r.width,p[0].y)}else if(d.type==="verticalLine"){x.moveTo(p[0].x,0);x.lineTo(p[0].x,r.height)}else if(d.type==="rectangle"){x.globalAlpha=d.style.fillOpacity??.1;x.fillRect(p[0].x,p[0].y,p[1].x-p[0].x,p[1].y-p[0].y);x.globalAlpha=d.style.opacity;x.rect(p[0].x,p[0].y,p[1].x-p[0].x,p[1].y-p[0].y)}else if(d.type==="fibonacci"){for(const level of d.ratios){const y=p[0].y+(p[1].y-p[0].y)*level;x.moveTo(Math.min(p[0].x,p[1].x),y);x.lineTo(Math.max(p[0].x,p[1].x),y);x.fillStyle=d.style.colour;x.fillText(String(level),Math.min(p[0].x,p[1].x)+3,y-3)}}else if(d.type==="text"){x.font=`${d.textSize}px system-ui`;x.fillStyle=d.style.textColour??"#fff";x.fillText(d.text,p[0].x,p[0].y)}else if(d.type==="parallelChannel"){const ox=p[2].x-p[0].x,oy=p[2].y-p[0].y;x.moveTo(p[0].x,p[0].y);x.lineTo(p[1].x,p[1].y);x.moveTo(p[0].x+ox,p[0].y+oy);x.lineTo(p[1].x+ox,p[1].y+oy)}else {x.moveTo(p[0].x,p[0].y);let end=p[1];if(d.type==="ray"){const scale=(r.width-p[0].x)/Math.max(1,p[1].x-p[0].x);end={x:r.width,y:p[0].y+(p[1].y-p[0].y)*scale}}x.lineTo(end.x,end.y)}x.stroke();if(d.id===selected){x.fillStyle="#fff";for(const h of p){x.beginPath();x.arc(h.x,h.y,4,0,Math.PI*2);x.fill();x.stroke()}}if(d.type==="measurement"){const m=measurement(d);x.fillStyle=m.price>=0?"#22c55e":"#ef4444";x.fillText(`${m.price.toFixed(2)} (${m.percentage.toFixed(2)}%)`,p[1].x+5,p[1].y)}}x.restore()})},[chart,drawings,selected,series]);
 useEffect(render,[render]);useEffect(()=>{const ch=chart();ch?.timeScale().subscribeVisibleLogicalRangeChange(render);return()=>ch?.timeScale().unsubscribeVisibleLogicalRangeChange(render)},[chart,render]);
 useEffect(()=>{let stop=false;fetch(`/api/chart-workspace?exchange=${exchange}&symbol=${symbol}&timeframe=${timeframe}`).then(r=>r.json()).then(w=>{if(stop)return;version.current=w.version??0;setDrawings(w.drawings??[]);history.current=[];redo.current=[];setCanUndo(false);setCanRedo(false);setSave("Saved")}).catch(()=>setSave("Unsaved"));return()=>{stop=true}},[exchange,symbol,timeframe]);
 const commit=(next:Drawing[])=>{history.current=[...history.current.slice(-99),drawings];redo.current=[];setCanUndo(true);setCanRedo(false);setDrawings(next);setSave("Unsaved")};
 useEffect(()=>{if(save!=="Unsaved"||readOnly)return;const timer=setTimeout(()=>{setSave("Saving");fetch(`/api/chart-workspace?exchange=${exchange}&symbol=${symbol}&timeframe=${timeframe}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({version:version.current,drawings,indicators:[]})}).then(async r=>{const w=await r.json();if(!r.ok)throw Error(w.error);version.current=w.version;setSave("Saved")}).catch(()=>setSave("Unsaved"))},800);return()=>clearTimeout(timer)},[drawings,exchange,readOnly,save,symbol,timeframe]);
 const complete=(points:DrawingPoint[])=>{const common={points} as Partial<Drawing>;let d:Drawing|null;if(tool==="horizontalLine"||tool==="verticalLine")d=createDrawing(tool,{point:points[0]} as Partial<Drawing>);else if(tool==="text"){const text=prompt("Note text (maximum 300 characters)","");d=text===null?null:createDrawing("text",{point:points[0],text,textSize:12} as Partial<Drawing>)}else d=createDrawing(tool as DrawingType,{...common,...(tool==="fibonacci"?{ratios:[0,.236,.382,.5,.618,.786,1]}:{})} as Partial<Drawing>);if(d){commit([...drawings,d]);setSelected(d.id)}draft.current=[];preview.current=null;render()};
 const down=(e:React.PointerEvent)=>{if(tool==="cursor"||readOnly)return;const p=point(e);if(!p)return;e.currentTarget.setPointerCapture(e.pointerId);if(tool==="select"){setSelected(null);return}draft.current.push(p);const need=tool==="parallelChannel"?3:tool==="horizontalLine"||tool==="verticalLine"||tool==="text"?1:2;if(draft.current.length>=need)complete(draft.current)};
 const undo=()=>{const prior=history.current.pop();if(prior){redo.current.push(drawings);setDrawings(prior);setCanUndo(history.current.length>0);setCanRedo(true);setSave("Unsaved")}},redoIt=()=>{const next=redo.current.pop();if(next){history.current.push(drawings);setDrawings(next);setCanUndo(true);setCanRedo(redo.current.length>0);setSave("Unsaved")}};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches("input,textarea,select,[contenteditable=true]"))return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="z"){e.preventDefault();(() => { if (e.shiftKey) redoIt(); else undo(); })()}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redoIt()}else if(e.key==="Escape"){draft.current=[];setSelected(null)}else if((e.key==="Delete"||e.key==="Backspace")&&selected){commit(drawings.filter(d=>d.id!==selected));setSelected(null)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)});
 const selectedDrawing=drawings.find(d=>d.id===selected);
 return <><aside className="drawing-toolbar" aria-label="Drawing tools">{TOOLS.map(([id,label])=><button aria-label={label} className={tool===id?"active":""} disabled={readOnly&&id!=="cursor"} key={id} onClick={()=>{draft.current=[];setTool(id)}} title={label}>{label.split(" ").map(w=>w[0]).join("").slice(0,2)}</button>)}<button aria-label="Undo" disabled={!canUndo} onClick={undo}>↶</button><button aria-label="Redo" disabled={!canRedo} onClick={redoIt}>↷</button><button aria-label="Delete selected" disabled={!selected} onClick={()=>{commit(drawings.filter(d=>d.id!==selected));setSelected(null)}}>⌫</button><button aria-label="Clear drawings" disabled={!drawings.length||readOnly} onClick={()=>{if(confirm("Clear drawings for this market and timeframe?"))commit([])}}>×</button><small>{save}</small></aside><canvas aria-label="Manual drawing interaction layer" className={`drawing-layer tool-${tool}`} onContextMenu={e=>{e.preventDefault();draft.current=[];preview.current=null}} onPointerDown={down} onPointerMove={e=>{preview.current=point(e);render()}} ref={canvas}/>{selectedDrawing?<div className="drawing-properties"><input aria-label="Drawing colour" type="color" value={selectedDrawing.style.colour} onChange={e=>commit(drawings.map(d=>d.id===selected?{...d,style:{...d.style,colour:e.target.value}}:d))}/><select aria-label="Line thickness" value={selectedDrawing.style.lineWidth} onChange={e=>commit(drawings.map(d=>d.id===selected?{...d,style:{...d.style,lineWidth:Number(e.target.value)}}:d))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select><button onClick={()=>commit(drawings.map(d=>d.id===selected?{...d,locked:!d.locked}:d))}>{selectedDrawing.locked?"Unlock":"Lock"}</button><button onClick={()=>commit(drawings.map(d=>d.id===selected?{...d,visible:!d.visible}:d))}>{selectedDrawing.visible?"Hide":"Show"}</button></div>:null}</>;
}
