"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/preserve-manual-memoization */
import {useEffect,useMemo,useRef,useState} from "react";
import type {FlowRenderStore} from "./lib/order-flow/render-store";
import {aggregateRecentTrades,buildDomRows,calculateBookMarketState,domGroupingOptions,flashStrength,liquidityWidths,navigationIndex,queueAhead,virtualWindow,type DomRow} from "./lib/order-flow/dom";
import {formatOrderImbalance} from "./lib/order-flow/imbalance";
import type {FlowSummary} from "./lib/order-flow/use-order-flow";
import type {MarketDescriptor} from "./lib/market/types";
import {DOM_SAFE_MINIMUM_WIDTH,type OrderFlowSettings} from "./lib/order-flow/settings";
const compact=(v:number)=>new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:2}).format(v);
export function DizyFlowDom({store,summary,contractSize,market,onGrouping,onClose,onWidth,onDomSettings}:{store:FlowRenderStore;summary:FlowSummary;contractSize:number;market:MarketDescriptor;onGrouping:(step:string)=>void;onClose:()=>void;onWidth:(width:number)=>void;onDomSettings:(patch:Partial<OrderFlowSettings["dom"]>)=>void}){
 const[tick,setTick]=useState(0),[scrollTop,setScrollTop]=useState(0),[height,setHeight]=useState(400),[manual,setManual]=useState(false),[selectedQueue,setSelectedQueue]=useState<string|null>(null),[now,setNow]=useState(()=>Date.now()),bookRef=useRef<HTMLDivElement>(null);
 useEffect(()=>store.subscribe(()=>setTick(v=>v+1)),[store]);
 const snapshot=store.getSnapshot(),settings=snapshot.settings.dom,options=domGroupingOptions(market.depthStepList,market.priceUnit),selected=options.includes(settings.groupingBySymbol[market.symbol])?settings.groupingBySymbol[market.symbol]:options[0]??market.priceUnit??"1",step=Number(selected);
 useEffect(()=>{setManual(false);setSelectedQueue(null);setScrollTop(0)},[market.symbol,snapshot.generation]);
 useEffect(()=>{const node=bookRef.current;if(!node)return;const observer=new ResizeObserver(([entry])=>setHeight(entry.contentRect.height));observer.observe(node);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!settings.recentTradeFlashes)return;const id=setInterval(()=>setNow(Date.now()),100);return()=>clearInterval(id)},[settings.recentTradeFlashes]);
 const rows=useMemo(()=>buildDomRows(snapshot.book,contractSize,settings.levels,selected,{enabled:settings.highlightClusters,multiple:snapshot.settings.marketDepth.clusterMultiple,minimumSamples:snapshot.settings.marketDepth.clusterMinimumSamples}),[snapshot.book,contractSize,settings.levels,selected,settings.highlightClusters,snapshot.settings.marketDepth.clusterMultiple,snapshot.settings.marketDepth.clusterMinimumSamples]),state=calculateBookMarketState(snapshot.book),ordered=useMemo(()=>[...rows.asks].reverse().concat(rows.bids),[rows]),widths=useMemo(()=>liquidityWidths(rows.bids,rows.asks,settings.scaling,settings.comparison,settings.cumulative),[rows,settings.scaling,settings.comparison,settings.cumulative]),flashes=useMemo(()=>settings.recentTradeFlashes?aggregateRecentTrades(snapshot.trades,step,now,settings.flashDurationMs):[],[snapshot.trades,step,now,settings]),flashByPrice=new Map(flashes.map(v=>[v.price,v])),virtual=virtualWindow(ordered.length,scrollTop,height,settings.rowHeight,4),visible=ordered.slice(virtual.start,virtual.end),age=snapshot.depthReceivedAt?now-snapshot.depthReceivedAt:null,stale=age===null||age>settings.staleThresholdMs,imbalanceLabel=formatOrderImbalance(summary.imbalance),imbalanceColour=summary.imbalance===null?"#81899c":summary.imbalance>=0?"#66e0b2":"#ff7186";
 const priceDigits=Math.max(0,(selected.split(".")[1]??"").length),formatPrice=(price:number)=>price.toLocaleString(undefined,{minimumFractionDigits:priceDigits,maximumFractionDigits:priceDigits}),formatSize=(row:DomRow)=>settings.units==="usdt"?compact(row.notional):settings.units==="base"?compact(row.baseQuantity):compact(row.contractQuantity),centre=()=>{setManual(false);onDomSettings({autoCentre:true});const target=Math.max(0,rows.asks.length*settings.rowHeight-height/2);bookRef.current?.scrollTo({top:target,behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"})};
 useEffect(()=>{if(settings.autoCentre&&!manual&&bookRef.current){const target=Math.max(0,rows.asks.length*settings.rowHeight-height/2);bookRef.current.scrollTop=target}},[state.midpoint,rows.asks.length,height,settings.autoCentre,settings.rowHeight,manual]);
 useEffect(()=>{store.updateDiagnostics({domVisibleRows:visible.length,domTotalRows:ordered.length,domOverscan:virtual.overscan,domCentrePrice:state.midpoint,domNavigation:settings.autoCentre&&!manual?"auto":"manual",domBookAgeMs:age,domRenderCount:tick,domRecentFlashes:flashes.length,domClusterRows:ordered.filter(v=>v.largeCluster).length,domQueueCalculations:selectedQueue?1:0,domSymbol:market.symbol,domGroupingStep:step,domBookState:state.kind})},[store,visible.length,ordered,virtual.overscan,state,settings.autoCentre,manual,age,flashes.length,selectedQueue,market.symbol,step,tick]);
 const onKey=(e:React.KeyboardEvent)=>{if(e.key==="Escape"){e.preventDefault();centre();return}if(!["ArrowUp","ArrowDown","PageUp","PageDown","Home","End"].includes(e.key))return;e.preventDefault();setManual(true);const current=Math.floor(bookRef.current!.scrollTop/settings.rowHeight),next=navigationIndex(current,e.key,ordered.length,virtual.visible);bookRef.current!.scrollTop=next*settings.rowHeight};
 const resize=(event:React.PointerEvent)=>{event.preventDefault();const start=event.clientX,initial=settings.width;const move=(e:PointerEvent)=>onWidth(Math.max(DOM_SAFE_MINIMUM_WIDTH,Math.min(380,initial+start-e.clientX))),up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)};
 void tick;return <aside className={`dizyflow-dom ${settings.density}`} style={{background:settings.backgroundColour,"--dom-width":`${settings.width}px`,"--dom-row-height":`${settings.rowHeight}px`} as React.CSSProperties}>
 <button className="dom-resize" aria-label="Resize DOM" onPointerDown={resize}/><header><b>DOM</b><span className={stale?"stale":summary.status.toLowerCase()} title={summary.reason}>{stale?"STALE":summary.status.toUpperCase()}</span><output className="dom-order-imbalance" aria-label={`25-level order imbalance ${imbalanceLabel}`} title="25-level order imbalance. Positive means displayed bid notional outweighs displayed ask notional." style={{color:imbalanceColour,fontSize:9,fontWeight:800,fontVariantNumeric:"tabular-nums",whiteSpace:"nowrap"}}>IMB {imbalanceLabel}</output><button onClick={onClose} aria-label="Close DOM">×</button></header>
 <div className="dom-tools"><label>Group<select aria-label="DOM price grouping" value={selected} onChange={e=>onGrouping(e.target.value)}>{options.map(v=><option key={v}>{v}</option>)}</select></label><button aria-pressed={settings.autoCentre&&!manual} onClick={()=>settings.autoCentre&&!manual?onDomSettings({autoCentre:false}):centre()}>{settings.autoCentre&&!manual?"Auto Centre ON":"Return to market"}</button><label>Scale<select value={settings.scaling} onChange={e=>onDomSettings({scaling:e.target.value as "linear"|"logarithmic"})}><option value="linear">Linear</option><option value="logarithmic">Log</option></select></label></div>
 <div className="dom-head"><span>Bid size</span><span>Price</span><span>Ask size</span>{settings.cumulative?<span>Total</span>:null}{settings.showQueueEstimate?<span>Queue</span>:null}</div>
 <div className={`dom-market ${state.kind} ${stale?"stale":""}`}><strong>{state.kind==="valid"?<>Midpoint {formatPrice(state.midpoint!)} · Spread {formatPrice(state.spread!)}</>:state.kind==="crossed"?"Warning: crossed or locked book":state.kind==="one-sided"?"One-sided book · midpoint unavailable":state.kind==="empty"?"Empty book":"Invalid book"}</strong><span>Best bid {state.bestBid?formatPrice(state.bestBid):"—"} · Best ask {state.bestAsk?formatPrice(state.bestAsk):"—"}</span></div>
 <div className="dom-book" ref={bookRef} tabIndex={0} role="grid" aria-label="Order-book ladder. Arrow keys navigate; Escape returns to market." onKeyDown={onKey} onScroll={e=>{setScrollTop(e.currentTarget.scrollTop);if(Math.abs(e.currentTarget.scrollTop-scrollTop)>2)setManual(true)}} style={{position:"relative"}}><div style={{height:ordered.length*settings.rowHeight,position:"relative"}}><div style={{transform:`translateY(${virtual.offset}px)`}}>{visible.map(row=>{const flash=flashByPrice.get(row.price),strength=flash?flashStrength(flash,now,settings.flashDurationMs)*settings.flashIntensity:0,isBest=row.price===(row.side==="bid"?state.bestBid:state.bestAsk),queue=selectedQueue===row.key?queueAhead(row,settings.units):null;return <div role="row" aria-label={`${isBest?"Best ":""}${row.side}, ${formatPrice(row.price)}, current resting liquidity ${formatSize(row)}${row.largeCluster?", Large liquidity cluster":""}`} className={`dom-row ${row.side} ${isBest?"best":""} ${row.largeCluster?"cluster":""}`} key={row.key} style={{height:settings.rowHeight,backgroundColor:strength?`${flash?.side==="buy"?settings.bidColour:settings.askColour}${Math.round(strength*255).toString(16).padStart(2,"0")}`:undefined}} onClick={()=>settings.showQueueEstimate&&setSelectedQueue(row.key)} title={row.largeCluster?"Large liquidity cluster":"Current resting liquidity"}><i className="liquidity" style={{width:`${(widths.get(row.key)??0)*settings.barMaximumWidth}%`,background:row.side==="bid"?settings.bidColour:settings.askColour,opacity:settings.barOpacity}}/><span>{row.side==="bid"?formatSize(row):""}</span><b>{formatPrice(row.price)}{isBest?row.side==="bid"?" B":" A":""}</b><span>{row.side==="ask"?formatSize(row):""}</span>{settings.cumulative?<span>{compact(row.cumulativeNotional)}</span>:null}{settings.showQueueEstimate?<span>{queue===null?"—":compact(queue)}</span>:null}</div>})}</div></div></div>
 <footer><span>{manual?"View locked":"Following midpoint"} · {visible.length}/{ordered.length} rows</span><small>Resting orders may be cancelled, moved or consumed.</small>{settings.showQueueEstimate?<small>Estimated visible queue ahead. Visible queue is only an estimate and excludes hidden liquidity, exchange priority rules and latency.</small>:null}<span title="Focus the ladder first">Keys: ↑ ↓ PgUp PgDn Home End · Esc centre</span></footer></aside>}
