"use client";
import {useEffect,useRef,useState} from "react";
import {CandlestickSeries,ColorType,createChart,type IChartApi,type UTCTimestamp} from "lightweight-charts";
import {StrategyWorldLinesPrimitive,type StrategyWorldLineEntry,type StrategyWorldLinesPaint} from "../lib/chart/strategy-world-lines-primitive";

const definitions=[["Upper trend",42,44,"trend"],["Lower trend",26,28,"trend"],["LR Upper",48,50,"lr-upper"],["LR Basis",39,41,"lr-basis"],["LR Lower",30,32,"lr-lower"]] as const;
const lines:readonly StrategyWorldLineEntry[]=Object.freeze(definitions.map(([id,start,end,group],i)=>Object.freeze({line:Object.freeze({id,start:Object.freeze({index:10,time:100,price:start}),end:Object.freeze({index:20,time:200,price:end}),createdAt:200+i,status:"confirmed" as const}),extension:"both" as const,style:Object.freeze({colour:["#ff7b8b","#52d6a0","#6ea8ff","#ffd166","#6ea8ff"][i],width:2,style:"solid" as const,halo:true,haloColour:"#ffffff",label:true,labelText:id,labelTextColour:"#07101e"}),lanePriority:5+i,group})));
const model=Object.freeze({lines,channelFill:Object.freeze({visible:true,colour:"#4f8cff",opacity:.16}),fontSize:12,labelPadding:6,compactLabels:false});
const anchorSnapshot=JSON.stringify(lines.map(({line})=>({id:line.id,start:line.start,end:line.end})));
export default function WorldLinesFixture(){
 const host=useRef<HTMLDivElement>(null),chart=useRef<IChartApi|null>(null),[paint,setPaint]=useState<StrategyWorldLinesPaint>({ids:[],segments:{}});
 useEffect(()=>{if(!host.current)return;const instance=createChart(host.current,{autoSize:true,layout:{background:{type:ColorType.Solid,color:"#0b1020"},textColor:"#dbe7ff"},timeScale:{barSpacing:18,rightOffset:3},rightPriceScale:{scaleMargins:{top:.12,bottom:.12}}}),series=instance.addSeries(CandlestickSeries,{upColor:"#20e3a2",downColor:"#ff5573",wickUpColor:"#20e3a2",wickDownColor:"#ff5573",borderVisible:false});series.setData(Array.from({length:80},(_,index)=>({time:(1_700_000_000+index*60) as UTCTimestamp,open:35+Math.sin(index/4),high:80,low:0,close:35+Math.cos(index/4)})));const primitive=new StrategyWorldLinesPrimitive(value=>setPaint({...value,segments:{...value.segments}}));series.attachPrimitive(primitive);primitive.setModel(model);instance.timeScale().setVisibleLogicalRange({from:0,to:30});chart.current=instance;return()=>{series.detachPrimitive(primitive);instance.remove();chart.current=null}},[]);
 const setRange=(from:number,to:number)=>chart.current?.timeScale().setVisibleLogicalRange({from,to});
 return <main style={{padding:20,background:"#050914",minHeight:"100vh",color:"white"}}><h1>Native strategy world-line primitive fixture</h1><div><button data-testid="anchors-left" onClick={()=>setRange(30,60)}>Anchors left</button><button data-testid="future" onClick={()=>setRange(45,75)}>Future viewport</button><button data-testid="pan-left" onClick={()=>setRange(-25,-5)}>Pan left</button><button data-testid="zoom-x" onClick={()=>setRange(50,65)}>Horizontal zoom in</button><button data-testid="zoom-out" onClick={()=>setRange(35,78)}>Horizontal zoom out</button><button data-testid="zoom-y" onClick={()=>chart.current?.priceScale("right").applyOptions({autoScale:true,scaleMargins:{top:.3,bottom:.3}})}>Vertical zoom</button><button data-testid="drag-scale" onClick={()=>chart.current?.priceScale("right").applyOptions({autoScale:false})}>Freeze/rescale price scale</button><button data-testid="original" onClick={()=>setRange(0,30)}>Original viewport</button></div><div ref={host} data-testid="world-lines-chart" style={{width:"100%",height:520,marginTop:12}}/><pre data-testid="world-lines-diagnostics">{JSON.stringify({anchorSnapshot,paint})}</pre></main>;
}
