import { NextResponse } from "next/server";
import { requireApiUser } from "../../../lib/auth";
import { deleteJournalEntry, getJournalEntry, setJournalArchived, updateJournalEntry } from "../../../lib/journal-store";
import { JournalValidationError } from "../../../lib/journal-validation";
import { appendAudit } from "../../../lib/store";
import { journalWritesAllowed } from "../../../lib/journal-model";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const fail=(status:number,message:string)=>NextResponse.json({error:{message}},{status});
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const user=await requireApiUser();if(!user)return fail(401,"Unauthorised");const entry=await getJournalEntry(user.id,(await params).id);return entry?NextResponse.json({entry,readOnly:user.role==="viewer"}):fail(404,"Journal entry not found.");}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const user=await requireApiUser();if(!user)return fail(401,"Unauthorised");if(!journalWritesAllowed(user.role))return fail(403,"Viewer sessions are read-only.");try{const entry=await updateJournalEntry(user.id,(await params).id,await request.json());if(!entry)return fail(404,"Journal entry not found.");await appendAudit(user.id,"journal.update",{entryId:entry.id});return NextResponse.json({entry});}catch(reason){return reason instanceof JournalValidationError?fail(400,reason.message):fail(400,"Invalid journal update.");}}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const user=await requireApiUser();if(!user)return fail(401,"Unauthorised");if(!journalWritesAllowed(user.role))return fail(403,"Viewer sessions are read-only.");const body=await request.json().catch(()=>null) as {action?:unknown}|null;if(body?.action!=="archive"&&body?.action!=="restore")return fail(400,"Invalid Journal action.");const entry=await setJournalArchived(user.id,(await params).id,body.action==="archive");if(!entry)return fail(404,"Journal entry not found.");await appendAudit(user.id,body.action==="archive"?"journal.archive":"journal.restore",{entryId:entry.id});return NextResponse.json({entry});}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const user=await requireApiUser();if(!user)return fail(401,"Unauthorised");if(!journalWritesAllowed(user.role))return fail(403,"Viewer sessions are read-only.");const entry=await deleteJournalEntry(user.id,(await params).id);if(!entry)return fail(404,"Journal entry not found.");await appendAudit(user.id,"journal.delete",{entryId:entry.id,type:entry.type,tradeId:entry.trade?.tradeId});return NextResponse.json({deleted:true});}
