import {NextResponse} from "next/server";
import {requireApiUser} from "../../lib/auth";
import {appendAudit} from "../../lib/store";
import {closeManualPosition,flattenManualPositions,latestPublicContractMetadata,latestPublicFundingHistory,latestPublicFundingRate,latestPublicRiskPrice,ManualPaperError,markManualPosition,partialCloseManualPosition,readManualAccount,resetManualAccount,reverseManualPosition,submitManualOrder,syncManualFunding,updateManualSettings} from "../../lib/manual-paper";
import {latestManualPaperDepth} from "../../lib/manual-paper-depth-source";
export const runtime="nodejs";export const dynamic="force-dynamic";
const attempts=new Map<string,{at:number;count:number}>();function limited(id:string){const now=Date.now(),old=attempts.get(id),value=!old||now-old.at>60_000?{at:now,count:1}:{at:old.at,count:old.count+1};attempts.set(id,value);return value.count>20}
const apiError=(code:string,field:string,message:string,status=400)=>NextResponse.json({error:{code,field,message}},{status});
async function publicFunding(symbol:string,includeHistory=false){let current:Awaited<ReturnType<typeof latestPublicFundingRate>>|null=null,history:Awaited<ReturnType<typeof latestPublicFundingHistory>>=[];try{current=await latestPublicFundingRate(symbol)}catch{/* Funding preview remains explicitly unavailable. */}if(includeHistory)try{history=await latestPublicFundingHistory(symbol)}catch{/* Funding catch-up remains explicitly unavailable. */}return {current,history}}
async function requiredDepth(symbol:string){try{return await latestManualPaperDepth(symbol)}catch{throw new ManualPaperError("DEPTH_UNAVAILABLE","depth","Fresh public DizyFlow depth is unavailable for this market action.")}}
export async function GET(request:Request){const user=await requireApiUser();if(!user)return apiError("UNAUTHORISED","session","Unauthorised",401);let account=await readManualAccount(user.id),riskPrice=null;const symbol=new URL(request.url).searchParams.get("symbol");if(!symbol)return NextResponse.json({account,readOnly:user.role==="viewer",riskPrice:null,contract:null,funding:null,depth:null});const hasPosition=Boolean(account.positions[symbol]),[contract,fundingData,depth]=await Promise.all([latestPublicContractMetadata(symbol).catch(()=>null),publicFunding(symbol,hasPosition&&user.role!=="viewer"),latestManualPaperDepth(symbol,2_500).catch(()=>null)]);if(hasPosition){try{const selected=await latestPublicRiskPrice(symbol,account.positions[symbol].lastRiskPrice);riskPrice=selected;if(user.role!=="viewer")account=await markManualPosition(user.id,symbol,selected.price,selected.source,fundingData.current??undefined,fundingData.history)}catch{/* Preserve the last valid risk mark and funding state. */}}return NextResponse.json({account,readOnly:user.role==="viewer",riskPrice,contract,funding:fundingData.current,depth})}
export async function POST(request:Request){const user=await requireApiUser();if(!user)return apiError("UNAUTHORISED","session","Unauthorised",401);if(user.role==="viewer")return apiError("VIEWER_READ_ONLY","session","Viewer sessions are read-only.",403);if(limited(user.id))return apiError("RATE_LIMITED","request","Rate limit exceeded.",429);try{const body=await request.json() as Record<string,unknown>,action=String(body.action??"order");let account;if(action==="reset")account=await resetManualAccount(user.id,String(body.confirmation));else if(action==="settings")account=await updateManualSettings(user.id,body.settings as never);else if(action==="flatten-all"){const current=await readManualAccount(user.id),entries=await Promise.all(Object.keys(current.positions).map(async symbol=>{const risk=await latestPublicRiskPrice(symbol,current.positions[symbol].lastRiskPrice),fundingData=await publicFunding(symbol,true);await syncManualFunding(user.id,symbol,risk.price,risk.source,fundingData.current??undefined,fundingData.history);return [symbol,risk.price] as const}));account=await flattenManualPositions(user.id,String(body.idempotencyKey),Object.fromEntries(entries))}else{const symbol=String(body.symbol??""),risk=await latestPublicRiskPrice(symbol),before=await readManualAccount(user.id),fundingData=await publicFunding(symbol,Boolean(before.positions[symbol]));if(before.positions[symbol])await syncManualFunding(user.id,symbol,risk.price,risk.source,fundingData.current??undefined,fundingData.history);if(action==="close"||action==="flash-close"){const [contract,depth]=await Promise.all([latestPublicContractMetadata(symbol),requiredDepth(symbol)]);account=await closeManualPosition(user.id,symbol,String(body.idempotencyKey),risk.price,depth,contract)}else if(action==="partial-close"){const [contract,depth]=await Promise.all([latestPublicContractMetadata(symbol),requiredDepth(symbol)]);account=await partialCloseManualPosition(user.id,symbol,String(body.idempotencyKey),risk.price,body,depth,contract)}else if(action==="reverse")account=await reverseManualPosition(user.id,symbol,String(body.idempotencyKey),risk.price);else{const [contract,depth]=await Promise.all([latestPublicContractMetadata(symbol),requiredDepth(symbol)]);account=await submitManualOrder(user.id,body as never,risk.price,risk.source,contract,fundingData.current??undefined,depth)}}await appendAudit(user.id,"manual-paper."+action,{symbol:body.symbol});return NextResponse.json({account})}catch(error){if(error instanceof ManualPaperError)return apiError(error.code,error.field,error.message);return apiError("INVALID_REQUEST","request","Invalid request.")}}
