import {NextResponse} from "next/server";
import {requireApiUser} from "../../lib/auth";
import {appendAudit} from "../../lib/store";
import {closeManualPosition,flattenManualPositions,latestPublicContractMetadata,latestPublicFundingHistory,latestPublicFundingRate,latestPublicPrice,latestPublicRiskPrice,ManualPaperError,markManualPosition,partialCloseManualPosition,readManualAccount,resetManualAccount,reverseManualPosition,submitManualOrder,syncManualFunding,updateManualSettings} from "../../lib/manual-paper";
export const runtime="nodejs";export const dynamic="force-dynamic";
const attempts=new Map<string,{at:number;count:number}>();function limited(id:string){const now=Date.now(),old=attempts.get(id),value=!old||now-old.at>60_000?{at:now,count:1}:{at:old.at,count:old.count+1};attempts.set(id,value);return value.count>20}
const apiError=(code:string,field:string,message:string,status=400)=>NextResponse.json({error:{code,field,message}},{status});
async function publicFunding(symbol:string){let current:Awaited<ReturnType<typeof latestPublicFundingRate>>|null=null,history:Awaited<ReturnType<typeof latestPublicFundingHistory>>=[];try{current=await latestPublicFundingRate(symbol)}catch{/* Funding preview remains explicitly unavailable. */}try{history=await latestPublicFundingHistory(symbol)}catch{/* Funding catch-up remains explicitly unavailable. */}return {current,history}}
export async function GET(request:Request){const user=await requireApiUser();if(!user)return apiError("UNAUTHORISED","session","Unauthorised",401);let account=await readManualAccount(user.id),riskPrice=null,contract=null,funding=null;const symbol=new URL(request.url).searchParams.get("symbol");if(symbol){try{contract=await latestPublicContractMetadata(symbol)}catch{/* Contract metadata remains explicitly unavailable. */}const fundingData=await publicFunding(symbol);funding=fundingData.current;if(account.positions[symbol]){try{const selected=await latestPublicRiskPrice(symbol,account.positions[symbol].lastRiskPrice);riskPrice=selected;if(user.role!=="viewer")account=await markManualPosition(user.id,symbol,selected.price,selected.source,fundingData.current??undefined,fundingData.history)}catch{/* Preserve the last valid risk mark and funding state. */}}}return NextResponse.json({account,readOnly:user.role==="viewer",riskPrice,contract,funding})}
export async function POST(request:Request){const user=await requireApiUser();if(!user)return apiError("UNAUTHORISED","session","Unauthorised",401);if(user.role==="viewer")return apiError("VIEWER_READ_ONLY","session","Viewer sessions are read-only.",403);if(limited(user.id))return apiError("RATE_LIMITED","request","Rate limit exceeded.",429);try{const body=await request.json() as Record<string,unknown>;let account;if(body.action==="reset")account=await resetManualAccount(user.id,String(body.confirmation));else if(body.action==="settings")account=await updateManualSettings(user.id,body.settings as never);else if(body.action==="flatten-all"){const current=await readManualAccount(user.id),entries=await Promise.all(Object.keys(current.positions).map(async symbol=>{const risk=await latestPublicRiskPrice(symbol,current.positions[symbol].lastRiskPrice),fundingData=await publicFunding(symbol);await syncManualFunding(user.id,symbol,risk.price,risk.source,fundingData.current??undefined,fundingData.history);return [symbol,risk.price] as const}));account=await flattenManualPositions(user.id,String(body.idempotencyKey),Object.fromEntries(entries))}else{const symbol=String(body.symbol??""),risk=await latestPublicRiskPrice(symbol),fundingData=await publicFunding(symbol),before=await readManualAccount(user.id);if(before.positions[symbol])await syncManualFunding(user.id,symbol,risk.price,risk.source,fundingData.current??undefined,fundingData.history);account=body.action==="close"||body.action==="flash-close"?await closeManualPosition(user.id,symbol,String(body.idempotencyKey),risk.price):body.action==="partial-close"?await partialCloseManualPosition(user.id,symbol,String(body.idempotencyKey),risk.price,body):body.action==="reverse"?await reverseManualPosition(user.id,symbol,String(body.idempotencyKey),risk.price):await submitManualOrder(user.id,body as never,risk.price,risk.source,await latestPublicContractMetadata(symbol),fundingData.current??undefined)}await appendAudit(user.id,"manual-paper."+String(body.action??"order"),{symbol:body.symbol});return NextResponse.json({account})}catch(error){if(error instanceof ManualPaperError)return apiError(error.code,error.field,error.message);return apiError("INVALID_REQUEST","request","Invalid request.")}}
