import { NextResponse } from "next/server";
import { requireApiUser } from "../../lib/auth";
import { createJournalEntry, DuplicateJournalTradeError, readJournal } from "../../lib/journal-store";
import { journalWritesAllowed, toJournalListItem } from "../../lib/journal-model";
import { JournalValidationError } from "../../lib/journal-validation";
import { appendAudit } from "../../lib/store";
import { journalCreateFields } from "../../lib/journal-validation";
import { captureHistoricalReplayMemory } from "../../lib/historical-replay-memory";
import { createReplayMemory } from "../../lib/replay-memory-store";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const error=(code:string,message:string,status:number,field="request")=>NextResponse.json({error:{code,field,message}},{status});
export async function GET(request:Request){const user=await requireApiUser();if(!user)return error("UNAUTHORISED","Unauthorised",401,"session");const includeArchived=new URL(request.url).searchParams.get("archived")==="true";const record=await readJournal(user.id);return NextResponse.json({entries:record.entries.filter(entry=>includeArchived||!entry.archived).slice().reverse().map(toJournalListItem),readOnly:user.role==="viewer"});}
export async function POST(request:Request){const user=await requireApiUser();if(!user)return error("UNAUTHORISED","Unauthorised",401,"session");if(!journalWritesAllowed(user.role))return error("VIEWER_READ_ONLY","Viewer sessions are read-only.",403,"session");try{const body=await request.json() as Record<string,unknown>;let memoryWarning:string|null=null;const fields=journalCreateFields(body);if(fields.trade&&body.replayMemory&&typeof body.replayMemory==="object"){try{const supplied=body.replayMemory as {candles?:unknown;capturedAtMs?:number};const replay=fields.trade.replay;if(!replay)throw new Error("Trade replay identity is unavailable.");const memory=await createReplayMemory(user.id,captureHistoricalReplayMemory({tradeId:fields.trade.tradeId,marketKey:replay.marketKey,symbol:fields.trade.symbol,timeframe:fields.trade.timeframe as never,signalTimeMs:fields.trade.signal?Date.parse(fields.trade.signal.signalTime):null,entryTimeMs:Date.parse(fields.trade.openTime),exitTimeMs:Date.parse(fields.trade.closeTime),direction:fields.trade.direction,strategyVersion:fields.trade.strategyVersion,candles:supplied.candles,capturedAtMs:supplied.capturedAtMs}));body.trade={...fields.trade,replay:{...replay,available:true,source:"retained-memory",memoryId:memory.id,capturedRangeStartMs:memory.rangeStartMs,capturedRangeEndMs:memory.rangeEndMs,candleCount:memory.integrity.candleCount,integrityWarnings:memory.integrity.warnings,brainAvailable:Boolean(memory.brainContext),flowAvailability:memory.flowAvailability}};await appendAudit(user.id,"replay-memory.create",{memoryId:memory.id,tradeId:memory.tradeId,candleCount:memory.candles.length});}catch(reason){memoryWarning=reason instanceof Error?reason.message:"Replay memory could not be retained.";}}
const entry=await createJournalEntry(user.id,body);await appendAudit(user.id,"journal.create",{entryId:entry.id,type:entry.type,tradeId:entry.trade?.tradeId,replayMemoryId:entry.trade?.replay?.memoryId});return NextResponse.json({entry,memoryWarning},{status:201});}catch(reason){if(reason instanceof JournalValidationError)return error("INVALID_JOURNAL_ENTRY",reason.message,400,reason.field);if(reason instanceof DuplicateJournalTradeError)return NextResponse.json({error:{code:"TRADE_ALREADY_JOURNALED",field:"tradeId",message:"This trade already has a Journal review."},existingEntry:{id:reason.entryId,archived:reason.archived}},{status:409});return error("INVALID_REQUEST","Invalid journal request.",400);}}
