import Link from "next/link";
import SiteHeader, { Brand, GitHubIcon } from "./site-header";
import TerminalPreview from "./terminal-preview";
import { SCHOOL_DISPLAY_NAME } from "@/app/lib/branding";

const products = [
  ["DizyCharts", "Chart", "Real-time charting, indicators and manual drawing tools."],
  ["DizySignals", "Analyse", "Confluence-based confirmed-candle signals and strategy simulation."],
  ["DizyFlow", "Follow", "DOM, liquidity, volume bubbles and large-market activity."],
  ["DizyDEX", "Discover", "Discovery and analysis for Solana, BNB Chain and other on-chain pools."],
  [SCHOOL_DISPLAY_NAME, "Learn", "Approachable lessons covering trading and every DizyTrades feature."],
  ["DizyPaper", "Test", "Manual and signal-based practice without risking real funds."],
  ["DizyTrade", "Coming Later", "Future secure exchange connectivity."],
];

const features = [
  ["mexc", "CENTRALISED MARKETS", "Supported MEXC Spot and Futures markets", "Search a broad public catalogue, compare instruments and move from price action to depth without leaving your workspace."],
  ["dex", "ON-CHAIN DISCOVERY", "Find the market before the chart", "DizyDEX brings pool discovery for Solana, BNB Chain and more into one consistent research flow—with chain, liquidity and pair context close at hand."],
  ["signals", "CONFIRMED-CANDLE ANALYSIS", "Signal without the intrabar noise", "DizySignals evaluates confluence only after a candle closes. Simulated entries are modelled on the following bar, keeping research honest and repeatable."],
  ["flow", "ORDER-FLOW TOOLS", "See activity beneath price", "DizyFlow combines depth of market, retained liquidity, volume bubbles and large-market activity to make participation easier to interpret."],
  ["paper", "SIMULATION", "Practice the process, not the promise", "Use DizyPaper for manual orders and signal-based simulations. Review decisions and risk without connecting an exchange account or risking real funds."],
  ["school", "EDUCATION", "Learn at your own pace", `${SCHOOL_DISPLAY_NAME} explains trading foundations and every DizyTrades tool in approachable, practical lessons built alongside the workspace.`],
];

export default function MarketingPage() {
  return <div className="marketing-shell"><SiteHeader /><main>
    <section className="hero"><div className="hero-glow" aria-hidden="true" /><div className="eyebrow"><i /> EVERYTHING DIZY™</div><h1>Chart it. Analyse it.<br /><span>Follow it. Learn it. Test it.</span></h1><p>One crypto workspace for centralised markets, on-chain discovery, confirmed-candle signals, order flow, education and paper trading.</p><div className="hero-actions"><Link className="button primary" href="/explore">Open View-Only Terminal <span aria-hidden="true">→</span></Link><Link className="button secondary" href="/signup">Create Account</Link><Link className="text-action" href="/login">Sign In</Link><Link className="text-action" href="/school">Explore {SCHOOL_DISPLAY_NAME}</Link></div><div className="trust-row"><span><i /> Public market data</span><span><i /> No exchange credentials</span><span><i /> Simulation only</span></div></section>
    <section className="preview-section" aria-labelledby="preview-title"><div className="section-heading"><div><span>THE WORKSPACE</span><h2 id="preview-title">Built like a terminal.<br />Designed for clarity.</h2></div><p>Move from chart structure to confirmed signals and order flow without stitching together disconnected tools.</p></div><TerminalPreview /><p className="preview-note">Efficient illustrative preview — no live feed is loaded on this page.</p></section>
    <section className="products section" aria-labelledby="products-title"><div className="section-kicker">ONE FAMILY. ONE WORKFLOW.</div><h2 id="products-title">Everything you need to build market context.</h2><div className="product-grid">{products.map(([name,label,description], index)=><article key={name} className={`product-card product-${index}`}><span>{String(index+1).padStart(2,"0")}</span><div className="product-icon" aria-hidden="true">{name.slice(4,6).toUpperCase()}</div><small>{label}</small><h3>{name}</h3><p>{description}</p>{name === "DizyTrade" ? <b className="coming">Coming Later</b> : null}</article>)}</div></section>
    <section className="workflow section" aria-labelledby="workflow-title"><div><div className="section-kicker">HOW DIZYTRADES WORKS</div><h2 id="workflow-title">Context first.<br />Decisions second.</h2><p>Build a repeatable research loop while every execution feature remains safely simulated.</p></div><ol><li><b>01</b><span><strong>Choose your market</strong><small>Browse supported MEXC instruments or discover an on-chain pool.</small></span></li><li><b>02</b><span><strong>Build context</strong><small>Chart structure, indicators, liquidity and market activity in one view.</small></span></li><li><b>03</b><span><strong>Wait for confirmation</strong><small>DizySignals analyses closed candles and models entry on the next bar.</small></span></li><li><b>04</b><span><strong>Test and learn</strong><small>Simulate with DizyPaper, review the outcome and deepen your skills.</small></span></li></ol></section>
    <section className="feature-stack">{features.map(([id,kicker,title,copy], i)=><article id={id} className="feature-row section" key={id}><div className="feature-visual" aria-hidden="true"><span>0{i+1}</span><div className={`visual-${id}`}><i/><i/><i/><i/><i/></div></div><div><div className="section-kicker">{kicker}</div><h2>{title}</h2><p>{copy}</p><Link href={id === "dex" ? "/dex" : id === "school" ? "/school" : "/explore"}>Explore {id === "mexc" ? "markets" : id === "school" ? SCHOOL_DISPLAY_NAME : `Dizy${id[0].toUpperCase()}${id.slice(1)}`} <span aria-hidden="true">→</span></Link></div></article>)}</section>
    <section className="safety section" aria-labelledby="safety-title"><div><div className="section-kicker">SECURITY BY BOUNDARY</div><h2 id="safety-title">Research freely.<br />Risk nothing real.</h2></div><div className="safety-grid"><article><b>LIVE TRADING</b><strong>Disabled</strong><p>DizyTrades is a private test deployment. There is no exchange order route and no live execution.</p></article><article><b>CREDENTIALS</b><strong>Never requested</strong><p>View-only and simulation workflows use public market data. Exchange credentials do not belong in the browser.</p></article><article><b>VIEW-ONLY MODE</b><strong>Read-only</strong><p>Explore without a profile. View-only mode cannot write settings, save paper orders or access another user’s information.</p></article></div><p className="safety-callout"><i /> DizyTrade exchange connectivity is <b>Coming Later</b> and will require a separate security review.</p></section>
    <section className="developers section" aria-labelledby="developer-title"><div className="developer-mark"><GitHubIcon /></div><div><div className="section-kicker">BUILT IN THE OPEN</div><h2 id="developer-title">Inspect the code.<br />Help shape the workspace.</h2><p>DizyTrades is developed in the open. Explore the architecture, report a reproducible issue or start with the repository documentation.</p><div className="developer-actions"><a className="button primary" href="https://github.com/DizygoticCode/DizyTrades" target="_blank" rel="noopener noreferrer">View on GitHub</a><a className="button secondary" href="https://github.com/DizygoticCode/DizyTrades/issues" target="_blank" rel="noopener noreferrer">Report an Issue</a><a className="text-action" href="https://github.com/DizygoticCode/DizyTrades#readme" target="_blank" rel="noopener noreferrer">Developer Documentation →</a></div></div></section>
    <section className="final-cta"><div className="eyebrow">EVERYTHING DIZY™</div><h2>Your market workspace<br />starts here.</h2><p>Explore the terminal without an account, or create your workspace to begin learning and testing.</p><div><Link className="button primary" href="/explore">Open View-Only Terminal</Link><Link className="button secondary" href="/signup">Create Account</Link></div></section>
  </main><footer className="site-footer"><div className="footer-top"><Brand /><div><b>PRODUCT</b><Link href="/explore">Terminal</Link><Link href="/dex">DizyDEX</Link><Link href="/school">{SCHOOL_DISPLAY_NAME}</Link></div><div><b>ACCOUNT</b><Link href="/login">Sign In</Link><Link href="/signup">Create Account</Link></div><div><b>DEVELOPERS</b><a href="https://github.com/DizygoticCode/DizyTrades" target="_blank" rel="noopener noreferrer"><GitHubIcon /> GitHub</a><a href="https://github.com/DizygoticCode/DizyTrades/issues" target="_blank" rel="noopener noreferrer">Issues</a><a href="https://github.com/DizygoticCode/DizyTrades#readme" target="_blank" rel="noopener noreferrer">Documentation</a></div></div><div className="risk"><p><b>Risk disclaimer:</b> Cryptocurrency markets are volatile. DizyTrades provides research, education and simulation tools—not financial advice. Simulated results do not guarantee future performance. Live trading is disabled.</p><span>© {new Date().getFullYear()} DizyTrades · Everything Dizy™</span></div></footer></div>;
}
