import "server-only";
import { EventEmitter } from "node:events";
import { parseRawMexcDepthLevels } from "./mexc-depth.ts";
import type { DepthEnvelope,DepthSnapshot } from "./types.ts";

const REST_BASE=(process.env.MEXC_FUTURES_REST_BASE_URL??"https://api.mexc.com").replace(/\/$/,"");
export function parseDepthPollMs(value=process.env.MEXC_DEPTH_POLL_MS){const parsed=Number(value);return Number.isFinite(parsed)?Math.max(250,Math.floor(parsed)):250}
export const DEPTH_POLL_MS=parseDepthPollMs(),DEPTH_STALE_MS=Math.max(2_500,DEPTH_POLL_MS*5);
const TIMEOUT_MS=5_000,HISTORY_MS=30*60_000,MAX_HISTORY=1_800,HISTORY_SAMPLE_MS=1_000;
const symbolPattern=/^[A-Z0-9]{1,20}_[A-Z0-9]{1,20}$/;
export function normalizeDepthSymbol(value:string){const symbol=value.trim().toUpperCase().replace(/[-/]/g,"_");return symbolPattern.test(symbol)?symbol:null;}

type Fetcher=typeof fetch;
export type CollectorDiagnostic={symbol:string;running:boolean;lastSuccessfulSnapshot:number|null;snapshotAgeMs:number|null;lastVersion:number|null;bids:number;asks:number;consecutiveFailures:number;lastError:string|null;subscribers:number};
const safeError=(error:unknown)=>error instanceof Error?error.message.slice(0,180):"Public depth request failed";
export function normalizeMexcSnapshot(raw:unknown,symbol:string):DepthSnapshot{
 const root=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:null,data=root?.data&&typeof root.data==="object"&&!Array.isArray(root.data)?root.data as Record<string,unknown>:null;
 if(!root||root.success!==true||!(root.code===0||root.code==="0"||root.code==null)||!data)throw Error("Invalid MEXC depth envelope");
 const version=Number(data.version),engineTimeMs=Number(data.timestamp);if(!Number.isInteger(version)||version<0||!Number.isFinite(engineTimeMs)||engineTimeMs<=0)throw Error("Invalid MEXC depth version or timestamp");
 const bids=parseRawMexcDepthLevels(data.bids),asks=parseRawMexcDepthLevels(data.asks);if(!Array.isArray(data.bids)||!Array.isArray(data.asks)||!bids.length||!asks.length||bids.length!==data.bids.length||asks.length!==data.asks.length)throw Error("Invalid MEXC depth levels");
 return {symbol,version,engineTimeMs,bids:bids.sort((a,b)=>b.price-a.price),asks:asks.sort((a,b)=>a.price-b.price)};
}

export class DepthCollector{
 private timer:ReturnType<typeof setTimeout>|null=null;private pingTimer:ReturnType<typeof setInterval>|null=null;private reconnectTimer:ReturnType<typeof setTimeout>|null=null;private socket:WebSocket|null=null;private inFlight=false;private failures=0;private error:string|null=null;private latest:DepthEnvelope|null=null;private lastHistoryAt:number|null=null;private history:DepthEnvelope[]=[];private emitter=new EventEmitter();private running=false;private connectionState="stopped";private wsMessages=0;private gaps=0;private recoveries=0;private wsLive=false;private bids=new Map<number,import("./types.ts").DepthLevel>();private asks=new Map<number,import("./types.ts").DepthLevel>();
 readonly symbol:string;private fetcher:Fetcher;private now:()=>number;private socketFactory:(url:string)=>WebSocket;
 constructor(symbol:string,fetcher:Fetcher=fetch,now=()=>Date.now(),socketFactory=(url:string)=>new WebSocket(url)){this.symbol=symbol;this.fetcher=fetcher;this.now=now;this.socketFactory=socketFactory;}
 private sourceMode():import("./types.ts").DepthSourceMode{return this.wsLive?"FULL DEPTH WS":this.latest?(this.socket?"RECONNECTING — LAST BOOK RETAINED":"REST FALLBACK"):"NO VALID BOOK"}
 private transition(state:string){if(state===this.connectionState)return;this.connectionState=state;const detail={symbol:this.symbol,state,sourceMode:this.sourceMode()};if(state==="live")console.info("DizyFlow depth collector state",detail);else console.warn("DizyFlow depth collector state",detail);}
 start(){if(this.running)return;this.running=true;this.transition("connecting");void this.pollScheduled();this.connect();}
 stop(){this.running=false;if(this.timer)clearTimeout(this.timer);if(this.pingTimer)clearInterval(this.pingTimer);if(this.reconnectTimer)clearTimeout(this.reconnectTimer);this.timer=this.pingTimer=this.reconnectTimer=null;this.socket?.close();this.socket=null;this.wsLive=false;}
 private connect(){if(!this.running||this.socket)return;this.transition(this.latest?"reconnecting":"connecting");let socket:WebSocket;try{socket=this.socketFactory("wss://contract.mexc.com/edge")}catch{this.scheduleReconnect();return}this.socket=socket;socket.addEventListener("open",()=>{if(socket!==this.socket)return;socket.send(JSON.stringify({method:"sub.depth",param:{symbol:this.symbol,compress:false}}));this.pingTimer=setInterval(()=>{if(socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify({method:"ping"}))},15_000)});socket.addEventListener("message",event=>void this.onSocketMessage(event.data));socket.addEventListener("close",()=>this.socketClosed(socket));socket.addEventListener("error",()=>{if(socket===this.socket)socket.close()});}
 private socketClosed(socket:WebSocket){if(socket!==this.socket)return;this.socket=null;this.wsLive=false;if(this.pingTimer)clearInterval(this.pingTimer);this.pingTimer=null;this.transition(this.latest?"reconnecting":"error");this.scheduleReconnect();}
 private scheduleReconnect(){if(!this.running||this.reconnectTimer)return;this.reconnectTimer=setTimeout(()=>{this.reconnectTimer=null;this.connect()},Math.min(30_000,1_000*2**Math.min(this.failures,5)))}
 private async onSocketMessage(raw:unknown){let value:unknown;try{value=typeof raw==="string"?JSON.parse(raw):JSON.parse(new TextDecoder().decode(raw as ArrayBuffer))}catch{return}const {parseDepthMessage}=await import("./mexc-depth.ts"),update=parseDepthMessage(value,this.symbol);if(!update)return;this.wsMessages++;const current=this.latest?.snapshot.version??-1;if(current>=0&&update.version<=current)return;if(current>=0&&update.version!==current+1){this.gaps++;this.wsLive=false;this.transition("reconnecting");await this.poll(false,true);return}this.applyIncrement(update);this.wsLive=true;this.transition("live");this.publish(this.snapshot(update.version,update.engineTimeMs),this.now(),true)}
 private applyIncrement(update:import("./types.ts").DepthUpdate){for(const [map,levels] of [[this.bids,update.bids],[this.asks,update.asks]] as const)for(const level of levels){if(level.contractQuantity===0)map.delete(level.price);else map.set(level.price,level)}}
 private snapshot(version:number,engineTimeMs:number):DepthSnapshot{return{symbol:this.symbol,version,engineTimeMs,bids:[...this.bids.values()].sort((a,b)=>b.price-a.price),asks:[...this.asks.values()].sort((a,b)=>a.price-b.price)}}
 private publish(snapshot:DepthSnapshot,receivedAt:number,forceHistory=false){const envelope:DepthEnvelope={snapshot,receivedAt,diagnostic:{snapshotAgeMs:0,consecutiveFailures:this.failures,lastError:this.error,...(this.running?{sourceMode:this.sourceMode(),wsMessagesReceived:this.wsMessages,versionGaps:this.gaps,restRecoveries:this.recoveries}:{})}};this.latest=envelope;if(forceHistory||this.lastHistoryAt===null||receivedAt-this.lastHistoryAt>=HISTORY_SAMPLE_MS){this.lastHistoryAt=receivedAt;this.history.push(envelope);const cutoff=receivedAt-HISTORY_MS;while(this.history.length>MAX_HISTORY||this.history[0]?.receivedAt<cutoff)this.history.shift()}this.emitter.emit("envelope",envelope)}
 private async pollScheduled(){await depthRequestLimiter.acquire();if(!this.running)return;await this.poll(true)}
 async poll(scheduled=false,recovery=false){if(this.inFlight)return false;this.inFlight=true;let delay=DEPTH_POLL_MS;try{const response=await this.fetcher(`${REST_BASE}/api/v1/contract/depth/${encodeURIComponent(this.symbol)}?limit=100`,{cache:"no-store",signal:AbortSignal.timeout(TIMEOUT_MS),headers:{accept:"application/json"}});if(!response.ok)throw Error(`MEXC depth HTTP ${response.status}`);const snapshot=normalizeMexcSnapshot(await response.json(),this.symbol),receivedAt=this.now();this.failures=0;this.error=null;if(recovery)this.recoveries++;if(!this.wsLive||recovery||!this.latest){this.bids=new Map(snapshot.bids.map(v=>[v.price,v]));this.asks=new Map(snapshot.asks.map(v=>[v.price,v]));this.publish(snapshot,receivedAt,recovery)}if(!this.socket)this.transition("fallback");}catch(error){this.failures++;this.error=safeError(error);this.transition(this.latest?"reconnecting":"error");delay=Math.min(30_000,DEPTH_POLL_MS*2**Math.min(this.failures,5));}finally{this.inFlight=false;if(scheduled&&this.running)this.timer=setTimeout(()=>void this.pollScheduled(),delay);}return true;}
 getLatest(){return this.latest&&this.running?{...this.latest,diagnostic:{...this.latest.diagnostic,sourceMode:this.sourceMode(),wsMessagesReceived:this.wsMessages,versionGaps:this.gaps,restRecoveries:this.recoveries}}:this.latest;}
 getHistory(){return [...this.history];}
 subscribe(listener:(envelope:DepthEnvelope)=>void){this.emitter.on("envelope",listener);return()=>this.emitter.off("envelope",listener);}
 diagnostic():CollectorDiagnostic&{sourceMode:import("./types.ts").DepthSourceMode;wsMessagesReceived:number;versionGaps:number;restRecoveries:number}{const snapshot=this.latest?.snapshot,lastSuccessAt=this.latest?.receivedAt??null;return{symbol:this.symbol,running:this.running,lastSuccessfulSnapshot:lastSuccessAt,snapshotAgeMs:lastSuccessAt===null?null:Math.max(0,this.now()-lastSuccessAt),lastVersion:snapshot?.version??null,bids:snapshot?.bids.length??0,asks:snapshot?.asks.length??0,consecutiveFailures:this.failures,lastError:this.error,subscribers:this.emitter.listenerCount("envelope"),sourceMode:this.sourceMode(),wsMessagesReceived:this.wsMessages,versionGaps:this.gaps,restRecoveries:this.recoveries};}
}
export class DepthRequestLimiter{private queue:(()=>void)[]=[];private timer:ReturnType<typeof setTimeout>|null=null;private nextAt=0;private intervalMs:number;private now:()=>number;private schedule:(fn:()=>void,ms:number)=>ReturnType<typeof setTimeout>;constructor(intervalMs=250,now=()=>Date.now(),schedule:(fn:()=>void,ms:number)=>ReturnType<typeof setTimeout>=(fn,ms)=>setTimeout(fn,ms)){this.intervalMs=intervalMs;this.now=now;this.schedule=schedule}acquire(){return new Promise<void>(resolve=>{this.queue.push(resolve);this.drain()})}private drain(){if(this.timer||!this.queue.length)return;const wait=Math.max(0,this.nextAt-this.now());this.timer=this.schedule(()=>{this.timer=null;const resolve=this.queue.shift();if(resolve){this.nextAt=Math.max(this.nextAt,this.now())+this.intervalMs;resolve()}this.drain()},wait)}}
export const depthRequestLimiter=new DepthRequestLimiter(250);
const collectors=new Map<string,DepthCollector>();
export function getDepthCollector(symbol:string){let value=collectors.get(symbol);if(!value){value=new DepthCollector(symbol);collectors.set(symbol,value);}value.start();return value;}
