/** DizyFlow Intelligence is a public-data-only, deterministic observation engine. */
export const DIZYFLOW_ENGINE_VERSION = "1.0.0";
export const DIZYFLOW_SCHEMA_VERSION = 1;

export type MarketType = "spot" | "futures";
export type AggressorSide = "buy-aggressor" | "sell-aggressor" | "unknown";
export type OrderBookLevel = Readonly<{ price: number; quantity: number }>;
export type NormalizedPublicTrade = Readonly<{ id: string | null; timeMs: number; price: number; quantity: number; side: AggressorSide }>;
export type OrderFlowFeedState = Readonly<{ connected:boolean;snapshotComplete:boolean;sequenceKnown:boolean;sequenceContinuous:boolean|null;sourceTimestampKnown:boolean;ageMs:number;stale:boolean;bidLevelCount:number;askLevelCount:number;recentTradeCount:number;warnings:readonly string[] }>;
export type ReferencePriceSource="last"|"fair"|"mark"|"midpoint";
export type NormalizedOrderFlowInput = Readonly<{ marketKey:string;symbol:string;marketType:MarketType;exchange:string;exchangeTimeMs:number|null;receivedTimeMs:number;referencePrice:number;referencePriceSource:ReferencePriceSource;tickSize:number|null;quantityStep:number|null;bids:readonly OrderBookLevel[];asks:readonly OrderBookLevel[];recentTrades:readonly NormalizedPublicTrade[];feed:OrderFlowFeedState }>;

export type DizyFlowConfig = Readonly<{ version:number;bandsPct:readonly number[];maxLevelsPerSide:number;maxTrades:number;maxHistory:number;maxHistoryAgeMs:number;staleAfterMs:number;spreadTightPct:number;spreadWidePct:number;wallBandPct:number;wallMedianMultiple:number;wallDepthSharePct:number;wallMinimumNotional:number;wallMinimumNeighbours:number;maxWallsPerSide:number;wallMatchTicks:number;largeTradeMedianMultiple:number;thinDepthRatio:number;gapTicks:number;sweepMinimumLevels:number;sweepMinimumNotional:number;absorptionMinimumEvents:number;absorptionMinimumVolume:number;absorptionMinimumDurationMs:number;materialReductionRatio:number;maxFindings:number }>;
export const DEFAULT_DIZYFLOW_CONFIG:DizyFlowConfig=Object.freeze({version:1,bandsPct:[.1,.25,.5,1],maxLevelsPerSide:200,maxTrades:200,maxHistory:40,maxHistoryAgeMs:180_000,staleAfterMs:5_000,spreadTightPct:.02,spreadWidePct:.1,wallBandPct:1,wallMedianMultiple:3,wallDepthSharePct:20,wallMinimumNotional:0,wallMinimumNeighbours:3,maxWallsPerSide:3,wallMatchTicks:1,largeTradeMedianMultiple:3,thinDepthRatio:.25,gapTicks:5,sweepMinimumLevels:2,sweepMinimumNotional:1,absorptionMinimumEvents:3,absorptionMinimumVolume:1,absorptionMinimumDurationMs:1000,materialReductionRatio:.5,maxFindings:20});

export type DepthBand=Readonly<{bandPct:number;bidQuantity:number;askQuantity:number;bidNotional:number;askNotional:number;bidLevelCount:number;askLevelCount:number;nearestBidPrice:number|null;nearestAskPrice:number|null}>;
export type LiquidityWallCandidate=Readonly<{side:"bid"|"ask";price:number;quantity:number;notional:number;distancePct:number;relativeToMedian:number|null;shareOfBandDepthPct:number|null;classification:"large-visible-level"|"dominant-visible-level";confidence:number;status:"new"|"persisted"|"grown"|"reduced";snapshotCount:number;durationMs:number}>;
export type DizyFlowEvidencePoint=Readonly<{metric:string;value:number|string|null;unit:string|null}>;
export type DizyFlowFinding=Readonly<{code:string;category:"feed"|"spread"|"depth"|"imbalance"|"wall"|"withdrawal"|"replenishment"|"trade-flow"|"sweep"|"absorption"|"thin-liquidity";severity:"information"|"notable"|"caution";title:string;summary:string;evidence:readonly DizyFlowEvidencePoint[];confidence:number;deterministic:true}>;
export type DizyFlowLimitation=Readonly<{code:string;message:string}>;
export type DizyFlowIntelligenceSnapshot=Readonly<{schemaVersion:number;engineVersion:string;configVersion:number;generatedAt:string;marketKey:string;symbol:string;marketType:MarketType;exchangeTimeMs:number|null;receivedTimeMs:number;referencePrice:number;referencePriceSource:ReferencePriceSource;inputHash:string;availability:"available"|"limited"|"stale"|"disconnected";feedQuality:OrderFlowFeedState;spread:Readonly<{bestBid:number|null;bestAsk:number|null;absolute:number|null;percentage:number|null;midpoint:number|null;ticks:number|null;classification:"tight"|"normal"|"wide"|"unavailable"}>;depth:Readonly<{bands:readonly DepthBand[]}>;imbalance:Readonly<{formula:"(bidNotional-askNotional)/(bidNotional+askNotional)";bands:readonly {bandPct:number;value:number|null}[]}>;walls:Readonly<{candidates:readonly LiquidityWallCandidate[];withdrawals:readonly {side:"bid"|"ask";price:number;previousQuantity:number}[];replenishment:readonly {side:"bid"|"ask";price:number;classification:"possible-visible-replenishment"|"repeated-visible-replenishment";eventCount:number}[]}>;liquidity:Readonly<{bidConcentrationNearPct:number|null;askConcentrationNearPct:number|null;nearestBidWallDistancePct:number|null;nearestAskWallDistancePct:number|null;bidLargestLevelSharePct:number|null;askLargestLevelSharePct:number|null;thinSides:readonly ("bid"|"ask")[];bookGaps:readonly {side:"bid"|"ask";fromPrice:number;toPrice:number;distancePct:number}[]}>;trades:Readonly<{available:boolean;buyAggressorVolume:number;sellAggressorVolume:number;unknownVolume:number;aggressorImbalance:number|null;tradeCount:number;averageTradeSize:number|null;sampleDurationMs:number;largeTrades:readonly NormalizedPublicTrade[]}>;absorption:Readonly<{available:boolean;candidates:readonly {side:"bid"|"ask";price:number;tradeVolume:number;classification:"possible-absorption-candidate"}[]}>;sweeps:Readonly<{available:boolean;candidates:readonly {direction:"upward-ask"|"downward-bid";levelCount:number;notional:number;durationMs:number}[]}>;findings:readonly DizyFlowFinding[];limitations:readonly DizyFlowLimitation[];intelligenceConfidence:number;confidenceBand:"high"|"moderate"|"limited"|"insufficient";confidenceReasons:readonly string[]} >;

const finitePositive=(value:number,name:string)=>{if(!Number.isFinite(value)||value<=0)throw new TypeError(`${name} must be finite and positive`);return value};
const optionalPositive=(value:number|null,name:string)=>value===null?null:finitePositive(value,name);
const stable=(value:unknown):string=>{if(Array.isArray(value))return `[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return `{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(",")}}`;return JSON.stringify(value)};
export const deterministicHash=(value:unknown)=>{let hash=2166136261;for(const char of stable(value)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619)}return `fnv1a-${(hash>>>0).toString(16).padStart(8,"0")}`};
const median=(values:readonly number[])=>{if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2};
const round=(value:number,places=10)=>Number(value.toFixed(places));

export function normalizeOrderFlowInput(raw:NormalizedOrderFlowInput,config=DEFAULT_DIZYFLOW_CONFIG):NormalizedOrderFlowInput{
 if(!raw.marketKey?.trim()||!raw.symbol?.trim()||!raw.exchange?.trim())throw new TypeError("market identity is required");
 if(raw.marketType!=="spot"&&raw.marketType!=="futures")throw new TypeError("market type is invalid");
 finitePositive(raw.receivedTimeMs,"received time");finitePositive(raw.referencePrice,"reference price");optionalPositive(raw.tickSize,"tick size");optionalPositive(raw.quantityStep,"quantity step");
 if(raw.exchangeTimeMs!==null)finitePositive(raw.exchangeTimeMs,"exchange time");
 const levels=(input:readonly OrderBookLevel[],side:"bid"|"ask")=>{const map=new Map<number,number>();for(const level of input){finitePositive(level.price,`${side} price`);finitePositive(level.quantity,`${side} quantity`);map.set(level.price,(map.get(level.price)??0)+level.quantity)}return [...map].map(([price,quantity])=>({price,quantity:round(quantity)})).sort((a,b)=>side==="bid"?b.price-a.price:a.price-b.price).slice(0,config.maxLevelsPerSide)};
 const bids=levels(raw.bids,"bid"),asks=levels(raw.asks,"ask");if(bids.length&&asks.length&&bids[0].price>=asks[0].price)throw new TypeError("crossed or inverted book");
 const seen=new Set<string>(),recentTrades:NormalizedPublicTrade[]=[];for(const trade of [...raw.recentTrades].sort((a,b)=>a.timeMs-b.timeMs||a.price-b.price||a.quantity-b.quantity||a.side.localeCompare(b.side))){finitePositive(trade.timeMs,"trade time");finitePositive(trade.price,"trade price");finitePositive(trade.quantity,"trade quantity");if(!["buy-aggressor","sell-aggressor","unknown"].includes(trade.side))throw new TypeError("trade side is invalid");const key=trade.id?`id:${trade.id}`:`composite:${trade.timeMs}:${trade.price}:${trade.quantity}:${trade.side}`;if(!seen.has(key)){seen.add(key);recentTrades.push({...trade})}}
 const trades=recentTrades.slice(-config.maxTrades),warnings=[...new Set(raw.feed.warnings.map(String))].sort();
 const feed={...raw.feed,ageMs:Math.max(0,raw.feed.ageMs),stale:raw.feed.stale||raw.feed.ageMs>config.staleAfterMs,bidLevelCount:bids.length,askLevelCount:asks.length,recentTradeCount:trades.length,warnings};
 return {...raw,marketKey:raw.marketKey.trim(),symbol:raw.symbol.trim(),exchange:raw.exchange.trim(),bids,asks,recentTrades:trades,feed};
}

const band=(input:NormalizedOrderFlowInput,pct:number):DepthBand=>{const low=input.referencePrice*(1-pct/100),high=input.referencePrice*(1+pct/100),b=input.bids.filter(x=>x.price>=low&&x.price<=input.referencePrice),a=input.asks.filter(x=>x.price<=high&&x.price>=input.referencePrice);return {bandPct:pct,bidQuantity:round(b.reduce((s,x)=>s+x.quantity,0)),askQuantity:round(a.reduce((s,x)=>s+x.quantity,0)),bidNotional:round(b.reduce((s,x)=>s+x.quantity*x.price,0)),askNotional:round(a.reduce((s,x)=>s+x.quantity*x.price,0)),bidLevelCount:b.length,askLevelCount:a.length,nearestBidPrice:b[0]?.price??null,nearestAskPrice:a[0]?.price??null}};
function candidateWalls(input:NormalizedOrderFlowInput,side:"bid"|"ask",config:DizyFlowConfig,history:readonly NormalizedOrderFlowInput[]):LiquidityWallCandidate[]{const levels=(side==="bid"?input.bids:input.asks).filter(x=>Math.abs(x.price-input.referencePrice)/input.referencePrice*100<=config.wallBandPct),notionals=levels.map(x=>x.price*x.quantity),med=median(notionals),total=notionals.reduce((a,b)=>a+b,0);if(levels.length<config.wallMinimumNeighbours)return [];return levels.flatMap((level):LiquidityWallCandidate[]=>{const notional=level.price*level.quantity,relative=med&&med>0?notional/med:null,share=total?notional/total*100:null;if(notional<config.wallMinimumNotional||!((relative??0)>=config.wallMedianMultiple||(share??0)>=config.wallDepthSharePct))return [];const tolerance=input.tickSize?input.tickSize*config.wallMatchTicks:input.referencePrice*.00005,matches=history.filter(h=>h.feed.sequenceContinuous!==false&&!h.feed.stale).map(h=>(side==="bid"?h.bids:h.asks).find(x=>Math.abs(x.price-level.price)<=tolerance)).filter((x):x is OrderBookLevel=>Boolean(x)),first=history.find(h=>(side==="bid"?h.bids:h.asks).some(x=>Math.abs(x.price-level.price)<=tolerance)),previous=matches.at(-1),status=!previous?"new":level.quantity>previous.quantity*1.1?"grown":level.quantity<previous.quantity*.9?"reduced":"persisted";return [{side,price:level.price,quantity:level.quantity,notional:round(notional),distancePct:round(Math.abs(level.price-input.referencePrice)/input.referencePrice*100),relativeToMedian:relative===null?null:round(relative),shareOfBandDepthPct:share===null?null:round(share),classification:(share??0)>=config.wallDepthSharePct?"dominant-visible-level":"large-visible-level",confidence:input.feed.sequenceContinuous===true?80:60,status,snapshotCount:matches.length+1,durationMs:first?Math.max(0,input.receivedTimeMs-first.receivedTimeMs):0}] }).sort((a,b)=>(b.shareOfBandDepthPct??0)-(a.shareOfBandDepthPct??0)||a.distancePct-b.distancePct||a.price-b.price).slice(0,config.maxWallsPerSide)}

export function buildDizyFlowIntelligenceSnapshot(args:{current:NormalizedOrderFlowInput;history:readonly NormalizedOrderFlowInput[];config?:DizyFlowConfig;generatedAt:string}):DizyFlowIntelligenceSnapshot{
 const config=args.config??DEFAULT_DIZYFLOW_CONFIG;if(!Number.isFinite(Date.parse(args.generatedAt)))throw new TypeError("generatedAt must be an ISO timestamp");const current=normalizeOrderFlowInput(args.current,config);const history=args.history.map(x=>normalizeOrderFlowInput(x,config)).filter(x=>x.marketKey===current.marketKey&&x.symbol===current.symbol&&x.referencePriceSource===current.referencePriceSource&&!x.feed.stale&&x.receivedTimeMs<current.receivedTimeMs&&current.receivedTimeMs-x.receivedTimeMs<=config.maxHistoryAgeMs).sort((a,b)=>a.receivedTimeMs-b.receivedTimeMs).slice(-config.maxHistory);
 const bestBid=current.bids[0]?.price??null,bestAsk=current.asks[0]?.price??null,absolute=bestBid!==null&&bestAsk!==null?bestAsk-bestBid:null,midpoint=absolute===null?null:(bestBid!+bestAsk!)/2,percentage=absolute===null||midpoint===null||midpoint===0?null:absolute/midpoint*100,ticks=absolute!==null&&current.tickSize?absolute/current.tickSize:null,classification=percentage===null?"unavailable":percentage<=config.spreadTightPct?"tight":percentage>=config.spreadWidePct?"wide":"normal";
 const bands=config.bandsPct.map(p=>band(current,p)),imbalances=bands.map(x=>({bandPct:x.bandPct,value:x.bidNotional+x.askNotional?round((x.bidNotional-x.askNotional)/(x.bidNotional+x.askNotional)):null}));
 const candidates=[...candidateWalls(current,"bid",config,history),...candidateWalls(current,"ask",config,history)];const previous=history.at(-1);const tolerance=current.tickSize?current.tickSize*config.wallMatchTicks*1.000001:current.referencePrice*.00005;const previousWalls=previous?[...candidateWalls(previous,"bid",config,history.slice(0,-1)),...candidateWalls(previous,"ask",config,history.slice(0,-1))]:[];const withdrawals=current.feed.sequenceContinuous===true?previousWalls.filter(w=>!candidates.some(c=>c.side===w.side&&Math.abs(c.price-w.price)<=tolerance)).map(w=>({side:w.side,price:w.price,previousQuantity:w.quantity})).slice(0,6):[];
 const tradeVolumes={buy:0,sell:0,unknown:0};for(const t of current.recentTrades)tradeVolumes[t.side==="buy-aggressor"?"buy":t.side==="sell-aggressor"?"sell":"unknown"]+=t.quantity;const known=tradeVolumes.buy+tradeVolumes.sell,tradeMedian=median(current.recentTrades.map(t=>t.quantity)),largeTrades=current.recentTrades.filter(t=>tradeMedian&&t.quantity>=tradeMedian*config.largeTradeMedianMultiple).slice(-10),tradeDuration=current.recentTrades.length>1?current.recentTrades.at(-1)!.timeMs-current.recentTrades[0].timeMs:0;
 const outer=bands.at(-1),near=bands.find(x=>x.bandPct===.25)??bands[0];const ratio=(nearValue:number,outerValue:number)=>outerValue?round(nearValue/outerValue*100):null,largest=(levels:readonly OrderBookLevel[],total:number)=>total?round(Math.max(0,...levels.map(x=>x.price*x.quantity))/total*100):null;const gaps=(side:"bid"|"ask")=>(side==="bid"?current.bids:current.asks).slice(0,50).flatMap((x,i,a)=>{const next=a[i+1];if(!next)return [];const distance=Math.abs(x.price-next.price),large=current.tickSize?distance/current.tickSize>=config.gapTicks:distance/current.referencePrice*100>=.1;return large?[{side,fromPrice:x.price,toPrice:next.price,distancePct:round(distance/current.referencePrice*100)}]:[]}).slice(0,3);const thinSides: ("bid"|"ask")[]=[];if(outer&&outer.askNotional&&outer.bidNotional<outer.askNotional*config.thinDepthRatio)thinSides.push("bid");if(outer&&outer.bidNotional&&outer.askNotional<outer.bidNotional*config.thinDepthRatio)thinSides.push("ask");
 const continuity=current.feed.sequenceContinuous===true&&current.feed.snapshotComplete&&!current.feed.stale;
 const sweepCandidates: {direction:"upward-ask"|"downward-bid";levelCount:number;notional:number;durationMs:number}[]=[];
 if(continuity&&previous&&previous.feed.sequenceContinuous===true&&current.recentTrades.length>=config.sweepMinimumLevels){const eventTolerance=current.tickSize?current.tickSize*.25:tolerance;for(const [aggressor,direction,side] of [["buy-aggressor","upward-ask","ask"],["sell-aggressor","downward-bid","bid"]] as const){const trades=current.recentTrades.filter(t=>t.side===aggressor),duration=trades.length>1?trades.at(-1)!.timeMs-trades[0].timeMs:0,prior=side==="ask"?previous.asks:previous.bids,currentLevels=side==="ask"?current.asks:current.bids;const consumed=prior.filter(level=>{const after=currentLevels.find(x=>Math.abs(x.price-level.price)<=eventTolerance);return !after||after.quantity<=level.quantity*config.materialReductionRatio}).filter(level=>trades.some(t=>Math.abs(t.price-level.price)<=eventTolerance));const notional=trades.filter(t=>consumed.some(level=>Math.abs(t.price-level.price)<=eventTolerance)).reduce((sum,t)=>sum+t.price*t.quantity,0);if(consumed.length>=config.sweepMinimumLevels&&duration<=5_000&&notional>=config.sweepMinimumNotional)sweepCandidates.push({direction,levelCount:consumed.length,notional:round(notional),durationMs:duration})}}
 const absorptionCandidates: {side:"bid"|"ask";price:number;tradeVolume:number;classification:"possible-absorption-candidate"}[]=[];
 if(continuity&&previous&&previous.feed.sequenceContinuous===true&&tradeDuration>=config.absorptionMinimumDurationMs){for(const side of ["bid","ask"] as const){const priorLevels=side==="bid"?previous.bids:previous.asks,currentLevels=side==="bid"?current.bids:current.asks,aggressor=side==="bid"?"sell-aggressor":"buy-aggressor";for(const prior of priorLevels.slice(0,10)){const level=currentLevels.find(x=>Math.abs(x.price-prior.price)<=tolerance);if(!level)continue;const trades=current.recentTrades.filter(t=>t.side===aggressor&&Math.abs(t.price-prior.price)<=tolerance),volume=trades.reduce((sum,t)=>sum+t.quantity,0),progressed=side==="bid"?current.referencePrice<prior.price-tolerance:current.referencePrice>prior.price+tolerance,stable=level.quantity>=prior.quantity*config.materialReductionRatio;if(trades.length>=config.absorptionMinimumEvents&&volume>=config.absorptionMinimumVolume&&!progressed&&stable){absorptionCandidates.push({side,price:prior.price,tradeVolume:round(volume),classification:"possible-absorption-candidate"});break}}}}
 const replenishment=continuity&&previous?candidates.flatMap(w=>{const prior=(w.side==="bid"?previous.bids:previous.asks).find(x=>Math.abs(x.price-w.price)<=tolerance),trades=current.recentTrades.filter(t=>Math.abs(t.price-w.price)<=tolerance&&t.side===(w.side==="bid"?"sell-aggressor":"buy-aggressor"));return prior&&trades.length>=2&&w.quantity>=prior.quantity*.9?[{side:w.side,price:w.price,classification:(trades.length>=4?"repeated-visible-replenishment":"possible-visible-replenishment") as "possible-visible-replenishment"|"repeated-visible-replenishment",eventCount:trades.length}]:[]}):[];
 let confidence=100;const reasons:string[]=[];const deduct=(amount:number,reason:string)=>{confidence-=amount;reasons.push(reason)};if(!current.feed.connected)deduct(100,"Feed is disconnected.");else{if(current.feed.stale)deduct(55,"Snapshot is stale.");if(!current.feed.snapshotComplete)deduct(25,"Order-book snapshot is incomplete.");if(!current.feed.sequenceKnown)deduct(10,"Exchange sequence is unknown.");else if(current.feed.sequenceContinuous!==true)deduct(25,"Exchange sequence continuity is not confirmed.");if(!current.feed.sourceTimestampKnown)deduct(10,"Exchange source timestamp is unavailable.");if(current.bids.length<10||current.asks.length<10)deduct(15,"Visible book depth is shallow.");if(!current.recentTrades.length)deduct(10,"Recent public trades are unavailable.");if(!current.tickSize)deduct(5,"Tick size is unavailable.");if(history.length<2)deduct(5,"Temporal observation history is limited.")}confidence=Math.max(0,Math.min(100,confidence));const confidenceBand=confidence>=80?"high":confidence>=55?"moderate":confidence>=25?"limited":"insufficient",availability=!current.feed.connected?"disconnected":current.feed.stale?"stale":!current.feed.snapshotComplete||!current.bids.length||!current.asks.length?"limited":"available";
 const limitations:DizyFlowLimitation[]=[{code:"VISIBLE_PUBLIC_DATA_ONLY",message:"Observations use only bounded visible public market data; hidden liquidity and participant identity are not observable."}];if(!current.recentTrades.length)limitations.push({code:"TRADE_FLOW_UNAVAILABLE",message:"Recent public trades are unavailable, so trade-flow, sweep and absorption observations are unavailable."});if(!continuity)limitations.push({code:"TEMPORAL_CONTINUITY_LIMITED",message:"Continuous book sequencing is not confirmed; temporal event classifications are suppressed."});if(!current.feed.snapshotComplete)limitations.push({code:"INCOMPLETE_BOOK",message:"The visible book snapshot is incomplete; levels outside the retained book are not analysed."});
 const findings:DizyFlowFinding[]=[];const add=(finding:DizyFlowFinding)=>{if(current.feed.connected&&!current.feed.stale&&!findings.some(x=>x.code===finding.code)&&findings.length<config.maxFindings)findings.push(finding)};if(percentage!==null)add({code:`SPREAD_${classification.toUpperCase()}`,category:"spread",severity:classification==="wide"?"caution":"information",title:`${classification[0].toUpperCase()+classification.slice(1)} visible spread`,summary:`The visible spread was ${round(percentage,6)}% at the sampled time; this does not imply future direction.`,evidence:[{metric:"spreadPct",value:round(percentage,6),unit:"percent"}],confidence,deterministic:true});for(const x of imbalances){if(x.value!==null&&Math.abs(x.value)>=.2)add({code:`VISIBLE_DEPTH_IMBALANCE_${x.bandPct}`,category:"imbalance",severity:"notable",title:"Visible depth imbalance",summary:`Visible ${x.value>0?"bid":"ask"} depth exceeded the opposite side within ${x.bandPct}%.`,evidence:[{metric:"centredImbalance",value:x.value,unit:"ratio"},{metric:"bandPct",value:x.bandPct,unit:"percent"}],confidence,deterministic:true})}for(const w of candidates)add({code:`VISIBLE_WALL_${w.side.toUpperCase()}_${w.price}`,category:"wall",severity:"notable",title:"Visible wall candidate",summary:`A ${w.classification} was observed on the ${w.side} side ${w.distancePct}% from the ${current.referencePriceSource} reference price.`,evidence:[{metric:"price",value:w.price,unit:"quote"},{metric:"notional",value:w.notional,unit:"quote"}],confidence:w.confidence,deterministic:true});for(const w of withdrawals)add({code:`VISIBLE_WITHDRAWAL_${w.side.toUpperCase()}_${w.price}`,category:"withdrawal",severity:"notable",title:"Visible level withdrawal",summary:`A previously visible ${w.side} concentration was no longer present in the continuous comparison.`,evidence:[{metric:"price",value:w.price,unit:"quote"},{metric:"previousQuantity",value:w.previousQuantity,unit:"quantity"}],confidence,deterministic:true});
 const hashPayload={engineVersion:DIZYFLOW_ENGINE_VERSION,configVersion:config.version,current,history};
 return {schemaVersion:DIZYFLOW_SCHEMA_VERSION,engineVersion:DIZYFLOW_ENGINE_VERSION,configVersion:config.version,generatedAt:args.generatedAt,marketKey:current.marketKey,symbol:current.symbol,marketType:current.marketType,exchangeTimeMs:current.exchangeTimeMs,receivedTimeMs:current.receivedTimeMs,referencePrice:current.referencePrice,referencePriceSource:current.referencePriceSource,inputHash:deterministicHash(hashPayload),availability,feedQuality:current.feed,spread:{bestBid,bestAsk,absolute:absolute===null?null:round(absolute),percentage:percentage===null?null:round(percentage),midpoint:midpoint===null?null:round(midpoint),ticks:ticks===null?null:round(ticks),classification},depth:{bands},imbalance:{formula:"(bidNotional-askNotional)/(bidNotional+askNotional)",bands:imbalances},walls:{candidates,withdrawals,replenishment},liquidity:{bidConcentrationNearPct:outer&&near?ratio(near.bidNotional,outer.bidNotional):null,askConcentrationNearPct:outer&&near?ratio(near.askNotional,outer.askNotional):null,nearestBidWallDistancePct:candidates.filter(x=>x.side==="bid")[0]?.distancePct??null,nearestAskWallDistancePct:candidates.filter(x=>x.side==="ask")[0]?.distancePct??null,bidLargestLevelSharePct:outer?largest(current.bids,outer.bidNotional):null,askLargestLevelSharePct:outer?largest(current.asks,outer.askNotional):null,thinSides,bookGaps:[...gaps("bid"),...gaps("ask")]},trades:{available:current.recentTrades.length>0,buyAggressorVolume:round(tradeVolumes.buy),sellAggressorVolume:round(tradeVolumes.sell),unknownVolume:round(tradeVolumes.unknown),aggressorImbalance:known?round((tradeVolumes.buy-tradeVolumes.sell)/known):null,tradeCount:current.recentTrades.length,averageTradeSize:current.recentTrades.length?round((known+tradeVolumes.unknown)/current.recentTrades.length):null,sampleDurationMs:tradeDuration,largeTrades},absorption:{available:continuity&&current.recentTrades.length>0,candidates:absorptionCandidates},sweeps:{available:continuity&&current.recentTrades.length>0,candidates:sweepCandidates},findings,limitations,intelligenceConfidence:confidence,confidenceBand,confidenceReasons:reasons};
}

/** Short live context only: no persistence, storage, Replay, Journal, or Behaviour coupling. */
export class DizyFlowLiveHistory{private values:NormalizedOrderFlowInput[]=[];private identity:string|null=null;resets=0;constructor(private config:DizyFlowConfig=DEFAULT_DIZYFLOW_CONFIG){}push(raw:NormalizedOrderFlowInput){const value=normalizeOrderFlowInput(raw,this.config),identity=`${value.marketKey}|${value.symbol}|${value.referencePriceSource}`;if(this.identity!==identity||value.feed.sequenceContinuous===false){this.values=[];this.resets++;this.identity=identity}this.values=this.values.filter(x=>value.receivedTimeMs-x.receivedTimeMs<=this.config.maxHistoryAgeMs&&!x.feed.stale).concat(value).slice(-this.config.maxHistory);return value}prior(){return this.values.slice(0,-1)}clear(){this.values=[];this.identity=null;this.resets++}size(){return this.values.length}resetCount(){return this.resets}}

export type DizyFlowEvidenceReference=Readonly<{available:boolean;snapshotTimeMs:number|null;inputHash:string|null;confidence:number|null;findingCodes:readonly string[]}>;
export const toDizyFlowEvidenceReference=(snapshot:DizyFlowIntelligenceSnapshot|null):DizyFlowEvidenceReference=>snapshot?{available:snapshot.availability==="available",snapshotTimeMs:snapshot.receivedTimeMs,inputHash:snapshot.inputHash,confidence:snapshot.intelligenceConfidence,findingCodes:snapshot.findings.map(x=>x.code).slice(0,10)}:{available:false,snapshotTimeMs:null,inputHash:null,confidence:null,findingCodes:[]};
export type CompactDizyFlowCapture=Readonly<{snapshotTimeMs:number;marketKey:string;symbol:string;referencePrice:number;inputHash:string;confidence:number;findingCodes:readonly string[];keyMetrics:Readonly<{spreadPct:number|null;nearImbalance:number|null;bidWallPrice:number|null;askWallPrice:number|null;tradeFlowImbalance:number|null}>}>;
