import type {CompactLiquidityChange,LiquidityTileCell,LiquidityTileResponse} from "./types.ts";
import {expandHeatmapDetectionRange,readHeatmapDisplayTuning} from "./heatmap.ts";

export type LiquidityViewport={from:number;to:number;minPrice:number;maxPrice:number;effectiveTimeBucketMs:number;effectivePriceStep:number;retentionMs?:number};
export type LiquidityCacheStatus="idle"|"loading"|"connected"|"unchanged"|"resynchronising"|"disconnected"|"gap";
export type LiquidityMetadata={priceStep:number;coverage:{archiveStartMs:number|null;archiveEndMs:number|null;hasGaps:boolean};diagnostic?:{sequence?:number}};
export type LiquidityCacheSnapshot={cells:readonly LiquidityTileCell[];endState:readonly CompactLiquidityChange[];priceStep:number;timeBucketMs:number;requests:number;requestsStarted:number;requestsCompleted:number;requestsAborted:number;requestsFailed:number;hits:number;misses:number;loadedFrom:number|null;loadedTo:number|null;archiveFrom:number|null;archiveTo:number|null;hasGap:boolean;sequence:number|null;status:LiquidityCacheStatus;revision:number;liveRevision:number;lastTileError:string|null;lastTileHttpStatus:number|null;lastRequestedTileRange:{from:number;to:number}|null;lastSuccessfulTileRange:{from:number;to:number}|null};
type Range={key:string;from:number;to:number;cells:LiquidityTileCell[];used:number};
const MAX_CELLS=40_000,MAX_RANGES=24,CHUNK_MS=6*60*60_000,keyFor=(exchange:string,symbol:string)=>`${exchange.toLowerCase()}:${symbol.toUpperCase()}`;

export class LiquidityHistoryCache{
 readonly exchange:string;readonly symbol:string;private maximumCells:number;private ranges=new Map<string,Range>();private listeners=new Set<()=>void>();private controller:AbortController|null=null;private groupId=0;private groupKey="";private requestsStarted=0;private requestsCompleted=0;private requestsAborted=0;private requestsFailed=0;private hits=0;private misses=0;private priceStep=1;private timeBucketMs=5000;private archiveFrom:number|null=null;private archiveTo:number|null=null;private hasGap=false;private sequence:number|null=null;private status:LiquidityCacheStatus="idle";private revision=0;private liveRevision=0;private endState:CompactLiquidityChange[]=[];private lastTileError:string|null=null;private lastTileHttpStatus:number|null=null;private lastRequestedTileRange:{from:number;to:number}|null=null;private lastSuccessfulTileRange:{from:number;to:number}|null=null;
 constructor(exchange:string,symbol:string,maximumCells=MAX_CELLS){this.exchange=exchange;this.symbol=symbol.toUpperCase();this.maximumCells=maximumCells}
 subscribe=(listener:()=>void)=>{this.listeners.add(listener);return()=>this.listeners.delete(listener)};private emit(){this.listeners.forEach(v=>v())}
 snapshot():LiquidityCacheSnapshot{const ranges=[...this.ranges.values()],cells=ranges.flatMap(v=>v.cells).sort((a,b)=>a.fromMs-b.fromMs||a.price-b.price),loadedFrom=ranges.length?Math.min(...ranges.map(v=>v.from)):null,loadedTo=ranges.length?Math.max(...ranges.map(v=>v.to)):null;return{cells,endState:this.endState,priceStep:this.priceStep,timeBucketMs:this.timeBucketMs,requests:this.requestsCompleted,requestsStarted:this.requestsStarted,requestsCompleted:this.requestsCompleted,requestsAborted:this.requestsAborted,requestsFailed:this.requestsFailed,hits:this.hits,misses:this.misses,loadedFrom,loadedTo,archiveFrom:this.archiveFrom,archiveTo:this.archiveTo,hasGap:this.hasGap,sequence:this.sequence,status:this.status,revision:this.revision,liveRevision:this.liveRevision,lastTileError:this.lastTileError,lastTileHttpStatus:this.lastTileHttpStatus,lastRequestedTileRange:this.lastRequestedTileRange,lastSuccessfulTileRange:this.lastSuccessfulTileRange}}
 applyMetadata(metadata:LiquidityMetadata){this.priceStep=metadata.priceStep||this.priceStep;this.archiveFrom=metadata.coverage.archiveStartMs;this.archiveTo=metadata.coverage.archiveEndMs;this.hasGap=metadata.coverage.hasGaps;this.sequence=metadata.diagnostic?.sequence??this.sequence;this.status="connected";this.emit()}
 private evict(){let total=[...this.ranges.values()].reduce((n,v)=>n+v.cells.length,0);while(this.ranges.size>MAX_RANGES||total>this.maximumCells){const oldest=[...this.ranges.values()].sort((a,b)=>a.used-b.used)[0];if(!oldest)break;this.ranges.delete(oldest.key);total-=oldest.cells.length}}
 async ensure(view:LiquidityViewport,fetcher:typeof fetch=fetch){
  if(!Number.isFinite(view.from)||!Number.isFinite(view.to)||view.to<=view.from||view.minPrice<=0||view.maxPrice<=view.minPrice)return;
  const bucket=Math.max(5000,view.effectiveTimeBucketMs),viewportFrom=Math.floor(Math.max(0,view.from)/bucket)*bucket,viewportTo=Math.ceil(view.to/bucket)*bucket;
  // Until SSE metadata arrives, retention bounds the request and prevents an arbitrarily large chart query.
  const fallbackFrom=viewportTo-(view.retentionMs??6*60*60_000),from=Math.max(viewportFrom,this.archiveFrom??fallbackFrom),to=Math.min(viewportTo,this.archiveTo??viewportTo);
  this.lastRequestedTileRange={from,to};
  if(to<=from){this.status="unchanged";this.lastTileError=null;this.lastTileHttpStatus=null;this.emit();return}
  const tuning=readHeatmapDisplayTuning(),expanded=expandHeatmapDetectionRange(view.minPrice,view.maxPrice,tuning.detectionRangeBps),pricePad=(expanded.maxPrice-expanded.minPrice)*.02,minPrice=Math.max(1e-8,expanded.minPrice-pricePad),maxPrice=expanded.maxPrice+pricePad;
  const chunks:{from:number;to:number;key:string}[]=[];for(let start=Math.floor(from/CHUNK_MS)*CHUNK_MS;start<to;start+=CHUNK_MS){const chunkFrom=Math.max(from,start),chunkTo=Math.min(to,start+CHUNK_MS),key=[chunkFrom,chunkTo,minPrice.toPrecision(8),maxPrice.toPrecision(8),bucket,view.effectivePriceStep].join(":");chunks.push({from:chunkFrom,to:chunkTo,key})}
  const nextGroupKey=chunks.map(v=>v.key).join("|");if(nextGroupKey===this.groupKey&&this.status==="loading")return;
  if(this.controller){this.controller.abort();this.requestsAborted++;}
  this.controller=new AbortController();this.groupKey=nextGroupKey;const controller=this.controller,id=++this.groupId;
  const missing=chunks.filter(chunk=>{const found=this.ranges.get(chunk.key);if(found){found.used=Date.now();this.hits++;return false}this.misses++;return true});
  if(!missing.length){this.status=this.hasGap?"gap":"unchanged";this.emit();return}
  this.status="loading";this.lastTileError=null;this.lastTileHttpStatus=null;this.emit();let cursor=0;
  const worker=async()=>{while(cursor<missing.length){const chunk=missing[cursor++];this.requestsStarted++;this.lastRequestedTileRange={from:chunk.from,to:chunk.to};this.emit();try{const query=new URLSearchParams({symbol:this.symbol,fromMs:String(chunk.from),toMs:String(chunk.to),minPrice:String(minPrice),maxPrice:String(maxPrice),timeBucketMs:String(bucket),priceStep:String(view.effectivePriceStep)}),response=await fetcher(`/api/dizyflow/heatmap/tiles?${query}`,{signal:controller.signal});if(!response.ok){let message="";try{const body=await response.json() as {error?:string};message=body.error?.slice(0,240)??""}catch{}const error=Error(`HTTP ${response.status}${message?`: ${message}`:""}`);Object.assign(error,{status:response.status});throw error}const tile=await response.json() as LiquidityTileResponse;if(id!==this.groupId)return;this.requestsCompleted++;this.priceStep=tile.priceStep;this.timeBucketMs=tile.timeBucketMs;this.archiveFrom=tile.capturedFromMs??this.archiveFrom;this.archiveTo=tile.capturedToMs??this.archiveTo;this.hasGap=this.hasGap||tile.hasGaps;this.endState=tile.endState;this.ranges.set(chunk.key,{key:chunk.key,from:chunk.from,to:chunk.to,cells:tile.cells,used:Date.now()});this.lastSuccessfulTileRange={from:chunk.from,to:chunk.to};this.evict();this.revision++;this.emit()}catch(error){if(controller.signal.aborted)return;this.requestsFailed++;this.lastTileHttpStatus=typeof error==="object"&&error!==null&&"status" in error?Number(error.status):null;this.lastTileError=error instanceof Error?error.message:"Tile request failed";this.status="disconnected";this.emit();throw error}}};
  try{await Promise.all(Array.from({length:Math.min(2,missing.length)},worker));if(id===this.groupId){this.status=this.hasGap?"gap":"connected";this.lastTileError=null;this.lastTileHttpStatus=null;this.emit()}}finally{if(this.controller===controller)this.controller=null}
 }
 mergeLive(changes:readonly CompactLiquidityChange[],sequence:number|null,priceStep=this.priceStep){if(sequence!==null&&this.sequence!==null&&sequence!==this.sequence+1){this.status="resynchronising";this.sequence=sequence;this.ranges.clear();this.revision++;this.emit();return false}this.priceStep=priceStep;this.sequence=sequence??this.sequence;for(const change of changes){const i=this.endState.findIndex(v=>v.priceTick===change.priceTick);if(i>=0)this.endState[i]=change;else this.endState.push(change)}this.liveRevision++;this.revision++;this.status="connected";this.emit();return true}
 markDisconnected(){this.status="disconnected";this.emit()}markResynchronising(){this.status="resynchronising";this.emit()}abort(){if(this.controller){this.controller.abort();this.requestsAborted++;this.controller=null;this.emit()}}
}
const caches=new Map<string,LiquidityHistoryCache>();export function liquidityHistoryCache(exchange:string,symbol:string){const key=keyFor(exchange,symbol);let cache=caches.get(key);if(!cache){cache=new LiquidityHistoryCache(exchange,symbol);caches.set(key,cache)}return cache}
