import type {CompactLiquidityChange} from "./types.ts";

export type LiquidityHistoryPage={symbol:string;priceStep:number;seed?:CompactLiquidityChange[];changes:CompactLiquidityChange[];nextCursor:string|null;coverage?:{archiveStartMs:number|null;archiveEndMs:number|null;hasGaps:boolean}};
export type LiquidityCacheStatus="idle"|"loading"|"connected"|"unchanged"|"resynchronising"|"disconnected"|"gap";
export type LiquidityCacheSnapshot={records:readonly CompactLiquidityChange[];priceStep:number;pages:number;loadedFrom:number|null;loadedTo:number|null;archiveFrom:number|null;archiveTo:number|null;hasGap:boolean;sequence:number|null;status:LiquidityCacheStatus;revision:number;liveRevision:number;lastLive:readonly CompactLiquidityChange[]};
type Span={from:number;to:number};
const MAX_RECORDS=40_000,MAX_SPANS=24,OVERSCAN=.35;
const keyFor=(exchange:string,symbol:string)=>`${exchange.toLowerCase()}:${symbol.toUpperCase()}`;
const mergeSpans=(spans:Span[])=>{const sorted=[...spans].sort((a,b)=>a.from-b.from),out:Span[]=[];for(const span of sorted){const last=out.at(-1);if(last&&span.from<=last.to+1)last.to=Math.max(last.to,span.to);else out.push({...span})}return out};

/** Exchange/symbol cache. Candle timeframe deliberately is not part of its identity. */
export class LiquidityHistoryCache{
 readonly exchange:string;readonly symbol:string;private maximumRecords:number;
 private records=new Map<string,CompactLiquidityChange>();private spans:Span[]=[];private listeners=new Set<()=>void>();private controller:AbortController|null=null;private requestId=0;private pageCount=0;private priceStep=1;private archiveFrom:number|null=null;private archiveTo:number|null=null;private hasGap=false;private sequence:number|null=null;private status:LiquidityCacheStatus="idle";private revision=0;private liveRevision=0;private lastLive:readonly CompactLiquidityChange[]=[];
 constructor(exchange:string,symbol:string,maximumRecords=MAX_RECORDS){this.exchange=exchange;this.symbol=symbol;this.maximumRecords=maximumRecords}
 subscribe=(listener:()=>void)=>{this.listeners.add(listener);return()=>this.listeners.delete(listener)};private emit(){this.listeners.forEach(v=>v())}
 snapshot():LiquidityCacheSnapshot{const bounds=this.spans.length?{from:this.spans[0].from,to:this.spans.at(-1)!.to}:null;return{records:[...this.records.values()].sort((a,b)=>a.timestampMs-b.timestampMs||a.priceTick-b.priceTick),priceStep:this.priceStep,pages:this.pageCount,loadedFrom:bounds?.from??null,loadedTo:bounds?.to??null,archiveFrom:this.archiveFrom,archiveTo:this.archiveTo,hasGap:this.hasGap,sequence:this.sequence,status:this.status,revision:this.revision,liveRevision:this.liveRevision,lastLive:this.lastLive}}
 private ingest(records:readonly CompactLiquidityChange[]){for(const value of records)this.records.set(`${value.timestampMs}:${value.priceTick}`,value);this.revision++}
 private evict(centre:number){if(this.records.size<=this.maximumRecords)return;const ordered=[...this.records.entries()].sort((a,b)=>Math.abs(a[1].timestampMs-centre)-Math.abs(b[1].timestampMs-centre));this.records=new Map(ordered.slice(0,this.maximumRecords));let min=Infinity,max=-Infinity;for(const value of this.records.values()){min=Math.min(min,value.timestampMs);max=Math.max(max,value.timestampMs)}if(Number.isFinite(min))this.spans=[{from:min,to:max}]}
 covers(from:number,to:number){return this.spans.some(span=>span.from<=from&&span.to>=to)}
 async ensure(from:number,to:number,fetcher:typeof fetch=fetch){if(!Number.isFinite(from)||!Number.isFinite(to)||to<=from)return;const padding=(to-from)*OVERSCAN,wanted={from:Math.max(0,Math.floor(from-padding)),to:Math.ceil(to+padding)};if(this.covers(wanted.from,wanted.to)){this.status=this.hasGap?"gap":"unchanged";this.emit();return}this.controller?.abort();const controller=new AbortController(),id=++this.requestId;this.controller=controller;this.status="loading";this.emit();let cursor:string|null=null,pages=0;try{do{const query=new URLSearchParams({symbol:this.symbol,fromMs:String(wanted.from),toMs:String(wanted.to),limit:"1000"});if(cursor)query.set("cursor",cursor);const response=await fetcher(`/api/dizyflow/heatmap/history?${query}`,{signal:controller.signal});if(!response.ok)throw Error(`history ${response.status}`);const page=await response.json() as LiquidityHistoryPage;if(id!==this.requestId)return;this.priceStep=page.priceStep;this.ingest([...(pages===0?page.seed??[]:[]),...page.changes]);this.archiveFrom=page.coverage?.archiveStartMs??this.archiveFrom;this.archiveTo=page.coverage?.archiveEndMs??this.archiveTo;this.hasGap=page.coverage?.hasGaps??this.hasGap;cursor=page.nextCursor;pages++}while(cursor&&!controller.signal.aborted);if(id!==this.requestId)return;this.pageCount+=pages;this.spans=mergeSpans([...this.spans,wanted]).slice(-MAX_SPANS);this.evict((wanted.from+wanted.to)/2);this.status=this.hasGap?"gap":"connected";this.emit()}catch(error){if(!controller.signal.aborted){this.status="disconnected";this.emit();throw error}}}
 mergeLive(changes:readonly CompactLiquidityChange[],sequence:number|null,priceStep=this.priceStep){if(sequence!==null&&this.sequence!==null&&sequence!==this.sequence+1){this.status="resynchronising";this.sequence=sequence;this.spans=[];this.emit();return false}this.priceStep=priceStep;this.sequence=sequence??this.sequence;this.ingest(changes);this.lastLive=changes;this.liveRevision++;const at=changes.at(-1)?.timestampMs;if(at!==undefined){const start=changes[0]?.timestampMs??at;this.spans=mergeSpans([...this.spans,{from:start,to:at}]);this.evict(at)}this.status=changes.length?"connected":"unchanged";this.emit();return true}
 markDisconnected(){this.status="disconnected";this.emit()}markResynchronising(){this.status="resynchronising";this.emit()}
 abort(){this.controller?.abort();this.controller=null}
}
const caches=new Map<string,LiquidityHistoryCache>();
export function liquidityHistoryCache(exchange:string,symbol:string){const key=keyFor(exchange,symbol);let cache=caches.get(key);if(!cache){cache=new LiquidityHistoryCache(exchange,symbol);caches.set(key,cache)}return cache}
