import type {CompactLiquidityChange,LiquidityTileCell,LiquidityTileResponse} from "./types.ts";
export type LiquidityViewport={from:number;to:number;minPrice:number;maxPrice:number;effectiveTimeBucketMs:number;effectivePriceStep:number};
export type LiquidityCacheStatus="idle"|"loading"|"connected"|"unchanged"|"resynchronising"|"disconnected"|"gap";
export type LiquidityCacheSnapshot={cells:readonly LiquidityTileCell[];endState:readonly CompactLiquidityChange[];priceStep:number;timeBucketMs:number;requests:number;hits:number;misses:number;loadedFrom:number|null;loadedTo:number|null;archiveFrom:number|null;archiveTo:number|null;hasGap:boolean;sequence:number|null;status:LiquidityCacheStatus;revision:number;liveRevision:number};
type Range={key:string;from:number;to:number;cells:LiquidityTileCell[];used:number};
const MAX_CELLS=40_000,MAX_RANGES=24,OVERSCAN=.25,keyFor=(exchange:string,symbol:string)=>`${exchange.toLowerCase()}:${symbol.toUpperCase()}`;
export class LiquidityHistoryCache{
 readonly exchange:string;readonly symbol:string;private maximumCells:number;private ranges=new Map<string,Range>();private listeners=new Set<()=>void>();private controller:AbortController|null=null;private requestId=0;private requests=0;private hits=0;private misses=0;private priceStep=1;private timeBucketMs=5000;private archiveFrom:number|null=null;private archiveTo:number|null=null;private hasGap=false;private sequence:number|null=null;private status:LiquidityCacheStatus="idle";private revision=0;private liveRevision=0;private endState:CompactLiquidityChange[]=[];
 constructor(exchange:string,symbol:string,maximumCells=MAX_CELLS){this.exchange=exchange;this.symbol=symbol.toUpperCase();this.maximumCells=maximumCells}
 subscribe=(listener:()=>void)=>{this.listeners.add(listener);return()=>this.listeners.delete(listener)};private emit(){this.listeners.forEach(v=>v())}
 snapshot():LiquidityCacheSnapshot{const ranges=[...this.ranges.values()],cells=ranges.flatMap(v=>v.cells).sort((a,b)=>a.fromMs-b.fromMs||a.price-b.price),loadedFrom=ranges.length?Math.min(...ranges.map(v=>v.from)):null,loadedTo=ranges.length?Math.max(...ranges.map(v=>v.to)):null;return{cells,endState:this.endState,priceStep:this.priceStep,timeBucketMs:this.timeBucketMs,requests:this.requests,hits:this.hits,misses:this.misses,loadedFrom,loadedTo,archiveFrom:this.archiveFrom,archiveTo:this.archiveTo,hasGap:this.hasGap,sequence:this.sequence,status:this.status,revision:this.revision,liveRevision:this.liveRevision}}
 private evict(){let total=[...this.ranges.values()].reduce((n,v)=>n+v.cells.length,0);while(this.ranges.size>MAX_RANGES||total>this.maximumCells){const oldest=[...this.ranges.values()].sort((a,b)=>a.used-b.used)[0];if(!oldest)break;this.ranges.delete(oldest.key);total-=oldest.cells.length}}
 async ensure(view:LiquidityViewport,fetcher:typeof fetch=fetch){if(!Number.isFinite(view.from)||!Number.isFinite(view.to)||view.to<=view.from||view.minPrice<=0||view.maxPrice<=view.minPrice)return;const padding=(view.to-view.from)*OVERSCAN,bucket=Math.max(5000,view.effectiveTimeBucketMs),from=Math.floor(Math.max(0,view.from-padding)/bucket)*bucket,to=Math.ceil((view.to+padding)/bucket)*bucket,pricePad=(view.maxPrice-view.minPrice)*.08,minPrice=Math.max(1e-8,view.minPrice-pricePad),maxPrice=view.maxPrice+pricePad,key=[from,to,minPrice.toPrecision(8),maxPrice.toPrecision(8),bucket,view.effectivePriceStep].join(":");const found=this.ranges.get(key);if(found){found.used=Date.now();this.hits++;this.status=this.hasGap?"gap":"unchanged";this.emit();return}this.misses++;this.controller?.abort();const controller=new AbortController(),id=++this.requestId;this.controller=controller;this.status="loading";this.emit();try{const query=new URLSearchParams({symbol:this.symbol,fromMs:String(from),toMs:String(to),minPrice:String(minPrice),maxPrice:String(maxPrice),timeBucketMs:String(bucket),priceStep:String(view.effectivePriceStep)}),response=await fetcher(`/api/dizyflow/heatmap/tiles?${query}`,{signal:controller.signal});if(!response.ok)throw Error(`tiles ${response.status}`);const tile=await response.json() as LiquidityTileResponse;if(id!==this.requestId)return;this.requests++;this.priceStep=tile.priceStep;this.timeBucketMs=tile.timeBucketMs;this.archiveFrom=tile.capturedFromMs??this.archiveFrom;this.archiveTo=tile.capturedToMs??this.archiveTo;this.hasGap=tile.hasGaps;this.endState=tile.endState;this.ranges.set(key,{key,from,to,cells:tile.cells,used:Date.now()});this.evict();this.revision++;this.status=this.hasGap?"gap":"connected";this.emit()}catch(error){if(!controller.signal.aborted){this.status="disconnected";this.emit();throw error}}}
 mergeLive(changes:readonly CompactLiquidityChange[],sequence:number|null,priceStep=this.priceStep){if(sequence!==null&&this.sequence!==null&&sequence!==this.sequence+1){this.status="resynchronising";this.sequence=sequence;this.ranges.clear();this.emit();return false}this.priceStep=priceStep;this.sequence=sequence??this.sequence;for(const change of changes){const i=this.endState.findIndex(v=>v.priceTick===change.priceTick);if(i>=0)this.endState[i]=change;else this.endState.push(change)}this.liveRevision++;this.status=changes.length?"connected":"unchanged";this.emit();return true}
 markDisconnected(){this.status="disconnected";this.emit()}markResynchronising(){this.status="resynchronising";this.emit()}abort(){this.controller?.abort();this.controller=null}
}
const caches=new Map<string,LiquidityHistoryCache>();export function liquidityHistoryCache(exchange:string,symbol:string){const key=keyFor(exchange,symbol);let cache=caches.get(key);if(!cache){cache=new LiquidityHistoryCache(exchange,symbol);caches.set(key,cache)}return cache}
