export type OrderFlowSettings = {
  version: 3; captureHistoryMinutes:number; maxRecords:number;
  enabled: boolean; marketDepthVisible:boolean; heatmapVisible: boolean; bubblesVisible: boolean; domVisible: boolean; alertsVisible: boolean; imbalanceVisible: boolean;
  marketDepth:{width:number;opacity:number;scaling:"linear"|"logarithmic";displayMode:"absolute"|"side-percentage"|"total-percentage";levels:10|25|50|100;smoothing:number;updateThrottleMs:number;highlightClusters:boolean;clusterMultiple:number;clusterMinimumSamples:number;bidColour:string;askColour:string};
  heatmap: { colourMap:"bookmap"; bidColour:string; askColour:string; opacity:number; brightness:number; contrast:number; lowerPercentile:number; upperPercentile:number; rangeBps:number; timeBucketMs:0|1000|5000|15000|30000|60000; priceMode:"auto"|"manual"|"none"|"fixed"; fixedPriceStep:number; minimumNotional:number; intensity:"log"|"linear"; intensityMultiplier:number; gamma:number; percentile:number; historyMinutes:number; side:"both"|"bids"|"asks" };
  bubbles: { buyColour:string; sellColour:string; outlineColour:string; opacity:number; outlineOpacity:number; timeBucketMs:250|500|1000|2000|5000; priceMode:"auto"|"fixed"; fixedPriceStep:number; minimumNotional:number; adaptive:boolean; percentile:number; minimumSamples:number; minimumRadius:number; maximumRadius:number; hover:boolean; maximumRetained:number };
  dom: { width:number; levels:10|25|50|100; groupingBySymbol:Record<string,string>; units:"contracts"|"base"|"usdt"; cumulative:boolean; autoCentre:boolean; density:"compact"|"comfortable"; rowHeight:number; bidColour:string; askColour:string; midpointColour:string; backgroundColour:string; barOpacity:number; barMaximumWidth:number; scaling:"linear"|"logarithmic"; comparison:"per-side"|"total"; recentTradeFlashes:boolean; flashDurationMs:number; flashIntensity:number; highlightClusters:boolean; showQueueEstimate:boolean; liveThresholdMs:number; staleThresholdMs:number };
  alerts: { toasts:boolean; placement:"top-left"|"top-right"|"top-centre"; durationMs:number; maximumVisible:number; historyCapacity:number; marketBuys:boolean; marketSells:boolean; bidWalls:boolean; askWalls:boolean; liquidityPulled:boolean; buyColour:string; sellColour:string; bidWallColour:string; askWallColour:string; pulledColour:string; fixedThreshold:number; adaptive:boolean; percentile:number; minimumSamples:number; cooldownMs:number; wallMultiple:number; wallPersistenceMs:number; pulledPercentage:number };
};

export const DOM_SAFE_MINIMUM_WIDTH = 260;

export const DEFAULT_ORDER_FLOW_SETTINGS: OrderFlowSettings = {
  version:3,captureHistoryMinutes:360,maxRecords:20_000,
  enabled:false, marketDepthVisible:true, heatmapVisible:true, bubblesVisible:true, domVisible:false, alertsVisible:true, imbalanceVisible:true,
  marketDepth:{width:150,opacity:.3,scaling:"logarithmic",displayMode:"absolute",levels:25,smoothing:.25,updateThrottleMs:100,highlightClusters:true,clusterMultiple:4,clusterMinimumSamples:5,bidColour:"#19c98b",askColour:"#ef5b72"},
  heatmap:{colourMap:"bookmap",bidColour:"#18c8e8",askColour:"#ff8a24",opacity:.62,brightness:1,contrast:1,lowerPercentile:.05,upperPercentile:.98,rangeBps:100,timeBucketMs:0,priceMode:"auto",fixedPriceStep:.1,minimumNotional:0,intensity:"log",intensityMultiplier:1,gamma:.8,percentile:.98,historyMinutes:360,side:"both"},
  bubbles:{buyColour:"#20e3a2",sellColour:"#ff5573",outlineColour:"#f3f6ff",opacity:.22,outlineOpacity:.33,timeBucketMs:1000,priceMode:"auto",fixedPriceStep:.1,minimumNotional:100,adaptive:false,percentile:.8,minimumSamples:50,minimumRadius:3,maximumRadius:20,hover:true,maximumRetained:5000},
  dom:{width:DOM_SAFE_MINIMUM_WIDTH,levels:10,groupingBySymbol:{},units:"contracts",cumulative:true,autoCentre:true,density:"compact",rowHeight:20,bidColour:"#19c98b",askColour:"#ef5b72",midpointColour:"#a985ff",backgroundColour:"#0b0e17",barOpacity:.25,barMaximumWidth:100,scaling:"linear",comparison:"per-side",recentTradeFlashes:true,flashDurationMs:1200,flashIntensity:.7,highlightClusters:true,showQueueEstimate:false,liveThresholdMs:2000,staleThresholdMs:5000},
  alerts:{toasts:true,placement:"top-right",durationMs:6000,maximumVisible:3,historyCapacity:250,marketBuys:true,marketSells:true,bidWalls:true,askWalls:true,liquidityPulled:true,buyColour:"#20e3a2",sellColour:"#ff5573",bidWallColour:"#19c98b",askWallColour:"#ef5b72",pulledColour:"#f7b955",fixedThreshold:25_000,adaptive:true,percentile:.99,minimumSamples:30,cooldownMs:10_000,wallMultiple:5,wallPersistenceMs:1000,pulledPercentage:70},
};

const number=(v:unknown,d:number,min:number,max:number)=>Number.isFinite(Number(v))?Math.min(max,Math.max(min,Number(v))):d;
const bool=(v:unknown,d:boolean)=>typeof v==="boolean"?v:d;
const colour=(v:unknown,d:string)=>typeof v==="string"&&/^#[0-9a-f]{6}$/i.test(v)?v:d;
const choice=<T extends string|number>(v:unknown, values:readonly T[], d:T):T=>values.includes(v as T)?v as T:d;
export function sanitiseOrderFlowSettings(value:unknown):OrderFlowSettings {
  const input=value&&typeof value==="object"?value as Record<string,unknown>:{}, h=input.heatmap&&typeof input.heatmap==="object"?input.heatmap as Record<string,unknown>:{}, b=input.bubbles&&typeof input.bubbles==="object"?input.bubbles as Record<string,unknown>:{}, dom=input.dom&&typeof input.dom==="object"?input.dom as Record<string,unknown>:{}, md=input.marketDepth&&typeof input.marketDepth==="object"?input.marketDepth as Record<string,unknown>:{}, a=input.alerts&&typeof input.alerts==="object"?input.alerts as Record<string,unknown>:{};
  const d=DEFAULT_ORDER_FLOW_SETTINGS;
  return {version:3,captureHistoryMinutes:number(input.captureHistoryMinutes,d.captureHistoryMinutes,5,360),maxRecords:number(input.maxRecords,d.maxRecords,1000,200000),enabled:bool(input.enabled,d.enabled),marketDepthVisible:bool(input.marketDepthVisible,d.marketDepthVisible),heatmapVisible:bool(input.heatmapVisible,d.heatmapVisible),bubblesVisible:bool(input.bubblesVisible,d.bubblesVisible),domVisible:bool(input.domVisible,d.domVisible),alertsVisible:bool(input.alertsVisible,d.alertsVisible),imbalanceVisible:bool(input.imbalanceVisible,d.imbalanceVisible),
    marketDepth:{width:number(md.width,d.marketDepth.width,60,240),opacity:number(md.opacity,d.marketDepth.opacity,.05,.8),scaling:choice(md.scaling,["linear","logarithmic"] as const,d.marketDepth.scaling),displayMode:choice(md.displayMode,["absolute","side-percentage","total-percentage"] as const,d.marketDepth.displayMode),levels:choice(md.levels,[10,25,50,100] as const,d.marketDepth.levels),smoothing:number(md.smoothing,d.marketDepth.smoothing,0,.6),updateThrottleMs:number(md.updateThrottleMs,d.marketDepth.updateThrottleMs,50,500),highlightClusters:bool(md.highlightClusters,d.marketDepth.highlightClusters),clusterMultiple:number(md.clusterMultiple,d.marketDepth.clusterMultiple,2,20),clusterMinimumSamples:number(md.clusterMinimumSamples,d.marketDepth.clusterMinimumSamples,3,50),bidColour:colour(md.bidColour,d.marketDepth.bidColour),askColour:colour(md.askColour,d.marketDepth.askColour)},
    heatmap:{colourMap:"bookmap",bidColour:colour(h.bidColour,d.heatmap.bidColour),askColour:colour(h.askColour,d.heatmap.askColour),opacity:number(h.opacity,d.heatmap.opacity,0,1),brightness:number(h.brightness,d.heatmap.brightness,.25,3),contrast:number(h.contrast,d.heatmap.contrast,.25,3),lowerPercentile:number(h.lowerPercentile,d.heatmap.lowerPercentile,0,.49),upperPercentile:number(h.upperPercentile??h.percentile,d.heatmap.upperPercentile,.51,1),rangeBps:number(h.rangeBps,d.heatmap.rangeBps,10,200),timeBucketMs:choice(h.timeBucketMs,[0,1000,5000,15000,30000,60000] as const,d.heatmap.timeBucketMs),priceMode:choice(h.priceMode,["auto","manual","none","fixed"] as const,d.heatmap.priceMode),fixedPriceStep:number(h.fixedPriceStep,d.heatmap.fixedPriceStep,.00000001,100000),minimumNotional:number(h.minimumNotional,d.heatmap.minimumNotional,0,1e9),intensity:choice(h.intensity,["log","linear"] as const,d.heatmap.intensity),intensityMultiplier:number(h.intensityMultiplier,d.heatmap.intensityMultiplier,.1,10),gamma:number(h.gamma,d.heatmap.gamma,.2,3),percentile:number(h.percentile,d.heatmap.percentile,.5,1),historyMinutes:number(h.historyMinutes,d.heatmap.historyMinutes,5,360),side:choice(h.side,["both","bids","asks"] as const,d.heatmap.side)},
    bubbles:{buyColour:colour(b.buyColour,d.bubbles.buyColour),sellColour:colour(b.sellColour,d.bubbles.sellColour),outlineColour:colour(b.outlineColour,d.bubbles.outlineColour),opacity:number(b.opacity,d.bubbles.opacity,0,1),outlineOpacity:number(b.outlineOpacity,d.bubbles.outlineOpacity,0,1),timeBucketMs:choice(b.timeBucketMs,[250,500,1000,2000,5000] as const,d.bubbles.timeBucketMs),priceMode:choice(b.priceMode,["auto","fixed"] as const,d.bubbles.priceMode),fixedPriceStep:number(b.fixedPriceStep,d.bubbles.fixedPriceStep,.00000001,100000),minimumNotional:number(b.minimumNotional,d.bubbles.minimumNotional,0,1e9),adaptive:bool(b.adaptive,d.bubbles.adaptive),percentile:number(b.percentile,d.bubbles.percentile,.5,1),minimumSamples:number(b.minimumSamples,d.bubbles.minimumSamples,1,5000),minimumRadius:number(b.minimumRadius,d.bubbles.minimumRadius,1,20),maximumRadius:number(b.maximumRadius,d.bubbles.maximumRadius,3,40),hover:bool(b.hover,d.bubbles.hover),maximumRetained:number(b.maximumRetained,d.bubbles.maximumRetained,100,20000)},
    dom:{width:number(dom.width,d.dom.width,DOM_SAFE_MINIMUM_WIDTH,380),levels:choice(dom.levels,[10,25,50,100] as const,d.dom.levels),groupingBySymbol:sanitiseGrouping(dom.groupingBySymbol),units:choice(dom.units,["contracts","base","usdt"] as const,d.dom.units),cumulative:bool(dom.cumulative,d.dom.cumulative),autoCentre:bool(dom.autoCentre,d.dom.autoCentre),density:choice(dom.density,["compact","comfortable"] as const,d.dom.density),rowHeight:number(dom.rowHeight,d.dom.rowHeight,16,32),bidColour:colour(dom.bidColour,d.dom.bidColour),askColour:colour(dom.askColour,d.dom.askColour),midpointColour:colour(dom.midpointColour,d.dom.midpointColour),backgroundColour:colour(dom.backgroundColour,d.dom.backgroundColour),barOpacity:number(dom.barOpacity,d.dom.barOpacity,0,1),barMaximumWidth:number(dom.barMaximumWidth,d.dom.barMaximumWidth,25,100),scaling:choice(dom.scaling,["linear","logarithmic"] as const,d.dom.scaling),comparison:choice(dom.comparison,["per-side","total"] as const,d.dom.comparison),recentTradeFlashes:bool(dom.recentTradeFlashes,d.dom.recentTradeFlashes),flashDurationMs:number(dom.flashDurationMs,d.dom.flashDurationMs,250,3000),flashIntensity:number(dom.flashIntensity,d.dom.flashIntensity,.1,1),highlightClusters:bool(dom.highlightClusters,d.dom.highlightClusters),showQueueEstimate:bool(dom.showQueueEstimate,d.dom.showQueueEstimate),liveThresholdMs:number(dom.liveThresholdMs,d.dom.liveThresholdMs,500,5000),staleThresholdMs:number(dom.staleThresholdMs,d.dom.staleThresholdMs,2000,15000)},
    alerts:{toasts:bool(a.toasts,d.alerts.toasts),placement:choice(a.placement,["top-left","top-right","top-centre"] as const,d.alerts.placement),durationMs:number(a.durationMs,d.alerts.durationMs,1000,30000),maximumVisible:number(a.maximumVisible,d.alerts.maximumVisible,1,3),historyCapacity:number(a.historyCapacity,d.alerts.historyCapacity,10,1000),marketBuys:bool(a.marketBuys,d.alerts.marketBuys),marketSells:bool(a.marketSells,d.alerts.marketSells),bidWalls:bool(a.bidWalls,d.alerts.bidWalls),askWalls:bool(a.askWalls,d.alerts.askWalls),liquidityPulled:bool(a.liquidityPulled,d.alerts.liquidityPulled),buyColour:colour(a.buyColour,d.alerts.buyColour),sellColour:colour(a.sellColour,d.alerts.sellColour),bidWallColour:colour(a.bidWallColour,d.alerts.bidWallColour),askWallColour:colour(a.askWallColour,d.alerts.askWallColour),pulledColour:colour(a.pulledColour,d.alerts.pulledColour),fixedThreshold:number(a.fixedThreshold,d.alerts.fixedThreshold,0,1e9),adaptive:bool(a.adaptive,d.alerts.adaptive),percentile:number(a.percentile,d.alerts.percentile,.5,1),minimumSamples:number(a.minimumSamples,d.alerts.minimumSamples,1,5000),cooldownMs:number(a.cooldownMs,d.alerts.cooldownMs,0,300000),wallMultiple:number(a.wallMultiple,d.alerts.wallMultiple,1,100),wallPersistenceMs:number(a.wallPersistenceMs,d.alerts.wallPersistenceMs,0,60000),pulledPercentage:number(a.pulledPercentage,d.alerts.pulledPercentage,1,100)}};
}

function sanitiseGrouping(value:unknown):Record<string,string>{
  if(!value||typeof value!=="object"||Array.isArray(value))return {};
  return Object.fromEntries(Object.entries(value as Record<string,unknown>).filter((entry):entry is [string,string]=>{const [symbol,step]=entry;return /^[A-Z0-9]+_[A-Z0-9]+$/.test(symbol)&&typeof step==="string"&&Number.isFinite(Number(step))&&Number(step)>0}).slice(0,200));
}
