export type OrderFlowSettings = {
  enabled: boolean; heatmapVisible: boolean; bubblesVisible: boolean; domVisible: boolean; alertsVisible: boolean; imbalanceVisible: boolean;
  heatmap: { bidColour:string; askColour:string; opacity:number; rangeBps:number; timeBucketMs:250|500|1000|2000|5000; priceMode:"auto"|"fixed"; fixedPriceStep:number; minimumNotional:number; intensity:"log"|"linear"; gamma:number; percentile:number; historyMinutes:number; side:"both"|"bids"|"asks" };
  bubbles: { buyColour:string; sellColour:string; outlineColour:string; opacity:number; timeBucketMs:250|500|1000|2000|5000; priceMode:"auto"|"fixed"; fixedPriceStep:number; minimumNotional:number; adaptive:boolean; percentile:number; minimumSamples:number; minimumRadius:number; maximumRadius:number; hover:boolean };
  dom: { levels:10|25|50|100; units:"contracts"|"base"|"usdt"; cumulative:boolean; autoCentre:boolean; density:"compact"|"comfortable"; bidColour:string; askColour:string; midpointColour:string; backgroundColour:string; barOpacity:number };
  alerts: { toasts:boolean; placement:"top-left"|"top-right"|"top-centre"; durationMs:number; maximumVisible:number; historyCapacity:number; marketBuys:boolean; marketSells:boolean; bidWalls:boolean; askWalls:boolean; liquidityPulled:boolean; buyColour:string; sellColour:string; bidWallColour:string; askWallColour:string; pulledColour:string; fixedThreshold:number; adaptive:boolean; percentile:number; minimumSamples:number; cooldownMs:number; wallMultiple:number; wallPersistenceMs:number; pulledPercentage:number };
};

export const DEFAULT_ORDER_FLOW_SETTINGS: OrderFlowSettings = {
  enabled:false, heatmapVisible:true, bubblesVisible:true, domVisible:false, alertsVisible:true, imbalanceVisible:true,
  heatmap:{bidColour:"#19c98b",askColour:"#ef5b72",opacity:.35,rangeBps:50,timeBucketMs:1000,priceMode:"auto",fixedPriceStep:.1,minimumNotional:0,intensity:"log",gamma:1,percentile:.98,historyMinutes:30,side:"both"},
  bubbles:{buyColour:"#20e3a2",sellColour:"#ff5573",outlineColour:"#f3f6ff",opacity:.72,timeBucketMs:1000,priceMode:"auto",fixedPriceStep:.1,minimumNotional:500,adaptive:true,percentile:.8,minimumSamples:20,minimumRadius:3,maximumRadius:18,hover:true},
  dom:{levels:25,units:"contracts",cumulative:true,autoCentre:true,density:"compact",bidColour:"#19c98b",askColour:"#ef5b72",midpointColour:"#a985ff",backgroundColour:"#0b0e17",barOpacity:.22},
  alerts:{toasts:true,placement:"top-right",durationMs:6000,maximumVisible:3,historyCapacity:250,marketBuys:true,marketSells:true,bidWalls:true,askWalls:true,liquidityPulled:true,buyColour:"#20e3a2",sellColour:"#ff5573",bidWallColour:"#19c98b",askWallColour:"#ef5b72",pulledColour:"#f7b955",fixedThreshold:25_000,adaptive:true,percentile:.99,minimumSamples:30,cooldownMs:10_000,wallMultiple:5,wallPersistenceMs:1000,pulledPercentage:70},
};

const number=(v:unknown,d:number,min:number,max:number)=>Number.isFinite(Number(v))?Math.min(max,Math.max(min,Number(v))):d;
const bool=(v:unknown,d:boolean)=>typeof v==="boolean"?v:d;
const colour=(v:unknown,d:string)=>typeof v==="string"&&/^#[0-9a-f]{6}$/i.test(v)?v:d;
const choice=<T extends string|number>(v:unknown, values:readonly T[], d:T):T=>values.includes(v as T)?v as T:d;
export function sanitiseOrderFlowSettings(value:unknown):OrderFlowSettings {
  const input=value&&typeof value==="object"?value as Record<string,unknown>:{}, h=input.heatmap&&typeof input.heatmap==="object"?input.heatmap as Record<string,unknown>:{}, b=input.bubbles&&typeof input.bubbles==="object"?input.bubbles as Record<string,unknown>:{}, dom=input.dom&&typeof input.dom==="object"?input.dom as Record<string,unknown>:{}, a=input.alerts&&typeof input.alerts==="object"?input.alerts as Record<string,unknown>:{};
  const d=DEFAULT_ORDER_FLOW_SETTINGS;
  return {enabled:bool(input.enabled,d.enabled),heatmapVisible:bool(input.heatmapVisible,d.heatmapVisible),bubblesVisible:bool(input.bubblesVisible,d.bubblesVisible),domVisible:bool(input.domVisible,d.domVisible),alertsVisible:bool(input.alertsVisible,d.alertsVisible),imbalanceVisible:bool(input.imbalanceVisible,d.imbalanceVisible),
    heatmap:{bidColour:colour(h.bidColour,d.heatmap.bidColour),askColour:colour(h.askColour,d.heatmap.askColour),opacity:number(h.opacity,d.heatmap.opacity,0,1),rangeBps:number(h.rangeBps,d.heatmap.rangeBps,10,200),timeBucketMs:choice(h.timeBucketMs,[250,500,1000,2000,5000] as const,d.heatmap.timeBucketMs),priceMode:choice(h.priceMode,["auto","fixed"] as const,d.heatmap.priceMode),fixedPriceStep:number(h.fixedPriceStep,d.heatmap.fixedPriceStep,.00000001,100000),minimumNotional:number(h.minimumNotional,d.heatmap.minimumNotional,0,1e9),intensity:choice(h.intensity,["log","linear"] as const,d.heatmap.intensity),gamma:number(h.gamma,d.heatmap.gamma,.2,3),percentile:number(h.percentile,d.heatmap.percentile,.5,1),historyMinutes:number(h.historyMinutes,d.heatmap.historyMinutes,5,120),side:choice(h.side,["both","bids","asks"] as const,d.heatmap.side)},
    bubbles:{buyColour:colour(b.buyColour,d.bubbles.buyColour),sellColour:colour(b.sellColour,d.bubbles.sellColour),outlineColour:colour(b.outlineColour,d.bubbles.outlineColour),opacity:number(b.opacity,d.bubbles.opacity,0,1),timeBucketMs:choice(b.timeBucketMs,[250,500,1000,2000,5000] as const,d.bubbles.timeBucketMs),priceMode:choice(b.priceMode,["auto","fixed"] as const,d.bubbles.priceMode),fixedPriceStep:number(b.fixedPriceStep,d.bubbles.fixedPriceStep,.00000001,100000),minimumNotional:number(b.minimumNotional,d.bubbles.minimumNotional,0,1e9),adaptive:bool(b.adaptive,d.bubbles.adaptive),percentile:number(b.percentile,d.bubbles.percentile,.5,1),minimumSamples:number(b.minimumSamples,d.bubbles.minimumSamples,1,5000),minimumRadius:number(b.minimumRadius,d.bubbles.minimumRadius,1,20),maximumRadius:number(b.maximumRadius,d.bubbles.maximumRadius,3,40),hover:bool(b.hover,d.bubbles.hover)},
    dom:{levels:choice(dom.levels,[10,25,50,100] as const,d.dom.levels),units:choice(dom.units,["contracts","base","usdt"] as const,d.dom.units),cumulative:bool(dom.cumulative,d.dom.cumulative),autoCentre:bool(dom.autoCentre,d.dom.autoCentre),density:choice(dom.density,["compact","comfortable"] as const,d.dom.density),bidColour:colour(dom.bidColour,d.dom.bidColour),askColour:colour(dom.askColour,d.dom.askColour),midpointColour:colour(dom.midpointColour,d.dom.midpointColour),backgroundColour:colour(dom.backgroundColour,d.dom.backgroundColour),barOpacity:number(dom.barOpacity,d.dom.barOpacity,0,1)},
    alerts:{toasts:bool(a.toasts,d.alerts.toasts),placement:choice(a.placement,["top-left","top-right","top-centre"] as const,d.alerts.placement),durationMs:number(a.durationMs,d.alerts.durationMs,1000,30000),maximumVisible:number(a.maximumVisible,d.alerts.maximumVisible,1,3),historyCapacity:number(a.historyCapacity,d.alerts.historyCapacity,10,1000),marketBuys:bool(a.marketBuys,d.alerts.marketBuys),marketSells:bool(a.marketSells,d.alerts.marketSells),bidWalls:bool(a.bidWalls,d.alerts.bidWalls),askWalls:bool(a.askWalls,d.alerts.askWalls),liquidityPulled:bool(a.liquidityPulled,d.alerts.liquidityPulled),buyColour:colour(a.buyColour,d.alerts.buyColour),sellColour:colour(a.sellColour,d.alerts.sellColour),bidWallColour:colour(a.bidWallColour,d.alerts.bidWallColour),askWallColour:colour(a.askWallColour,d.alerts.askWallColour),pulledColour:colour(a.pulledColour,d.alerts.pulledColour),fixedThreshold:number(a.fixedThreshold,d.alerts.fixedThreshold,0,1e9),adaptive:bool(a.adaptive,d.alerts.adaptive),percentile:number(a.percentile,d.alerts.percentile,.5,1),minimumSamples:number(a.minimumSamples,d.alerts.minimumSamples,1,5000),cooldownMs:number(a.cooldownMs,d.alerts.cooldownMs,0,300000),wallMultiple:number(a.wallMultiple,d.alerts.wallMultiple,1,100),wallPersistenceMs:number(a.wallPersistenceMs,d.alerts.wallPersistenceMs,0,60000),pulledPercentage:number(a.pulledPercentage,d.alerts.pulledPercentage,1,100)}};
}
