"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import type {MexcDeal} from "../market/realtime";
import {FlowAggregator} from "./aggregator";
import {AlertEngine} from "./alerts";
import {calculateImbalance} from "./imbalance";
import {parseDepthSnapshot} from "./mexc-depth";
import {OrderBook} from "./order-book";
import {FlowRenderStore} from "./render-store";
import type {OrderFlowSettings} from "./settings";
import type {DepthUpdate,FlowAlert,FlowStatus} from "./types";
export type FlowSummary={status:FlowStatus;imbalance:number|null;bidNotional:number;askNotional:number;spread:number;version:number;snapshotVersion:number;lastWebSocketVersion:number;bufferedUpdates:number;lastValidUpdate:number|null;recoveryAttempts:number;levels:number;latencyMs:number;captureStarted:number|null;alerts:FlowAlert[]};
const empty:FlowSummary={status:"Off",imbalance:null,bidNotional:0,askNotional:0,spread:0,version:-1,snapshotVersion:-1,lastWebSocketVersion:-1,bufferedUpdates:0,lastValidUpdate:null,recoveryAttempts:0,levels:0,latencyMs:0,captureStarted:null,alerts:[]};
export function useOrderFlow({settings,paused,symbol,contractSize}:{settings:OrderFlowSettings;paused:boolean;symbol:string;contractSize:number}){
 const settingsRef=useRef(settings),book=useRef(new OrderBook()),aggregate=useRef(new FlowAggregator()),alerts=useRef(new AlertEngine()),generation=useRef(0),lastUi=useRef(0),recover=useRef<()=>void>(()=>{});const [renderStore]=useState(()=>new FlowRenderStore(settings));const[summary,setSummary]=useState(empty),enabled=settings.enabled;useEffect(()=>{settingsRef.current=settings},[settings]);
 const syncRender=useCallback(()=>renderStore.update({enabled,bookValid:book.current.view().valid,book:book.current.view(),heatmap:aggregate.current.heatmap,bubbles:aggregate.current.bubbles,settings:settingsRef.current}),[enabled,renderStore]);
 const publish=useCallback((status:FlowStatus,engineTime=Date.now())=>{if(Date.now()-lastUi.current<200)return;lastUi.current=Date.now();const view=book.current.view(),metric=calculateImbalance(view,contractSize,{kind:"levels",value:25});setSummary(v=>({...v,status,imbalance:metric?.imbalance??null,bidNotional:metric?.bidNotional??0,askNotional:metric?.askNotional??0,spread:metric?.spread??0,version:view.version,levels:view.bids.length+view.asks.length,latencyMs:Math.max(0,Date.now()-engineTime),lastValidUpdate:view.valid?Date.now():v.lastValidUpdate}));},[contractSize]);
 useEffect(()=>{aggregate.current.configure({historyMs:settings.heatmap.historyMinutes*60_000,timeBucketMs:settings.heatmap.timeBucketMs,priceStep:settings.heatmap.priceMode==="fixed"?settings.heatmap.fixedPriceStep:.1});syncRender()},[settings,syncRender]);
 // Subscribe first: onDepth buffers in OrderBook until this sequence-aware snapshot completes.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const id=++generation.current;book.current.reset();aggregate.current.clear();alerts.current.clear();renderStore.reset(`${symbol}:${id}`,settingsRef.current);if(!enabled){recover.current=()=>{};setSummary(empty);return;}const started=Date.now();setSummary({...empty,status:"Warming up",captureStarted:started});renderStore.update({captureStarted:started});let controller:AbortController|null=null,timer:ReturnType<typeof setTimeout>|null=null,inFlight=false,attempt=0;
  const snapshot=async()=>{const response=await fetch(`/api/order-flow/depth?symbol=${encodeURIComponent(symbol)}`,{signal:controller!.signal});if(!response.ok)throw Error("snapshot");const value=parseDepthSnapshot(await response.json(),symbol);if(!value)throw Error("snapshot");if(id!==generation.current)return;book.current.snapshot(value);const view=book.current.view();if(!view.valid)throw Error("unbridged snapshot");aggregate.current.captureBook(view,contractSize,value.engineTimeMs,settingsRef.current.heatmap.rangeBps);setSummary(v=>({...v,snapshotVersion:value.version,recoveryAttempts:attempt}));syncRender();publish("Live",value.engineTimeMs)};
  const recovery=()=>{if(inFlight||id!==generation.current)return;inFlight=true;controller=new AbortController();setSummary(v=>({...v,status:"Recovering",recoveryAttempts:attempt}));(async()=>{try{const local=book.current.view().version;if(local>=0){const response=await fetch(`/api/order-flow/depth?symbol=${encodeURIComponent(symbol)}&mode=commits`,{signal:controller!.signal});if(response.ok){const data=await response.json() as {commits?:DepthUpdate[]};for(const update of data.commits??[]){if(update.version>=local+1)book.current.update(update)}if(book.current.view().valid){attempt=0;syncRender();publish("Live");return}}}await snapshot();attempt=0}catch{if(id===generation.current&&!controller!.signal.aborted){attempt++;const delay=Math.min(30_000,500*2**Math.min(attempt,6));setSummary(v=>({...v,status:"Recovering",recoveryAttempts:attempt}));timer=setTimeout(recovery,delay)}}finally{inFlight=false;controller=null}})()};recover.current=recovery;recovery();return()=>{recover.current=()=>{};controller?.abort();if(timer)clearTimeout(timer)};
  },[enabled,symbol,contractSize,publish,renderStore,syncRender]);
 const onDepth=useCallback((update:DepthUpdate)=>{if(!enabled||paused||update.symbol!==symbol)return;setSummary(v=>({...v,lastWebSocketVersion:update.version,bufferedUpdates:book.current.view().version<0?v.bufferedUpdates+1:v.bufferedUpdates}));const result=book.current.update(update);if(result==="gap"){renderStore.update({bookValid:false,book:book.current.view()});setSummary(v=>({...v,status:"Recovering"}));recover.current();return}const view=book.current.view();if(view.valid){aggregate.current.captureBook(view,contractSize,update.engineTimeMs,settings.heatmap.rangeBps);const next=alerts.current.walls(view,symbol,contractSize,update.engineTimeMs,settings.alerts.wallMultiple,settings.alerts.wallPersistenceMs);if(next.length)setSummary(v=>({...v,alerts:[...next,...v.alerts].slice(0,settings.alerts.historyCapacity)}));syncRender();publish("Live",update.engineTimeMs)}},[enabled,paused,symbol,contractSize,publish,renderStore,settings,syncRender]);
 const onDeal=useCallback((deal:MexcDeal)=>{if(!enabled||paused||deal.symbol!==symbol)return;aggregate.current.addDeal(deal,settings.bubbles.timeBucketMs,settings.bubbles.priceMode==="fixed"?settings.bubbles.fixedPriceStep:.1);const alert=alerts.current.trade(deal,{fixed:settings.alerts.fixedThreshold,adaptive:settings.alerts.adaptive,percentileValue:settings.alerts.percentile,minSamples:settings.alerts.minimumSamples});if(alert&&((alert.type==="Large Market Buy"&&settings.alerts.marketBuys)||(alert.type==="Large Market Sell"&&settings.alerts.marketSells)))setSummary(v=>({...v,alerts:[alert,...v.alerts].slice(0,settings.alerts.historyCapacity)}));syncRender()},[enabled,paused,symbol,settings,syncRender]);
 const clear=useCallback(()=>{aggregate.current.clear();alerts.current.clear();renderStore.update({heatmap:[],bubbles:[],captureStarted:Date.now()});setSummary(v=>({...v,alerts:[],captureStarted:Date.now()}))},[renderStore]);return{summary,onDepth,onDeal,clear,renderStore};
}
