"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import type {MexcDeal} from "../market/realtime";
import {parseMexcRecentDeals} from "../market/realtime";
import {FlowAggregator} from "./aggregator";
import {AlertEngine} from "./alerts";
import {calculateImbalance} from "./imbalance";
import {decodeDepthCommitsResponse,decodeDepthSnapshotResponse} from "./mexc-depth";
import {OrderBook} from "./order-book";
import {FlowRenderStore} from "./render-store";
import {normalizeExchangeTimestamp} from "./time-projection";
import type {OrderFlowSettings} from "./settings";
import type {DepthUpdate,FlowAlert,FlowStatus} from "./types";
import {feedAgeStatus} from "./lifecycle";
export {feedAgeStatus} from "./lifecycle";

export type FlowSummary={
 status:FlowStatus;reason:string;wsState:string;activeSymbol:string;imbalance:number|null;bidNotional:number;askNotional:number;spread:number;
 version:number;snapshotVersion:number;lastWebSocketVersion:number;bufferedUpdates:number;lastWebSocketMessage:number|null;lastDepthEvent:number|null;
 lastValidUpdate:number|null;lastTradeEvent:number|null;lastSnapshot:number|null;lastSuccessfulRecovery:number|null;recoveryAttempts:number;currentGap:string|null;
 levels:number;latencyMs:number;captureStarted:number|null;alerts:FlowAlert[];restTradesLoaded:number;dealsReceived:number;dealsAccepted:number;
 duplicatesRejected:number;rejectedTimestamps:number;belowThresholdDeals:number;lastUpstreamError:string|null; snapshotBids:number;snapshotAsks:number;bookBids:number;bookAsks:number;heatmapCellsRetained:number;heatmapCellsVisible:number;depthMessagesReceived:number;depthMessagesApplied:number;versionGaps:number;lastRecoveryError:string|null;
};
const empty:FlowSummary={status:"Off",reason:"Disabled",wsState:"closed",activeSymbol:"",imbalance:null,bidNotional:0,askNotional:0,spread:0,version:-1,snapshotVersion:-1,lastWebSocketVersion:-1,bufferedUpdates:0,lastWebSocketMessage:null,lastDepthEvent:null,lastValidUpdate:null,lastTradeEvent:null,lastSnapshot:null,lastSuccessfulRecovery:null,recoveryAttempts:0,currentGap:null,levels:0,latencyMs:0,captureStarted:null,alerts:[],restTradesLoaded:0,dealsReceived:0,dealsAccepted:0,duplicatesRejected:0,rejectedTimestamps:0,belowThresholdDeals:0,lastUpstreamError:null,snapshotBids:0,snapshotAsks:0,bookBids:0,bookAsks:0,heatmapCellsRetained:0,heatmapCellsVisible:0,depthMessagesReceived:0,depthMessagesApplied:0,versionGaps:0,lastRecoveryError:null};

export function useOrderFlow({settings,paused,symbol,contractSize}:{settings:OrderFlowSettings;paused:boolean;symbol:string;contractSize:number}){
 const settingsRef=useRef(settings),contractRef=useRef(contractSize),book=useRef(new OrderBook()),aggregate=useRef(new FlowAggregator()),alerts=useRef(new AlertEngine()),generation=useRef(0),lastUi=useRef(0),recover=useRef<(reason:string)=>void>(()=>{}),ready=useRef(false);
 const [renderStore]=useState(()=>new FlowRenderStore(settings));const[summary,setSummary]=useState(empty),enabled=settings.enabled;
 useEffect(()=>{settingsRef.current=settings;contractRef.current=contractSize},[settings,contractSize]);
 const syncRender=useCallback(()=>renderStore.update({enabled:settingsRef.current.enabled,bookValid:book.current.view().valid,book:book.current.view(),heatmap:aggregate.current.heatmap,bubbles:aggregate.current.bubbles,settings:settingsRef.current}),[renderStore]);
 const publish=useCallback((status:FlowStatus,reason:string,engineTime=Date.now())=>{if(Date.now()-lastUi.current<125)return;lastUi.current=Date.now();const view=book.current.view(),metric=calculateImbalance(view,contractRef.current,{kind:"levels",value:25}),now=Date.now();setSummary(v=>({...v,status,reason,imbalance:metric?.imbalance??null,bidNotional:metric?.bidNotional??0,askNotional:metric?.askNotional??0,spread:metric?.spread??0,version:view.version,bufferedUpdates:0,levels:view.bids.length+view.asks.length,bookBids:view.bids.length,bookAsks:view.asks.length,heatmapCellsRetained:aggregate.current.heatmap.length,heatmapCellsVisible:aggregate.current.heatmap.length,latencyMs:Math.max(0,now-engineTime),lastValidUpdate:view.valid?now:v.lastValidUpdate,currentGap:view.valid?null:v.currentGap}));},[]);
 useEffect(()=>{aggregate.current.configure({historyMs:settings.heatmap.historyMinutes*60_000,maxCells:settings.maxRecords,maxBubbles:settings.bubbles.maximumRetained,timeBucketMs:settings.heatmap.timeBucketMs||1000,priceStep:settings.heatmap.priceMode==="fixed"?settings.heatmap.fixedPriceStep:.1});syncRender()},[settings,syncRender]);

 // Feed identity depends only on the master switch and symbol. Visual settings,
 // DOM width and asynchronously loaded contract metadata cannot reconnect it.
 useEffect(()=>{const id=++generation.current;ready.current=false;book.current.reset();aggregate.current.clear();alerts.current.clear();renderStore.reset(`${symbol}:${id}`,settingsRef.current);if(!enabled){recover.current=()=>{};setSummary(empty);return;}const started=Date.now();setSummary({...empty,status:"Connecting",reason:"Opening MEXC public WebSocket",wsState:"connecting",activeSymbol:symbol,captureStarted:started});renderStore.update({captureStarted:started});const controllers=new Set<AbortController>();let retryTimer:ReturnType<typeof setTimeout>|null=null,gapTimer:ReturnType<typeof setTimeout>|null=null,inFlight=false,attempt=0,stopped=false,terminalError=false;
  const fetchJson=async(path:string)=>{const controller=new AbortController();controllers.add(controller);const timeout=setTimeout(()=>controller.abort("Public request timeout"),7000);try{const response=await fetch(path,{signal:controller.signal});const body=await response.json().catch(()=>({}));if(!response.ok){const failures=Array.isArray(body.failures)?body.failures:[],blocked=failures.find((item:unknown)=>item&&typeof item==="object"&&("status" in item)&&((item as {status?:number}).status===403||(item as {status?:number}).status===451));const failure=Error(blocked&&typeof blocked==="object"&&"message" in blocked?String(blocked.message):typeof body.error==="string"?`${body.error} HTTP ${response.status}`:`Public request HTTP ${response.status}`);if(blocked)(failure as Error&{permanent?:boolean}).permanent=true;throw failure}return body;}finally{clearTimeout(timeout);controllers.delete(controller)}};
  const recovery=(why:string)=>{if(inFlight||terminalError||id!==generation.current||!ready.current||stopped)return;inFlight=true;if(gapTimer){clearTimeout(gapTimer);gapTimer=null}const hadBook=book.current.view().version>=0;setSummary(v=>({...v,status:hadBook?"Recovering":"LoadingSnapshot",reason:why,recoveryAttempts:attempt,currentGap:hadBook?`${book.current.view().version+1}…${v.lastWebSocketVersion}`:null}));void(async()=>{try{
    if(!hadBook){const raw=await fetchJson(`/api/order-flow/depth?symbol=${encodeURIComponent(symbol)}`);if(id!==generation.current)return;const value=decodeDepthSnapshotResponse(raw,symbol)?.snapshot;if(!value)throw Error("Snapshot JSON validation failure");setSummary(v=>({...v,status:"Bridging",reason:`Joining snapshot ${value.version} to buffered updates`,snapshotVersion:value.version,snapshotBids:value.bids.length,snapshotAsks:value.asks.length,lastSnapshot:Date.now()}));book.current.snapshot(value);
    }if(!book.current.view().valid){const raw=await fetchJson(`/api/order-flow/depth?symbol=${encodeURIComponent(symbol)}&mode=commits`);if(id!==generation.current)return;const commits=decodeDepthCommitsResponse(raw,symbol)?.commits??[];if(!book.current.bridge(commits)){
       book.current.beginResnapshot();const snapshotRaw=await fetchJson(`/api/order-flow/depth?symbol=${encodeURIComponent(symbol)}`);if(id!==generation.current)return;const snapshot=decodeDepthSnapshotResponse(snapshotRaw,symbol)?.snapshot;if(!snapshot)throw Error("Fresh snapshot could not repair sequence gap");book.current.applyResnapshot(snapshot);setSummary(v=>({...v,snapshotVersion:snapshot.version,lastSnapshot:Date.now()}));
      }
    }
    const validated=book.current.view();if(id!==generation.current||!validated.valid)throw Error("Buffered depth remains non-contiguous");if(!validated.bids.length||!validated.asks.length)throw Error(`Depth protocol error: empty ${!validated.bids.length?"bids":"asks"} side`);attempt=0;terminalError=false;const view=book.current.view(),now=Date.now();aggregate.current.captureBook(view,contractRef.current,now,settingsRef.current.heatmap.rangeBps);syncRender();setSummary(v=>({...v,lastSuccessfulRecovery:hadBook?now:v.lastSuccessfulRecovery,lastUpstreamError:null}));publish("Live",`Sequence ${view.version} valid`);
   }catch(error){if(id===generation.current&&!stopped){attempt++;terminalError=Boolean((error as Error&{permanent?:boolean})?.permanent)||attempt>=3;const reason=error instanceof Error?error.message:"Recovery failed";setSummary(v=>({...v,status:terminalError?"Error":"Recovering",reason,recoveryAttempts:attempt,lastUpstreamError:reason,lastRecoveryError:reason}));if(!terminalError){const delay=Math.min(30_000,500*2**Math.min(attempt,6));retryTimer=setTimeout(()=>recovery(reason),delay)}}}finally{inFlight=false}})()};recover.current=recovery;const manualRetry=()=>{if(stopped||id!==generation.current)return;terminalError=false;attempt=0;if(retryTimer){clearTimeout(retryTimer);retryTimer=null}setSummary(v=>({...v,recoveryAttempts:0,lastUpstreamError:null}));recovery("Manual retry requested")};(recover as typeof recover & {manual?:()=>void}).manual=manualRetry;
  // Recent trades are a one-shot seed, never a poll. Websocket overlap is
  // rejected by FlowAggregator's transaction/composite ID set.
  void(async()=>{try{const raw=await fetchJson(`/api/order-flow/trades?symbol=${encodeURIComponent(symbol)}&limit=100`);if(id!==generation.current)return;const deals=parseMexcRecentDeals(raw,symbol,contractRef.current);let accepted=0,duplicates=0;for(const deal of deals){if(aggregate.current.addDeal(deal,settingsRef.current.bubbles.timeBucketMs,settingsRef.current.bubbles.priceMode==="fixed"?settingsRef.current.bubbles.fixedPriceStep:.1))accepted++;else duplicates++;}syncRender();setSummary(v=>({...v,restTradesLoaded:deals.length,dealsAccepted:v.dealsAccepted+accepted,duplicatesRejected:v.duplicatesRejected+duplicates}));}catch(error){if(id===generation.current)setSummary(v=>({...v,lastUpstreamError:error instanceof Error?error.message:"Recent trade backfill failed"}))}})();
  const ageTimer=setInterval(()=>setSummary(v=>{if(!v.lastValidUpdate||["Bridging","LoadingSnapshot","Recovering","Error"].includes(v.status))return v;const age=Date.now()-v.lastValidUpdate,status=feedAgeStatus(age,settingsRef.current.dom.liveThresholdMs,settingsRef.current.dom.staleThresholdMs);return {...v,status,reason:status==="Live"?`Sequence ${v.version} valid`:`Last applied depth ${(age/1000).toFixed(1)}s ago`};}),500);
  const scheduleGap=(why:string)=>{if(gapTimer||inFlight||terminalError)return;gapTimer=setTimeout(()=>{gapTimer=null;if(!book.current.view().valid)recovery(why)},400)};
  (recover as typeof recover & {schedule?:typeof scheduleGap}).schedule=scheduleGap;
  return()=>{stopped=true;recover.current=()=>{};controllers.forEach(v=>v.abort());if(retryTimer)clearTimeout(retryTimer);if(gapTimer)clearTimeout(gapTimer);clearInterval(ageTimer)};
 },[enabled,symbol,publish,renderStore,syncRender]);

 const onDepth=useCallback((update:DepthUpdate)=>{if(!enabled||paused||update.symbol!==symbol)return;const now=Date.now();if(!ready.current){ready.current=true;setSummary(v=>({...v,status:"Subscribing",reason:"Depth and deal subscriptions acknowledged",wsState:"open"}));}setSummary(v=>({...v,depthMessagesReceived:v.depthMessagesReceived+1,lastWebSocketMessage:now,lastDepthEvent:now,lastWebSocketVersion:Math.max(v.lastWebSocketVersion,update.version),bufferedUpdates:book.current.view().version<0?v.bufferedUpdates+1:v.bufferedUpdates}));const result=book.current.update(update);if(result==="buffered"){setSummary(v=>({...v,status:"LoadingSnapshot",reason:"Buffering depth while loading snapshot"}));recover.current("Loading initial snapshot");return}if(result==="gap"){setSummary(v=>({...v,versionGaps:v.versionGaps+1}));const reason=`Waiting for version ${book.current.view().version+1} before ${update.version}`;setSummary(v=>({...v,reason,currentGap:`${book.current.view().version+1}…${update.version-1}`}));(recover as typeof recover & {schedule?:((reason:string)=>void)}).schedule?.(reason);return}if(result==="applied")setSummary(v=>({...v,depthMessagesApplied:v.depthMessagesApplied+1}));const view=book.current.view();if(view.valid&&view.bids.length>0&&view.asks.length>0){aggregate.current.captureBook(view,contractRef.current,update.engineTimeMs,settingsRef.current.heatmap.rangeBps);const next=alerts.current.walls(view,symbol,contractRef.current,update.engineTimeMs,settingsRef.current.alerts.wallMultiple,settingsRef.current.alerts.wallPersistenceMs);if(next.length)setSummary(v=>({...v,alerts:[...next,...v.alerts].slice(0,settingsRef.current.alerts.historyCapacity)}));syncRender();publish("Live",`Sequence ${view.version} valid`,update.engineTimeMs)}},[enabled,paused,symbol,publish,syncRender]);
 const onDeal=useCallback((deal:MexcDeal)=>{if(!enabled||paused||deal.symbol!==symbol)return;const now=Date.now();setSummary(v=>({...v,dealsReceived:v.dealsReceived+1,lastWebSocketMessage:now,lastTradeEvent:now}));const time=normalizeExchangeTimestamp(deal.timeMs);if(time===null){setSummary(v=>({...v,rejectedTimestamps:v.rejectedTimestamps+1}));return}if(deal.notional<settingsRef.current.bubbles.minimumNotional)setSummary(v=>({...v,belowThresholdDeals:v.belowThresholdDeals+1}));const accepted=aggregate.current.addDeal({...deal,timeMs:time},settingsRef.current.bubbles.timeBucketMs,settingsRef.current.bubbles.priceMode==="fixed"?settingsRef.current.bubbles.fixedPriceStep:.1);setSummary(v=>accepted?({...v,dealsAccepted:v.dealsAccepted+1}):({...v,duplicatesRejected:v.duplicatesRejected+1}));const alert=alerts.current.trade(deal,{fixed:settingsRef.current.alerts.fixedThreshold,adaptive:settingsRef.current.alerts.adaptive,percentileValue:settingsRef.current.alerts.percentile,minSamples:settingsRef.current.alerts.minimumSamples});if(alert)setSummary(v=>({...v,alerts:[alert,...v.alerts].slice(0,settingsRef.current.alerts.historyCapacity)}));syncRender()},[enabled,paused,symbol,syncRender]);
 const retry=useCallback(()=>{(recover as typeof recover & {manual?:()=>void}).manual?.()},[]);
 const clear=useCallback(()=>{aggregate.current.clear();alerts.current.clear();renderStore.update({heatmap:[],bubbles:[],captureStarted:Date.now()});setSummary(v=>({...v,alerts:[],captureStarted:Date.now()}))},[renderStore]);return{summary,onDepth,onDeal,retry,clear,renderStore};
}
