import {readFile,writeFile} from "node:fs/promises";
const path="app/lib/manual-paper.ts",source=await readFile(path,"utf8");
const once=(value,oldText,newText,label)=>{const count=value.split(oldText).length-1;if(count!==1)throw new Error(label+": "+count);return value.replace(oldText,newText)};
let next=once(source,"function closeWithDepthAt(account:ManualAccount,userId:string,symbol:string,marketPrice:number,key:string,requestedQuantity:number,depth:DepthEnvelope,current?:MexcContractMetadata){","function closeWithDepthAt(account:ManualAccount,userId:string,symbol:string,marketPrice:number,key:string,requestedQuantity:number,depth:DepthEnvelope,current?:MexcContractMetadata,closeReason:CloseReason=\"manual\"){","close reason parameter");
next=once(next,"closeReason:fullyClosed?\"manual\":undefined","closeReason:fullyClosed?closeReason:undefined","close reason evidence");
next=once(next,"export async function reverseManualPosition(userId:string,symbol:string,key:string,marketPrice:number){","async function reverseManualPositionLegacy(userId:string,symbol:string,key:string,marketPrice:number){","legacy reverse rename");
const reverseMarker="\n\nexport async function attachManualHistoricalDizyFlow";
const reverseCode=`
function mapDepthReverseEntryError(error:unknown,rules:PaperDepthContractRules):never{const code=error instanceof Error?error.message:"DEPTH_UNAVAILABLE";if(code==="DEPTH_STALE")return fail(code,"depth","Public DizyFlow depth is stale.");if(code==="DEPTH_INCOMPLETE"||code==="DEPTH_SYMBOL_MISMATCH"||code==="DEPTH_PRIOR_CONSUMPTION_EXCEEDS_BOOK")return fail("DEPTH_UNAVAILABLE","depth","The remaining public DizyFlow book cannot represent the reversed entry.");if(code==="DEPTH_LIQUIDITY_BELOW_MINIMUM")return fail(code,"quantity","Visible liquidity after the close leg cannot open the minimum "+rules.minVol+" contracts for the reversed position.");return fail("DEPTH_UNAVAILABLE","depth","The reversed paper entry cannot be represented by current public depth.")}
function openReversedDepthPosition(account:ManualAccount,userId:string,old:ManualPosition,key:string,marketPrice:number,openSide:ManualSide,entryDepthFill:PaperDepthFillEvidence,current:MexcContractMetadata){const notional=entryDepthFill.notional,feeSnapshot=mexcPublicMarketTakerFeeSnapshot(current),feeBreakdown=paperExecutionFee(notional,feeSnapshot),fee=feeBreakdown.totalFee,margin=notional/old.leverage,available=manualEquity(account,{[old.symbol]:marketPrice})-usedManualMargin(account);if(margin>available)fail("INSUFFICIENT_EQUITY","amount","Reversed position exceeds available equity after the close leg.");const timestamp=new Date().toISOString(),tradeId="mp1_"+randomUUID().replaceAll("-",""),estimatedLiquidation=estimateLiquidation({side:openSide,entryPrice:entryDepthFill.executionPrice,quantity:entryDepthFill.quantity,marginMode:old.marginMode,assignedMargin:margin,crossCollateral:manualEquity(account,{[old.symbol]:marketPrice}),entryFee:fee,maintenanceMarginRate:current.maintenanceMarginRate,liquidationPenaltyRate:account.settings.liquidationPenaltyPct/100});account.cashBalance=Math.max(0,account.cashBalance-fee);account.fees+=fee;account.positions[old.symbol]={...old,...feeSnapshot,tradeId,side:openSide,quantity:entryDepthFill.quantity,contractVolume:entryDepthFill.filledContractVolume,contractSize:current.contractSize,priceUnit:current.priceUnit,volUnit:current.volUnit,minContractVolume:current.minVol,maxContractVolume:current.maxVol,entryDepthFill,entryPrice:entryDepthFill.executionPrice,entryFee:fee,margin,stopLoss:null,takeProfit:null,estimatedLiquidation,fundingPnl:0,lastFundingSettlementAt:Date.parse(timestamp),lastRiskPrice:marketPrice,openedAt:timestamp};account.fills.push({orderId:randomUUID(),fillId:randomUUID(),tradeId,marketKey:old.marketKey,marketType:old.marketType,idempotencyKey:key,userId,symbol:old.symbol,side:openSide,marginMode:old.marginMode,leverage:old.leverage,price:entryDepthFill.executionPrice,quantity:entryDepthFill.quantity,contractVolume:entryDepthFill.filledContractVolume,contractSize:current.contractSize,priceUnit:current.priceUnit,volUnit:current.volUnit,minContractVolume:current.minVol,maxContractVolume:current.maxVol,entryDepthFill,notional,marginUsed:margin,estimatedLiquidation,riskPriceSource:old.riskPriceSource,entryFee:fee,...feeSnapshot,tradingFee:feeBreakdown.tradingFee,liquidationPenalty:feeBreakdown.liquidationPenalty,fee,timestamp,realisedPnl:0,resultingBalance:account.cashBalance})}
export async function reverseManualPosition(userId:string,symbol:string,key:string,marketPrice:number,depth?:DepthEnvelope,current?:MexcContractMetadata){if(!depth||!current)return reverseManualPositionLegacy(userId,symbol,key,marketPrice);return serial(userId,async()=>{const account=await readManualAccount(userId);if(!account.settings.enabled)fail("MANUAL_PAPER_DISABLED","settings.enabled","Manual Paper is disabled.");validateKey(account,key);const old=account.positions[symbol];if(!old)fail("NO_POSITION","symbol","No manual position.");const rules=positionDepthRules(old,current),openContractVolume=quantizeMexcStep(old.contractVolume??old.quantity/rules.contractSize,rules.volUnit,"nearest"),openSide:ManualSide=old.side==="long"?"short":"long";let closePreview:PaperDepthFillEvidence;try{closePreview=simulatePaperMarketDepthFill({side:old.side,opening:false,requestedContractVolume:openContractVolume,openContractVolume,minimumRemainingContractVolume:old.minContractVolume??rules.minVol,referencePrice:marketPrice,contract:rules,depth})}catch(error){return mapDepthExitError(error,rules)}const remaining=closePreview.remainingPositionContractVolume??Math.max(0,openContractVolume-closePreview.filledContractVolume);if(remaining>rules.volUnit*1e-9){closeWithDepthAt(account,userId,symbol,marketPrice,key+":close",old.quantity,depth,current,"reversal")}else{let entryDepthFill:PaperDepthFillEvidence;try{entryDepthFill=simulatePaperMarketDepthFill({side:openSide,opening:true,requestedContractVolume:openContractVolume,priorConsumedContractVolume:closePreview.filledContractVolume,referencePrice:marketPrice,contract:rules,depth})}catch(error){return mapDepthReverseEntryError(error,rules)}closeWithDepthAt(account,userId,symbol,marketPrice,key+":close",old.quantity,depth,current,"reversal");openReversedDepthPosition(account,userId,old,key+":open",marketPrice,openSide,entryDepthFill,current)}account.idempotencyKeys.push(key);account.fills=account.fills.slice(-500);account.idempotencyKeys=account.idempotencyKeys.slice(-1000);account.updatedAt=new Date().toISOString();await writeManualAccount(userId,account);return account})}
`;
next=once(next,reverseMarker,reverseCode+reverseMarker,"reverse insertion");
next=once(next,"export async function flattenManualPositions(userId:string,key:string,prices:Record<string,number>){","async function flattenManualPositionsLegacy(userId:string,key:string,prices:Record<string,number>){","legacy flatten rename");
const flattenMarker="\nexport async function updateManualSettings";
const flattenCode=`
export async function flattenManualPositions(userId:string,key:string,markets:Record<string,number|{price:number;depth:DepthEnvelope;contract:MexcContractMetadata}>){if(Object.values(markets).every(value=>typeof value==="number"))return flattenManualPositionsLegacy(userId,key,markets as Record<string,number>);return serial(userId,async()=>{const account=await readManualAccount(userId);if(!account.settings.enabled)fail("MANUAL_PAPER_DISABLED","settings.enabled","Manual Paper is disabled.");validateKey(account,key);const symbols=Object.keys(account.positions);for(const symbol of symbols){const market=markets[symbol],price=typeof market==="number"?market:market?.price;if(!Number.isFinite(price)||Number(price)<=0)fail("PRICE_UNAVAILABLE","marketPrice","Public price unavailable for "+symbol+".")}for(const symbol of symbols){const market=markets[symbol],position=account.positions[symbol];if(!position)continue;if(typeof market==="number")closeAt(account,userId,symbol,market,key+":"+symbol);else try{closeWithDepthAt(account,userId,symbol,market.price,key+":"+symbol,position.quantity,market.depth,market.contract)}catch(error){if(error instanceof ManualPaperError&&error.code==="DEPTH_LIQUIDITY_BELOW_MINIMUM")continue;throw error}}account.idempotencyKeys.push(key);account.fills=account.fills.slice(-500);account.idempotencyKeys=account.idempotencyKeys.slice(-1000);account.updatedAt=new Date().toISOString();await writeManualAccount(userId,account);return account})}
`;
next=once(next,flattenMarker,flattenCode+flattenMarker,"flatten insertion");
await writeFile(path,next);
