import {readFile,writeFile} from "node:fs/promises";
const path="app/lib/manual-paper.ts",source=await readFile(path,"utf8");
const once=(value,oldText,newText,label)=>{const count=value.split(oldText).length-1;if(count!==1)throw new Error(label+": "+count);return value.replace(oldText,newText)};
let next=once(source,'export type ManualSide="long"|"short";\nexport type ManualSizeMode=PaperSizeMode;','export type ManualSide="long"|"short";\nexport type ManualRiskExitTrigger={reason:Extract<CloseReason,"stop"|"target"|"liquidation">;triggeredAt:string;triggerPrice:number;priceSource:RiskPriceSource};\nexport type ManualSizeMode=PaperSizeMode;','risk trigger type');
next=once(next,'riskPriceSource:RiskPriceSource;lastRiskPrice:number;openedAt:string};','riskPriceSource:RiskPriceSource;lastRiskPrice:number;pendingRiskExit?:ManualRiskExitTrigger;openedAt:string};','position trigger field');
next=once(next,'openedAt?:string;closeReason?:CloseReason;','openedAt?:string;riskExitTrigger?:ManualRiskExitTrigger;closeReason?:CloseReason;','fill trigger field');
next=once(next,'function mapDepthExitError(error:unknown,rules:PaperDepthContractRules):never{','const isRiskExitReason=(value:CloseReason):value is ManualRiskExitTrigger["reason"]=>value==="stop"||value==="target"||value==="liquidation";\nfunction mapDepthExitError(error:unknown,rules:PaperDepthContractRules):never{','risk reason helper');
const depthStart=next.indexOf('function closeWithDepthAt('),depthEnd=next.indexOf('\nexport async function submitManualOrder',depthStart);if(depthStart<0||depthEnd<0)throw new Error('depth block missing');
let depthBlock=next.slice(depthStart,depthEnd);
depthBlock=once(depthBlock,'feeBreakdown=paperExecutionFee(notional,feeSnapshot),fee=feeBreakdown.totalFee','feeBreakdown=paperExecutionFee(notional,feeSnapshot,closeReason==="liquidation"?account.settings.liquidationPenaltyPct/100:0),riskExitTrigger=isRiskExitReason(closeReason)?position.pendingRiskExit:undefined,fee=feeBreakdown.totalFee','depth liquidation fee');
depthBlock=once(depthBlock,'openedAt:position.openedAt,closeReason:fullyClosed?closeReason:undefined','openedAt:position.openedAt,...(riskExitTrigger?{riskExitTrigger}:{}),closeReason:fullyClosed?closeReason:undefined','depth trigger evidence');
next=next.slice(0,depthStart)+depthBlock+next.slice(depthEnd);
const closeStart=next.indexOf('function closeAt('),closeEnd=next.indexOf('\nexport async function closeManualPosition',closeStart);if(closeStart<0||closeEnd<0)throw new Error('close block missing');
let closeBlock=next.slice(closeStart,closeEnd);
closeBlock=once(closeBlock,'openedAt:position.openedAt,closeReason,','openedAt:position.openedAt,...(position.pendingRiskExit?{riskExitTrigger:position.pendingRiskExit}:{}),closeReason,','legacy trigger evidence');
next=next.slice(0,closeStart)+closeBlock+next.slice(closeEnd);
const markStart=next.indexOf('export async function markManualPosition('),markEnd=next.indexOf('\nfunction validateKey',markStart);if(markStart<0||markEnd<0)throw new Error('mark block missing');
const markCode='export async function markManualPosition(userId:string,symbol:string,riskPrice:number,source:RiskPriceSource,current?:MexcFundingRateSnapshot,history:readonly MexcFundingSettlement[]=[],depth?:DepthEnvelope|null,contract?:MexcContractMetadata|null,requireDepth=false){return serial(userId,async()=>{const account=await readManualAccount(userId),position=account.positions[symbol];if(!position)return account;applyFundingHistory(account,userId,position,riskPrice,source,current,history);position.lastRiskPrice=riskPrice;position.riskPriceSource=source;const evaluated=evaluatePaperClose({side:position.side,riskPrice,stopLoss:position.stopLoss,takeProfit:position.takeProfit,estimatedLiquidation:position.estimatedLiquidation}),reason:ManualRiskExitTrigger["reason"]|null=position.pendingRiskExit?.reason??(evaluated&&isRiskExitReason(evaluated)?evaluated:null);if(reason){if(!position.pendingRiskExit)position.pendingRiskExit={reason,triggeredAt:new Date().toISOString(),triggerPrice:riskPrice,priceSource:source};if(requireDepth){if(depth&&contract)try{closeWithDepthAt(account,userId,symbol,riskPrice,`auto-${reason}-${Date.now()}`,position.quantity,depth,contract,reason)}catch(error){if(!(error instanceof ManualPaperError&&["DEPTH_STALE","DEPTH_UNAVAILABLE","DEPTH_LIQUIDITY_BELOW_MINIMUM"].includes(error.code)))throw error}}else closeAt(account,userId,symbol,riskPrice,`auto-${reason}-${Date.now()}`,reason)}account.updatedAt=new Date().toISOString();await writeManualAccount(userId,account);return account})}';
next=next.slice(0,markStart)+markCode+next.slice(markEnd);
const legacyReverseStart=next.indexOf('async function reverseManualPositionLegacy('),legacyReverseEnd=next.indexOf('\nfunction mapDepthReverseEntryError',legacyReverseStart);if(legacyReverseStart>=0&&legacyReverseEnd>legacyReverseStart){let block=next.slice(legacyReverseStart,legacyReverseEnd);block=block.replace('fundingPnl:0,lastFundingSettlementAt','fundingPnl:0,pendingRiskExit:undefined,lastFundingSettlementAt');next=next.slice(0,legacyReverseStart)+block+next.slice(legacyReverseEnd)}
const depthReverseStart=next.indexOf('function openReversedDepthPosition('),depthReverseEnd=next.indexOf('\nexport async function reverseManualPosition',depthReverseStart);if(depthReverseStart>=0&&depthReverseEnd>depthReverseStart){let block=next.slice(depthReverseStart,depthReverseEnd);block=block.replace('fundingPnl:0,lastFundingSettlementAt','fundingPnl:0,pendingRiskExit:undefined,lastFundingSettlementAt');next=next.slice(0,depthReverseStart)+block+next.slice(depthReverseEnd)}
await writeFile(path,next);
