import {readFile,writeFile,readdir} from "node:fs/promises";

await writeFile("tests/manual-paper-margin-model.test.mjs",`import test from "node:test";
import assert from "node:assert/strict";
import {buildPaperMarginAccountSnapshot,buildPaperPositionMarginAudit,settlePaperMarginCash} from "../app/lib/manual-paper-margin-model.ts";

const position=(overrides={})=>({symbol:"BTC_USDT",side:"long",quantity:10,entryPrice:100,markPrice:100,margin:100,marginMode:"cross",maintenanceMarginRate:.01,liquidationPenaltyRate:.001,...overrides});

test("single-asset margin snapshot fences isolated collateral from the cross pool",()=>{const isolated=position({symbol:"ISO_USDT",marginMode:"isolated",markPrice:50}),crossLong=position({symbol:"LONG_USDT",markPrice:110}),crossShort=position({symbol:"SHORT_USDT",side:"short",markPrice:90}),snapshot=buildPaperMarginAccountSnapshot(1000,[isolated,crossLong,crossShort],123);assert.equal(snapshot.isolatedReservedMargin,100);assert.equal(snapshot.crossPoolCash,900);assert.equal(snapshot.crossUnrealisedPnl,200);assert.equal(snapshot.crossEquity,1100);assert.equal(snapshot.crossInitialMargin,200);assert.equal(snapshot.crossAvailableEquity,900);assert.equal(snapshot.crossPositionCount,2);assert.equal(snapshot.capturedAt,123);assert.equal(snapshot.settlementAsset,"USDT")});

test("position audits distinguish fenced isolated support from the shared cross pool",()=>{const isolated=position({symbol:"ISO_USDT",marginMode:"isolated"}),cross=position({symbol:"CROSS_USDT",markPrice:110}),other=position({symbol:"OTHER_USDT",side:"short",markPrice:90}),snapshot=buildPaperMarginAccountSnapshot(1000,[isolated,cross,other],456),isolatedAudit=buildPaperPositionMarginAudit(isolated,snapshot),crossAudit=buildPaperPositionMarginAudit(cross,snapshot);assert.equal(isolatedAudit.calculationMethod,"isolated-position-collateral-v1");assert.equal(isolatedAudit.collateralAvailableToPosition,isolated.margin);assert.equal(isolatedAudit.supportingCrossPositionCount,1);assert.equal(crossAudit.calculationMethod,"cross-shared-usdt-pool-v1");assert.equal(crossAudit.supportingCrossPositionCount,2);assert.equal(crossAudit.collateralAvailableToPosition,snapshot.crossPoolCash+crossAudit.otherCrossUnrealisedPnl-crossAudit.otherCrossMaintenanceRequirement-crossAudit.otherCrossLiquidationReserve)});

test("loss settlement caps isolated loss and protects isolated collateral from cross loss",()=>{const isolated=settlePaperMarginCash({cashBalance:1000,marginMode:"isolated",allocatedMargin:100,isolatedReservedMargin:100,requestedCashDelta:-500}),cross=settlePaperMarginCash({cashBalance:1000,marginMode:"cross",allocatedMargin:200,isolatedReservedMargin:300,requestedCashDelta:-900});assert.equal(isolated.cashAfter,900);assert.equal(isolated.appliedCashDelta,-100);assert.equal(isolated.capped,true);assert.equal(cross.cashAfter,300);assert.equal(cross.appliedCashDelta,-700);assert.equal(cross.protectedCollateral,300);assert.equal(cross.capped,true)});
`,"utf8");

await writeFile("tests/manual-paper-margin-lifecycle.test.mjs",`import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {parseMexcContractMetadata} from "../app/lib/mexc-contract-metadata.ts";

const contract=symbol=>parseMexcContractMetadata({success:true,data:[{symbol,displayNameEn:symbol+" SWAP",positionOpenType:3,contractSize:1,minLeverage:1,maxLeverage:50,priceUnit:.1,volUnit:1,minVol:1,maxVol:1000,makerFeeRate:.0002,takerFeeRate:.0006,maintenanceMarginRate:.01,initialMarginRate:.02,riskLimitType:"BY_VOLUME"}]},symbol);
const levels=(price,volume)=>[{price,orderCount:1,contractQuantity:volume}];
const book=(symbol,price=100,volume=1000)=>({snapshot:{symbol,version:1,engineTimeMs:Date.now(),bids:levels(price,volume),asks:levels(price,volume)},receivedAt:Date.now(),diagnostic:{snapshotAgeMs:0,consecutiveFailures:0,lastError:null,sourceMode:"REST FALLBACK",snapshotComplete:true}});
async function isolated(name,fn){const prior=process.env.DATA_DIR,root=await mkdtemp(join(tmpdir(),name));process.env.DATA_DIR=root;try{return await fn()}finally{if(prior===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=prior;await rm(root,{recursive:true,force:true})}}
const open=(submit,user,symbol,marginMode,notional)=>submit(user,{idempotencyKey:`open-${symbol.toLowerCase().replaceAll("_","")}-000001`,symbol,side:"long",sizeMode:"fixed-notional",amount:notional,leverage:50,marginMode},100,"fair",contract(symbol),undefined,book(symbol));

test("cross marks re-audit every shared-pool liquidation while isolated liquidation stays fenced",()=>isolated("dizy-margin-life-",async()=>{const {submitManualOrder,markManualPosition}=await import("../app/lib/manual-paper.ts"),user="margin-life-user";let account=await open(submitManualOrder,user,"BTC_USDT","cross",40000);account=await open(submitManualOrder,user,"ETH_USDT","cross",40000);const base=account.positions.BTC_USDT.estimatedLiquidation;account=await markManualPosition(user,"ETH_USDT",110,"fair");const rescued=account.positions.BTC_USDT.estimatedLiquidation;account=await markManualPosition(user,"ETH_USDT",90,"fair");const pressured=account.positions.BTC_USDT.estimatedLiquidation;assert.ok(rescued<base,`expected ${rescued} < ${base}`);assert.ok(pressured>base,`expected ${pressured} > ${base}`);assert.equal(account.positions.BTC_USDT.marginAudit.calculationMethod,"cross-shared-usdt-pool-v1");assert.equal(account.positions.BTC_USDT.marginAudit.supportingCrossPositionCount,2)}));

test("isolated liquidation does not move when a cross position gains or loses",()=>isolated("dizy-margin-iso-",async()=>{const {submitManualOrder,markManualPosition}=await import("../app/lib/manual-paper.ts"),user="margin-isolated-user";let account=await open(submitManualOrder,user,"BTC_USDT","isolated",1000);account=await open(submitManualOrder,user,"ETH_USDT","cross",40000);const base=account.positions.BTC_USDT.estimatedLiquidation;account=await markManualPosition(user,"ETH_USDT",110,"fair");assert.ok(Math.abs(account.positions.BTC_USDT.estimatedLiquidation-base)<1e-10);account=await markManualPosition(user,"ETH_USDT",90,"fair");assert.ok(Math.abs(account.positions.BTC_USDT.estimatedLiquidation-base)<1e-10);assert.equal(account.positions.BTC_USDT.marginAudit.collateralAvailableToPosition,account.positions.BTC_USDT.margin)}));

test("isolated close losses are capped to assigned margin and survive backup validation",()=>isolated("dizy-margin-cap-",async()=>{const {submitManualOrder,closeManualPosition}=await import("../app/lib/manual-paper.ts"),{validateManualPaperBackup}=await import("../app/lib/manual-paper-backup.ts"),user="margin-cap-user";let account=await open(submitManualOrder,user,"BTC_USDT","isolated",1000),before=account.cashBalance,margin=account.positions.BTC_USDT.margin;account=await closeManualPosition(user,"BTC_USDT","close-btcusdt-000001",1);const fill=account.fills.at(-1);assert.equal(fill.marginSettlement.capped,true);assert.ok(Math.abs((before-account.cashBalance)-margin)<1e-8);assert.equal(fill.marginSettlement.calculationMethod,"isolated-position-loss-cap-v1");assert.doesNotThrow(()=>validateManualPaperBackup(account,user));const copy=structuredClone(account);copy.fills.at(-1).marginSettlement.cashAfter+=1;assert.throws(()=>validateManualPaperBackup(copy,user),/settlement|reconcile/i)}));

test("backup validation rejects contradictory cross-pool evidence",()=>isolated("dizy-margin-backup-",async()=>{const {submitManualOrder}=await import("../app/lib/manual-paper.ts"),{validateManualPaperBackup}=await import("../app/lib/manual-paper-backup.ts"),user="margin-backup-user";const account=await open(submitManualOrder,user,"BTC_USDT","cross",40000);assert.doesNotThrow(()=>validateManualPaperBackup(account,user));const accountCopy=structuredClone(account);accountCopy.marginSnapshot.crossEquity+=1;assert.throws(()=>validateManualPaperBackup(accountCopy,user),/cross equity/i);const positionCopy=structuredClone(account);positionCopy.positions.BTC_USDT.marginAudit.collateralAvailableToPosition+=1;assert.throws(()=>validateManualPaperBackup(positionCopy,user),/cross collateral/i)}));
`,"utf8");

await writeFile("tests/manual-paper-margin-source.test.mjs",`import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";

test("isolated and cross assumptions are explicit at source boundaries",async()=>{const [model,core,backup,ticket,roadmap]=await Promise.all([readFile("app/lib/manual-paper-margin-model.ts","utf8"),readFile("app/lib/manual-paper.ts","utf8"),readFile("app/lib/manual-paper-backup.ts","utf8"),readFile("app/manual-paper-ticket.tsx","utf8"),readFile("ROADMAP.md","utf8")]);for(const value of ["single-asset-usdt-margin-pool-v1","isolated-position-collateral-v1","cross-shared-usdt-pool-v1","isolated-position-loss-cap-v1","cross-shared-pool-loss-cap-v1"])assert.match(model,new RegExp(value));assert.match(core,/refreshAccountRisk/);assert.match(core,/settleManualClose/);assert.match(backup,/cross pool cash does not reconcile/);assert.match(backup,/cross collateral does not reconcile/);assert.match(ticket,/Isolated collateral reserved/);assert.match(ticket,/Cross shared equity/);assert.match(ticket,/Cross · shared USDT pool/);assert.ok(roadmap.includes("- [x] clearer isolated versus cross-margin assumptions"));assert.match(roadmap,/Next slice: migration-safe history and backup support/)});
`,"utf8");

for(const name of await readdir("tests")){if(!name.endsWith(".mjs"))continue;const path="tests/"+name,source=await readFile(path,"utf8"),next=source.replaceAll("cross-collateral-snapshot","cross-shared-usdt-pool").replaceAll("Next slice: clearer isolated versus cross-margin assumptions","Next slice: migration-safe history and backup support");if(next!==source)await writeFile(path,next,"utf8")}
