"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CandlestickSeries, ColorType, createChart, LineSeries, LineStyle, type IChartApi } from "lightweight-charts";
import { DEFAULT_TERMINAL_SETTINGS, type UserTerminalSettings } from "../lib/config";
import { analyzeStrategy, type Candle, type StrategyAnalysis } from "../lib/strategy";
import type { CandleTimeframe, MarketDescriptor } from "../lib/market/types";
import { buildAdvancedMarketStructure, type AdvancedMarketStructure, type StructureLevelKind, type VwapAnchorMode } from "../lib/advanced-market-structure";
import styles from "./structure.module.css";

const TIMEFRAMES:CandleTimeframe[]=["15m","1h","4h","1d"];
const money=(value:number|null)=>value===null?"Unavailable":value.toLocaleString(undefined,{maximumSignificantDigits:9});
const signed=(value:number|null)=>value===null?"Unavailable":`${value>=0?"+":""}${value.toFixed(3)}%`;
const colour:Record<StructureLevelKind,string>={session:"#58a6ff","opening-range":"#d7a74d","previous-day":"#9f7aea","previous-week":"#e879a9",vwap:"#48d9cb",swing:"#93a4bc"};

type FrameResult={timeframe:CandleTimeframe;candles:Candle[];analysis:StrategyAnalysis|null;error:string|null};

function Chart({candles,structure}:{candles:readonly Candle[];structure:AdvancedMarketStructure|null}){
  const host=useRef<HTMLDivElement>(null),chartRef=useRef<IChartApi|null>(null);
  useEffect(()=>{
    const container=host.current;if(!container||!candles.length)return;
    const chart=createChart(container,{autoSize:true,layout:{background:{type:ColorType.Solid,color:"#090f1a"},textColor:"#98a9c3"},grid:{vertLines:{color:"#151f31"},horzLines:{color:"#151f31"}},rightPriceScale:{borderColor:"#24334c"},timeScale:{borderColor:"#24334c",timeVisible:true,secondsVisible:false,rightOffset:8},crosshair:{vertLine:{color:"#5e7598"},horzLine:{color:"#5e7598"}}});chartRef.current=chart;
    const candleSeries=chart.addSeries(CandlestickSeries,{upColor:"#35c895",downColor:"#ed6478",wickUpColor:"#35c895",wickDownColor:"#ed6478",borderVisible:false});
    candleSeries.setData(candles.map(candle=>({time:candle.time,open:candle.open,high:candle.high,low:candle.low,close:candle.close})));
    if(structure?.anchoredVwap.series.length){const line=chart.addSeries(LineSeries,{color:"#48d9cb",lineWidth:2,priceLineVisible:false,lastValueVisible:true,title:structure.anchoredVwap.label});line.setData(structure.anchoredVwap.series.map(point=>({time:point.time,value:point.value})));}
    for(const level of structure?.levels??[]){if(level.kind==="vwap")continue;candleSeries.createPriceLine({price:level.price,color:colour[level.kind],lineWidth:1,lineStyle:level.complete?LineStyle.Dashed:LineStyle.Dotted,axisLabelVisible:true,title:level.label});}
    chart.timeScale().fitContent();const observer=new ResizeObserver(()=>chart.applyOptions({width:container.clientWidth,height:container.clientHeight}));observer.observe(container);
    return()=>{observer.disconnect();chart.remove();chartRef.current=null;};
  },[candles,structure]);
  return <div className={styles.chart} ref={host}/>;
}

function frameLean(analysis:StrategyAnalysis|null){if(!analysis)return "unavailable" as const;if(analysis.scoreLong>analysis.scoreShort)return "long" as const;if(analysis.scoreShort>analysis.scoreLong)return "short" as const;return "balanced" as const;}

export default function StructureClient({readOnly,userName}:{readOnly:boolean;userName:string}){
  const [settings,setSettings]=useState<UserTerminalSettings|null>(null),[markets,setMarkets]=useState<MarketDescriptor[]>([]),[selectedKey,setSelectedKey]=useState(""),[timeframe,setTimeframe]=useState<CandleTimeframe>("1h"),[anchorMode,setAnchorMode]=useState<VwapAnchorMode>("utc-week"),[customAnchor,setCustomAnchor]=useState(""),[openingMinutes,setOpeningMinutes]=useState(60),[tolerance,setTolerance]=useState(.18),[query,setQuery]=useState(""),[frames,setFrames]=useState<FrameResult[]>([]),[structure,setStructure]=useState<AdvancedMarketStructure|null>(null),[loading,setLoading]=useState(true),[status,setStatus]=useState("Loading current market profile…");
  const controller=useRef<AbortController|null>(null),request=useRef(0);
  const selected=useMemo(()=>markets.find(market=>market.key===selectedKey)??null,[markets,selectedKey]);
  const chartFrame=frames.find(frame=>frame.timeframe===timeframe),chartCandles=chartFrame?.candles??[];
  const searchResults=useMemo(()=>{const needle=query.trim().toLowerCase();if(!needle)return [];return markets.filter(market=>market.status==="active"&&`${market.displayName} ${market.baseAsset} ${market.quoteAsset} ${market.marketType}`.toLowerCase().includes(needle)).sort((a,b)=>(b.volume24h??0)-(a.volume24h??0)).slice(0,12);},[markets,query]);

  useEffect(()=>{const abort=new AbortController();const timer=window.setTimeout(()=>{void Promise.all([
    fetch("/api/profile",{signal:abort.signal}).then(async response=>response.ok?(await response.json() as {settings:UserTerminalSettings}).settings:DEFAULT_TERMINAL_SETTINGS),
    fetch("/api/markets?exchange=mexc",{signal:abort.signal}).then(async response=>response.ok?(await response.json() as {markets:MarketDescriptor[]}).markets:[]),
  ]).then(([profile,available])=>{if(abort.signal.aborted)return;const viewer=readOnly?JSON.parse(sessionStorage.getItem("dizy-viewer-market")||"null") as UserTerminalSettings["market"]|null:null,market=available.find(item=>item.key===(viewer?.marketKey??profile.market.marketKey))??available.find(item=>item.marketType==="futures"&&item.sourceSymbol==="BTC_USDT")??available[0];setSettings(profile);setMarkets(available);setSelectedKey(market?.key??"");setTimeframe(TIMEFRAMES.includes((viewer?.timeframe??profile.market.timeframe) as CandleTimeframe)?(viewer?.timeframe??profile.market.timeframe) as CandleTimeframe:"1h");setStatus(market?"Market loaded. Building closed-candle structure…":"MEXC market catalogue is unavailable.");}).catch(reason=>{if((reason as Error).name!=="AbortError")setStatus("DizyStructure initialization failed.");});},0);return()=>{window.clearTimeout(timer);abort.abort();};},[readOnly]);

  const load=useCallback(async()=>{
    if(!selected||!settings)return;const id=++request.current;controller.current?.abort();const abort=new AbortController();controller.current=abort;setLoading(true);setStatus(`Loading ${selected.displayName} closed candles across 15m, 1h, 4h and 1d…`);
    try{
      const results=await Promise.all(TIMEFRAMES.map(async frame=>{try{const limit=frame==="15m"?1000:frame==="1h"?900:frame==="4h"?700:240,response=await fetch(`/api/market?exchange=mexc&marketType=${selected.marketType}&symbol=${encodeURIComponent(selected.sourceSymbol)}&timeframe=${frame}&limit=${limit}`,{signal:abort.signal});if(!response.ok)throw new Error("feed unavailable");const body=await response.json() as {candles:Candle[]},candles=body.candles;return {timeframe:frame,candles,analysis:candles.length>=40?analyzeStrategy(candles,settings.strategy):null,error:candles.length?null:"no confirmed candles"} satisfies FrameResult;}catch(reason){if((reason as Error).name==="AbortError")throw reason;return {timeframe:frame,candles:[],analysis:null,error:"feed unavailable"} satisfies FrameResult;}}));
      if(abort.signal.aborted||id!==request.current)return;setFrames(results);const primary=results.find(result=>result.timeframe===timeframe)?.candles??[],intraday=results.find(result=>result.timeframe==="15m")?.candles??[],daily=results.find(result=>result.timeframe==="1d")?.candles??[],customMs=customAnchor?new Date(customAnchor).getTime():NaN;
      const next=buildAdvancedMarketStructure({chartCandles:primary,intradayCandles:intraday,dailyCandles:daily,anchorMode,customAnchorTime:Number.isFinite(customMs)?Math.floor(customMs/1000):null,openingRangeMinutes:openingMinutes,clusterTolerancePct:tolerance});setStructure(next);const failed=results.filter(result=>result.error).length;setStatus(`${results.length-failed} / ${results.length} timeframe feeds available · structure as of ${next.asOfTime?new Date(next.asOfTime*1000).toLocaleString():"unavailable"}.`);
    }catch(reason){if((reason as Error).name!=="AbortError"&&id===request.current)setStatus("Market structure refresh failed. Existing analysis is preserved.");}finally{if(id===request.current&&!abort.signal.aborted)setLoading(false);}
  },[anchorMode,customAnchor,openingMinutes,selected,settings,timeframe,tolerance]);
  useEffect(()=>{if(!selected||!settings)return;const timer=window.setTimeout(()=>void load(),80);return()=>window.clearTimeout(timer);},[selected,settings,timeframe,anchorMode,customAnchor,openingMinutes,tolerance,load]);
  useEffect(()=>()=>controller.current?.abort(),[]);

  const mtf=frames.map(frame=>({frame,...frame,lean:frameLean(frame.analysis)})),longs=mtf.filter(item=>item.lean==="long").length,shorts=mtf.filter(item=>item.lean==="short").length,alignment=longs>shorts?`${longs} / ${mtf.length} timeframes lean long`:shorts>longs?`${shorts} / ${mtf.length} timeframes lean short`:`${mtf.length} timeframe evidence is mixed`;
  async function openChart(){if(!selected||!settings)return;const next={...settings,market:{...settings.market,symbol:selected.sourceSymbol,marketKey:selected.key,timeframe}};setStatus(`Opening ${selected.displayName} ${timeframe} in DizyCharts…`);try{if(readOnly)sessionStorage.setItem("dizy-viewer-market",JSON.stringify(next.market));else{const response=await fetch("/api/profile",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(next)});if(!response.ok)throw new Error();}window.location.assign("/terminal");}catch{setStatus("Selected chart settings could not be saved.");}}

  return <main className={styles.shell}><header className={styles.topbar}><div><b>DizyTrades</b><span>DizyStructure</span></div><nav><a href="/terminal">DizyCharts</a><a href="/scanner">DizyScanner</a><a href="/performance">DizyPerformance</a><a href="/journal">DizyJournal</a><strong>{userName}{readOnly?" · Viewer":""}</strong></nav></header>
    <section className={styles.hero}><div><span>ADVANCED CLOSED-CANDLE MARKET STRUCTURE</span><h1>Sessions, anchored value and multi-timeframe structure in one workspace.</h1><p>Crypto session boundaries use the stated UTC convention. Levels are descriptive references from confirmed public candles, not liquidity guarantees or directional predictions.</p></div><div className={styles.heroActions}><button disabled={loading} onClick={()=>void load()}>{loading?"Refreshing…":"Refresh structure"}</button><button disabled={!selected} onClick={()=>void openChart()}>Open in DizyCharts</button></div></section>
    <section className={styles.controls}><div className={styles.marketSearch}><label>Market<input placeholder="Search BTC, ETH, spot, futures…" value={query} onChange={event=>setQuery(event.target.value)}/></label>{searchResults.length?<div className={styles.searchResults}>{searchResults.map(market=><button key={market.key} onClick={()=>{setSelectedKey(market.key);setQuery("");}}><span>{market.displayName}</span><small>{market.marketType}</small></button>)}</div>:null}<strong>{selected?.displayName??"No market selected"} · {selected?.marketType??""}</strong></div><label>Chart timeframe<select value={timeframe} onChange={event=>setTimeframe(event.target.value as CandleTimeframe)}>{TIMEFRAMES.map(frame=><option key={frame}>{frame}</option>)}</select></label><label>VWAP anchor<select value={anchorMode} onChange={event=>setAnchorMode(event.target.value as VwapAnchorMode)}><option value="utc-day">UTC day</option><option value="utc-week">UTC week</option><option value="swing-high">Latest swing high</option><option value="swing-low">Latest swing low</option><option value="custom">Custom time</option></select></label>{anchorMode==="custom"?<label>Custom anchor<input type="datetime-local" value={customAnchor} onChange={event=>setCustomAnchor(event.target.value)}/></label>:null}<label>Opening range<select value={openingMinutes} onChange={event=>setOpeningMinutes(Number(event.target.value))}>{[30,60,120,240].map(value=><option value={value} key={value}>{value} minutes</option>)}</select></label><label>Cluster tolerance<select value={tolerance} onChange={event=>setTolerance(Number(event.target.value))}>{[[.1,"0.10%"],[.18,"0.18%"],[.25,"0.25%"],[.5,"0.50%"]].map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><div className={styles.status} role="status"><b>{status}</b><small>UTC 00:00 daily session · Monday 00:00 weekly boundary · closed candles only</small></div></section>
    <section className={styles.workspace}><article className={styles.chartPanel}><header><div><h2>{selected?.displayName??"Market"} · {timeframe}</h2><p>{structure?.anchoredVwap.label??"Anchored VWAP"} · {structure?.anchoredVwap.available?`${structure.anchoredVwap.sampleCount} volume-bearing candles`:structure?.anchoredVwap.reason??"waiting"}</p></div><strong>{money(structure?.referencePrice??null)}</strong></header><Chart candles={chartCandles} structure={structure}/></article><aside className={styles.summary}><article><span>SWING STRUCTURE</span><strong>{structure?.swing.state.replaceAll("-"," ")??"Unavailable"}</strong><p>{structure?.swing.highSequence??"—"} highs · {structure?.swing.lowSequence??"—"} lows</p></article><article><span>MULTI-TIMEFRAME ALIGNMENT</span><strong>{alignment}</strong><p>Evidence split only; no prediction or trade instruction.</p></article><article><span>ANCHORED VWAP</span><strong>{money(structure?.anchoredVwap.value??null)}</strong><p>{structure?.anchoredVwap.anchorTime?`Anchored ${new Date(structure.anchoredVwap.anchorTime*1000).toLocaleString()}`:"Anchor unavailable"}</p></article><article><span>NEAREST LEVEL CLUSTER</span><strong>{structure?.clusters[0]?money(structure.clusters[0].price):"Unavailable"}</strong><p>{structure?.clusters[0]?.labels.join(" · ")??"No levels cluster inside the selected tolerance."}</p></article></aside></section>
    <section className={styles.grid}><article className={styles.panel}><header><h2>Multi-timeframe evidence</h2><p>Uses the existing DizySignals engine independently on each confirmed timeframe.</p></header><div className={styles.frames}>{mtf.map(item=><div key={item.frame.timeframe}><b>{item.frame.timeframe}</b><strong className={item.lean==="long"?styles.positive:item.lean==="short"?styles.negative:styles.neutral}>{item.lean}</strong>{item.frame.analysis?<><span>{item.frame.analysis.bias} · {item.frame.analysis.phase}</span><small>L {item.frame.analysis.scoreLong} · S {item.frame.analysis.scoreShort} · {item.frame.candles.length} candles</small></>:<small>{item.frame.error??"Analysis unavailable"}</small>}</div>)}</div></article><article className={styles.panel}><header><h2>UTC session map</h2><p>24/7 crypto convention, not an exchange trading-hours claim.</p></header><dl className={styles.session}>{[["Session open",structure?.currentDay?.open],["Session high",structure?.currentDay?.high],["Session low",structure?.currentDay?.low],[`${openingMinutes}m OR high`,structure?.openingRange?.high],[`${openingMinutes}m OR low`,structure?.openingRange?.low],["Previous day high",structure?.previousDay?.high],["Previous day low",structure?.previousDay?.low],["Previous week high",structure?.previousWeek?.high],["Previous week low",structure?.previousWeek?.low]].map(([label,value])=><div key={label as string}><dt>{label as string}</dt><dd>{money((value as number|undefined)??null)}</dd></div>)}</dl></article></section>
    <section className={styles.panel}><header><h2>Nearest structural levels</h2><p>Distance is measured from the latest confirmed close on the selected chart timeframe.</p></header><div className={styles.levels}>{structure?.levels.length?structure.levels.map(level=><article key={level.key}><i style={{background:colour[level.kind]}}/><div><b>{level.label}</b><small>{level.kind.replaceAll("-"," ")} · {level.complete?"complete":"partial"}</small></div><strong>{money(level.price)}</strong><span className={(level.distancePct??0)>=0?styles.positive:styles.negative}>{signed(level.distancePct)}</span></article>):<div className={styles.empty}>No structural levels are available.</div>}</div></section>
    <section className={styles.grid}><article className={styles.panel}><header><h2>Level clusters</h2><p>Multiple independent references within {tolerance.toFixed(2)}% of their group mean.</p></header>{structure?.clusters.length?<div className={styles.clusters}>{structure.clusters.map(cluster=><div key={cluster.key}><strong>{money(cluster.price)}</strong><span>{signed(cluster.distancePct)}</span><p>{cluster.labels.join(" · ")}</p></div>)}</div>:<div className={styles.empty}>No current confluence clusters at this tolerance.</div>}</article><article className={styles.panel}><header><h2>Evidence limitations</h2><p>Missing evidence stays missing.</p></header>{structure?.limitations.length?<ul className={styles.limitations}>{structure.limitations.map(item=><li key={item}>{item}</li>)}</ul>:<p className={styles.clear}>All requested closed-candle structure inputs are available.</p>}</article></section>
  </main>;
}
