import "server-only";
import { chmodSync,existsSync,mkdirSync,statSync } from "node:fs";
import { dirname,join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import type { MexcExecutionLifecycleStore,MexcIntentEvidence,MexcLifecycleEvidence,MexcLifecycleState } from "./mexc-execution-writer";

const STATE=new Set<MexcLifecycleState>(["reserved","submitting","submitted","indeterminate","reconciled","quarantined"]);
const HEX=/^[a-f0-9]{64}$/,OID=/^dizy_[a-f0-9]{27}$/,TOKEN=/^[A-Za-z0-9_-]{1,120}$/,POSITION=/^[1-9][0-9]{0,30}$/;
export class MexcLifecycleStoreError extends Error {constructor(){super("MEXC_EXECUTION_LIFECYCLE_STORE_FAILURE");this.name="MexcLifecycleStoreError";}}
const fail=():never=>{throw new MexcLifecycleStoreError();};
export class SqliteMexcExecutionLifecycleStore implements MexcExecutionLifecycleStore {
  private database:DatabaseSync|null=null;private identity:{dev:number;ino:number}|null=null;private poisoned=false;
  constructor(private readonly path=join(process.env.DATA_DIR||join(process.cwd(),".data"),"mexc-execution-lifecycle.sqlite")){}
  private backing(){try{const s=statSync(this.path);return {dev:s.dev,ino:s.ino};}catch{return fail();}}
  private poison():never{this.poisoned=true;try{this.database?.close();}catch{}this.database=null;return fail();}
  private assertBacking(){if(this.poisoned)return fail();if(this.path===":memory:")return;const x=this.backing();if(!this.identity||x.dev!==this.identity.dev||x.ino!==this.identity.ino)return this.poison();}
  private harden(){if(this.path===":memory:")return;for(const p of [this.path,`${this.path}-wal`,`${this.path}-shm`])if(existsSync(p))chmodSync(p,0o600);}
  private db(){if(this.poisoned)return fail();if(this.database){this.assertBacking();return this.database;}let db:DatabaseSync|null=null;try{if(this.path!==":memory:")mkdirSync(dirname(this.path),{recursive:true,mode:0o700});db=new DatabaseSync(this.path);db.exec(`PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000;
CREATE TABLE IF NOT EXISTS lifecycle(identity_digest TEXT PRIMARY KEY,external_oid TEXT UNIQUE NOT NULL,state TEXT NOT NULL,attempt INTEGER NOT NULL,order_id TEXT,error_class TEXT,updated_at TEXT NOT NULL,intent_digest TEXT NOT NULL,symbol TEXT NOT NULL,side INTEGER NOT NULL,volume REAL NOT NULL,position_id TEXT NOT NULL,position_mode INTEGER NOT NULL,open_type INTEGER NOT NULL,binding_generation TEXT NOT NULL,rollout_revision INTEGER NOT NULL,risk_revision INTEGER NOT NULL,reconciliation_revision INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS account_quarantine(user_id TEXT NOT NULL,account_id TEXT NOT NULL,reason TEXT NOT NULL,quarantined_at TEXT NOT NULL,PRIMARY KEY(user_id,account_id));`);this.database=db;this.harden();if(this.path!==":memory:")this.identity=this.backing();return db;}catch{try{db?.close();}catch{}return this.poison();}}
  private parse(row:Record<string,unknown>|undefined):MexcLifecycleEvidence|null{if(!row)return null;const state=String(row.state) as MexcLifecycleState,updatedAt=String(row.updated_at),orderId=row.order_id===null?null:String(row.order_id),errorClass=row.error_class===null?null:String(row.error_class),volume=Number(row.volume);if(!HEX.test(String(row.identity_digest))||!OID.test(String(row.external_oid))||!HEX.test(String(row.intent_digest))||!STATE.has(state)||!Number.isSafeInteger(row.attempt)||(row.attempt as number)<0||(orderId!==null&&!/^[A-Za-z0-9_-]{1,64}$/.test(orderId))||(errorClass!==null&&errorClass.length>64)||new Date(updatedAt).toISOString()!==updatedAt||!POSITION.test(String(row.position_id))||![2,4].includes(Number(row.side))||!Number.isFinite(volume)||volume<=0||Number(row.position_mode)!==2||![1,2].includes(Number(row.open_type)))return fail();return Object.freeze({identityDigest:String(row.identity_digest),externalOid:String(row.external_oid),state,attempt:row.attempt as number,orderId,errorClass,updatedAt,intentDigest:String(row.intent_digest),symbol:String(row.symbol),side:Number(row.side),volume,positionId:String(row.position_id),positionMode:2,openType:Number(row.open_type) as 1|2,bindingGeneration:String(row.binding_generation),rolloutRevision:Number(row.rollout_revision),riskRevision:Number(row.risk_revision),reconciliationRevision:Number(row.reconciliation_revision)});}
  read(digest:string){if(!HEX.test(digest))return fail();const db=this.db();try{const value=this.parse(db.prepare("SELECT * FROM lifecycle WHERE identity_digest=?").get(digest) as Record<string,unknown>|undefined);this.assertBacking();return value;}catch(e){if(e instanceof MexcLifecycleStoreError)throw e;return fail();}}
  reserve(digest:string,oid:string,intent:MexcIntentEvidence,at:string){if(!HEX.test(digest)||!OID.test(oid)||!HEX.test(intent.intentDigest))return fail();const db=this.db();try{db.prepare("INSERT OR IGNORE INTO lifecycle VALUES(?,?,'reserved',0,NULL,NULL,?,?,?,?,?,?,?,?,?,?,?,?)").run(digest,oid,at,intent.intentDigest,intent.symbol,intent.side,intent.volume,intent.positionId,intent.positionMode,intent.openType,intent.bindingGeneration,intent.rolloutRevision,intent.riskRevision,intent.reconciliationRevision);this.harden();return this.read(digest)!;}catch{return fail();}}
  claim(digest:string,at:string){if(!HEX.test(digest))return fail();const db=this.db();try{const result=db.prepare("UPDATE lifecycle SET state='submitting',attempt=attempt+1,updated_at=? WHERE identity_digest=? AND state='reserved' AND attempt=0").run(at,digest);this.harden();return result.changes===1?this.read(digest):null;}catch{return fail();}}
  transition(digest:string,expected:readonly MexcLifecycleState[],state:MexcLifecycleState,patch:Readonly<{orderId?:string|null;errorClass?:string|null}>,at:string){if(!HEX.test(digest)||!expected.length||!expected.every(x=>STATE.has(x))||!STATE.has(state))return fail();const old=this.read(digest);if(!old||!expected.includes(old.state))return fail();const orderId=patch.orderId===undefined?old.orderId:patch.orderId,errorClass=patch.errorClass===undefined?old.errorClass:patch.errorClass,db=this.db();try{const result=db.prepare("UPDATE lifecycle SET state=?,order_id=?,error_class=?,updated_at=? WHERE identity_digest=? AND state=?").run(state,orderId,errorClass,at,digest,old.state);if(result.changes!==1)return fail();this.harden();return this.read(digest)!;}catch(e){if(e instanceof MexcLifecycleStoreError)throw e;return fail();}}
  quarantineAccount(userId:string,accountId:string,reason:string,at:string){if(!TOKEN.test(userId)||!TOKEN.test(accountId)||!reason||reason.length>64)return fail();try{this.db().prepare("INSERT OR IGNORE INTO account_quarantine VALUES(?,?,?,?)").run(userId,accountId,reason,at);this.harden();}catch{return fail();}}
  isAccountQuarantined(userId:string,accountId:string){if(!TOKEN.test(userId)||!TOKEN.test(accountId))return fail();try{return Boolean(this.db().prepare("SELECT 1 FROM account_quarantine WHERE user_id=? AND account_id=?").get(userId,accountId));}catch{return fail();}}
  close(){try{this.database?.close();}finally{this.database=null;this.identity=null;}}
  databasePath(){return this.path;}
}
